### ISSUE TITLE
Bookmarks: When making a post, I get a double post

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#10]
<img width="1308" alt="screen shot 2017-08-03 at 11 55 51 am" src="https://user-images.githubusercontent.com/1217271/28933462-bf491d04-7842-11e7-9e3a-a3110c3e5928.png">

**Comment by JakeBooher** [comment]
This isn't from bookmarks, it's likely caused by the same thing as #1
