### ISSUE TITLE
Topics bug unchecking filters as guest

### ISSUE THREAD

**Issue by kylerc** [Audentio/xf2addon-issues#1002]
Seems to be keeping a filter after I uncheck.  Repro case: on https://demo.themehouse.com/xf2/uix-pro/trending/threads.1/ Click `Soccer` in right sidebar, wait for page load, then unclick `Soccer`.

**Comment by mikecreuzer** [comment]
Unable to replicate this

**Comment by kylerc** [comment]
@mikecreuzer https://photos.app.goo.gl/73WXK3Z6nLeYDmKH6 if it helps explain the issue

**Comment by mikecreuzer** [comment]
Ah indeed, requires you to be a guest.
