### ISSUE TITLE
Remove the word "topics" from "all topic" and "clear topics"

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#1003]

**Comment by mikecreuzer** [comment]
Where does this show @Ian-Hitt try to use screens as you know what you mean, maybe you had a call with someone, btu I dont

**Comment by Ian-Hitt** [comment]
The phrases for these things, they show in the modals.

**Comment by Ian-Hitt** [comment]
![screenshot_2018-10-24-10-20-59](https://user-images.githubusercontent.com/15836384/47523729-50dd3580-d85e-11e8-8b4d-8c5e179597dd.png)

**Comment by mikecreuzer** [comment]
`View all` and `Clear' is fine. Keep phrase slug the same I think, so this is just a quick fix

**Comment by Ian-Hitt** [comment]
The issue is that you don't see enough topics. All seems sufficient to me.

**Comment by mikecreuzer** [comment]
eh. idc thats fine - but definitely dont split to line beneath. Id rather use icons before that
