### ISSUE TITLE
browser back button doesn't respect topic selections in filter

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#1009]
To replicate:

1. Add a topic
2. Reload the page so the both the URL and the browser history updates
3. clear topics (do not re-load page)
4. Navigate away, to a thread or something
5. Use browser back button. The clear (or another other filter actions) are not saved because we are changing the URL, but not browser history for AJAX calls on topic filters

**Comment by jonw316** [comment]
I think the fix for #1002 has fixed this.
