### ISSUE TITLE
[TH] Nodes 2, ability to style and layout categories

### ISSUE THREAD

**Issue by kylerc** [Audentio/xf2addon-issues#101]
Was requested in ticket #9629.

**Comment by JakeBooher** [comment]
If this is the feature you've mentioned before I don't think it's worth adding, we had it in UI.X 1 but it was rarely used (once or twice, if ever) and would require refactoring the inheritance system quite a bit

**Comment by kylerc** [comment]
Was from a ticket so figured I'd officially add it here.  Also were requesting basically to be able to style the category strip and maybe some of the category itself similarly to how nodes can be styled.  The styling part might actually be more useful arguably.

**Comment by JakeBooher** [comment]
The category strip styling can likely be handled with the system we already have in place, so it'd just be a matter of having it build the css for category strips. Will look into it
