### ISSUE TITLE
UI.X Pro Report number of add-ons

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xf2addon-issues#1012]
The UI.X Pro report says I have 6 add-ons running but I only have 5 on my demo.

<img width="827" alt="screen shot 2018-10-24 at 2 24 45 pm" src="https://user-images.githubusercontent.com/43186749/47455873-959e9900-d798-11e8-93df-8c9030f29d31.png">

<img width="260" alt="screen shot 2018-10-24 at 2 23 04 pm" src="https://user-images.githubusercontent.com/43186749/47455771-58d2a200-d798-11e8-94cb-5f6e7cb1bd68.png">

**Comment by Nirjonadda** [comment]
What is this add-on [TH] UI.X Pro? I have not this add-on !

**Comment by LukasWieditz** [comment]
Oh yeah, that's because XenForo itself is technically stored in the Add-on database. I'll reduce the count by one artificially.
