### ISSUE TITLE
[Topics] Permissions

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2addon-issues#1022]
Allow permissions for topics. At the moment, you can view threads/posts from nodes that are hidden to users in the New Posts, Latest Threads and All threads pages.

**Comment by jonw316** [comment]
Duplicate of #1004

**Comment by joyfreak** [comment]
This isn't a duplicate. I think I didn't explain myself properly. I want to be able to set a permission for a topic so registered members can't select it, only administrators. This is very handy if implemented.

**Comment by JakeBooher** [comment]
I think this may already be possible by associating the topic with a node since it'll inherit the permissions from there, but have reopened so @jonw316 can confirm.

**Comment by joyfreak** [comment]
But what if it's a sub topic that isn't associated with any forum?
