### ISSUE TITLE
Description for Sub topics

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2addon-issues#1023]
No description is displayed for sub topics, kind of making the description of the forum useless.

**Comment by Ian-Hitt** [comment]
<img width="1393" alt="screen shot 2018-10-25 at 9 48 31 am" src="https://user-images.githubusercontent.com/15836384/47509169-27f77900-d83b-11e8-8ee2-43cb87b4e067.png">

These show on topic list view

**Comment by joyfreak** [comment]
But if you read closely, the sub topics does not show.
