### ISSUE TITLE
[Topics] Add display order field for topics ordering outside of topics layout

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2addon-issues#1026]
Can you allow reordering of topic list.

**Comment by Ian-Hitt** [comment]
Could you expand more on what you mean here?

**Comment by joyfreak** [comment]
The topic list page... Would be good if you can reorder them. The reason for this is because the topics listed in the "Post Thread" overlay follows the ordering of the topics list page which you can't reorder. The reason for this is because if you decide to add a topic in the future but want it at the top of the list in the filter widget then you would use the topic layout page to do that but the topic will remain at the end in the list of overlay.

**Comment by jonw316** [comment]
You can already sort by any of the following:
Creation date
Alphabetically
Discussion count
Post count
Last post date

I assume you are requesting to sort by custom priority?

**Comment by joyfreak** [comment]
Custom priority as at the moment, you are limited to those options. Or at least have it read and follow the Topic layout ordering.
