### ISSUE TITLE
Number of topics to show in filter

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2addon-issues#1033]
I have raised these numbers for both vertical and horizontal to 11. But seems to be fixed on displaying only 10 even though there are 11 topics.

**Comment by jonw316** [comment]
Check your widget settings.

**Comment by mikecreuzer** [comment]
@joyfreak sorry maybe misunderstood, maybe check layout page as well and add more in.

**Comment by joyfreak** [comment]
Oh, that is pretty confusing. You can't increase it via widget either unless the numbers match.
