### ISSUE TITLE
UI.X Material theme missing thumbnail

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#1036]
https://demo.themehouse.com/xf2/uix-pro/admin.php?install-upgrade-products/installed#styles

**Comment by jonw316** [comment]
![small](https://user-images.githubusercontent.com/42781420/47551583-7b7ccc00-d8fa-11e8-93ec-a5698a0b9688.png)
![Uploading full.png…]()

**Comment by jonw316** [comment]
![full](https://user-images.githubusercontent.com/42781420/47551594-85063400-d8fa-11e8-8b87-feef5438b5a3.png)

**Comment by LukasWieditz** [comment]
I'm not following what is to do here for me. The thumbnails are pulled from the ThemeHouse API.

**Comment by JakeBooher** [comment]
UI.X Material isn't a standalone product so there isn't an entry in pinto for it to pull a thumbnail from.
