### ISSUE TITLE
Small visual stuff I found on Topics

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#1037]
- [ ] 1. covers.jpg has that overflow issue (should probably do that overflow JS function anywhere you list topics)

- [ ] 2. create-thread.jpg has an odd padding when inline creating a thread (may be on modal too not sure) - “Sports” should be flush with editor

- [ ] 3. create-thread.jpg says `Topics:` on left, but topics on right - I think we can get away with removing this entirely

- [ ] 4 edit-topics.jpg - why not grid?

![covers](https://user-images.githubusercontent.com/1217271/47522351-f2fb1e80-d85a-11e8-8cb4-54868509eeb5.jpg)
![edit-topics](https://user-images.githubusercontent.com/1217271/47522371-03ab9480-d85b-11e8-9ed2-ab35c6eb98ce.jpg)
![create-thread](https://user-images.githubusercontent.com/1217271/47522372-04442b00-d85b-11e8-8658-d2be52ca9cfc.jpg)

**Comment by Ian-Hitt** [comment]
@jonw316 Need to ad helper class `forum-filter-grid` to get gridded style. This was not the class i was using before, looks like it's been changed, but CSS is updated with it so should be good
