### ISSUE TITLE
[TH] Topics RC11 - Mobile view showing extra checkbox

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#1051]
Not sure if this is a dupe but here's an odd one.

See screenshot. Happens in any view Trending, New posts etc.... as long as you're in mobile (narrow) view.

![rc11](https://user-images.githubusercontent.com/5346876/47571801-6b1f1e00-d907-11e8-9e3a-452a52a804c8.png)

**Comment by jonw316** [comment]
I think this is due to topics not deleting properly in an early beta. You can usually fix by clearing out your 'Topics layout' list and starting it again. I can't replicate this in the final release, so I'm going to close.
