### ISSUE TITLE
[TH] Reactions > New Style Property: "Display Reactions bar location"

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#106]
Please add Support moving Reactions bar under or above content controls.

**Comment by JakeBooher** [comment]
Duplicate of #85

**Comment by Nirjonadda** [comment]
Maked as Duplicate but implemented, very strange things. I think we need go back using Xon Version because xon Version happened lot of improvement.

https://image.prntscr.com/image/CsjyQ-dcQkeWlAFemMLfbQ.png
