### ISSUE TITLE
[UIX] Ability for users to set their own homepage default

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#1066]
Trending, new posts, new threads, forum list, whats new, etc. 

I think maybe the UI.X Pro add-on would be nice for this setting?

**Comment by LukasWieditz** [comment]
I think he means per end user, not per homepage as a whole? Otherwise, yeah, that's already a thing.

**Comment by mikecreuzer** [comment]
Correct. I think this would be quite nice for Pro, as some people may prefer different experiences.

**Comment by JakeBooher** [comment]
What options would you want to have for this?
