### ISSUE TITLE
[TH] Trending - missing phrase

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#1067]
Missing phrase Trending Permissions in /admin.php?permissions/analyze (thtrending_trending_permissions).

![analyze permissions canadian corvette forums admin control panel](https://user-images.githubusercontent.com/5346876/47619160-fc31f880-dab1-11e8-807f-1b9ad6fa8bbe.png)

**Comment by LukasWieditz** [comment]
That appears to be a development leftover. The tab shouldn't exist in the first place.
