### ISSUE TITLE
[TH] Reactions > Option disable Reaction count show in thread list

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#107]
Please add option disable Reaction count show in thread list, a style property to disable this.

**Comment by JakeBooher** [comment]
@Nirjonadda could you elaborate on this? If you're referring to the reaction bar in the post bit this can already be disabled

**Comment by Nirjonadda** [comment]
@JakeBooher No I am referring Option disable Reaction count show in thread list: https://image.prntscr.com/image/KT80dK6iQYyn8Bzd0S4PBg.png

**Comment by suineg** [comment]
I would like to see this as well. I am looking through the templates to do it manually but it would be preferable to have it as a toggle in the options. 

Speaking specifically about removing it from the thread list.

**Comment by suineg** [comment]
@Nirjonadda 

In the meantime to disable it I added a line to th_reactions.less

From: 

`.reactions-bar.bit-list
{
	float: right;
	transform: scale(.75);
}`

To:

`.reactions-bar.bit-list
{
	display: none;
	float: right;
	transform: scale(.75);
}`

**Comment by kylerc** [comment]
Thanks for the suggestion, this will be a style property in our next release of Reactions.
