### ISSUE TITLE
[TH] Post Comments - Disable reply button from comments

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1071]
Please add option for Disable reply button from comments.

![screenshot00628](https://user-images.githubusercontent.com/6899856/47644829-87bd8f00-db6f-11e8-8d7d-ffa66d603af7.png)

**Comment by LukasWieditz** [comment]
![i3flzza](https://user-images.githubusercontent.com/38475165/47645456-678ecf80-db71-11e8-9d91-734fe3f038e9.png)

You originally requested the option to show this button in addition to the comment button in #409 ...

**Comment by Nirjonadda** [comment]
Yes But this replace for normal comments area but shouldn't show in Post comments area?
