### ISSUE TITLE
[TH] Post Comments - Maximum comment depth

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1072]
Maximum comment depth are not working get. I have set Maximum comment depth is 4 but this limit not work.

![screenshot00629](https://user-images.githubusercontent.com/6899856/47645077-38c42980-db70-11e8-9104-14c68dd3d8b8.png)

**Comment by LukasWieditz** [comment]
The option is not how many comments are allowed on an item but how many levels you can go deep.

Depth Level 0 (Original Post)
--> Depth Level 1
----> Depth Level 2
------> Depth Level 3
--------> Depth Level 4
