### ISSUE TITLE
Cannot install styles through UI.X Add-on when Install & Upgrade is installed

### ISSUE THREAD

**Issue by JakeBooher** [Audentio/xf2addon-issues#1077]
```
Fatal error: Cannot use XF\Entity\Style as Style because the name is already in use in [...]/public/src/addons/ThemeHouse/InstallAndUpgrade/Entity/Log.php on line 8
```

**Comment by mikecreuzer** [comment]
Ugh yeah, until Install and Upgrade merges with UI.X's install system, we are having people install via UIX still in the instructions for Pro/UIX themes, etc. So this probably is a priority as they will not work while other is installed.
