### ISSUE TITLE
 [TH] Install & Upgrade - Beta 10 added lot of profiles

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1080]
Beta 10 added lot of profiles for XenForo Customer Area but I have not added nothing or one. I have added only ThemeHouse profiles.

![screenshot00636](https://user-images.githubusercontent.com/6899856/47718823-b27c1600-dc49-11e8-89a8-498d23f34d62.png)

**Comment by Nirjonadda** [comment]
I think this profiles are added that what i am failed added before?

Before try adding but not added: https://github.com/Audentio/xf2addon-issues/issues/1057

**Comment by LukasWieditz** [comment]
Yeah, that's where they're coming from. Just delete them.
