### ISSUE TITLE
[TH] Install & Upgrade - Available products showing Installed products 

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1087]
Available products page showing that what add-on already Installed.

![screenshot00641](https://user-images.githubusercontent.com/6899856/47729173-f9750600-dc5f-11e8-8e2c-e5b43a38c4dd.png)

**Comment by LukasWieditz** [comment]
If they are not linked to Install & Upgrade, they show up on that page. Especially for UI.X Pro I would just recommend to uninstall it and reinstall it via Install & Upgrade to get rid of that. For topics, you'll have to wait for the next topics update for Install & Upgrade to pick it up.

**Comment by Nirjonadda** [comment]
@LukasWieditz UI.X Pro installed with Install & Upgrade from ThemeHouse Available products. So what uninstall it and reinstall it via Install & Upgrade?

**Comment by Nirjonadda** [comment]
Also Beta 11 update no more showing themehouse add-on.
