### ISSUE TITLE
[Topics] Stock topics for location (city/state/country)

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#1096]
I think it would be a cool idea to add a way to filter by these concepts, as a setting. 

I got to this idea by thinking about a common use case for forums: internationalization, location. 

If someone can set their city, we can derive their state/city etc. Then we have an object that lists out each city/country for each city entered. That way if I wanted to search Illinois, I could find chicago and otherr cities. I could also search USA and get everything there. 

This could be a huge feature and it requires nothing more than a means to filter it, a means to set it, and a means to have it preloaded with all the strings.

**Comment by victoriad1** [comment]
There should also be the ability to remove cities, states, and countries from the list.

**Comment by mikecreuzer** [comment]
I think that this isn't treated as a 'Topic but rather a special Group. And maybe that group can be an optional thing where if you choose location it can ask you for optionally country, then state/region or whatever is applicable per country, and then city. This could be a HUGE feature.
