### ISSUE TITLE
Topics Vertical Seperation

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xf2addon-issues#1104]
Vertical separation in topics layout should only consider top level and not nested level for the max. Don’t force max of 20.

**Comment by jonw316** [comment]
I'm going to leave it as including nested for now, but I've removed all forced maximums.

**Comment by jonw316** [comment]
Scratch that, I'm going to have to set a limit of 55 for verticals for now as anything above that causes an error.

**Comment by mikecreuzer** [comment]
@jonw316 what kind of error? whats the significance of 55

**Comment by jonw316** [comment]
Error: Maximum function nesting level of '256' reached, aborting! src/vendor/oyejorge/less.php/lib/Less/Tree/Element.php:38
