### ISSUE TITLE
Vertical & Horizontal line in Topics Layout

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xf2addon-issues#1105]
The label for the vertical and horizontal line in topics layout to show the display cut-off is missing.

**Comment by mikecreuzer** [comment]
This issue is now a triple duplicate https://github.com/Audentio/xf2addon-issues/issues/992 so @jonw316 maybe Im missing what you added?

**Comment by jonw316** [comment]
Working on this now. Haven't added it yet.

**Comment by jonw316** [comment]
<img width="551" alt="screenshot 2018-11-01 at 16 03 10" src="https://user-images.githubusercontent.com/42781420/47863647-a9c54480-ddef-11e8-934c-a391f202130f.png">

**Comment by mikecreuzer** [comment]
Ah perfect ok
