### ISSUE TITLE
[UIX Pro] image not showing

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xf2addon-issues#1109]
The UI.X Pro image isn't showing in the report.
<img width="528" alt="screen shot 2018-11-01 at 1 58 40 pm" src="https://user-images.githubusercontent.com/43186749/47873094-4ed72180-ddde-11e8-9918-de38e03278c7.png">

**Comment by mikecreuzer** [comment]
Are you running latest?

**Comment by victoriad1** [comment]
I have [TH] Topics 1.0.0. Install and Upgrade doesn't say there is a more recent one.

**Comment by LukasWieditz** [comment]
That's the UI.X Pro add-on, not topics
