### ISSUE TITLE
[TH] Install & Upgrade - UI.X Pro Download URL blank

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1116]
UI.X Pro Download URL blank and Available products page showing that add-on, when this add-on already Installed.

![screenshot00668](https://user-images.githubusercontent.com/6899856/47931241-82917480-dece-11e8-9cfd-42acf33e9174.png)

![screenshot00669](https://user-images.githubusercontent.com/6899856/47931247-87eebf00-dece-11e8-9216-a0b3edd5bf93.png)

**Comment by LukasWieditz** [comment]
Resolved with the rewrite
