### ISSUE TITLE
 Topics pages showing a thread checked for moderation incorrectly

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#1118]
To replicate: navigate to some random forum view, check a thread, and then navigate to Topics: New posts or probably also latest threads. Make sure the thread you checkde is not in the list. It still shows there is a thread marked for modeation even though the thread does not appear on the page

Note: this is without any filtering whatsoever. There may be additional issues with also filtering where this is a problem.

**Comment by jonw316** [comment]
Unless I'm misunderstanding your problem, this is as designed.

If you go into a forum and select a thread for moderation and then go into a completely different forum, then there is a thread marked for moderation even though the thread does not appear on the page.
