### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2addon-issues#1119]
Server error log
ErrorException: Template error: Method canTrash is not callable on the given object (ThemeHouse\Bookmarks\XF\Entity\Thread) src/XF/Template/Templater.php:936
Generated by: Unknown account Nov 2, 2018 at 8:56 PM
Stack trace
#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Method canTrash...', '/home/gnonline/...', 936, Array)
#1 src/XF/Template/Templater.php(936): trigger_error('Method canTrash...', 512)
#2 internal_data/code_cache/templates/l1/s75/public/thread_view.php(533): XF\Template\Templater->method(Object(ThemeHouse\Bookmarks\XF\Entity\Thread), 'canTrash', Array)
#3 src/XF/Template/Templater.php(1250): XF\Template\Templater->{closure}(Object(KL\UserImprovements\Template\Templater), Array)
#4 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('public:thread_v...', Array)
#5 src/XF/Mvc/Renderer/Html.php(48): XF\Template\Template->render()
#6 src/XF/Mvc/Dispatcher.php(332): XF\Mvc\Renderer\Html->renderView('XF:Thread\\View', 'public:thread_v...', Array)
#7 src/XF/Mvc/Dispatcher.php(303): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#8 src/XF/Mvc/Dispatcher.php(44): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#9 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#10 src/XF.php(329): XF\App->run()
#11 index.php(13): XF::runApp('XF\\Pub\\App')
#12 {main}
Request state
array(4) {
  ["url"] => string(52) "/threads/ad-hypermu-online-season-6-episode-3.18373/"
  ["referrer"] => bool(false)
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}

**Comment by mikecreuzer** [comment]
Assuming this has something to do with deleting a bookmark?

**Comment by JakeBooher** [comment]
`canTrash` isn't a function we (or XenForo, for that matter) use anywhere, if you have any add-ons that would add this you'll need to report it to them
