### ISSUE TITLE
 [TH] Topics -  Topics: showing in Search results

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1120]
Topics: showing in Search results, when disabled topics system.

![screenshot00680](https://user-images.githubusercontent.com/6899856/47956996-88f71d80-dfae-11e8-8d11-dfbd27b86496.png)

![screenshot00679](https://user-images.githubusercontent.com/6899856/47957000-8eecfe80-dfae-11e8-8585-5d3b3bbf7097.png)

**Comment by mikecreuzer** [comment]
@jonw316 I just want that label always gone. Always looked weird anyway have it on the left and the topics on right.
