### ISSUE TITLE
[TH] XPress - Saving/Planning a blog posts doesn't save the selected forum

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1121]
It has been reported that when saving a post as a draft it doesn't save in the selected forum. When planning a blog post for a release date in the future ignores the selected forum and posts it instead in the default forum location.

It has been reported in ticket #12321

**Comment by LukasWieditz** [comment]
Please post XPress related issues in the [XPress repository](https://github.com/Audentio/xpress-issues/).
