### ISSUE TITLE
Topics - Removing first Topic should show a list of all topics OR redirect you to all topics page

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#1124]
Right now it keeps you on that forum view. This will post a thread without a topic at all which is bad.

**Comment by jonw316** [comment]
Are you saying that it shouldn't ever be possible to post a thread without a topic?

**Comment by mikecreuzer** [comment]
I think thats a good feature.

**Comment by mikecreuzer** [comment]
Lets make it a setting, default to on.

**Comment by mikecreuzer** [comment]
Reference #1148
