### ISSUE TITLE
[TH] Reactions - Deleting user reactions

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1135]
Deleting user reactions are not compete. This start over 1 to 40 then start again from 1st.

![screenshot00713](https://user-images.githubusercontent.com/6899856/48306740-85c7d880-e53e-11e8-8c21-bdd968ec2b49.png)

**Comment by Nirjonadda** [comment]
How can stop this? This running .....

**Comment by Nirjonadda** [comment]
Also can not delete user. This page stand by after want to delete.

![screenshot00719](https://user-images.githubusercontent.com/6899856/48372579-4ecd0080-e6bf-11e8-9b0c-7e7f0d28f442.png)

**Comment by jonw316** [comment]
Duplicate of #841
