### ISSUE TITLE
iO thread list hover not centered

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2addon-issues#1140]
As seen in the SS.
![hover](https://user-images.githubusercontent.com/43339306/48507383-aeecaf80-e843-11e8-9597-6e9f0627fe5b.png)

**Comment by daltonp** [comment]
I believe this issue might've already been fixed as I'm seeing this now
![screen shot 2018-11-16 at 1 32 10 pm](https://user-images.githubusercontent.com/32306910/48642992-191c6600-e9a4-11e8-87bc-2361d6f066df.png)

**Comment by LukasWieditz** [comment]
Theme-related issues should be posted in the [XF2 Theme repository](https://github.com/Audentio/xf2theme-issues/issues).
