### ISSUE TITLE
Importing iO, Console Error

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2addon-issues#1141]
Failed to load resource: the server responded with a status of 500 ()
core-compiled.js?_v=642f96e5:43 PHP: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at
<a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="eb82858d84ab8184928d998e8a80c5888486">[email&#160;protected]</a> to inform them of the time this error occurred,
and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script></body></html>

defaultAjaxError @ core-compiled.js?_v=642f96e5:43

**Comment by mikecreuzer** [comment]
@joyfreak did this happen by doing something specific? I cannot imagine this would have something to do with the theme itself

**Comment by JakeBooher** [comment]
@joyfreak is there anything in your XF error log?

**Comment by joyfreak** [comment]
Sorry for the late reply. You can close this as this was due to my server host.
