### ISSUE TITLE
[Donate] Avatar are not show in Comments from mobile

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1144]
Avatar are not show in Comments from mobile browser.

![screenshotcapture_2018_11_15_13_12_47_642](https://user-images.githubusercontent.com/6899856/48552432-e6596b80-e8d8-11e8-8792-34f1a45e00ba.jpg)

**Comment by daltonp** [comment]
I'm able to replicate this as well on one of our demo boards ;) Thanks for reporting this.
