### ISSUE TITLE
[Donate] Unable to specify cents in donate amount

### ISSUE THREAD

**Issue by jonw316** [Audentio/xf2addon-issues#1145]
>One more question though, why do donations have to be exact dollar amounts?
>
>Why can’t I have a donation option be 3.25?
>
>I like to charge for premium + the paypal fees so we actually make the amount we charge.
>
>With this addon I have to charge a whole dollar extra, when the fees are only 30 cents (roughly.)

**Comment by LukasWieditz** [comment]
Worth mentioning that PayPal ToS forbids to put the fees on the buyer by raising your prices by the respective amount.

**Comment by jonw316** [comment]
I've passed that on. Thanks.
