### ISSUE TITLE
[UIX] Template public:_widget_thuix_quickNavWidget is unknown (src/XF/Template/Templater.php:584)

### ISSUE THREAD

**Issue by jonw316** [Audentio/xf2addon-issues#1152]
Looks like this template was removed from the I&U add-on in this commit:
https://github.com/Audentio/xf2/commit/3fd6c5914657ee8c91a8d626e165743e327386a9

Not sure what is happening here.

**Comment by LukasWieditz** [comment]
@Ian-Hitt

**Comment by LukasWieditz** [comment]
Those templates get dynamically created when you install the UI.X add-on, and associated with any add-on that is currently set as active dev add-on. Shouldn't be in the repository.
