### ISSUE TITLE
Topics Wording Changes

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xf2addon-issues#1156]
- Under Topics>Options>Depth of node topics in widget - is that just for node topics or is it for thread topics as well? If it is for both it should just be "topics". Same for the description underneath. 

- Under Topics>Options>Number of topics to show when creating thread - should say "thread topics"

- Under Topics>Options>Thread search filter> "This option allows you to control if your users are able to filter their thread & post searches by topics, forums or both. If no topics have been created, this option will be ignored." Can they be searched by post as well? Maybe "post" should be removed". Also it should be "searches by thread topics, node topics, or both."

- Under Topics>Options>Thread topics sort field - Is this just for thread topics or for node topics as well? If it is for both then it should just be topics. Same for the description underneath. 

-  Under Topics>Options>Thread topics sort order - Is this just for thread topics or for node topics as well? If it is for both then it should just be topics. 

- Under Topics>Thread topics - I think the "Add topic" button should be "Add thread topic".

-Under Topics>Layout- Is the topics layout supposed to be labeled like this?
<img width="306" alt="screen shot 2018-11-20 at 12 21 52 pm" src="https://user-images.githubusercontent.com/43186749/48794224-f7322480-ecbe-11e8-9cd0-eb8991627eaf.png">

- Under Topics>Layout- The heading of the 2 columns should be "Selected thread topics" and "Available thread topics". Or maybe just label it Thread Topics Layout instead. I am guessing that each additional topic type would have it's own layout page.

- Under Topics>Thread topic tools> Create topics for forums - It should be thread topics along with the description below.

- Under Topics>Thread topic tools> Rebuild topic counters - Should be thread topics.

- Under Topics>Thread topic tools>Batch moderation - Should be "Thread topic batch moderation"

- Under Topics>Thread topics> Add thread topic>"This is the forum that a thread will live in if this topic is chosen. If this value is changed, all threads associated with this topic will be moved to the new forum." I think it should be "This is the forum that a thread will live in if this thread topic is chosen as the primary thread topic. If this value is changed, all threads associated with this thread topic will be moved to the new forum."

- Under Topics>Thread topics> Add thread topic> thtopics_topic_group - is that how it is supposed to be displayed?

- Under Topics>Thread topics> Add thread topic> thtopics_topic_group - Description should say "up to 10 thread topic(s)"

- Under Topics>Thread topics> Add thread topic> Can be selected as additional topic - should be thread topic. Same for the description underneath. 

- Under Topics> Groups> Add thread topic group> Title - the description should say thread topic

- Under Topics> Groups> Add thread topic group> Topics - should be Thread topics and same for the description underneath. 

- On my demo forum, when making a new thread and it shows the possible thread topics, the topic that need to go on 2 lines wasn't aligned correctly. 
<img width="153" alt="screen shot 2018-11-20 at 12 40 35 pm" src="https://user-images.githubusercontent.com/43186749/48795137-9b1ccf80-ecc1-11e8-8b98-a39029e5f16e.png">

**Comment by jonw316** [comment]
>Under Topics>Options>Depth of node topics in widget - is that just for node topics or is it for thread topics as well? If it is for both it should just be "topics". Same for the description underneath.
Just for node topics.

>Under Topics>Options>Thread topics sort order - Is this just for thread topics or for node topics as well? If it is for both then it should just be topics.
>Under Topics>Options>Thread topics sort order - Is this just for thread topics or for node topics as well? If it is for both then it should just be topics.
Just thread topics.

For most of the latter ones, I am going to leave as "topics" when the page title says "thread topics".
