### ISSUE TITLE
Topics - Topics tag alightment on the Postings page of a users profile

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1158]
When viewing the Postings page on users profiles. The topics tags are sometimes aligned to the bottom and sometimes aligned to the top with the topics/threads title. Can we maybe align them to always be at the top or keep them at the bottom instead?

https://gyazo.com/b78b2b3fa5798415e60aa3d486b2a4ac

**Comment by jonw316** [comment]
I'm not able to replicate this. Do you have a link to a demo site where this is happening?

**Comment by mikecreuzer** [comment]
This is a bug with XenForo's overflow function. Going to close. If we decide this is a big issue, the only solution I see is a new JS overflow script.
