### ISSUE TITLE
Reactions Threadlist Layout Alignment

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2addon-issues#116]
When viewing the thread list (at least as a staff member), you can see some crazy alignments going on.

I think you'll agree this can be cleaned up a bit.

I can reproduce this in both the UI.X2 style, as well as the default XF2 style.

![reactions_bug_1](https://user-images.githubusercontent.com/35111972/34738331-af2fffe2-f546-11e7-92d8-c0c9212bf689.png)

**Comment by ellisonpatterson** [comment]
Fixed.

**Comment by lilalien** [comment]
This one still seems like it can be improved upon a bit?

Reactions on thread list still seem to bounce around a bit depending on how many reactions are listed...

![reactions_thread_list_alignment](https://user-images.githubusercontent.com/35111972/35018075-e5018bde-faed-11e7-9b30-30bb18736f4a.png)

**Comment by lilalien** [comment]
Any thoughts on this?
