### ISSUE TITLE
[Topics]  Thread Topics Widget

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xf2addon-issues#1161]
Is there a way to visually indicate that there are items nested under other thread topics? You can't tell just by looking at it and some have nesting things and some don't. 
<img width="271" alt="screen shot 2018-11-20 at 3 51 43 pm" src="https://user-images.githubusercontent.com/43186749/48805219-69fdc880-ecdc-11e8-8050-cae45127aa70.png">
<img width="269" alt="screen shot 2018-11-20 at 3 54 31 pm" src="https://user-images.githubusercontent.com/43186749/48805297-974a7680-ecdc-11e8-8c83-ddceabee9618.png">

**Comment by LukasWieditz** [comment]
There's not, but it would probably be a good addition.
