### ISSUE TITLE
Topics - tags tool

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xf2addon-issues#1162]
Just a suggestion. I was trying to think of ways it would be easier for someone to adopt thread topics. It is great that there is a tool to add thread topics based on the node that they lived in but that only adds one thread topic per thread. It would be nice if it could do more. So maybe have a tool where you could assign each tag to a thread topic and then it would add that thread topic to the thread. Then you could get rid of using tags all together. Otherwise, the admin would need to do it manually for each thread or keep using tags as well if they already were using tags.

Another method if someone wasn't using tags, could be to do a key word search of the original post in each thread for any of the thread topics. Then if that word/thread topic is found it adds that thread topic to the thread.

**Comment by mikecreuzer** [comment]
This has been discussed as a replacement for what, say, Toms Guide/Hardware have. So I want be a bit more specific on what we need. Going to merge your two main suggestions (filter by tag, filter by keyword search) to https://github.com/Audentio/xf2addon-issues/issues/793
