### ISSUE TITLE
Topics - When closing the first topic, it will delete whatever you added without warning

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#1164]
2 main solutions:

- [ ] Prompt the user that this will happen
- [x] Save it as a draft, and auto load it in (which to me should be an XF thing no? 

Id understand losing thread fields, but the title/main content? that would be a shame.

**Comment by jonw316** [comment]
It does save as a draft, although drafts are saved on a per-forum basis. So if you pick a topic from a different forum, the draft won't go with you (although it is still there).

Completely changing how the draft system works could be problematic...
