### ISSUE TITLE
[TH] Giphy -  Pending changes

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1168]
Rebuild add-on are not update Pending changes.

![screenshot00739](https://user-images.githubusercontent.com/6899856/48920239-fa343d00-ee97-11e8-949e-865db29d5b37.png)

**Comment by daltonp** [comment]
This can easily be fixed by clicking "Sync changes"

**Comment by Nirjonadda** [comment]
@daltonp Where the "Sync changes" option?

**Comment by daltonp** [comment]
Click on the cog with the drop-down before clicking "Sync Changes" in the drop-down.

**Comment by Nirjonadda** [comment]
Doesn't know that what you are referring. Doing lot of time Rebuild add-on data but not changed.

**Comment by Nirjonadda** [comment]
Oh "Sync Changes" only show with development.

````
$config['development']['enabled'] = true;
````
