### ISSUE TITLE
[TH] Topics - SP Thread list > Enable topic bar and Remove breadcrumb not work

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1176]
SP Thread list > Enable topic bar and Remove breadcrumb not work.

**Comment by jonw316** [comment]
I'm removing this option as it makes no sense any more.

**Comment by Nirjonadda** [comment]
So this option no more need? I like to have a option enable topic bar and breadcrumb.

Thread view SP option still are working.

**Comment by jonw316** [comment]
On what page would you like to see that option?

**Comment by jonw316** [comment]
Yeah, that option doesn't make sense any more because a forum can have multiple topics associated with it. That's why I have now removed the style properties as they don't do anything.

**Comment by Nirjonadda** [comment]
Thread view have multiple topics So Then no style can not improved for thread list?

**Comment by Nirjonadda** [comment]
![screenshot00752](https://user-images.githubusercontent.com/6899856/48971695-b9663080-f01d-11e8-8e28-1cc0c044fbab.png)

**Comment by jonw316** [comment]
There is not currently a way to set the default topic on a forum like there is on a thread. This is not currently planned as a feature.
