### ISSUE TITLE
[Donate] Allow donate comments to be hard deleted

### ISSUE THREAD

**Issue by jonw316** [Audentio/xf2addon-issues#1187]

**Comment by LukasWieditz** [comment]
This should already be possible if you have the permission to hard delete any campaign comment.

**Comment by LukasWieditz** [comment]
@jonw316 is this possible? Otherwise we should classify this as bug.

**Comment by jonw316** [comment]
Looks like a bug to me. You can keep soft deleting the same comment, but can't hard delete as far as I can tell.
