### ISSUE TITLE
[TH] Topics - Add option enable node topics system

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1196]
Please can be add option enable/disable node topics system?

**Comment by jonw316** [comment]
Why? Just disable the widgets.

**Comment by Nirjonadda** [comment]
Topics v1.0.0 are worked once disabling. So does not understating what going on this add-on? You can close this. go ahead what you are like to do. If you are not listening our request. We are here for support development improvement then asking any thing will marking wont-fix or lock from discussion.

Can i ask that why adding any functionality if that are not work right way and if can not fix?

**Comment by jonw316** [comment]
If you say something is a bug and it isn't a bug I will close it.

If you say something is a feature request I will leave it open and it will be discussed and if it is a good idea it will be added.

If I close a bug but you think it should still be added, you can create another issue and mark it as a feature request.

I didn't close this issue, you did. I am happy to add the option, although I don't actually understand why you want it.

**Comment by Nirjonadda** [comment]
because Topics v1.0.0 are working with disabling Enable thread topics system. So why this are now separated? What the difference between thread topics system vs node topics system?

**Comment by mikecreuzer** [comment]
Its more a matter of clarity than a technical one, I commented on a previous issue just a few mins ago same thing. Its kinda like SINCE we have a thread topics, its not immediately apparent that the widget would not be in that system so it sticks around when we disable it. Since we do kinda have these 2 experiences (Node Topics and Thread Topics) then it kinda might make sense even if all it does currently is disable the sidebar widget @jonw316

**Comment by jonw316** [comment]
I'm happy to add this option. I never closed it, I just asked for more explanation.

**Comment by mikecreuzer** [comment]
@jonw316 in the other issue you asked what if you want both? idk, I mean I get it you definitely could. I guess you can do checkboxes but man oh man 99% of the time you want one or the other.

**Comment by jonw316** [comment]
I'm probably going to hold off on this until we build our XF 2.1 version of this add-on, as that has Widget display conditions, so it actually makes more sense.

**Comment by Nirjonadda** [comment]
@jonw316 My PL2 installation does not have this option?

Other note: I think dead lock found issue are fixed with PL2, Still not getting any error about dead lock.

**Comment by jonw316** [comment]
I'll post a beta for 1.0.2 shortly. Glad the dead lock issue is now fixed.
