### ISSUE TITLE
[Trending] Default Navigation Icon

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1197]
> An idea for this addon, it would be nice to be able to set it as a public navigation item such as Forums, What's New, Members, as an option instead of a child of Forums. I mean you can set it, but it would be nice for it to have it's own icon. Also another question is the configuration setting for views per minute, is this based off members views only, or is it guest views as well?
> 
> See the screenshot below as an example. Is there anyway we can get an icon for it?

One of our customers has [suggested](https://xenforo.com/community/threads/fluxoid.54882/page-2#post-1300872) this even though it is shown under sub-navigation.

**Comment by mikecreuzer** [comment]
I think its something only UI.X can do. Tagging @Ian-Hitt as I assume they mean when its top level, NOT sub nav

**Comment by omegaxnodle** [comment]
Basically I am looking to be able to add this as a main navigation item. You can add it as a main navigation item but it has no icon associated with it.  I have attached quick mock-up of what it would look like:

![1](https://user-images.githubusercontent.com/41705145/49966294-dd11ed80-fedc-11e8-8ea6-25c9a22ae604.jpg)

Basically when clicking this it would then load the trending page link.

Some code that gets it halfway there:

In uix_icons.less, add:

Code:

`<xf:if is="{$icon} == 'trending'">content: '@xf-uix_icon_thtrending';</xf:if>`

In uix.less, add:

Code:

`&[data-nav-id="thtrending"]:before {<xf:macro name="content" template="uix_icons.less" arg-icon="\f535" />}`

But would still need to have highlight on navigation when selected such as:

![2](https://user-images.githubusercontent.com/41705145/49966510-5dd0e980-fedd-11e8-803e-d52e1c38885d.jpg)

Looking forward to it guys!

**Comment by omegaxnodle** [comment]
It would be nice to have an option as a regular tab option. Or as a default navigation link. This can be achieved by adding:
**<xf:page option="section" value="thtrending" />** to the template **thtrending_trending_view** and add this anywhere in the template. Why hide it always as a sub navigation item? I would at least be nice to either display it as a primary navigation item or a sub-navigation item.
