### ISSUE TITLE
Topics Labels on Threads

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xf2addon-issues#1201]
On the demo board this seems to happen with Topics and Covers together:
<img width="164" alt="screen shot 2018-11-29 at 9 02 50 am" src="https://user-images.githubusercontent.com/43186749/49231252-2b8c9b80-f3b7-11e8-829b-5bd5edbad067.png">

When there is a solid background it works fine:
<img width="253" alt="screen shot 2018-11-29 at 9 04 27 am" src="https://user-images.githubusercontent.com/43186749/49231277-39422100-f3b7-11e8-93e8-75b2dfcb1341.png">

On my demo board that doesn't have any background, it does this:
<img width="281" alt="screen shot 2018-11-29 at 8 47 15 am" src="https://user-images.githubusercontent.com/43186749/49231320-4fe87800-f3b7-11e8-84fd-1509f0cf87fa.png">

**Comment by jonw316** [comment]
I'm unable to replicate this.

@Ian-Hitt I think this might be to do with the UI.X template update I made. Has that been released now? Can you check that @victoriad1 has the latest version?

**Comment by victoriad1** [comment]
It looks like this was sort of fixed. I can read the thread topic but the main thread topic has a white background on each thread rather than the background color the thread topic was set to. Not sure if that was intentional or not. 
<img width="261" alt="screen shot 2018-12-04 at 12 27 55 pm" src="https://user-images.githubusercontent.com/43186749/49464307-316feb80-f7c0-11e8-8bce-9a7bd273d9d3.png">

It is working on the demo board with a solid background cover.
<img width="337" alt="screen shot 2018-12-04 at 12 30 36 pm" src="https://user-images.githubusercontent.com/43186749/49464433-7c89fe80-f7c0-11e8-833c-215049b8a1ed.png">

But it still isn't with a picture for a cover.
<img width="319" alt="screen shot 2018-12-04 at 12 30 07 pm" src="https://user-images.githubusercontent.com/43186749/49464446-84e23980-f7c0-11e8-955e-12b351424e6a.png">

**Comment by jonw316** [comment]
@Ian-Hitt Is this a UI.X issue?
