### ISSUE TITLE
[TH] Reactions: Some reactions show up under incorrect reaction type

### ISSUE THREAD

**Issue by JakeBooher** [Audentio/xf2addon-issues#121]
https://xenforo.com/community/threads/th-reactions-paid.134133/page-20#post-1213125
![1516056215724](https://user-images.githubusercontent.com/179180/34993987-c0a67a02-fa97-11e7-833b-04388e9a4f33.png)
![1516056215724](https://user-images.githubusercontent.com/179180/34993992-c1cb32b0-fa97-11e7-88a5-4c76a3c1461b.png)

**Comment by ellisonpatterson** [comment]
Fixed but more precise sorting will be needed for the future.
