### ISSUE TITLE
Topics show up on forum list if they are set prior

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#1210]
Thanks to @nirjonadda for this one: https://giant.gfycat.com/RecklessTastyFerret.webm

**Comment by mikecreuzer** [comment]
Hmm the more I look at this, its confusing but I suppose its correct. It looks like a bug but is actually doing what you expect. Its just confusing with the Topic is same name as node, but yeah. nvm

**Comment by jonw316** [comment]
Duplicate of #1193.
