### ISSUE TITLE
Thread Topics Widget on Material

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xf2addon-issues#1227]
The Thread Topics widget on Material has a few issues. It looks like it has too much spacing in between thread topics, the nested thread topics don't have any sort of symbol/plus sign showing they have items nested, and when you expand a nested item the items nested underneath are inline with the rest of the thread topics instead of indented in. @Ian-Hitt

**Comment by victoriad1** [comment]
The node topics widget also has similar issues.

**Comment by Ian-Hitt** [comment]
This was using an old version of the theme, not a present in latest theme
