### ISSUE TITLE
Topics thread topics sort fields

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xf2addon-issues#1228]
It doesn't look like the options for discussion count, post count or last post date are working for the thread topics sort fields. All three appear to be the same or very similar order and don't look correct for whichever option I picked.

**Comment by jonw316** [comment]
The description of the option is actually wrong. This sorting is actually only used in the "All Topics" list on the front end, and the "Available Topics" and "Thread Topics" lists in the back end.
