### ISSUE TITLE
[Topics] layout nesting

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xf2addon-issues#1229]
Example:

Summer Sports
       Diving  
       Swimming
         
In Topics layout if I nest my thread topics like the example above, I can't unnest Diving. I can unnest Swimming but not Diving. I just end up accidentally getting rid of Diving. Then if I put Wrestling under Swimming while it is nested, I can no loner unnest Swimming. I can only unnest the last one.

**Comment by jonw316** [comment]
This is a weird one but I can't see any other way of doing it.

If you were allowed to unnest Diving as you are intending to do, then what ends up happening is that Swimming becomes a child of Diving, which actually makes no sense.

It is possible to unnest, but you have to move Diving up to a position above Summer Sports or down below Swimming, and then unnest it, which actually makes sense when you think about it.

I'll close for now but re-open if you disagree.

**Comment by victoriad1** [comment]
I see what you are saying but to me it was just a matter of being able to move them around easily. If someone accidentally nests one it just creates more work to fix it or if they did it on purpose and then want to change it. Also, if I have a bunch that are nested, I cant then add an unnested one to separate them into groups. Having it set up this way is fine but it makes the user have to be more particular about where they go rather than just arranging them I think.

**Comment by jonw316** [comment]
I think for the amount of work it's going to take to fix this (it's a third party library that we're using), it's probably never going to be worth it, but I'll mark it as a possible future enhancement.
