### ISSUE TITLE
Topics List

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xf2addon-issues#1230]
1. My topics list has the first row of the thread topics taller than the rest. 

2. Also, it looks like based on the layout, any thread topics that were nested only appear when you click on the sub topics drop down for the thread topic they are nested under. The thread topic they are nested under shows x threads and x messages. It looks like it is only for that specific thread topic. Maybe that should be for all of the threads and messages in that thread topic and the nested thread topics. Right now one of mine says 0 threads 0 messages. If all of the nested thread topics and the one they are nested under counted it would say 7 threads 14 messages.

**Comment by jonw316** [comment]
1. If one of the topics in a row has subtopics or a description or a longer name etc., then the whole row will be taller. This is as designed.

2. This is basically a limitation of XenForo, so going to say as designed too.
