### ISSUE TITLE
 [TH] Topics - Filter AJAX are not complete

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1232]
See here: https://giant.gfycat.com/BreakableJovialCockerspaniel.webm

browser console error:

![screenshot00789](https://user-images.githubusercontent.com/6899856/49645695-2cf43e80-fa1d-11e8-9728-d905f9d291c2.png)

**Comment by jonw316** [comment]
Just noting that this is an XF2.1 bug.

**Comment by jonw316** [comment]
Never mind, I can replicate in Safari.
