### ISSUE TITLE
Remove ability to select "none" as payment profile

### ISSUE THREAD

**Issue by jonw316** [Audentio/xf2addon-issues#1239]
> in the Back-End at /admin.php?donate/campaigns/xenforo.1/edit (xenforo.1 is my campaigns) we can select "None" for "Payment profile",

![screenshot_3](https://user-images.githubusercontent.com/42781420/49668446-01da1100-fa56-11e8-8512-78ac0f18e2ae.png)

**Comment by LukasWieditz** [comment]
This is as designed. The purpose is to allow campaigns to be active, yet you cannot donate to them yourself.
