### ISSUE TITLE
[TH] Topics - Issue with Widget Display style

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1243]
Issue with Widget Display style, see full video: https://giant.gfycat.com/NervousCreativeAllosaurus.webm

**Comment by jonw316** [comment]
This is as designed. The 'Default' setting is the best option.

**Comment by Nirjonadda** [comment]
OK If designed then does not that necessary showing double Widget 2 time?

![screenshot00800](https://user-images.githubusercontent.com/6899856/49669172-df012a00-fa60-11e8-8bf6-416033836a5b.png)

**Comment by Ian-Hitt** [comment]
This looks like a bug i thing? re-opening to check with @jonw316
