### ISSUE TITLE
topics widgets duplicated

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#1245]
<img width="1305" alt="screen shot 2018-12-07 at 3 36 13 pm" src="https://user-images.githubusercontent.com/15836384/49673947-dfd09680-fa35-11e8-88d1-a3a5eeb272b5.png">

**Comment by Ian-Hitt** [comment]
<img width="1260" alt="screen shot 2018-12-07 at 3 37 08 pm" src="https://user-images.githubusercontent.com/15836384/49673976-f971de00-fa35-11e8-960f-3196f0f94451.png">

**Comment by jonw316** [comment]
This is intentional and as designed. You either need to create 2 separate widgets, one for horizontal and one for vertical, or you need to just set it to default so that it displays the appropriate widget.
