### ISSUE TITLE
[TH] Topics - Blank space from forum list or thread list

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1246]
Blank space from forum list or thread list.

![screenshot00802](https://user-images.githubusercontent.com/6899856/49687095-4ae5a000-fafe-11e8-8b0c-5be3507af04c.png)

**Comment by jonw316** [comment]
This is sort of intentional as the node filter does not work on the forum list. The simple way to fix this would be to just remove the widget from that location. It could be handled better though.

**Comment by jonw316** [comment]
Also getting this issue on other pages on XF2.1, although I suspect this is a bug with XenForo. I've created an issue here:
https://xenforo.com/community/threads/context-params-not-being-passed-to-widget.157626/

**Comment by jonw316** [comment]
The XF 2.1 bug will be fixed in the next beta release.

**Comment by Nirjonadda** [comment]
We need for XF 2.0

**Comment by jonw316** [comment]
Working on it now...
