### ISSUE TITLE
Edit Topics Overlay 

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xf2addon-issues#1247]
The edit topics overlay doesn't appear when you click on a node/forum and then click Post Thread. It just automatically picks the main thread topic based on the forum and in order to add additional topics I would need to choose "Edit Topics".

**Comment by Nirjonadda** [comment]
What issue you are asking for create? You are fixing Edit Topics Overlay are not open for multiple Topics. So When using Maximum additional thread topics is 0 then automatically picks the main thread topic based on the forum. So Edit Topics Overlay should not open, this how are working now.

**Comment by jonw316** [comment]
Please create a separate issue for "When using Maximum additional thread topics is 0 then Edit Topics Overlay should not open".
