### ISSUE TITLE
Reactions - Reaction Trigger Hover Link Wonkiness!

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2addon-issues#125]
Add-on Name: Reactions

Add-on Version: 1.0.8

XenForo Version: 2.0.1

Operating System (and Version): Windows 10 / 64-Bit (Latest Updates)

Browser Name (and Version): Chrome 63 (latest stable)

Summary of issue: I reported this in the Reactions thread a version or two ago, but I don't think it made it into the tracker so here you go!

If you hover your mouse in a thread and move your mouse left and right a few times across the default up/down reaction trigger image it affects ALL of the pages links with dimming oddities. Do it a few times over and over, happens with any style. Its very visible depending on what your link color is, you have to look closely (most visible on dark styles) such as our WTF.com style (based on UI.X Dark). It does not occur the other way (hovering over any other links does not effect the reaction trigger image). Reactions causing the links to get wonky on hover!

I have included an animated video gif to show it!

![reactions_bug_trigger_hover](https://user-images.githubusercontent.com/35111972/35012058-5e876658-fad6-11e7-8284-e34c29328cda.gif)

Thanks!
-Jason

**Comment by mikecreuzer** [comment]
Wow that is indeed goofy. Will get this fixed asap!

**Comment by kylerc** [comment]
@lilalien I've been trying to replicate this but haven't been able to so far.  It looks like it could be a render bug, but I'm not sure yet.  Are you still seeing this issue?

**Comment by lilalien** [comment]
Yes, I can easily replicate this on any browser (in Windows at least) using ui.x dark or light. Its harder to see with light, but its still there. Wonkiness doesn't happen with this add-on disabled. It seems to happen with only hovering that up/down thumbs trigger.

**Comment by kylerc** [comment]
Fixed by Audentio/xf2#294
