### ISSUE TITLE
Topics: 'all topics' modal legibility issues

### ISSUE THREAD

**Issue by nikkiradloff** [Audentio/xf2addon-issues#1250]
<img width="833" alt="screen shot 2018-12-11 at 2 02 20 pm" src="https://user-images.githubusercontent.com/15836402/49826796-6db9c380-fd4d-11e8-98a9-7923c22c59bb.png">

**Comment by jonw316** [comment]
This looks like a UI.X issue. It's not supposed to look anything like that. @Ian-Hitt ?
