### ISSUE TITLE
[Post Comments] silently fails when you try replying when you would exceed the max depth

### ISSUE THREAD

**Issue by JakeBooher** [Audentio/xf2addon-issues#1253]
If you have the max depth set to 1 and you try to reply to a post's comment you will get no error message after clicking on "Reply" it just silently fails.

**Comment by LukasWieditz** [comment]
@Ian-Hitt the reply button needs to be hidden when the max depth is reached. This was working before the last design change.

**Comment by jonw316** [comment]
Think this is an XF2.1 bug (source: https://xenforo.com/community/threads/th-post-comments-paid.153862/post-1315087)

**Comment by JakeBooher** [comment]
> Think this is an XF2.1 bug (source: https://xenforo.com/community/threads/th-post-comments-paid.153862/post-1315087)

Hasn't got anything to do with 2.1, happens on 2.0 as well
