### ISSUE TITLE
[TH] Reactions: Widget Font Color Consistency

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2addon-issues#126]
Add-on Name: Reactions

Add-on Version: 1.0.8

XenForo Version: 2.0.1

Description: When viewing the new reactions widget in member profiles, you will notice that the header text for "Reaction" does not match the color of "Given" and "Received". I think it should for consistency.

Screenshot attached!

![reactions_widget_color_bug](https://user-images.githubusercontent.com/35111972/35012172-d6f35e62-fad6-11e7-83f8-6b307b00eb3a.png)

Thank you!
-Jason

**Comment by lilalien** [comment]
Just a note about above.. The screenshot was from my custom version based on UI.X, however I tested it with UI.X Dark just now and the results are the same.

Just wanted to shout that out. :)

**Comment by daltonp** [comment]
This is confirmed, thank you for the report!
