### ISSUE TITLE
[Covers] Display Order in Cover Presets

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xf2addon-issues#1280]
I'm not sure if this is a bug or not but when I try to change the display order in Covers to something other than 10 or 0, I get a notification saying "Please enter a valid value. The two nearest valid values are 0 and 10."

**Comment by LukasWieditz** [comment]
@victoriad1 I am unable to reproduce this. Can you make a screenshot/video of this?

**Comment by daltonp** [comment]
I'm also experiencing the same issue but it says this "Please enter a valid value. The two nearest valid values are 10 and 20." Is this normal?
![cover_issues](https://user-images.githubusercontent.com/32306910/52870009-814a2780-310c-11e9-98b0-4af853a98e34.png)
