### ISSUE TITLE
[TH] Reactions: Reactions type color markup

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#129]
Improvement Request, Please add support for Reactions type color markup. currently impossible understand that what type Reactions is. Add enable/disable option for this functionality.

![screenshot00070](https://user-images.githubusercontent.com/6899856/35047689-fff37bf2-fb9a-11e7-8ec1-7656b96299a1.png)

**Comment by LukasWieditz** [comment]
We've discussed about it internally and don't see which value this would offer, in addition to not having a way to represent this information in a feasible way.
