### ISSUE TITLE
[TH] Reactions: Reaction listings page

### ISSUE THREAD

**Issue by ellisonpatterson** [Audentio/xf2addon-issues#130]
Show a page in the help section that shows all reactions types, along with the reactions in them. Maybe include global numbers there as well.

**Comment by lilalien** [comment]
Just a screenshot of what a leaderboard could look like, maybe with the actual reaction visible or something though...

![reactions_leaderboard_example](https://user-images.githubusercontent.com/35111972/35545830-20f4a3aa-053f-11e8-8c8d-714d3aca0053.png)

**Comment by lilalien** [comment]
The one you closed isn't exactly the same thing...

I also gave the wrong url in the above referenced "closed" report...

It should have been:
https://www.wtf.com/pages/popular/

Basically I think what people would want would be:

* A Help page, which lists all of the reactions you can get or give.
* A Profile "tab", which displays all the reactions that a person has gotten for their content (and some sort of clickable total that can be used to display something like seen here: https://github.com/Audentio/xf2addon-issues/issues/137 )
* Several member stat widgets, which can be used anywhere on the site including creating an all-widget native XF page such as: https://www.wtf.com/pages/popular/

Thoughts?

**Comment by lilalien** [comment]
I also mentioned a "leaderboard" up top, for all time stuff which is the same as a widget, basically.

Would be nice on that widget page above if I could put top liked people, or any other specific reaction if I wanted to focus on one.. and other ones that were more general stats.

**Comment by LukasWieditz** [comment]
The listing page has been created. Go to Help > Reactions
