### ISSUE TITLE
[Donate] Campaign overview: toggle on goals widget alignment and visibility issue

### ISSUE THREAD

**Issue by nikkiradloff** [Audentio/xf2addon-issues#1302]
Add-on Version: 1.0.4 Patch Level 1
<img width="351" alt="screen shot 2018-12-21 at 2 15 41 pm" src="https://user-images.githubusercontent.com/15836402/50362371-1aa1f680-052d-11e9-9b6f-64c7ebf615c3.png">

**Comment by evertiro** [comment]
Alignment of what is off? If you're talking about the progress bar clipping on the border, it's missing a tiny bit of CSS. Add the following to your `extra.less`:

```css
.donate-progressBarContainer {
    overflow: hidden;
}
```

I'm only running one campaign, but I'll setup a multiple campaign setup and find the missing CSS for the visibility issue.

**Comment by nikkiradloff** [comment]
@evertiro the two arrow icons are slightly off both vertically and horizontally. I believe there's an issue made for the progress bar clipping #1130 

If the above fix is for making both sides rounded.

**Comment by evertiro** [comment]
On closer inspection, I see what you mean.

**Comment by JakeBooher** [comment]
Fixed this while fixing something else
