### ISSUE TITLE
[Donate] Campaign icon alignment off

### ISSUE THREAD

**Issue by nikkiradloff** [Audentio/xf2addon-issues#1303]
Add-on Version: 1.0.4 Patch Level 1
<img width="153" alt="screen shot 2018-12-21 at 2 15 34 pm" src="https://user-images.githubusercontent.com/15836402/50362411-48873b00-052d-11e9-8c1d-850f8923a2fe.png">
![add-campaign-icon](https://user-images.githubusercontent.com/15836402/50362424-53da6680-052d-11e9-892e-1c4a667ace1f.png)

**Comment by JakeBooher** [comment]
Seems like this was fixed automagically by XenForo 2.1, so going to go ahead and close this
