### ISSUE TITLE
[Spotify] "Response Was Not JSON" errors

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1310]
"Response Was Not JSON" errors randomly appearing on site. Disabling [TH] Nodes add-on then no more happen this error.

![screenshot00748](https://user-images.githubusercontent.com/6899856/50540721-4cebcd80-0b97-11e9-819a-6cc933be2990.png)

**Comment by JakeBooher** [comment]
Hi,

The only time I've seen this error occur is from an issue connecting to the Spotify API when you have [TH] Spotify installed. It going away when disabling Nodes is likely a coincidence. Are you running the latest version (1.0.2 I believe) of the Spotify add-on?

**Comment by Nirjonadda** [comment]
Yes, I am running the latest version 1.0.1

**Comment by Nirjonadda** [comment]
@JakeBooher Still getting "Response Was Not JSON" errors.

**Comment by evertiro** [comment]
Any level of consistency? Is it happening _all_ the time or just sometimes? Can you check the javascript console when it happens and see if you can get more detail on what _was_ returned?

**Comment by JakeBooher** [comment]
We ended up determining that the only way this happens is if your webserver (nginx/appache) or a load balancer/reverse proxy returns a non-json response. Typically from what we've seen this happens due to some form of DoS protection falsely flagging the frequent requests. Our recommended fix is to increase the polling time in the options

**Comment by Nirjonadda** [comment]
@JakeBooher Poll rate is 1000, So what increase recommendation?

**Comment by JakeBooher** [comment]
Are you using CloudFlare or something similar? 1 second pollrate (1000ms) should be more than enough to bypass any DoS protection, so it could be cloudflare detecting something suspicious in the request

**Comment by Nirjonadda** [comment]
No, I am not use CloudFlare, only using nginx.
