### ISSUE TITLE
[TH] Image Optimizer - Add option where Optimizer active

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1312]
Add enable/disable option where Optimizer active.

![screenshot00875](https://user-images.githubusercontent.com/6899856/50628363-22539900-0f38-11e9-90f1-4fab63deeb6d.png)

**Comment by Nirjonadda** [comment]
Also add for Media Gallery, as well add what area Optimizer are work.


- Attachment
- Media Gallery
- Avatars
- Image Proxy
- [TH] Covers

**Comment by JakeBooher** [comment]
This already exists, but is hidden because only attachments are supported currently. Additionally, Media Gallery cannot have a separate option because internally it (as well as many other add-ons) uses the attachment system
