### ISSUE TITLE
Reactions - Hovering a reaction displays tooltip AND alt-text?

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2addon-issues#132]
Add-on Name: Reactions

Add-on Version: 1.0.8

XenForo Version: 2.0.1

Operating System (and Version): Windows 10 / 64-bit (Latest Stable Updates)

Browser Name (and Version): Chrome 64-bit (Latest Stable)

Summary of issue:  When hovering over reactions in 1.0.8, I now see not only tooltips but I see alt-text showing as well. Looks ugly displaying both, I'm guessing this wasn't on purpose?

Detailed steps to reproduce the issue: Hover over any reaction, and see both a tooltip and a alttext.

Upload any screenshots related to the issue below
![reactions_bug_tooltip_and_alttext_redundancy](https://user-images.githubusercontent.com/35111972/35079768-8a8de8c4-fbd7-11e7-9001-5fbc5a48ca1f.png)

**Comment by lilalien** [comment]
Just a note, it can also be seen in Edge (and at this point, I'm assuming Firefox lol).

**Comment by daltonp** [comment]
This has been confirmed, thank you for reporting it.

**Comment by ellisonpatterson** [comment]
Fixed for next version.
