### ISSUE TITLE
Reactions Plus - [TH] Reactions importer

### ISSUE THREAD

**Issue by JakeBooher** [Audentio/xf2addon-issues#1322]
Include duplicates check for people who upgraded to 2.1 before Reactions Plus is available.

**Comment by jonw316** [comment]
How much do I need to leave in for the [TH] Donate add-on? Can I remove it from the Entity class, as long as I don't delete the column on upgrade?

**Comment by JakeBooher** [comment]
You can remove any reference to [TH] Reactions from the donate add-on, all I'll need are the entires in xf_th_reacted_content table, which Donate wouldn't be responsible for removing anyways
