### ISSUE TITLE
[TH] Nodes - Page Node Icons

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#133]
Add-on Name: [TH] Nodes

Add-on Version: 1.0.1 Patch Level 1

XenForo Version: 2.0.1

Operating System (and Version): Windows 8

Browser Name (and Version): Chrome 63.0.3239.132 (Official Build) (64-bit)

Summary of issue: Default Link forum icon saw on top of the Material Design icons being seen

Detailed steps to reproduce the issue:

1. Navigate to Forums > Nodes > Add Node > Selected Link Forum from the categories > Added in all the required informations > Navigated to Forums > Node layout and styling > Selected the node > Clicked Node Icons > Added a node format such as mdi mdi-discord before clicking save. It shows both the icon and the default icon.

Upload any screenshots related to the issue below

![screen shot 2018-01-18 at 4 12 54 pm](https://user-images.githubusercontent.com/32306910/35124109-817f0a9a-fc6a-11e7-8662-7615aa4d3a74.png)

**Comment by daltonp** [comment]
I was able to confirm this on one of our test forums.

**Comment by LukasWieditz** [comment]
I cannot reproduce this on our current build. I assume we have already fixed that, if not, reopen the ticket.
