### ISSUE TITLE
Convert [TH] Donate reactions into XF2.1 reactions

### ISSUE THREAD

**Issue by jonw316** [Audentio/xf2addon-issues#1347]
I think this is the only way we can do this that isn't going to be a complete mess.

There's probably not that many users this affects, but I think the process needs to be that a user upgrades [TH] Donate to the XF 2.1 specific version first (which supports XF2.1 reactions but still supports legacy [TH] Reactions), and then installs [TH] Reactions Plus, which converts their [TH] Reactions into XF2.1 reactions.

I might be being dumb, but I can't think of a better way.

**Comment by JakeBooher** [comment]
This will be covered with #1322
