### ISSUE TITLE
Donate - missing template: news_feed_item_thdonate_campaigncomment_react

### ISSUE THREAD

**Issue by jonw316** [Audentio/xf2addon-issues#1352]
Add-on Name:

Add-on Version:

XenForo Version:

Operating System (and Version):

Browser Name (and Version):

Summary of issue:

Detailed steps to reproduce the issue:

Upload any screenshots related to the issue below

**Comment by ichpen** [comment]
This is still an issue with 1.0.5

**Comment by jonw316** [comment]
Exact same issue?

**Comment by ichpen** [comment]
Without seeing the stack trace sure looks like it. See my latest bug on this.
