### ISSUE TITLE
[Nodes] Unnecessary colon after stats

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2addon-issues#1355]
As per title:
![image](https://user-images.githubusercontent.com/34864926/51085488-f30c0b80-1731-11e9-8e39-cf874b07c27c.png)

**Comment by Ian-Hitt** [comment]
This looks like you customized the theme to display in the reverse, so it in not a UI.X issue, rather just an incompatibility with your specific change. Here is how it should display
<img width="343" alt="screen shot 2019-02-05 at 10 29 14 am" src="https://user-images.githubusercontent.com/15836384/52288078-155c0800-2931-11e9-8388-a6a0853da818.png">
