### ISSUE TITLE
[TH] Image Optimizer - reverse psychology

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#1368]
Could be reverse psychology in action with V1.1

I realise this is provider dependent but maybe explore options to bypass optimization in the below case?

![reverse](https://user-images.githubusercontent.com/5346876/51218036-9870dc00-18f8-11e9-94de-b74f903b9b5e.png)

**Comment by JakeBooher** [comment]
We actually have something in place for this, but apparently it's only happening if the sizes are the same, will adjust that for the next release :)

**Comment by ichpen** [comment]
Yep, the growing in size is the part that amused :)

Thanks a lot.
