### ISSUE TITLE
[TH] Image Optimizer - Add option for excluded Optimization

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1369]
Add option for excluded Optimization when no Optimization required.

![screenshot00922](https://user-images.githubusercontent.com/6899856/51247154-8ccef500-198c-11e9-913d-3abf37717de7.png)

**Comment by JakeBooher** [comment]
We're not really able to tell if no optimization is required until we attempt to run it. If the original and new sizes are the same we do just keep the original image though.
