### ISSUE TITLE
[TH] Reactions - Please add ability for clickable "Likes" count to view reactions given to specific profile member

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2addon-issues#137]
Add-on Name: Reactions

Suggestion: This suggestion would resolve a long-standing missing ability for people to see liked content from all members to a specific member clickable from their profile. When I visit a profile, I'd like to be able to see reactions given TO THAT MEMBER. XF only has a newsfeed with likes being given to anyone all in one place, I want to see just a specific members when I view their profiles. There are already clickable links in the profile for trophies for example, that when you click on THOSE you can see the ones they've gotten.

Why not be shown the reactions that got too?

This way I can do something like the below... Note I removed the likes and points totals from the left summary, and stuck it in its own widget to highlight something I see as more important):
![wtf-reactions-suggestion](https://user-images.githubusercontent.com/35111972/36006064-d105b4ac-0d08-11e8-8172-04d817a8d95a.png)

You can see something similar here:
https://invisioncommunity.com/profile/62-matt/

Click the Reputation total on the left.. All that is, is the ability to see in a tab all the likes/reactions OTHERS have given TO that user. Creating an overall reputation...

I think this would be simple AND really put Reaction add-on over the top!

**Comment by ALMUSA** [comment]
Seems like this has become popular demand now, any idea when this actually going to be implemented?
