### ISSUE TITLE
[I&U] Update Error

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xf2addon-issues#1388]
I get the error below when trying to install Install and Update. 

XF\Db\Exception: MySQL statement prepare error [1054]: Unknown column 'xf_th_installupgrade_product.content_id' in 'where clause' in src/XF/Db/AbstractStatement.php at line 212
XF\Db\AbstractStatement->getException() in src/XF/Db/Mysqli/Statement.php at line 196
XF\Db\Mysqli\Statement->getException() in src/XF/Db/Mysqli/Statement.php at line 39
XF\Db\Mysqli\Statement->prepare() in src/XF/Db/Mysqli/Statement.php at line 54
XF\Db\Mysqli\Statement->execute() in src/XF/Db/AbstractAdapter.php at line 79
XF\Db\AbstractAdapter->query() in src/XF/Mvc/Entity/Finder.php at line 1130
XF\Mvc\Entity\Finder->fetchOne() in src/XF/Mvc/Entity/Manager.php at line 359
XF\Mvc\Entity\Manager->getRelation() in src/XF/Mvc/Entity/Entity.php at line 373
XF\Mvc\Entity\Entity->getRelation() in src/XF/Mvc/Entity/Entity.php at line 171
XF\Mvc\Entity\Entity->get() in src/XF/Mvc/Entity/Entity.php at line 100
XF\Mvc\Entity\Entity->offsetGet() in src/XF/AddOn/AddOn.php at line 736
XF\AddOn\AddOn->offsetGet() in src/XF/AddOn/AddOn.php at line 749
XF\AddOn\AddOn->__get() in src/addons/ThemeHouse/InstallAndUpgrade/XF/Admin/Controller/AddOn.php at line 27
ThemeHouse\InstallAndUpgrade\XF\Admin\Controller\AddOn->actionIndex() in src/XF/Mvc/Dispatcher.php at line 249
XF\Mvc\Dispatcher->dispatchClass() in src/XF/Mvc/Dispatcher.php at line 88
XF\Mvc\Dispatcher->dispatchLoop() in src/XF/Mvc/Dispatcher.php at line 41
XF\Mvc\Dispatcher->run() in src/XF/App.php at line 1931
XF\App->run() in src/XF.php at line 329
XF::runApp() in admin.php at line 13

**Comment by evertiro** [comment]
Any word on this? It's been a month and it's currently the only thing (that I've found) preventing a clean upgrade to 2.1

**Comment by LukasWieditz** [comment]
We do recommend a fresh installation.

**Comment by evertiro** [comment]
Yea, I figured that out. Bookmarks is a bit wonky on 2.1, but the I&U issues disappear when you do a fresh install.
