### ISSUE TITLE
Apply node styling to titlebar where applicable

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#139]
Node color class support

**Comment by LukasWieditz** [comment]
- Generator Macro is  `thnodes_generator_macros`
   - You have `$nodeId`, and `$styling` available
- When you edit the macro, run `Rebuild cache` in Forums -> Node layout and styling
- `$thNode` is available in the page container (always, when you need to apply the styling to the header)

**Comment by mikecreuzer** [comment]
@LukasWieditz can this cache rebuild on save of the macro?

**Comment by LukasWieditz** [comment]
@mikecreuzer No, but users aren't supposed to touch the macro, it's for automatic generation.
