### ISSUE TITLE
[UIX] Add location for UIX Pro theme to add widgets there

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#1390]
We used to have this. 

![image](https://user-images.githubusercontent.com/1217271/51398343-fd9b1c00-1b08-11e9-88ec-76bd784675f8.png)

**Comment by Ian-Hitt** [comment]
Is it no longer there?

**Comment by jonw316** [comment]
Still there as far as I know.

**Comment by Ian-Hitt** [comment]
Yes, this location still exits. I can confirm it is working properly. Closing

**Comment by Ian-Hitt** [comment]
For reference, it is the UI.X Sidebar Navigation location.
