### ISSUE TITLE
[QAForums] Full styling on default XenForo style

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1413]
![q aforums_full_unanswered_threads_styling png](https://user-images.githubusercontent.com/32306910/51768967-5f2e2e00-20a7-11e9-8981-a9bfdf4ff30a.jpg)
This happens only on the default XenForo theme no matter what the entry amount.

**Comment by jonw316** [comment]
This is exactly the same as the built-in New threads widget.

I've had a quick search and can't see that anyone has reported this as a bug with XenForo, so might be worth reporting it (about the New threads widget obviously) and seeing what they say.

**Comment by daltonp** [comment]
I recently viewed the widget on some of our themes on both XF2 and XF2.1. The styling looks rather horrible even when viewing it on either iO or UI.X 2.

![6d49f2aa-3536-42d7-8e5f-ab5b7e0e35da png](https://user-images.githubusercontent.com/32306910/51921970-e0d6d200-23ad-11e9-8fcb-9e0178ae080d.jpg)
![435bbf1e-8a99-4f83-b260-08bacbfb6ae8 png](https://user-images.githubusercontent.com/32306910/51921972-e0d6d200-23ad-11e9-9975-656f666c565f.jpg)

**Comment by jonw316** [comment]
The bug is with XenForo. I will raise with them and see what their response is.

**Comment by jonw316** [comment]
https://xenforo.com/community/threads/new-threads-widget-doesnt-work-in-sidebar-with-display-style-set-to-full.160052/#post-1318931
