### ISSUE TITLE
Report server error to ThemeHouse

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#1415]
I happened to login to one of our preferred clients and noticed they had 39k errors. Our clients, though they should watch this, often times do not. And I was wondering if there is a solution we can build (into UI.X Pro add-on, a new system, etc.) to essentially log this somewhere for us. Not every single one, maybe just one message per day (9am CT) that ways X.com has X errors. Click here to view.

Thoughts?

**Comment by kylerc** [comment]
@JakeBooher any idea how well sentry would work for something like this?  Guessing it's not needed since XF already has an error log?  But figured I'd check.

**Comment by JakeBooher** [comment]
Something like this just isn't practical. There are people with dozens of add-ons installed No way to easily know that it is for sure caused by our add-on. Not to mention that error messages could potentially contain sensitive information I don't think this is something we want the liability of.
