### ISSUE TITLE
Spotify - Clickable song links in Now Playing/Most Played widgets/Show who is playing the song

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1420]
Allow the songs that show on the widgets to be clickable. When clicked they open the now playing overlay that is used elsewhere.

Also, it was also suggested to add attribution to the widgets so that it show's who's playing the song.

**Comment by petethumped** [comment]
one more: Can you put a time limit on the most played widget? Most played in last x days/weeks would be very useful.

**Comment by NerdfaceUK** [comment]
It depends how far you want to take the widgets and statistics for this add-on!

I'd love to see the amount of plays that a song has had for it to be amongst the "Most played", and be able to see who has listened to that song within the given timeframe (whether indefinitely, or a setting per the above suggestion).

An additional widget / notable member statistic could be "Most active streamers", and list the top X users by time spent listening to music..

**Comment by petethumped** [comment]
Not planned?
