### ISSUE TITLE
[Nodes] Node Grid Separators not changing layout on XF 2.1

### ISSUE THREAD

**Issue by kylerc** [Audentio/xf2addon-issues#1441]
Jon, take a look at this and see if you can figure it out.  Lmk if not.

Expected behavior would be that the layout changes after a separator within a category, but seems to only be applying the category layout and ignoring the separator's layout.  See Ticket 13040 for more info.

**Comment by kylerc** [comment]
@jonw316 Seems like node separators aren't outputting to the frontend.  https://github.com/Audentio/xf2/blob/master/src/addons/ThemeHouse/Nodes/_output/templates/public/th_node_list_separator_nodes.html used to be inserted into the node list and is how the JS recognizes when to switch layouts.  I think that this might also be the issue in ticket 12094

**Comment by jonw316** [comment]
If I understand correctly, looks like it is only outputting separators if you put them at the root level (depth = 1), and not if you put them inside a category (depth = 2).

**Comment by kylerc** [comment]
Ah okay,  it should end up outputting them at any depth so that might be the issue here.
