### ISSUE TITLE
Reactions and PHP 7.2 Compatibility - Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2addon-issues#145]
Add-on Name: Reactions

Add-on Version: Latest

XenForo Version: 2.0.2

Operating System (and Version): Windows 10 / 64-bit (latest stable)

Browser Name (and Version): Chrome 64 / 64-bit (latest stable)

Summary of issue: Compatibility check with PHP 7.2?

Detailed steps to reproduce the issue: I got a few random error log messages:

**Error 1 (of 2):**

**ErrorException: Template error: count(): Parameter must be an array or an object that implements Countable src/XF/Entity/User.php:566**
Generated by: Unknown account Feb 17, 2018 at 12:31 AM

Stack trace

#0 [internal function]: XF\Template\Templater->handleTemplateError(2, 'count(): Parame...', '/home/wtf/publi...', 566, Array)
#1 src/XF/Entity/User.php(566): count(NULL)
#2 [internal function]: XF\Entity\User->canChangeStyle()
#3 src/XF/Template/Templater.php(936): call_user_func_array(Array, Array)
#4 internal_data/code_cache/templates/l1/s0/public/PAGE_CONTAINER.php(1070): XF\Template\Templater->method(Object(Siropu\Shoutbox\XF\Entity\User), 'canChangeStyle', Array)
#5 src/XF/Template/Templater.php(1246): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array)
#6 src/XF/Pub/App.php(449): XF\Template\Templater->renderTemplate('PAGE_CONTAINER', Array)
#7 src/XF/App.php(1724): XF\Pub\App->renderPageHtml('\n\n\n\n\n\n\n\n\n\t\n\t\n\t\n...', Array, Object(XF\Mvc\Reply\View), Object(XF\Mvc\Renderer\Html))
#8 src/XF/Mvc/Dispatcher.php(310): XF\App->renderPage('\n\n\n\n\n\n\n\n\n\t\n\t\n\t\n...', Object(XF\Mvc\Reply\View), Object(XF\Mvc\Renderer\Html))
#9 src/XF/Mvc/Dispatcher.php(44): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#10 src/XF/App.php(1889): XF\Mvc\Dispatcher->run()
#11 src/XF.php(328): XF\App->run()
#12 index.php(13): XF::runApp('XF\\Pub\\App')
#13 {main}

Request state

array(4) {
  ["url"] => string(35) "/threads/this-vs-that.31131/page-54"
  ["referrer"] => bool(false)
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}

------------------

**ERROR 2 of 2**

**ErrorException: Template error: count(): Parameter must be an array or an object that implements Countable src/XF/Entity/User.php:557**
Generated by: Unknown account Feb 20, 2018 at 10:13 PM

Stack trace

#0 [internal function]: XF\Template\Templater->handleTemplateError(2, 'count(): Parame...', '/home/wtf/publi...', 557, Array)
#1 src/XF/Entity/User.php(557): count(false)
#2 [internal function]: XF\Entity\User->canChangeLanguage()
#3 src/XF/Template/Templater.php(936): call_user_func_array(Array, Array)
#4 internal_data/code_cache/templates/l0/s35/public/PAGE_CONTAINER.php(2931): XF\Template\Templater->method(Object(Siropu\Shoutbox\XF\Entity\User), 'canChangeLangua...', Array)
#5 src/XF/Template/Templater.php(1246): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array)
#6 src/XF/Pub/App.php(449): XF\Template\Templater->renderTemplate('PAGE_CONTAINER', Array)
#7 src/XF/App.php(1724): XF\Pub\App->renderPageHtml('\n\n\n\n\n\n\n\n\n\t<div ...', Array, Object(XF\Mvc\Reply\View), Object(XF\Mvc\Renderer\Html))
#8 src/XF/Mvc/Dispatcher.php(310): XF\App->renderPage('\n\n\n\n\n\n\n\n\n\t<div ...', Object(XF\Mvc\Reply\View), Object(XF\Mvc\Renderer\Html))
#9 src/XF/Mvc/Dispatcher.php(44): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#10 src/XF/App.php(1889): XF\Mvc\Dispatcher->run()
#11 src/XF.php(328): XF\App->run()
#12 index.php(13): XF::runApp('XF\\Pub\\App')
#13 {main}

Request state

array(4) {
  ["url"] => string(28) "/reactions/list/post/1046327"
  ["referrer"] => bool(false)
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}

Refer to here as well (where it was discussed in another company's add-on that there was a 7.2 compat issue with it that was later fixed:

https://xenforo.com/community/threads/user-ignore-limit.100961/post-1201580

**Comment by lilalien** [comment]
With this relate at all? Perhaps there are some deprecated variables?

This was also fixed at some point:
https://github.com/xfrocks/bdMedal/pull/2

**Comment by JakeBooher** [comment]
None of these appear to be related to Reactions, and seems more likely to be related to the filecache issues you've been having:

https://xenforo.com/community/threads/unsupported-operand-types.144584
https://xenforo.com/community/threads/undefined-index-user_selectable.143034
