### ISSUE TITLE
[TH] Nodes - Node icon are not working 

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#146]
Add-on Name: [TH] Nodes

Add-on Version: 1.0.2 Patch Level 1

XenForo Version: v2.0.2

Operating System (and Version): Windows 8

Browser Name (and Version): Chrome Version 64.0.3282.167

Summary of issue: Nodes icons aren't working with other styles which aren't set to default. Any icons you set on the default style show across all the other themes. But if you try to set different icons on the other themes that aren't the default style, they won't change at all.

Detailed steps to reproduce the issue:

Upload any screenshots related to the issue below

**Comment by kylerc** [comment]
@JakeBooher I'm not sure the technical details of how you implemented node icons, but is this working as you'd expect?

**Comment by LukasWieditz** [comment]
Cannot replicate this. Might be already fixed.
