### ISSUE TITLE
Reactions Plus - show first post reactions on discussion list

### ISSUE THREAD

**Issue by JakeBooher** [Audentio/xf2addon-issues#1468]

**Comment by lilalien** [comment]
Just a screeny to help...

![thread_list_reactplus_icons](https://user-images.githubusercontent.com/35111972/52436010-2fd4e380-2ae1-11e9-9558-0eb69dce18bc.png)

**Comment by JakeBooher** [comment]
Turns out this already exists in the default reactions system. In Style Properties -> Misc turn on "Show reaction summary on lists"

**Comment by lilalien** [comment]
@JakeBooher Perhaps as an enhancement, ReactPlus can bring back the counter feature to it which XF does not provide?

**Comment by JakeBooher** [comment]
This already exists in Style Properties -> Reactions Plus, should work here as well

**Comment by lilalien** [comment]
I'll take a look!
