### ISSUE TITLE
Topics - Ignoring "Replace new thread modal with thread topics modal'

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#1475]
Topics on XF 2.1.

**_Replace new thread modal with thread topics modal_** in Options seems to have no bearing on the Edit Topics Modal. It shows up all the time.

**Comment by jonw316** [comment]
This option is not to do with the Edit Topics modal. It is to do with the Create New Thread modal.

**Comment by ichpen** [comment]
Right and it is always triggered so still an issue for me.

**Comment by jonw316** [comment]
Your other bug report is indeed a bug, but this one isn't.
