### ISSUE TITLE
[Donate] Editing a donation does not take the date format into account

### ISSUE THREAD

**Issue by jonw316** [Audentio/xf2addon-issues#1485]

**Comment by setoy** [comment]
Uhm, is this fixed now or is this actually `as designed`?

**Comment by jonw316** [comment]
Unless I've misunderstood, this is exactly the same as everywhere else in XenForo admin panel that asks for a date. So it is ```as designed```.

**Comment by setoy** [comment]
Mhmm I currently have no idea where a date picker is used on any page in the admin cp, so I couldn't check. Gotta live with it, then.
