### ISSUE TITLE
Reactions Plus - Watched Threads Icon Alignment on ThreadList

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2addon-issues#1494]
Add-on Name: Reactions Plus

Add-on Version: 2.1

XenForo Version: 2.1

Operating System: Windows 10 / 64-Bit (Latest Stable)

Browser Name (and Version): Chrome 72 / 64 Bit (Latest Stable)

Summary of issue: When viewing the threadlist, the watched thread icon is still on the right, when it should be grouped with the other icons such as LOCKED THREAD and POLL. You'll see in the screenshot that the XF-supplied thread STATUS icons should be grouped together for attractiveness.

Screenshot to help:

![reactions_plus_watched_threads_icon_alignment_bug](https://user-images.githubusercontent.com/35111972/52594279-1b625500-2e19-11e9-8448-9c7ed3a308b4.png)

**Comment by JakeBooher** [comment]
This entire section is handled entirely by XenForo, and this bug appears on the default style without Reactions Plus. Going to close this issue and report it to them 👍
