### ISSUE TITLE
Threads and posts: Perhaps OP banner can just be like a userBanner? To show with other userBanners

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#15]
I dont like it overlapping avatar, that should be a theme decision.

**Comment by JakeBooher** [comment]
There is a style property for this already

**Comment by mikecreuzer** [comment]
Can you make that the default style property?

**Comment by LukasWieditz** [comment]
This ticket is so ancient, is this still a thing?

**Comment by JakeBooher** [comment]
Nope, threads and posts isn't a thing anymore
