### ISSUE TITLE
Reactions: Reaction button doesn't work on overlay

### ISSUE THREAD

**Issue by JakeBooher** [Audentio/xf2addon-issues#150]
https://xenforo.com/community/threads/th-reactions-paid.134133/page-31#post-1229270

![918707c5-7ec8-4290-a9d4-ec31c67a658e](https://user-images.githubusercontent.com/179180/37052740-c4ddeb9a-213f-11e8-9582-8a4773e28df3.png)

**Comment by Nirjonadda** [comment]
@JakeBooher @kylerc Do you have any update?
