### ISSUE TITLE
Spotify - Allow administrators the ability to set specific songs from Spotify play when their users are on the forum

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1512]
Suggested by [RobinHood](https://xenforo.com/community/threads/th-spotify-paid.145257/post-1323786) on XenForo:

> How bizarre. I'd not seen SCM used in years, then today I come across a forum with it installed so they can have spooky music playing and follow them around the site. I wonder if something similar could be done with the spotify player.
> 
> Example Link: http://nightlyfrights.forumotion.com/

**Comment by JakeBooher** [comment]
Unfortunately this isn't really possible, most browsers disable autoplay now - even if they didn't it would restart the song on every page load since XenForo is not an SPA
