### ISSUE TITLE
Reactions: Hard coded phrase Reactions icon on mouse over

### ISSUE THREAD

**Issue by jOOc** [Audentio/xf2addon-issues#152]
Add-on Name: Reactions

Add-on Version: 1.0.9 Patch Level 4a

XenForo Version: 2.0.3

Operating System (and Version): Windows 10

Browser Name (and Version): Chrome

Summary of issue: Hard coded phrase "Reactions" shows on mouse over

Detailed steps to reproduce the issue:

Upload any screenshots related to the issue below
![image](https://user-images.githubusercontent.com/9382342/37537796-ea418a10-294e-11e8-9d73-a66e506054c2.png)

**Comment by kylerc** [comment]
@jOOc Thanks for the bug report.  This will be changed to use the correct phrase in our next update for Reactions.
