### ISSUE TITLE
[Donate] Missing template: news_feed_item_thdonate_campaign_react

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#1520]
Guys this is still an issue: 
#1127 and #1352 shows as closed (maybe related). Can someone please quash this bug?  Thanks.

TH Donate 1.0.5

ErrorException: Template error: Template public:news_feed_item_thdonate_campaign_react is unknown src/XF/Template/Templater.php:584
Generated by: Unknown account Feb 18, 2019 at 9:52 PM
Stack trace
#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Template public...', '/home/nginx/dom...', 584, Array)
#1 src/XF/Template/Templater.php(584): trigger_error('Template public...', 512)
#2 src/XF/Template/Templater.php(539): XF\Template\Templater->getTemplateData('public', 'news_feed_item_...')
#3 src/XF/Template/Templater.php(1249): XF\Template\Templater->getTemplateCode('public', 'news_feed_item_...')
#4 src/addons/ThemeHouse/Reactions/React/AbstractHandler.php(384): XF\Template\Templater->renderTemplate('news_feed_item_...', Array)
#5 src/addons/ThemeHouse/Reactions/Entity/ReactedContent.php(140): ThemeHouse\Reactions\React\AbstractHandler->render(Object(ThemeHouse\Reactions\Entity\ReactedContent))
#6 [internal function]: ThemeHouse\Reactions\Entity\ReactedContent->render()
#7 src/XF/Template/Templater.php(940): call_user_func_array(Array, Array)
#8 internal_data/code_cache/templates/l1/s7/public/threact_member_reactions.php(59): XF\Template\Templater->method(Object(ThemeHouse\Reactions\Entity\ReactedContent), 'render', Array)
#9 src/XF/Template/Templater.php(1250): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array)
#10 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('threact_member_...', Array)
#11 src/XF/Mvc/Renderer/Html.php(48): XF\Template\Template->render()
#12 src/XF/Mvc/Dispatcher.php(332): XF\Mvc\Renderer\Html->renderView('ThemeHouse\\Reac...', 'public:threact_...', Array)
#13 src/XF/Mvc/Dispatcher.php(303): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#14 src/XF/Mvc/Dispatcher.php(44): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#15 src/XF/App.php(1934): XF\Mvc\Dispatcher->run()
#16 src/XF.php(333): XF\App->run()
#17 index.php(13): XF::runApp('XF\\Pub\\App')
#18 {main}
Request state
array(4) {
  ["url"] => string(57) "/members/nik.1/reactions?reaction_id=2&type=given&page=34"
  ["referrer"] => string(91) "https://mysite.com/members/nik.1/reactions?reaction_id=2&type=given&page=34"
  ["_GET"] => array(4) {
    ["/members/nik_1/reactions"] => string(0) ""
    ["reaction_id"] => string(1) "2"
    ["type"] => string(5) "given"
    ["page"] => string(2) "34"
  }
  ["_POST"] => array(0) {
  }
}

**Comment by jonw316** [comment]
Any idea when you are getting this error? Is this only happening when either add-on has been disabled/uninstalled for example?

That template definitely exists in the latest version.

**Comment by jonw316** [comment]
Never mind, just realised the template name is different. This is not the same bug as #1352.

**Comment by ichpen** [comment]
Thanks @jonw316

**Comment by LukasWieditz** [comment]
@jonw316 unless this is relevant for XF 2.1., we can close this and recommend creating an empty template as workaround. Getting the 1.1.0 release out should take priority.
