### ISSUE TITLE
[Topics] Multiple Topics Overlap

### ISSUE THREAD

**Issue by Chazza** [Audentio/xf2addon-issues#1523]
Add-on Name: Topics

Add-on Version: 1.0.2

XenForo Version: 2.1.0

Operating System (and Version): CentOS, 7.2

Browser Name (and Version): Chrome, 72.0.3626.109 

Summary of issue: When viewing threads with topics, they seem to not show fully. Furthermore, when hovering over they seem to show beneath the watch icon (iO Theme).

Detailed steps to reproduce the issue:
- Add multiple topics to a thread.
- Go to the node where that thread is listed.

Upload any screenshots related to the issue below
![image](https://user-images.githubusercontent.com/47271716/53034734-bdaeb800-346b-11e9-93ee-900d2fa9ef87.png)
![image](https://user-images.githubusercontent.com/47271716/53034746-c3a49900-346b-11e9-8eb6-ab1b673805d4.png)

**Comment by mikecreuzer** [comment]
Indeed the same bug, can close this: https://github.com/Audentio/xf2addon-issues/issues/1550
