### ISSUE TITLE
[Reactions] - Error importing from Post Ratings (1.5) to [TH] Reactions on XF2.1. Saw it after clicking "Finalize Import"

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1530]
Issue experienced by Solidus on XenForo.com - Link [here](https://xenforo.com/community/threads/th-reactions-paid.134133/post-1327490)
> XF\Db\Exception: MySQL statement prepare error [1146]: Table 'test_xf2.xf_liked_content' doesn't exist in src/XF/Db/AbstractStatement.php at line 217
> 
>     XF\Db\AbstractStatement->getException() in src/XF/Db/Mysqli/Statement.php at line 196
>     XF\Db\Mysqli\Statement->getException() in src/XF/Db/Mysqli/Statement.php at line 39
>     XF\Db\Mysqli\Statement->prepare() in src/XF/Db/Mysqli/Statement.php at line 54
>     XF\Db\Mysqli\Statement->execute() in src/XF/Db/AbstractAdapter.php at line 89
>     XF\Db\AbstractAdapter->query() in src/XF/Db/AbstractAdapter.php at line 121
>     XF\Db\AbstractAdapter->fetchAllColumn() in src/addons/ThemeHouse/Reactions/Job/ConvertLike.php at line 43
>     ThemeHouse\Reactions\Job\ConvertLike->getNextIds() in src/XF/Job/AbstractRebuildJob.php at line 30
>     XF\Job\AbstractRebuildJob->run() in src/XF/Job/Atomic.php at line 38
>     XF\Job\Atomic->run() in src/XF/Job/Manager.php at line 253
>     XF\Job\Manager->runJobInternal() in src/XF/Job/Manager.php at line 195
>     XF\Job\Manager->runJobEntry() in src/XF/Job/Manager.php at line 111
>     XF\Job\Manager->runByIds() in src/XF/Admin/Controller/Tools.php at line 120
>     XF\Admin\Controller\Tools->actionRunJob() in src/XF/Mvc/Dispatcher.php at line 321
>     XF\Mvc\Dispatcher->dispatchClass() in src/XF/Mvc/Dispatcher.php at line 244
>     XF\Mvc\Dispatcher->dispatchFromMatch() in src/XF/Mvc/Dispatcher.php at line 100
>     XF\Mvc\Dispatcher->dispatchLoop() in src/XF/Mvc/Dispatcher.php at line 50
>     XF\Mvc\Dispatcher->run() in src/XF/App.php at line 2177
>     XF\App->run() in src/XF.php at line 390
>     XF::runApp() in admin.php at line 13

**Comment by JakeBooher** [comment]
Reactions doesn't support XenForo 2.1
