### ISSUE TITLE
[Covers] Save button is shown and grayed out when uploading a profile cover image

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1572]
Is it normal that the "Save" button be visible or grayed out when setting a cover image on your profile?
![image](https://user-images.githubusercontent.com/32306910/54043613-a8879800-4192-11e9-911d-d9a2e7067396.png)
Once you refresh the page it goes away.

**Comment by jonw316** [comment]
Technically this is correct as it has already been saved. I do find it odd that you have to click 'Cancel' after uploading though.

**Comment by LukasWieditz** [comment]
The button should be renamed to "save position" and always be clickable. The cover has been saved during the upload already anyway.
