### ISSUE TITLE
[Reaction Plus] SVGs need a size in ACP

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#1574]
See below. As they're SVGs you need to stipulate a 32x32 size for the ACP view or you need to provide SVGs with height and width stipulated within. If I stipulate a 32 size in ACP then they get rendered at 32 across the whole forum which breaks a number of views.

I think you need to supply a few svg variants for these. 

![react-admin](https://user-images.githubusercontent.com/5346876/54078072-f46c3700-428f-11e9-9299-07c59698e55c.png)

**Comment by ichpen** [comment]
If you want to save 2 mins of find/replace I have changed all your standard SVG width/height to 32px. Let me know and I'll send them back to you.

**Comment by JakeBooher** [comment]
These SVGs aren't included with Reactions Plus, they were included with our Reactions add-on for xf2.0 and were imported. Ultimately though, this is something I've reported to XenForo and they're calling it as designed:
https://xenforo.com/community/threads/no-easy-way-to-control-width-height-of-reactions-that-are-not-in-a-sprite-sheet.159298/

This isn't limited to just SVGs either, if you have a 2x image (PNG, JPEG, GIF, etc) that you want to use you'll run into the same issue
