### ISSUE TITLE
[Reaction Plus] ACP Error - Function th_reaction is unknown

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#1576]
Getting boat loads of the below since upgrading to 2.1 and reactions plus.

ErrorException: Template error: Function th_reaction is unknown src/XF/Template/Templater.php:893
Generated by: Black 03 Z06 Mar 9, 2019 at 4:58 PM
Stack trace
#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Function th_rea...', '/home/nginx/dom...', 893, Array)
#1 src/XF/Template/Templater.php(893): trigger_error('Function th_rea...', 512)
#2 internal_data/code_cache/templates/l1/s7/public/alert_post_react.php(9): XF\Template\Templater->fn('th_reaction', Array, true)
#3 src/XF/Template/Templater.php(1294): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array)
#4 src/XF/Alert/AbstractHandler.php(80): XF\Template\Templater->renderTemplate('alert_post_reac...', Array)
#5 src/XF/Entity/UserAlert.php(69): XF\Alert\AbstractHandler->render(Object(XF\Entity\UserAlert))
#6 [internal function]: XF\Entity\UserAlert->render()
#7 src/XF/Template/Templater.php(978): call_user_func_array(Array, Array)
#8 internal_data/code_cache/templates/l1/s7/public/alert_macros.php(18): XF\Template\Templater->method(Object(XF\Entity\UserAlert), 'render', Array)
#9 src/XF/Template/Templater.php(694): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array, Array)
#10 internal_data/code_cache/templates/l1/s7/public/account_alerts_popup.php(18): XF\Template\Templater->callMacro('alert_macros', 'row', Array, Array)
#11 src/XF/Template/Templater.php(1294): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array)
#12 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('account_alerts_...', Array)
#13 src/XF/Mvc/Renderer/Json.php(84): XF\Template\Template->render()
#14 src/XF/Mvc/Renderer/Json.php(68): XF\Mvc\Renderer\Json->renderHtmlFallback('XF:Account\\Aler...', 'public:account_...', Array)
#15 src/XF/Mvc/Dispatcher.php(418): XF\Mvc\Renderer\Json->renderView('XF:Account\\Aler...', 'public:account_...', Array)
#16 src/XF/Mvc/Dispatcher.php(400): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Json), Object(XF\Mvc\Reply\View))
#17 src/XF/Mvc/Dispatcher.php(360): XF\Mvc\Dispatcher->renderReply(Object(XF\Mvc\Renderer\Json), Object(XF\Mvc\Reply\View))
#18 src/XF/Mvc/Dispatcher.php(53): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'json')
#19 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#20 src/XF.php(390): XF\App->run()
#21 index.php(20): XF::runApp('XF\\Pub\\App')
#22 {main}
Request state
array(4) {
  ["url"] => string(145) "/account/alerts-popup?_xfRequestUri=%2F&_xfWithData=1&_xfToken=1552168720%2C823e0007a6607a22d62c778f10459586&_xfResponseType=json&_=1552168721959"
  ["referrer"] => string(35) "https://mysite.com/"
  ["_GET"] => array(6) {
    ["/account/alerts-popup"] => string(0) ""
    ["_xfRequestUri"] => string(1) "/"
    ["_xfWithData"] => string(1) "1"
    ["_xfToken"] => string(43) "1552168720,823e0007a6607a22d62c778f10459586"
    ["_xfResponseType"] => string(4) "json"
    ["_"] => string(13) "1552168721959"
  }
  ["_POST"] => array(0) {
  }
}

**Comment by JakeBooher** [comment]
This is because you still have [TH] Reactions installed, but likely disabled so that template function doesn't exist. You'll want to uninstall Reactions if you've confirmed everything has imported into Reactions Plus correctly
