### ISSUE TITLE
[Reaction Plus] Mobile View has serious issues

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#1577]
Two issues with Advanced Picker for Reactions Plus.

1. Long press to trigger picker automatically marks post as Liked (even though you've not picked any reaction  yet).
2. Once picker is up there's no way out without clicking out of bounds leaving the above Like which then needs to be manually removed. So need an X in there to close. 
3. Need to remove Search reaction field as it will never be used on mobile.

**Comment by JakeBooher** [comment]
1/2 I'll have a look into
3. Why wouldn't someone use it on mobile?

**Comment by JakeBooher** [comment]
I believe all of this was fixed, and was due to an issue in your custom theme
