### ISSUE TITLE
Spotify - Missing Stock Widgets

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#158]

**Comment by JakeBooher** [comment]
What "stock widgets" are you referring to?

**Comment by mikecreuzer** [comment]
Talked on the phone about this yesterday. Top x songs and people currently listening and to what song.

**Comment by mikecreuzer** [comment]
@JakeBooher this was done correct?

**Comment by LukasWieditz** [comment]
Spotify doesn't have any widgets atm.
