### ISSUE TITLE
[Monetize] Fix styling issues on upgrade page

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xf2addon-issues#1580]
- [x] The feature bullet points/icons aren't centered with the text.

- [x] The pop-up with the user upgrade page with the "More" button at the bottom directs to the XF upgrade page, not the Monetize upgrade page even though the "Show as accounts page" is enabled.

- [x] The upgrade options boxes overlap the bottom box that has the link for "more".

- [ ] Make an option to adjust the text size of the dollar amount.

**Comment by jonw316** [comment]
> The pop-up with the user upgrade page with the "More" button at the bottom directs to the XF upgrade page, not the Monetize upgrade page even though the "Show as accounts page" is enabled.
This is correct. The XF upgrade page shows all the available upgrades, so it fits the description of "more".
