### ISSUE TITLE
Monetize - Snippet length considers whitespace? 

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#1581]
I counted manually and on a setting with 30, I got 22 characters.

**Comment by jonw316** [comment]
This is just using the standard XenForo snippet tool, which includes whitespace and only snips at the end of words and not mid-word, so sometimes it will be 30 and sometimes it will be less. I think it might also count each of the dots as a character.

I could replace with a more basic snipper that just takes the first 30 characters no matter what, but I actually prefer XenForo's implementation.
