### ISSUE TITLE
[Covers] A grey cover is automatically added

### ISSUE THREAD

**Issue by setoy** [Audentio/xf2addon-issues#1590]
When a user views their forum profile (or clicks "modify cover image"), a grey cover is seemingly added automatically even though the user never selected a preset or uploaded an image.

**Comment by jonw316** [comment]
Do you have a screenshot? Isn't this just the default styling for when there is no cover?

**Comment by setoy** [comment]
Default Styling: https://abload.de/img/defaultlckwx.png

Sometimes (not always) the grey cover is added: https://abload.de/img/greyb0jsr.png

>  Isn't this just the default styling for when there is no cover?

Your comment makes it look like the actual error is that sometimes that grey box is *not* added?

**Comment by jonw316** [comment]
And you are getting the second 'grey cover' being added just by visiting a user's profile? Is it possible that a user has just set their cover to be the 'none' preset? Can you replicate this with a brand new user?

**Comment by setoy** [comment]
It happens randomly - sometimes by simply visiting their profile (as a different user, not their own profile) and sometimes by simply invoking the "preset modal" without actually selecting anything (no actual preset and not "none") and closing it right after.

**Comment by jonw316** [comment]
Hmmm... I'm still struggling to replicate this. It probably isn't random, so if you manage to figure out the exact steps that cause this to happen, can you let me know? I'll just keep this open for now.

**Comment by setoy** [comment]
Will do

**Comment by setoy** [comment]
Might indeed have something to do with selecting `None` as a preset... My users have no permission to style their cover, so uploading (or downloading) a cover is their only option. I think it'd be more accurate to not add any cover when the `None` preset is selected but no permission to style cover exists as to not add this "grey" cover.

What do you think?

**Comment by LukasWieditz** [comment]
The grey is very likely just the background color, the actual cover would be transparent. I've noticed and fixed a similar issue, but it requires the following steps:

1. Delete any existing cover (as in: currently no cover)
2. Click "Style cover" and save with an empty "Background color" field
3. Select "none" preset

But that bug very specifically requires the second step to be performed. As you said your users don't have permission to use the "Style cover", I don't think that's the bug we were searching for. As such, I unfortunately can't replicate this either.

**Comment by setoy** [comment]
I don't understand this. When I delete any "non-existing" cover, how could I select "Style Cover"?

**Comment by LukasWieditz** [comment]
You do not need a cover image to apply styling. It's entirely possible to have a background-color only cover.

**Comment by setoy** [comment]
Alright, my cover list in my AdminCP looks like this:
![image](https://user-images.githubusercontent.com/6497266/56907441-87fa0100-6aa4-11e9-9d69-8b3bb2c42ae4.png)

Those grey ones are the ones that were never uploaded by my users. It is shown like this in their profile:
![image](https://user-images.githubusercontent.com/6497266/56907492-a8c25680-6aa4-11e9-84e1-e6e65019e0d5.png)

When deleting it, it gets back to "normal":
![image](https://user-images.githubusercontent.com/6497266/56907543-c4c5f800-6aa4-11e9-9dbc-ba04635e4931.png)

That cannot be how it should be, can it?
