### ISSUE TITLE
[Covers] Permissions not always being respected

### ISSUE THREAD

**Issue by jonw316** [Audentio/xf2addon-issues#1594]
Hello there,

the permissions mentioned above all seem to allow or disallow the same kind of functionality - or is there some difference to it?

I've looked into the documentation but it is vague, too.

A user of mine has the following permissions:

Use cover on profile Yes

Can edit cover Yes

Can set cover image No

Can upload cover image Yes

However, despite the Can set cover image permission being "no", they can upload images and set them as their cover.

Why is that? What is the difference in all those permissions?

Thanks!

**Comment by setoy** [comment]
I just added a major security issue as a response to my Ticket (13474)

**Comment by LukasWieditz** [comment]
The security issue has been addressed and a fix has been released.
