### ISSUE TITLE
Attachment webp support

### ISSUE THREAD

**Issue by kylerc** [Audentio/xf2addon-issues#1595]
Adding this would have the downside of increasing storage space needed to store webp and a fallback format, but with webp now supported in all major browsers I think adding an option to enable webp output would be potentially interesting.  Looks like Kraken easily supports this https://kraken.io/docs/webp-compression and php has a built in encoding for this I believe?  Not entirely sure the technical work needed to support this, but bandwidth savings are ~30% on average so I'd guess some sites would use this.  Thoughts?

**Comment by jonw316** [comment]
Apparently you can just include a Javascript to support it in older browsers, so no fallback needed necessarily. I assume Image Optimizer always just keeps a fallback anyway though?

**Comment by kylerc** [comment]
Oh darn, guess I thought I had seen safari had support but they don't (yet) so only 75% on caniuse.  Still quite a reduction in image size though for a large percentage of users.  The fallback image would be in a format that isn't webp (likely jpg / png depending on lossy or not) so that browsers that can't render webp still can display an image.  https://css-tricks.com/using-webp-images/#article-header-id-3 essentially walks through how to display the images in a way that will fallback on non-supported browsers which would need some additional addon support.

**Comment by jonw316** [comment]
I was referring to this: http://webpjs.appspot.com/

**Comment by kylerc** [comment]
Oh, huh didn't know that was a thing that existed.  So that essentially converts the .webp file into a canvas it renders client side for unsupported browsers?  Not sure what the performance impact is, but that could be another option if an admin doesn't want to dedicate additional space to the fallback image.
