### ISSUE TITLE
[Monetize] Sponsors on Node alignment

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xf2addon-issues#1597]
I tried to add Sponsors to Nodes on the demo and it didn't look right. The node name isn't aligned correctly. 

<img width="940" alt="Screen Shot 2019-03-14 at 2 29 33 PM" src="https://user-images.githubusercontent.com/43186749/54386073-2d2c5780-4666-11e9-933c-f80ee25841d7.png">

**Comment by jonw316** [comment]
@Ian-Hitt Is there anything we can do about this which doesn't involve adding extra CSS styling to the node title?

**Comment by jonw316** [comment]
I don't think there is anything we can do about this. I think the answer to this is just going to be to encourage admins to use smaller sponsor logos or they need to apply custom CSS, but I don't think our add-on should be messing with the CSS for the node title.
