### ISSUE TITLE
[QA Forums] Add thread-option to allow voting on initial post in thread

### ISSUE THREAD

**Issue by setoy** [Audentio/xf2addon-issues#1601]
It'd be neat, for example for "Suggestions" forums, to be able to vote on the first post of a thread. This would, of course, not allow to select the first post as the "best answer".

Preferably this would be controllable through permissions to allow or disallow specific users / user groups to create questions with voting ability on the first post.

**Comment by JakeBooher** [comment]
This doesn't really seem like it's in scope with the intended use of this add-on, could probably make use of reactions for this as you're able to sort by reaction score. You could setup a 👍 and 👎 reaction that is either positive or negative

**Comment by mikecreuzer** [comment]
I personally want this as well, but indeed a new addon of some kind @JakeBooher - would we be able to expore a new addon where we can pull the UI out and a few other things?

**Comment by JakeBooher** [comment]
This is something Reactions already does, seems unnecessary to create another add-on to do the same thing

**Comment by mikecreuzer** [comment]
Well, kinda. Its just not a very good interace, not intuitive. I dont think its right that XF does this either for their suggestions as the score is not communicated.

**Comment by JakeBooher** [comment]
So just split out the up/downvote functionality and add it only to threads? Or is there something else it should do?

**Comment by mikecreuzer** [comment]
I dont think so, I think itd be fairly quick. I wanted this for Geex and didn't find Reactions to be the solution as you only care about Upvotes on a new topic. Id argue its fairly simple and doesnt really need any major features either.

**Comment by setoy** [comment]
I don't think butchering Reactions to do this is the right approach. QA Forums already does voting on posts, so why not simply make it configurable per-node or per thread (permission based)? This way you don't need to strip out all functionality for a new product (although you could charge extra because it's an extra product).

**Comment by mikecreuzer** [comment]
QA wont be a good fit for this addon @setoy but I think a new addon could make sense and be rather quick and simple to do.

**Comment by setoy** [comment]
Alright. I hope this integrates (or rather: co-exists) nicely with QA Forums then as I plan to use both add-ons in my forum when the time comes :)
