### ISSUE TITLE
[Reactions Plus] LogicException: Must set a reaction ID when importing from Post Ratings

### ISSUE THREAD

**Issue by jonw316** [Audentio/xf2addon-issues#1606]
Ticket 13580

When trying to import post ratings, I get the following error:

Expat Indo Forum - Information and Community for Expats in Indonesia
LogicException: Must set a reaction ID in src/XF/Import/Data/ReactionContent.php at line 26
XF\Import\Data\ReactionContent->preSave() in src/XF/Import/Data/AbstractData.php at line 112
XF\Import\Data\AbstractData->save() in src/addons/ThemeHouse/ReactPlus/Import/Importer/DarkPostRatings.php at line 161
ThemeHouse\ReactPlus\Import\Importer\DarkPostRatings->stepReactionContent() in src/XF/Import/Runner.php at line 231
XF\Import\Runner->runStep() in src/XF/Import/Runner.php at line 59
XF\Import\Runner->run() in src/XF/Admin/Controller/Import.php at line 234
XF\Admin\Controller\Import->actionRun() in src/XF/Mvc/Dispatcher.php at line 321
XF\Mvc\Dispatcher->dispatchClass() in src/XF/Mvc/Dispatcher.php at line 248
XF\Mvc\Dispatcher->dispatchFromMatch() in src/XF/Mvc/Dispatcher.php at line 100
XF\Mvc\Dispatcher->dispatchLoop() in src/XF/Mvc/Dispatcher.php at line 50
XF\Mvc\Dispatcher->run() in src/XF/App.php at line 2177
XF\App->run() in src/XF.php at line 390
XF::runApp() in admin.php at line 13

**Comment by JakeBooher** [comment]
This was already fixed in another issue
