### ISSUE TITLE
Donation History Pagination Does Not Work

### ISSUE THREAD

**Issue by jljr222** [Audentio/xf2addon-issues#161]
Add-on Name: Donate

Add-on Version: 1.0.0

XenForo Version: 2.0.4

Operating System (and Version): Windows 10

Browser Name (and Version): Chrome (Latest)

Summary of issue: When I click on the pagination for campaign history that has been imported, it doesn't do anything. It just loads the same page.

Detailed steps to reproduce the issue: https://www.bor3dgaming.com/donate/ You can see it happening if you try to click the pagination for my campaign.

Upload any screenshots related to the issue below

**Comment by JakeBooher** [comment]
Looks like this is related to the redirects we do when there is only one campaign, will be resolved in next update :)
