### ISSUE TITLE
[Donate] Phrase missing in Rebuild caches

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1610]
![ScreenShot00942](https://user-images.githubusercontent.com/6899856/54856385-919c8600-4cfa-11e9-8eb8-5033d3431e8d.png)

**Comment by setoy** [comment]
https://github.com/Audentio/xf2addon-issues/issues/1543

**Comment by Nirjonadda** [comment]
@setoy I think two are different because one of `Rebuild likes counted status` and one of `Rebuild Reactions counted status` ?

**Comment by jonw316** [comment]
The screenshot is different but the error is the same.

**Comment by Nirjonadda** [comment]
@jonw316 Yes error are same but does donate add-on added this `Rebuild likes counted status` Rebuild caches? As i know xenforo 2.1 are not using any more like. So this are now `Rebuild Reactions counted status`?

**Comment by jonw316** [comment]
If it is a bug with XenForo 2.0, then the next version will only support XenForo 2.1, so we won't be fixing this.

**Comment by Nirjonadda** [comment]
Oh so you will remove the `Rebuild likes counted status` from Rebuild caches page. I am asking because confused that why two Rebuild likes and Reactions counted status in Rebuild caches page, Thanks

![ScreenShot00957](https://user-images.githubusercontent.com/6899856/54869848-bba78400-4d9e-11e9-9924-308a9202b262.png)

**Comment by jonw316** [comment]
We will be replacing likes with reactions in the next version, yes. That is why it can only support XenForo 2.1.
