### ISSUE TITLE
[Donate] Custom entered donations are not shown in user profile

### ISSUE THREAD

**Issue by setoy** [Audentio/xf2addon-issues#1612]
Maybe has something to do with them not being indexed correctly (https://github.com/Audentio/xf2addon-issues/issues/1522)?

A user donated **an undisclosed amount** on a third party site that was subsequently entered manually into the appropriate campaign. It showed in the campaign correctly, but is not visible in the users profile.

**Comment by jonw316** [comment]
Does rebuilding the search index fix this?

**Comment by setoy** [comment]
Do you actually mean the **search** index? As the search index rebuild tool has no `donation` content type.

**Comment by jonw316** [comment]
Probably not that then. Oops.

**Comment by setoy** [comment]
I could try running the `Rebuild user donation caches` if you suggest doing so?

**Comment by jonw316** [comment]
You could try.

**Comment by setoy** [comment]
Na, didn't change anything. On a side note: you got an ETA on when you're going to release the 1.1.0 Beta 5 version that I'm currently running into stable?

**Comment by jonw316** [comment]
Good to know. I'll make sure manual donations get added into that cache then. Not sure why they are not being added.

As far as ETA, I couldn't say, although there are still some other bugs need fixing (like this one) that we would ideally fix first.

**Comment by jonw316** [comment]
I'm struggling to replicate this now.
