### ISSUE TITLE
[Reactions Plus] Allow users to click on an existing reaction in the like summary without the need to use the reactions picker

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1614]
Allow users to click on an existing reaction within the like summary without the need to use the reaction chooser. This was suggested by [AndrewC73](https://xenforo.com/community/threads/th-reactions-plus-paid.161636/post-1336588) on XenForo.

> Is there any hope that the ability to click on an existing reaction in the like summary on a message will use that reaction for the post, instead of having to go into the reaction chooser? (For example, if someone has already liked the post, clicking on the icon for the reaction will react that way as well). It was a nice feature of the previous reactions plugin. Also, do you think you'll ever be able to implement multiple reactions to the same message? That is really missed, though I understand it's a limitation of Xenforo's reaction implementation.

**Comment by JakeBooher** [comment]
Unfortunately because of the way XenForo handles rendering the reaction bar this isn't something that can be done feasibly at this time
