### ISSUE TITLE
[Covers] Choose cover preset phrase is missing in administrative panel

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1617]
![image](https://user-images.githubusercontent.com/32306910/54934691-f1f31980-4eec-11e9-8444-6eb50dd72002.png)
Content -> [TH] Covers -> Cover List -> Choose a cover to edit -> Click "Choose cover preset"

**Comment by setoy** [comment]
https://github.com/Audentio/xf2addon-issues/issues/1586
