### ISSUE TITLE
Conflict with Snog Advanced Forms (2): Template error: Cannot call method getFlattened on a non-object (NULL)

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#1618]
As per Snog's investigation:
https://xenforo.com/community/threads/advanced-forms-for-xenforo-2-1-paid.133580/post-1337804

@LukasWieditz was kind enough to look into this with the previous issue. Have a peek at what Snog wrote in the thread above.

Thanks.

**Comment by JakeBooher** [comment]
@ichpen what add-on is this for?

**Comment by JakeBooher** [comment]
From talking to him it seems that the actual error that was triggered has been resolved. I've been talking to him about a solution that would allow changes to work on both his list page as well as the tabbed method that comes by default in XenForo, so I'm going to go ahead and close this as there is no longer an error
