### ISSUE TITLE
Donating Does Not Go Through

### ISSUE THREAD

**Issue by jljr222** [Audentio/xf2addon-issues#162]
Add-on Name: Donate

Add-on Version: 1.0.0

XenForo Version: 2.0.4

Operating System (and Version): Windows 10

Browser Name (and Version): Chrome

Summary of issue: I attempted to run a fake donation on my installation, but I received some errors when attempting to donate.

Detailed steps to reproduce the issue: https://www.bor3dgaming.com/donate/ If you try to click the "Purchase" button then it doesn't do anything. If you check the console you will notice 404 errors.

Upload any screenshots related to the issue below
![image](https://user-images.githubusercontent.com/3527321/38217776-801847e4-369d-11e8-83f5-c051ea8b57e2.png)
![image](https://user-images.githubusercontent.com/3527321/38217784-8cd13b94-369d-11e8-847f-e6dcfa4c9cad.png)

**Comment by JakeBooher** [comment]
I can't replicate this issue, have sent you a message via Slack for additional details @jljr222
