### ISSUE TITLE
"Can set cover image" permission still not being respected

### ISSUE THREAD

**Issue by setoy** [Audentio/xf2addon-issues#1620]
Hi there,

I think this should have been fixed (https://github.com/Audentio/xf2addon-issues/issues/1594), but my user got the following permissions:

```
[TH] Covers permissions
Can view covers
Yes (Details)
Use covers on resources
No (Details)
Use cover on threads
No (Details)
Use cover on profile
Yes (Details)
Can edit cover
Yes (Details)
Can set cover image
No (Details)
Can upload cover image
Yes (Details)
Can download cover image
Yes (Details)
Can position cover image
Yes (Details)
Can style cover
No (Details)
Can use presets
Yes (Details)
Can delete cover
Yes (Details)
```

Although they don't have the `Can set cover image` permission, they can change their current cover image to something else (it being presets or upload a new one). It might be that I do not understand this permission correctly as it (in my opinion) directly collides with the `Use cover on profile` permission, but I thought to report it anyway.

If I'm mistaken: What is the `Can set cover image` permission actually doing?

Thanks

**Comment by jonw316** [comment]
The can set cover image is now for setting a cover image if one is not currently set. What you have described is correct I think.
