### ISSUE TITLE
[Covers] Profiles menu text

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1623]
Profiles menu text hard to read. Please improve this text more visible and readable.

![ScreenShot00976](https://user-images.githubusercontent.com/6899856/55158550-84025880-515f-11e9-8112-977d13128a03.png)

**Comment by Nirjonadda** [comment]
@LukasWieditz Please make sure this fix made for Covers 1.0.2?

**Comment by LukasWieditz** [comment]
There's no need to bump issues. We're aware of our log and will fix them when we get to them.
