### ISSUE TITLE
Documentation refers to non-existent XML

### ISSUE THREAD

**Issue by chrissnell** [Audentio/xf2addon-issues#1624]
Add-on Name: UI-X

Add-on Version:  2.1.0 pl2

XenForo Version: 2.1.1

Operating System (and Version): Linux (Arch)

Browser Name (and Version): Firefox nightly

Summary of issue:  Docs refer to non-existent XML and have outdated instructions

Detailed steps to reproduce the issue:
Have a look at these docs:
https://www.themehouse.com/help/documentation/uix/updating-uix

I couldn't find the uix-addon.xml file anywhere.  I finally got the update installed when I figured out that I needed to add this to `src/config.php`:
```
$config['enableAddOnArchiveInstaller'] = true;
```
After that was done, I could browse to the downloaded UI-X zip file and upload that and let XF automatically upgrade the add-on.

Please update your docs so that I don't have to poke around in confusion for an hour next time.  Thanks!

**Comment by daltonp** [comment]
Hello there,
That would be because you are viewing the wrong documentation: https://www.themehouse.com/help/documentation/uix2
