### ISSUE TITLE
"Associated with none of selected account providers" has weird ID/Array Key

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2addon-issues#1642]
Looks like it's a bug

**Comment by setoy** [comment]
Is this supposed to be [this](https://xenforo.com/community/threads/th-user-criteria-extended.144617/page-3#post-1311830) bug? If not, I can go ahead and create a new issu for that :)

**Comment by LukasWieditz** [comment]
Yes it is.

**Comment by setoy** [comment]
Thank you for the clarification. Looking forward to the, much anticipated, update :)
