### ISSUE TITLE
Donate - Add an option to allow donations to repeat indefinitely

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#167]

**Comment by JakeBooher** [comment]
Could you elaborate? If you set a campaign to repeat it will do so indefinitely until it is manually closed

**Comment by daltonp** [comment]
The best answer I can give is an option that does not relate to weekly, monthly, or yearly. It runs all the time without having to set a "Repeats every".

**Comment by JakeBooher** [comment]
This is already possible, just uncheck that box and leave the end date blank..
