### ISSUE TITLE
Prefix actions and methods

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2addon-issues#1679]
To avoid incompatibility with other add-ons.

![1554127828786](https://user-images.githubusercontent.com/38475165/55335927-5a696a00-549c-11e9-8f8c-4b41d5949fa3.png)

**Comment by jonw316** [comment]
This is a method that is extended by two different add-ons, but has presumably been updated at some point to have a different method signature (possibly XF 2.1). It is not a prefix issue.

**Comment by jonw316** [comment]
Never mind, I was looking at something else. It is a prefix issue!
