### ISSUE TITLE
Donate - Add the ability to create preset donation amounts

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#168]

**Comment by JakeBooher** [comment]
Could you elaborate?

**Comment by daltonp** [comment]
Allow administrators the ability to set default donation amounts that users are able to choose before making a donation.
![customdonationamounts](https://user-images.githubusercontent.com/32306910/38269732-ed6ed7d2-3746-11e8-9e64-35bdc127d953.png)

**Comment by mikecreuzer** [comment]
This is so common that I do agree it needs to be added.
