### ISSUE TITLE
Posts being inserted in wrong order

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2addon-issues#1685]
Ticket #13455.

My first assumption would be an implicit database sorting somewhere, returning rows not in order of ID but internal order, which means that some rows are inserted in recycled slots, hence out of order.

**Comment by jonw316** [comment]
The ticket says that the customer deactivated the add-on. Posts will end up out of order if you deactivate the add-on. There is not really much we can do about that.

**Comment by LukasWieditz** [comment]
The issue happens while the add-on is active, and the posts that aren't in order are no comments.

**Comment by jonw316** [comment]
This is hopefully resolved by all the other fixes I've made, but I can't be sure so I'll leave this open for now.
