### ISSUE TITLE
[Auto Post Merge] Merge posts above "Maximum message length"

### ISSUE THREAD

**Issue by setoy** [Audentio/xf2addon-issues#1714]
A user currently cannot answer on his own thread because he's inside the double-post merge period and merging would put the post above our maximum message length.

**Comment by LukasWieditz** [comment]
That would be as designed. He couldn't edit it into the post either.

**Comment by setoy** [comment]
Then I'd suggest adding a config option to be able to specify "Allow double post if merging would exceed maximum message length".
