### ISSUE TITLE
[Donate] Option to show donations for last X days

### ISSUE THREAD

**Issue by jonw316** [Audentio/xf2addon-issues#1717]
Ticket 13878

>Hi have a member who donated towards the end of the month so his donation only appears for about 2-3 days and the campaign resets to zero. Could we have an option which displays donations from the last 30 days instead of the current format date 1-30/31? Thanks.

**Comment by setoy** [comment]
I second this suggestion as it allows me to only show a specified amount of donations for a never-ending campaign. Ours has now amassed a lot of pages and I don't want to show all of them.

e.g. options "show all donations within current cycle" and "show donations within last X days".

**Comment by JakeBooher** [comment]
@setoy I may be missing some context here, as far as I can tell the campaign shows all donations, not just ones for the current period. In fact, there is no mechanism in the code that would make it possible to limit this. Are you referring to something else?

**Comment by setoy** [comment]
You're not missing anything as limiting shown donations to the current period is exactly what I suggest to be added.

**Comment by JakeBooher** [comment]
Okay, I think that's separate from the original suggestion - it seems like they're saying it already is limited somewhere. @jonw316 do you have any more details on the original suggestion, and whether or not that is what it was for?

**Comment by setoy** [comment]
You're right. The "problem" that the original question describes would actually solve MY problem, lol.

**Comment by LukasWieditz** [comment]
The original suggestion wants an option to only display total amount of the last X days on the progress bar.  Essentially what is asked, is to not reset the bar every X days but show the total amount of the last X days. I don't think that's something we want to add though.
