### ISSUE TITLE
[Donate] Option to lock a campaign when the goal is reached

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1720]
Suggested by [Lashman](https://xenforo.com/community/threads/th-donate-paid.145264/post-1343789) on xenforo.com

> for example, if i create a campaign with a $30 goal and the goal is reached - it would be nice to be able to automatically either hide the "donate" button for that campaign or at least display a message to anyone trying to donate (something like "this campaign goal has been reached") 
> 
> i know i can already manually disable a campaign whenever i want, but it would be nice to have it be done automatically ... and also disabling a campaign also hides it completely from the donation tab which also isn't ideal (especially in the case of recurring campaigns)

**Comment by JakeBooher** [comment]
Completed this along with #1720
