### ISSUE TITLE
[Donate] - Custom amount field isn't hidden when a preset amount is selected

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1724]
Custom amount fields are not hidden when go to direct URL link.

![ScreenShot01030](https://user-images.githubusercontent.com/6899856/56444712-1e3a6400-62fa-11e9-88ec-813f3935a946.png)

**Comment by JakeBooher** [comment]
You can disable the custom amount by unchecking "Allow custom amounts" on the campaign configuration

**Comment by JakeBooher** [comment]
Actually, I think I see what you're referring to now
