### ISSUE TITLE
[Feature Request] Allow user to input XF URL path and / or generate for linking to XF Admin interface in Themehouse Documentation

### ISSUE THREAD

**Issue by jeremywaudentio** [Audentio/xf2addon-issues#1726]
Add-on Name: General

Add-on Version: General

XenForo Version: XF2

Operating System (and Version): NR

Browser Name (and Version): NR

Summary of issue: Users should be able to if logged in have links in documentation of admin specific functions of products (i.e. Documentation tells user to goto Appearance -> Style Properties ) should link directly to.

Detailed steps to reproduce the issue: 

Upload any screenshots related to the issue below

**Comment by jonw316** [comment]
Tagging @victoriad1, but closing as this is not an add-on request.
