### ISSUE TITLE
[Nodes] Gradient Option in Admin Interface

### ISSUE THREAD

**Issue by jeremywaudentio** [Audentio/xf2addon-issues#1727]
Add-on Name: Nodes

Add-on Version: All

XenForo Version: 2

Operating System (and Version): NR

Browser Name (and Version): NR

Summary of issue: Instead of having a custom CSS property allow a drop down to apply gradient to any node

Detailed steps to reproduce the issue:

Upload any screenshots related to the issue below

**Comment by LukasWieditz** [comment]
Seems to be already possible. Just put the gradient into the background image field.
