### ISSUE TITLE
[QA Forums] Not working Next to user controls

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1742]
Not working Up and down vote controls location and Best answer control location > Next to user controls.

![ScreenShot01055](https://user-images.githubusercontent.com/6899856/56981963-7128dc80-6b80-11e9-94b1-1f5087155604.png)

**Comment by LukasWieditz** [comment]
Can't reproduce any issue here. Setting both options to "next to user controls" moves them to the action bar as expected.

**Comment by Nirjonadda** [comment]
See here: https://thumbs.gfycat.com/CalmNaturalAlligatorsnappingturtle-mobile.mp4

**Comment by LukasWieditz** [comment]
Looks like an incompatibility with your theme. Is there any template modification that isn't applied?

**Comment by Nirjonadda** [comment]
This issue also happened with Xenforo default style. Yes I think this template modification issue?

![ScreenShot01074](https://user-images.githubusercontent.com/6899856/57034270-5f623a80-6c4f-11e9-9f70-e2befbe3e7d9.png)

**Comment by LukasWieditz** [comment]
I can't reproduce it on the default style. This may be caused by a 3rd party add-on then.

**Comment by Nirjonadda** [comment]
This fixed with PL1 update.
