### ISSUE TITLE
Nodes sub-node icons wrong markup

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#1747]
Sub node icon with Nodes getting an extra unnecessary "subNodeLink" class on the icon. Remove this class, and instead add ```padding-right: .3em```
<img width="362" alt="Screen Shot 2019-04-30 at 2 20 44 PM" src="https://user-images.githubusercontent.com/15836384/56988187-0b732b00-6b55-11e9-8cfe-cd1b743b28e9.png">

**Comment by LukasWieditz** [comment]
Call me wrong, but that class seems pretty important.
https://giant.gfycat.com/GorgeousShrillCaiman.webm
