### ISSUE TITLE
[Notifier] notifications aren't sent when soft/hard deleting media ratings

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1748]
When attempting to get notifications when I soft/hard delete or undelete ratings I get no notification for either. I get one when rating a media item though.
![image](https://user-images.githubusercontent.com/32306910/56988292-50975d00-6b55-11e9-97ae-e4db29fcf0c4.png)

![image](https://user-images.githubusercontent.com/32306910/56988361-745aa300-6b55-11e9-891e-3601c6299717.png)

**Comment by LukasWieditz** [comment]
Is this working with other notification providers?

**Comment by daltonp** [comment]
No, it isn't working on Slack either.

**Comment by LukasWieditz** [comment]
Seems like this isn't a bug. In fact, Media Ratings can't be deleted in the first place, just the comment associated with them. I've removed the delete/undelete handler from the Rating instead and opened an issue for supporting media comments.
