### ISSUE TITLE
[Donate] Incorrect donation amount in member card

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1749]
Incorrect donation amount in member card.

![ScreenShot01059](https://user-images.githubusercontent.com/6899856/56992512-827ee280-6b9a-11e9-9fa8-f0de76e5109c.png)

**Comment by JakeBooher** [comment]
This shows the number of donations, not collective amount

**Comment by Nirjonadda** [comment]
@JakeBooher So where will be show up total amount donation? but before here will be show up total amount donation.

**Comment by Nirjonadda** [comment]
@JakeBooher Please re-open this issue because, will be show up total number of donation? but before here will be show up total amount donation. So old donation still showing total amount donation, not total number of donation. How to fixing this.

![ScreenShot01096](https://user-images.githubusercontent.com/6899856/57196674-7199ec80-6f5f-11e9-97f2-fa489a3af558.png)
