### ISSUE TITLE
[QA Forums] "Add question status to own thread" permission not respected

### ISSUE THREAD

**Issue by setoy** [Audentio/xf2addon-issues#1753]
After upgrading to v1.1.1, the "Add question status to own thread" permission is not respected anymore. A user with the following permissions just created a question thread in my forums:

![image](https://user-images.githubusercontent.com/6497266/57045058-ccd09400-6c6c-11e9-81ca-49c9e41a1250.png)

**Comment by LukasWieditz** [comment]
The permission check for this is as straightforward as it could be. I only see two reasons why the selection could show up:

1. It is overwritten on a node permission level basis
2. The affected accounts have the "Manage any thread" moderator permission

**Comment by setoy** [comment]
> The affected accounts have the "Manage any thread" moderator permission

They indeed have. I didn't know that this permission was relevant, so my other suggestion might even make more sense now: https://github.com/Audentio/xf2addon-issues/issues/1754

**Comment by LukasWieditz** [comment]
I'll close this with "As designed" then. We'll consider making changes when we get to #1754.
