### ISSUE TITLE
[QA Forums] Question status is added to thread by default even though the node is not configured to do so

### ISSUE THREAD

**Issue by setoy** [Audentio/xf2addon-issues#1755]
The node is not checked for `Add question status to threads by default (permission required)` and the user does not even have permission to add question status to own threads (see: https://github.com/Audentio/xf2addon-issues/issues/1753). The thread status is set to "Question" by default anyway.

![image](https://user-images.githubusercontent.com/6497266/57045434-deff0200-6c6d-11e9-9ccc-9b011ab17ca0.png)

**Comment by tom-coward** [comment]
https://github.com/Audentio/xf2addon-issues/issues/1743
