### ISSUE TITLE
[Spotify] Lot of Request

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1757]
Lot of Request loading from `spotify/update-current-playback`

```
spotify/update-current-playback
_xfRequestUri=%2F
_xfWithData=1
_xfToken=1556764752%2Cb2db8e8b7c49618d3642fc56f6a7b2a7
_xfResponseType=json
```

**Comment by Nirjonadda** [comment]
![ScreenShot01078](https://user-images.githubusercontent.com/6899856/57054480-2cdb3080-6c95-11e9-8b30-4292d2aaf6c6.png)

**Comment by setoy** [comment]
I think that is one per second as configured in the add-ons options?
