### ISSUE TITLE
[Emojify Pro] Browser console error

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1758]
Browser console error.

![ScreenShot01079](https://user-images.githubusercontent.com/6899856/57054596-d28e9f80-6c95-11e9-80c5-6943cc19f90d.png)

**Comment by LukasWieditz** [comment]
Due to the add-on being largely an aprils fools gag and this being a situational error, we're not going to fix this.

**Comment by Nirjonadda** [comment]
@LukasWieditz If you are not fix this error then this addon are not compatible with other style.
