### ISSUE TITLE
[ReactionsPlus] Emoji based reactions are smaller than default reactions on Member reaction list widget

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1759]
<img width="277" alt="Screen Shot 2019-05-02 at 10 08 31 AM" src="https://user-images.githubusercontent.com/32306910/57086626-1ac4b680-6cc4-11e9-8d0d-02569b8106f8.png">

**Comment by LukasWieditz** [comment]
Default emojis are smaller than default reactions by nature. Sizes can be manually adjusted.
