### ISSUE TITLE
Covers Style User Cover

### ISSUE THREAD

**Issue by kylerc** [Audentio/xf2addon-issues#176]
Currently says `No content was returned. Please try again later.` . I'm not exactly sure what styling we plan to support though.

Accessed by the `Cover` dropdown on a profile then `Style User Cover`

**Comment by LukasWieditz** [comment]
Accessing this section triggers an error `ErrorException: Template error: Template public:th_style_cover_covers is unknown`

**Comment by LukasWieditz** [comment]
Is this supposed to support a full css set or do we want to have stuff like a color picker for text color, background color, etc.?

**Comment by LukasWieditz** [comment]
I've built in background colors for now. System is built to work with more properties in the future.
