### ISSUE TITLE
[Notifier] Missing phrase

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1760]
Discord provider automatically save and save button not working after clicking the button. Also Phrases missing.

![ScreenShot01080](https://user-images.githubusercontent.com/6899856/57089710-592e9580-6d05-11e9-8600-e3bb4868c5cd.png)

**Comment by LukasWieditz** [comment]
The save button is working, it just needs to process for a while. The "automated" save you experienced was from a previous click.

**Comment by Nirjonadda** [comment]
No, this automatically save without clicking the save button

See here: https://drive.google.com/file/d/1Rg4SqxhqhJYtxFVtJpcTLXpC7qY8omG3/view?usp=sharing
