### ISSUE TITLE
[Donate] Enable/Disable donate campaigns is backwards

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1762]
When enabling a campaign it doesn't allow me to view the campaigns page but when disabling it I am able too. Seems like they are backwards.
![image](https://user-images.githubusercontent.com/32306910/57155592-829cff00-6da1-11e9-8b54-9d79512a2834.png)

**Comment by LukasWieditz** [comment]
I'm not able to reproduce this. Got an example install?
