### ISSUE TITLE
[Donate] Campaign description styling

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1763]
Looks like the description needs to be in line with the campaign tile as it is too far left which could cause it to cut into the campaign icon.
![image](https://user-images.githubusercontent.com/32306910/57155728-ce4fa880-6da1-11e9-98d2-2e195476d7f8.png)

**Comment by LukasWieditz** [comment]
I'm not able to reproduce this. Got an example install?
