### ISSUE TITLE
[Donate] thdonate_total_*_donation is rebuilding to contain the number of donations rather than the sum of donations

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#1766]
As per screenshot my top donors appear to have 'rolled over' to some random number for want of a better word. Basically counters in the member card as well as the top donor widget have reset but as you can see from the screenshot their donations are still showing. This is very very unwanted so would appreciate some urgent attention as my site is run almost entirely on donations.

@JakeBooher @mikecreuzer 

This is on TH Donate 1.1.0 on XF 2.1.2.

Thanks 

![donate](https://user-images.githubusercontent.com/5346876/57196339-18fc2c80-6f2a-11e9-8e5a-d9bd3db9e38d.png)

**Comment by JakeBooher** [comment]
Donation on the user's profile page never "reset", the number at the top right with the arrow shows the number of times that user has donated, and it lists all donations by that user. We should probably change the "Donated" phrase to "Donations" to be a bit more clear on exactly what that number is though

**Comment by ichpen** [comment]
I've rebuilt user donation caches and appears to have made things worse and reduced the donation summary for everyone to some very low amt (I don't think it's trimming zeroes either). Before rebuilding donation caches I had hundreds in there.

![donors1](https://user-images.githubusercontent.com/5346876/57196542-e0f5e900-6f2b-11e9-8c4b-cb4fc1cf7a9e.png)

**Comment by ichpen** [comment]
> Donation on the user's profile page never "reset", the number at the top right with the arrow shows the number of times that user has donated, and it lists all donations by that user. We should probably change the "Donated" phrase to "Donations" to be a bit more clear on exactly what that number is though

The number up until recently showed Total donated amounts so at some point it sounds like you guys changed it?

Yes you should change the phrase as it's freaked out a number of folks.

**Comment by Nirjonadda** [comment]
@JakeBooher From this [issue](https://github.com/Audentio/xf2addon-issues/issues/1749), will be show up total number of donation? but before here will be show up total amount donation. So old donation still showing total amount donation, not total number of donation. How to fixing this.

![ScreenShot01096](https://user-images.githubusercontent.com/6899856/57196654-339cc880-6f5f-11e9-8c52-dc023c3c56b1.png)

**Comment by ichpen** [comment]
Furthermore how can I restore my actual Top Donors widget given that it now shows information that is unrelated to Top Donors? :)

Or did you get rid of that widget?

**Comment by ichpen** [comment]
@JakeBooher 

Saga continues...

So I read through the 1.1.0 changelog as one does after the fact and nowhere does it state that you will completely hide total donation amounts nor remove Top Donors widget functionality. Also I see this in the changelog yet can't find that option under the campaigns to hide total donation amt nor can I find reactions support (I assume for individual donations):

-> Add option to hide total donation amount for a campaign.
-> Added full support for XenForo 2.1 reactions.

All in all can I please have the previous version back.

**Comment by JakeBooher** [comment]
Okay, so it used to show the actual amount donated? Not sure why that would've gotten changed, but I'll check through git logs and revert that if that's the case

**Comment by JakeBooher** [comment]
Same goes for that widget, not sure why that change would've been made, but I'll have a look

**Comment by ichpen** [comment]
> Okay, so it used to show the actual amount donated? Not sure why that would've gotten changed, but I'll check through git logs and revert that if that's the case

Sure did @JakeBooher and wouldn't mind having that functionality back pretty please as it's crucial. At least option in in ACP.

**Comment by JakeBooher** [comment]
Alright, this has been fixed. You'll need to run "Rebuild user donation caches" to fix it (after updating, of course)
