### ISSUE TITLE
Covers Choose Preset

### ISSUE THREAD

**Issue by kylerc** [Audentio/xf2addon-issues#177]
Currently says `The requested page could not be found. (Code: invalid_action, controller: ThemeHouse\Covers:Cover, action: Preset)` . I'm not exactly sure what styling we plan to support though.

Accessed by the `Cover` dropdown on a profile then `Choose Cover Preset`

**Comment by mikecreuzer** [comment]
It would be nice to support color (same as avatar maybe? by default. Presets arent super useful imo
