### ISSUE TITLE
[Donate] 1.1.1 Beta 2 - Minimum donation gets defaulted into donation field

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#1770]
Donations is currently defaulting the minimum campaign donation amounts straight into the donation input field which IMHO is wrong as it suggests to the user that that's the donation amount required and doesn't prompt them to override it.

As a suggestion, donation input field on modal should always be blank, minimum amt should be a phrase that's located beneath the donation amt input. Should say "Minimum donation amount is $campaign_min_amt".

**Comment by JakeBooher** [comment]
Okay, I think I may have misunderstood what you were referring to here initially. This was done intentionally, and I think it being an input is indication enough that you can change it. However, if you'd like to change this yourself it can be done fairly easily by editing the `thdonate_campaign_macros` template and changing:

```
								<xf:formrow rowtype="input"
										rowclass="js-CustomAmount {{ count($campaign.preset_amounts) ? 'custom-hidden' : '' }}"
										label="{{ !count($campaign.preset_amounts) ? phrase('th_donation_amount_donate') : phrase('thdonate_custom_amount') }}">
									<div class="inputGroup">
										<xf:textbox name="custom_amount"
											value="{$campaign.min_donation}"
											required="{{ !count($campaign.preset_amounts) }}" />
										<span class="inputGroup-text">{$campaign.currency}</span>
									</div>
								</xf:formrow>
```

to:

```
								<xf:formrow rowtype="input"
										rowclass="js-CustomAmount {{ count($campaign.preset_amounts) ? 'custom-hidden' : '' }}"
										label="{{ !count($campaign.preset_amounts) ? phrase('th_donation_amount_donate') : phrase('thdonate_custom_amount') }}"
										explain="The minimum amount that can be donated is ${$campaign.min_donation|number}">
									<div class="inputGroup">
										<xf:textbox name="custom_amount"
											required="{{ !count($campaign.preset_amounts) }}" />
										<span class="inputGroup-text">{$campaign.currency}</span>
									</div>
								</xf:formrow>
```

**Comment by teamracing** [comment]
Should be reopened.
