### ISSUE TITLE
[UserImprovements] Trophy Progress Macros counting error

### ISSUE THREAD

**Issue by PixelOrange** [Audentio/xf2addon-issues#1773]
Add-on Name: UserImprovements

Add-on Version: 1.3.0 Patch 6

XenForo Version: Latest

Operating System (and Version): Windows 10

Browser Name (and Version): Chrome

Summary of issue: Progress bar is out of order when looking at other user's progress. When looking at my own progress, it is fine.

Detailed steps to reproduce the issue: Create a series of trophies in a trophy category with predecessors. Grant the trophies in any order to someone other than yourself. Go to their trophy page and view their trophy progress.

Upload any screenshots related to the issue below
![mixed-foreach](https://user-images.githubusercontent.com/5042764/57268503-a8e4c800-7049-11e9-8c98-79a267c2ef2e.PNG)
![mixed-foreach-trophy-value](https://user-images.githubusercontent.com/5042764/57268504-a8e4c800-7049-11e9-9a8e-9e6a31e3a294.PNG)

**Comment by PixelOrange** [comment]
On the second picture, I removed all of the code except the foreach and then added {$trophy} to get a basic output as shown here:
`						<xf:foreach loop="$trophies" value="$trophy">
						{$trophy}
						</xf:foreach>`

**Comment by LukasWieditz** [comment]
The page your screenshot stems from always displays the own progress.

**Comment by PixelOrange** [comment]
I forgot to update this issue after some more testing. The out-of-order list also occurs on your own page. For me, it shows this:

Trophy for 25 posts, trophy for 50 posts, trophy for 500 posts, trophy for 250 posts, trophy for 100 posts, trophy for 75 posts, trophy for 750 posts, and trophy for 1000 posts.

I can't seem to figure out why XenForo is counting weird. The foreach is showing 11, 12, 16, 15, 14, 13, 17, 18, etc. It's iterating really strangely.
