### ISSUE TITLE
Making edits to the parent post of a comment gives an error

### ISSUE THREAD

**Issue by zethon** [Audentio/xf2addon-issues#1774]
Add-on Name: Post Comments

Add-on Version: 1.0.2

XenForo Version: 2.0

Steps to reproduce:

1. Comment on a post
1. Click "Edit" on the post you commented on (not the comment itself)
1.  Make an edit and click "Save"

**Expected**: the edits should be saved without a problem

**Actual**: error message saying "Oops, there was a problem...." pops up. 

If you refresh the page, the edits actually are saved but (obviously) the error message shouldn't pop up.

Here is a demonstration of the issue. I create a thread, and then comment on the post in the thread. I edit the post twice and each time get an error. Then I disable the plugin, make an edit and get no error. 

![bug](https://user-images.githubusercontent.com/5203583/57293992-4533bc80-7094-11e9-8f34-0454465ec77a.gif)

**Comment by daltonp** [comment]
I am able to replicate this as well. Thank you for the report!
