### ISSUE TITLE
Upgrade page text not fitting in shape

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xf2addon-issues#1775]
The text doesn't fit in the shape with the /mo after it. On the other ones it looks like "for 1 month" goes to a second line. Maybe it should for this as well and be "per month".
<img width="307" alt="Screen Shot 2019-05-07 at 11 30 37 AM" src="https://user-images.githubusercontent.com/43186749/57326335-e12fe900-70d1-11e9-91e3-d426ae731f0a.png">

**Comment by LukasWieditz** [comment]
Kinda depends on the chosen symbol. Could be a problem with a large cost amount too. Not really something that can generally be fixed.
