### ISSUE TITLE
[Donate] Donation comments should respect UI.X settings

### ISSUE THREAD

**Issue by setoy** [Audentio/xf2addon-issues#1779]
In UI.X there is a setting to show a "lean" comment box on profile posts (I don't currently know the exact name of that style property).

This shows the box as such:
![image](https://user-images.githubusercontent.com/6497266/57448470-bec8d780-7259-11e9-8bcc-5194a6250c37.png)

and only after clicking on it, it shows the entire froala editor.

I'd suggest doing the same for donation comments, as they look quite cluttered with a couple of editors on a single page.

**Comment by LukasWieditz** [comment]
Can you elaborate which style property you're referring to exactly? We're a bit clueless here which one you're thinking of.

**Comment by setoy** [comment]
Mhmm, I thought it was `profilePostCommentToggle`, but it appears I'm mistaken. Nevertheless I'd suggest changing the comment box on donation comments to a similar behavior like for profile post comments (as to not load the entire froala editor in each box).

Initial load:
![image](https://user-images.githubusercontent.com/6497266/57704690-b4944800-7662-11e9-9f58-d612dfb9ac80.png)

On first click:
![image](https://user-images.githubusercontent.com/6497266/57704696-b6f6a200-7662-11e9-9fbc-2723f65139ab.png)
