### ISSUE TITLE
Covers error

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2addon-issues#1789]
Server error log
LogicException: Content type resource must define an 'entity' value src/XF/App.php:2561
Generated by: Unknown account May 11, 2019 at 1:56 AM
Stack trace
#0 src/XF/App.php(2538): XF\App->getContentTypeEntity('resource')
#1 src/addons/ThemeHouse/Covers/Cover/AbstractHandler.php(25): XF\App->findByContentType('resource', '13', Array)
#2 src/addons/ThemeHouse/Covers/Pub/Controller/Cover.php(399): ThemeHouse\Covers\Cover\AbstractHandler->getContent('13')
#3 src/addons/ThemeHouse/Covers/Pub/Controller/Cover.php(27): ThemeHouse\Covers\Pub\Controller\Cover->assertCover('resource', '13')
#4 src/XF/Pub/Controller/AbstractController.php(30): ThemeHouse\Covers\Pub\Controller\Cover->preDispatchController('Position', Object(XF\Mvc\ParameterBag))
#5 src/XF/Mvc/Controller.php(123): XF\Pub\Controller\AbstractController->preDispatchType('Position', Object(XF\Mvc\ParameterBag))
#6 src/XF/Mvc/Dispatcher.php(320): XF\Mvc\Controller->preDispatch('Position', Object(XF\Mvc\ParameterBag))
#7 src/XF/Mvc/Dispatcher.php(244): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Cove...', 'Position', Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Covers\Pub\Controller\Cover), NULL)
#8 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Covers\Pub\Controller\Cover), NULL)
#9 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#10 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#11 src/XF.php(390): XF\App->run()
#12 index.php(20): XF::runApp('XF\\Pub\\App')
#13 {main}
Request state
array(4) {
  ["url"] => string(28) "/covers/resource/13/position"
  ["referrer"] => bool(false)
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}

**Comment by LukasWieditz** [comment]
As [here](https://xenforo.com/community/threads/th-covers-paid.148763/page-11#post-1349595). This is thrown by a resource cover that has been manually accessed via direct URL while the resource manager is disabled.

**Comment by joyfreak** [comment]
I don't use Resource add-on and never have done. I don't even have it installed and I checked in the resource type for covers and there isn't any photos for me to delete. I only got this error since the recent update. It's been showing on the error logs constantly. So what do I do?
