### ISSUE TITLE
[QA Forums] "Unanswered questions" in forum statistics widget are still not calculated correctly

### ISSUE THREAD

**Issue by setoy** [Audentio/xf2addon-issues#1799]
Backing off of: https://github.com/Audentio/xf2addon-issues/issues/1756

I have a single "question" thread in my forums with two answers (no best answer). The widget shows: 
```
Unanswered questions: 12
```

Upon clicking on it, the search shows `No results found.`.

**Comment by LukasWieditz** [comment]
The page linked to is the new threads page. Old threads that haven't been answered won't be shown there, but they're still unanswered, so they go into the statistics.

**Comment by setoy** [comment]
> Old threads that haven't been answered won't be shown there, but they're still unanswered, so they go into the statistics.

Well, how come there are 12 unanswered questions if only one thread in my entire forum is selected to be an actual question?

**Comment by LukasWieditz** [comment]
Have you rebuilt counters since the last update? XenForo calculates the counters only once each day iirc.

The code is fail-safe:
```
public function getTHQAUnansweredTotals()
    {
        return $this->db()->fetchRow("
			SELECT COUNT(*) AS thqaunanswered
			FROM xf_thread
			WHERE th_is_qa_qaforum = 1
			  AND th_answered_qaforum = 0
		");
    }
```

There's no possibility it counts threads that aren't questions as unanswered.

**Comment by setoy** [comment]
You're right. There were some threads I didn't know were selected as question threads because of the [bug you fixed already](https://github.com/Audentio/xf2addon-issues/issues/1755).

Sorry for the confusion.
