### ISSUE TITLE
[QA Forums] "Unanswered questions" in forum statistics widget are not calculated correctly

### ISSUE THREAD

**Issue by setoy** [Audentio/xf2addon-issues#1807]
Piggybacking from this issue: https://github.com/Audentio/xf2addon-issues/issues/1799

I now have a single question thread in my forums. The statistics show "Unanswered questions: 1" and upon clicking on it, the search comes up empty ("Show only: Unanswered questions Filters
No results found.").

**Comment by LukasWieditz** [comment]
As stated in #1799, the route that the add-on links to shows only recent content, hence it is possible that not all question threads are shown.
