### ISSUE TITLE
[I&U] DuplicateKeyException Error

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1820]
> [LIST]
> [*]XF\Db\DuplicateKeyException: Job ThemeHouse\InstallAndUpgrade:GetProducts: MySQL query error [1062]: Duplicate entry '3-336' for key 'PRIMARY'
> [*]src/XF/Db/AbstractStatement.php:217
> [*]Generated by: Unknown account
> [*]May 22, 2019 at 1:00 PM
> [/LIST]
> Stack trace
> INSERT  INTO `xf_th_installupgrade_product` (`profile_id`, `product_id`, `product_type`, `title`, `description`, `latest_version`, `extra`, `content_id`, `current_version`, `update_available`, `installed`, `json_hash`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
> ------------
> 
> #0 src/XF/Db/Mysqli/Statement.php(196): XF\Db\AbstractStatement->getException('MySQL query err...', 1062, '23000')
> #1 src/XF/Db/Mysqli/Statement.php(77): XF\Db\Mysqli\Statement->getException('MySQL query err...', 1062, '23000')
> #2 src/XF/Db/AbstractAdapter.php(94): XF\Db\Mysqli\Statement->execute()
> #3 src/XF/Db/AbstractAdapter.php(221): XF\Db\AbstractAdapter->query('INSERT INTO `x...', Array)
> #4 src/XF/Mvc/Entity/Entity.php(1452): XF\Db\AbstractAdapter->insert('xf_th_installup...', Array, false)
> #5 src/XF/Mvc/Entity/Entity.php(1184): XF\Mvc\Entity\Entity->_saveToSource()
> #6 src/addons/ThemeHouse/InstallAndUpgrade/InstallAndUpgrade/DragonByte.php(128): XF\Mvc\Entity\Entity->save()
> #7 src/addons/ThemeHouse/InstallAndUpgrade/Job/GetProducts.php(60): ThemeHouse\InstallAndUpgrade\InstallAndUpgrade\DragonByte->getProducts()
> #8 src/XF/Job/Manager.php(253): ThemeHouse\InstallAndUpgrade\Job\GetProducts->run(G)
> #9 src/XF/Job/Manager.php(195): XF\Job\Manager->runJobInternal(Array, G)
> #10 src/XF/Job/Manager.php(79): XF\Job\Manager->runJobEntry(Array, G)
> #11 job.php(42): XF\Job\Manager->runQueue(false, 8)
> #12 {main}
> Request state
> array(4) {
> ["url"] => string(8) "/job.php"
> ["referrer"] => string(64) "/admin.php?cron/th_iau_get_products/run"
> ["_GET"] => array(0) {
> }
> ["_POST"] => array(0) {
> }
> }

**Comment by LukasWieditz** [comment]
https://github.com/Audentio/xf2-installupgrade/issues

**Comment by xydrine** [comment]
Hi,

I am getting a very similar error using the latest version with all the latest forum software updates/versions. This is the error:

Server error log
XF\Db\DuplicateKeyException: Job ThemeHouse\InstallAndUpgrade:GetProducts: MySQL query error [1062]: Duplicate entry '2-350' for key 'PRIMARY' src/XF/Db/AbstractStatement.php:217
Generated by: Unknown account Aug 9, 2019 at 7:00 PM
Stack trace
INSERT  INTO `xf_th_installupgrade_product` (`profile_id`, `product_id`, `product_type`, `title`, `description`, `latest_version`, `extra`, `content_id`, `current_version`, `update_available`, `installed`, `json_hash`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
------------

#0 src/XF/Db/Mysqli/Statement.php(196): XF\Db\AbstractStatement->getException('MySQL query err...', 1062, '23000')
#1 src/XF/Db/Mysqli/Statement.php(77): XF\Db\Mysqli\Statement->getException('MySQL query err...', 1062, '23000')
#2 src/XF/Db/AbstractAdapter.php(94): XF\Db\Mysqli\Statement->execute()
#3 src/XF/Db/AbstractAdapter.php(218): XF\Db\AbstractAdapter->query('INSERT  INTO `x...', Array)
#4 src/XF/Mvc/Entity/Entity.php(1452): XF\Db\AbstractAdapter->insert('xf_th_installup...', Array, false)
#5 src/XF/Mvc/Entity/Entity.php(1184): XF\Mvc\Entity\Entity->_saveToSource()
#6 src/addons/ThemeHouse/InstallAndUpgrade/InstallAndUpgrade/DragonByte.php(128): XF\Mvc\Entity\Entity->save()
#7 src/addons/ThemeHouse/InstallAndUpgrade/Job/GetProducts.php(60): ThemeHouse\InstallAndUpgrade\InstallAndUpgrade\DragonByte->getProducts()
#8 src/XF/Job/Manager.php(253): ThemeHouse\InstallAndUpgrade\Job\GetProducts->run(G)
#9 src/XF/Job/Manager.php(195): XF\Job\Manager->runJobInternal(Array, G)
#10 src/XF/Job/Manager.php(79): XF\Job\Manager->runJobEntry(Array, G)
#11 job.php(42): XF\Job\Manager->runQueue(false, '120')
#12 {main}
Request state
array(4) {
  ["url"] => string(8) "/job.php"
  ["referrer"] => string(45) "https://www.rdforum.org/index.php?forums/169/"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}

----

I was going to open a new report about this but figured I'd ask here if there is a workaround/way to fix this/etc first.

Thanks!
