### ISSUE TITLE
Reactions - Add "Reactions" to admin index page for consistency?

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2addon-issues#184]
Suggestion:

Add "Reactions" to admin index page, for consistency?

![reactions_suggestion](https://user-images.githubusercontent.com/35111972/38457912-aabcd4cc-3a64-11e8-90f7-8871a2dcc9ce.png)

**Comment by JakeBooher** [comment]
I've made a suggestion that XenForo should populate these from the admin navigation to keep it consistent, because if we were to add it there we can't really guarantee it'll be in the same order as another add-on could attempt to add one to the same location

**Comment by lilalien** [comment]
Hope that recent tip was helpful!

https://xenforo.com/community/threads/populate-admin-index-page-links-with-the-admin-navigation.145756/
