### ISSUE TITLE
[Trending] Determine Trending by Usergroup

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1846]
It was suggested by [dethfire](https://xenforo.com/community/threads/th-trending-paid.145258/post-1352639) on XenForo.com

> What about determine trending by usergroup? I have a few "expert" usergroups that always post amazing threads.

**Comment by LukasWieditz** [comment]
Not feasible to implement.

**Comment by mikecreuzer** [comment]
If we did this, could look at a Trending Pro perspective
