### ISSUE TITLE
Error experienced with notices on UI.X 

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1856]
> Oops! We ran into some problems.
> XF\Db\Exception: MySQL statement prepare error [1054]: Unknown column 'thuix_icon' in 'field list' in src/XF/Db/AbstractStatement.php at line 217
> XF\Db\AbstractStatement->getException() in src/XF/Db/Mysqli/Statement.php at line 196
> XF\Db\Mysqli\Statement->getException() in src/XF/Db/Mysqli/Statement.php at line 40
> XF\Db\Mysqli\Statement->prepare() in src/XF/Db/Mysqli/Statement.php at line 54
> XF\Db\Mysqli\Statement->execute() in src/XF/Db/AbstractAdapter.php at line 94
> XF\Db\AbstractAdapter->query() in src/XF/Db/AbstractAdapter.php at line 327
> XF\Db\AbstractAdapter->update() in src/XF/Mvc/Entity/Entity.php at line 1457
> XF\Mvc\Entity\Entity->_saveToSource() in src/XF/Mvc/Entity/Entity.php at line 1184
> XF\Mvc\Entity\Entity->save() in src/XF/Mvc/FormAction.php at line 69
> XF\Mvc\FormAction->XF\Mvc{closure}() in src/XF/Mvc/FormAction.php at line 187
> XF\Mvc\FormAction->run() in src/XF/Admin/Controller/Notice.php at line 107
> XF\Admin\Controller\Notice->actionSave() in src/XF/Mvc/Dispatcher.php at line 321
> XF\Mvc\Dispatcher->dispatchClass() in src/XF/Mvc/Dispatcher.php at line 249
> XF\Mvc\Dispatcher->dispatchFromMatch() in src/XF/Mvc/Dispatcher.php at line 100
> XF\Mvc\Dispatcher->dispatchLoop() in src/XF/Mvc/Dispatcher.php at line 50
> XF\Mvc\Dispatcher->run() in src/XF/App.php at line 2177
> XF\App->run() in src/XF.php at line 390
> XF::runApp() in admin.php at line 13

**Comment by LukasWieditz** [comment]
Ask them to reinstall the uix add-on
