### ISSUE TITLE
[Monetize] Option to show sponsored node logo below node name

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1858]
This was suggested by [doublespaces](https://xenforo.com/community/threads/th-monetize-paid.162453/post-1353629) on xenforo.com:

> Second, is it possible to have an option to show the logo below the node name? in the description area? I've found that putting the logo up above doubles the height of the sponsored sections and that can be a bit much. Also, when you're inside this forum, it can be nice to see the company logo at the top of the forum. I think this is another good 'option' for applying this sponsoring logo. Or maybe just removing the forum node names entirely and allowing the logos to do the work? I have clickable nodes enabled or whatever the option is that makes the entire node row a clickable element.

**Comment by LukasWieditz** [comment]
We've played through a couple of possible structures for this, but none were really making sense. This would probably best be changed by the respective user to suit their needs/wants, if they need it.
