### ISSUE TITLE
[Trending] Issues with adding Trending as a primary navigation link

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1860]
It has been reported by one of our clients that there are troubles with the tab not showing on the navigation bar for Trending. You are only able to see it as a sub-navigation link under the Forums navigation tab. Even when editing the position of it within the navigation manager, it still doesn't work as it should.

Also, when enabling "Show tab" within trending configurations it still shows as a sub-navigation link within the forums tab instead of adding a main navigation tab marked "Trending".

More information is found in Ticket #14251

**Comment by LukasWieditz** [comment]
That's a limitation of XenForo. You can only define one tab to be marked as active for any given route. They'll either need to make that admin-editable or the user will require an add-on to change it, unfortunately.
