### ISSUE TITLE
[Monetize] Upgrade Required phrase not spacing correctly

### ISSUE THREAD

**Issue by GH-Rake** [Audentio/xf2addon-issues#1865]
Add-on Name:
Monetize

Add-on Version:
1.0.1 Patch level 3

XenForo Version:
2.1.2

Operating System (and Version):
Windows 10 1809

Browser Name (and Version):
Firefox 67.0.1

Summary of issue:
Upgrade Required phrase not spacing correctly

Detailed steps to reproduce the issue:
Go to a url that requires an upgrade to view, it'll prompt you to upgrade and you will see this phrase without proper spacing.

Upload any screenshots related to the issue below
![screenshot](https://guidedhacking.com/gh/sshots/chrome_2019-06-09_23-21-24.png)

**Comment by jonw316** [comment]
@Ian-Hitt This is only an issue with UI.X. Is this something you can fix?

**Comment by GH-Rake** [comment]
I would appreciate this patch released as soon as you can.

**Comment by GH-Rake** [comment]
This is still not fixed

**Comment by GH-Rake** [comment]
Neither [TH] Monetize 1.0.2 Patch Level 1 nor [TH] UI.X 2.1.2 Patch Level 4 fixed this issue

**Comment by LukasWieditz** [comment]
If you've overwritten the fixed phrase (e.g. through a translation), then the issue will remain.

**Comment by GH-Rake** [comment]
That is correct, but we had to modify your phrases because we get broken links on all these "you must upgrade to view" because they give improper urls which 404 due to this:

ThemeHouse-Monetize-1.0.2_Patch_Level_1\upload\src\addons\ThemeHouse\Monetize\XF\ControllerPlugin\Error.php

Line 60-64:

```
if (!$message) {
	$message = \XF::phrase('thmonetize_an_account_upgrade_is_required_to_continue', [
		'link' => \XF::app()->router('public')->buildLink('account/upgrade'),
	]);
}
```

"account/upgrade" should be "account/upgrades"

**Comment by GH-Rake** [comment]
This issue still exist, but only when using these features:
![image](https://user-images.githubusercontent.com/15186628/105739302-fa13aa00-5f05-11eb-8d91-6408fefaf810.png)

![image](https://user-images.githubusercontent.com/15186628/105739349-03047b80-5f06-11eb-93ff-5cc88cb3942c.png)

It was fixed in one place when this issue was originally fixed, but not here
