### ISSUE TITLE
[Monetize] Keyword replacement functionality isn't friendly with words that have accents

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1868]
Reported by [DavidXLD](https://xenforo.com/community/threads/th-monetize-paid.162453/post-1356049) on xenforo.com

> Hi, 
> It seems that keywords replacement does not work with words having accents.
> My forum being is french, it is a must have :)
> As an exemple, the keyword "tableau croisé" is not found and not replaced.
> Is it possible to have a quick fix?
> Thanks
> David

**Comment by LukasWieditz** [comment]
References #1914
