### ISSUE TITLE
[TH] Featured Threads and Content 1.0.0 Beta 1  - Editing details

### ISSUE THREAD

**Issue by arm5ky** [Audentio/xf2addon-issues#1874]
Add-on Name:
[TH] Featured Threads and Content
Add-on Version:
1.0.0 Beta 1 
XenForo Version:
v2.1.2

Summary of issue:
Once you feature a thread, your options, are feature/unfeature.
There isn't an edit feature, and feature doesn't fill current setting in.
Detailed steps to reproduce the issue:

Upload any screenshots related to the issue below
![image](https://user-images.githubusercontent.com/6074069/59360697-7b65fb00-8d28-11e9-8e7d-e110c3856f09.png)

**Comment by arm5ky** [comment]
Eg, i went into this one(using feature) to edit the expiry date and all is blank,

**Comment by JakeBooher** [comment]
That page is the edit page, any values you set will remain. Just tested and this seems to be working correctly for all of the fields
