### ISSUE TITLE
Undefined property <topics>

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2addon-issues#1875]
In `ThemeHouse\Topics\XF\Entity\Thread (Line 248)`

**Comment by JakeBooher** [comment]
Why is this as designed?

**Comment by jonw316** [comment]
It's not undefined. I don't know what you are using to find these "bugs" but they are not bugs.

**Comment by LukasWieditz** [comment]
Proper type hinting. Feel free to add the additional type hinting and comments to resolve the warning then.
