### ISSUE TITLE
Image optimizer error log

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2addon-issues#1881]
Server error log
ErrorException: [Image Optimizer] Error received for status ID 644: Pngquant failed to optimize image with response code 99 src/XF/Error.php:75
Generated by: Unknown account Jun 13, 2019 at 6:50 PM
Stack trace
#0 src/XF.php(187): XF\Error->logError('[Image Optimize...', false)
#1 src/addons/ThemeHouse/ImageOptimizer/ImageOptimizer/Traits/ExecutableProviderTrait.php(25): XF::logError('[Image Optimize...')
#2 src/addons/ThemeHouse/ImageOptimizer/Service/ImageOptimizer/Optimize.php(49): ThemeHouse\ImageOptimizer\ImageOptimizer\Pngquant->optimizeImage(Object(ThemeHouse\ImageOptimizer\Service\ImageOptimizer\Optimize))
#3 src/addons/ThemeHouse/ImageOptimizer/ContentHandler/AbstractHandler.php(57): ThemeHouse\ImageOptimizer\Service\ImageOptimizer\Optimize->run()
#4 src/addons/ThemeHouse/ImageOptimizer/Cron/Optimize.php(18): ThemeHouse\ImageOptimizer\ContentHandler\AbstractHandler->optimize(Object(ThemeHouse\ImageOptimizer\Entity\Status))
#5 [internal function]: ThemeHouse\ImageOptimizer\Cron\Optimize::optimizeImages(Object(XF\Entity\CronEntry))
#6 src/XF/Job/Cron.php(34): call_user_func(Array, Object(XF\Entity\CronEntry))
#7 src/XF/Job/Manager.php(253): XF\Job\Cron->run(G)
#8 src/XF/Job/Manager.php(195): XF\Job\Manager->runJobInternal(Array, G)
#9 src/XF/Job/Manager.php(79): XF\Job\Manager->runJobEntry(Array, G)
#10 job.php(42): XF\Job\Manager->runQueue(false, 8)
#11 {main}
Request state
array(4) {
  ["url"] => string(8) "/job.php"
  ["referrer"] => string(46) "https://www.joyfreak.com/forums/general-forum/"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}

**Comment by LukasWieditz** [comment]
Error code 99 means that Pngquant hasn't been able to match quality 65-80. If this is an ongoing issue, official recommendation from them is to drop the minimum quality to a lower threshold.
