### ISSUE TITLE
How can I get "Similar threads" add-on to work with the Nodes post thread overlay

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2addon-issues#1882]
![overlay](https://user-images.githubusercontent.com/43339306/59521468-3f679d00-8ec4-11e9-8d11-ea4e11b0baf5.png)

Similar threads add-on: https://www.xf2addons.com/resources/similar-threads.17/

I can't seem to get it to work with the overlay. I have spoken to AndyB and he said he doesn't support third party option. Would it be OK to make it compatible?

**Comment by LukasWieditz** [comment]
Nodes merely opens the normal post thread form in an overlay. If AndyBs Similar Threads add-on doesn't work there, that is quite unfortunately a _bug_ in his add-on and the way it handles things and there's nothing we can do about that.
