### ISSUE TITLE
[UserCriteriaExt] Replace earnt with earned

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1883]
![image](https://user-images.githubusercontent.com/32306910/59530600-a2980600-8ea9-11e9-8627-ed3937913f13.png)
Replace **earnt** with **earned** within the following criteria

- User has earnt at least one of the selected trophies
- User has earnt none of the selected trophies
- User has earnt all of the selected trophies

**Comment by LukasWieditz** [comment]
`Earnt` is a valid spelling, so will consider this as enhancement.
