### ISSUE TITLE
Featured content stat from user linkable

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#1889]
![image](https://user-images.githubusercontent.com/1217271/59637448-72579e00-911b-11e9-8328-1b2ad7eaf848.png)

Featured Content only one not linked

**Comment by LukasWieditz** [comment]
Wiki edits isn't linked either, as are a number of other stats. There's effectively no page that it could link to, as the featured content site can't be filtered by user at the moment.
