### ISSUE TITLE
Reaction types enable/disable option

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#189]
Please add support enable/disable option for Reaction types. So we can enable/disable Reaction types without delete.

![screenshot00098](https://user-images.githubusercontent.com/6899856/38691328-d70f9fd0-3e80-11e8-82f8-3b750a68de07.png)

**Comment by JakeBooher** [comment]
Hi,

Currently there are no plans on having a toggle for reaction types, your best bet would be to disable the reactions associated with these types
