### ISSUE TITLE
[ReactPlus] Hide posts after X neagative reactions/negative reaction percentage

### ISSUE THREAD

**Issue by JakeBooher** [Audentio/xf2addon-issues#19]
![1505327904214](https://user-images.githubusercontent.com/179180/30395465-e8eebd94-988b-11e7-85b5-dbbdf2313d50.png)

Post will need to display a placeholder with something along the lines of "This post has been hidden due to its rating" and an option to expand it

**Comment by kintaro1981** [comment]
how about a second level of action putting the post on moderation in case have more negative ratings/percentage?

**Comment by LukasWieditz** [comment]
@JakeBooher you have this planned with the automod feature, right?

**Comment by JakeBooher** [comment]
yep, this falls under #1326
