### ISSUE TITLE
Trending usergroup permissions

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#190]
For sake of disabling temporarily or showing only to admins

**Comment by mikecreuzer** [comment]
I think this might be good just so they can test it before releasing it.

**Comment by LukasWieditz** [comment]
As a reference: https://xenforo.com/community/threads/content-permissions-do-not-reset.148059/
This affects us in particular, as Trending has only one permission, so it'll happen more often.
