### ISSUE TITLE
[TH] ImageOptimizer Errors - TypeError:

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#1905]
Getting a good few hundred of the below errors since last night. List is growing so not sure what's tripping it off.

TypeError: Argument 1 passed to ThemeHouse\ImageOptimizer\ContentHandler\ImageProxy::hasImage() must be an instance of XF\Mvc\Entity\Entity, null given, called in /home/nginx/domains/mysite.com/public/src/addons/ThemeHouse/ImageOptimizer/ContentHandler/AbstractHandler.php on line 43 src/addons/ThemeHouse/ImageOptimizer/ContentHandler/ImageProxy.php:90
Generated by: Unknown account Jun 22, 2019 at 10:56 AM
Stack trace
#0 src/addons/ThemeHouse/ImageOptimizer/ContentHandler/AbstractHandler.php(43): ThemeHouse\ImageOptimizer\ContentHandler\ImageProxy->hasImage(NULL)
#1 src/addons/ThemeHouse/ImageOptimizer/Cron/Optimize.php(18): ThemeHouse\ImageOptimizer\ContentHandler\AbstractHandler->optimize(Object(ThemeHouse\ImageOptimizer\Entity\Status))
#2 [internal function]: ThemeHouse\ImageOptimizer\Cron\Optimize::optimizeImages(Object(XF\Entity\CronEntry))
#3 src/XF/Job/Cron.php(34): call_user_func(Array, Object(XF\Entity\CronEntry))
#4 src/XF/Job/Manager.php(253): XF\Job\Cron->run(G)
#5 src/XF/Job/Manager.php(195): XF\Job\Manager->runJobInternal(Array, G)
#6 src/XF/Job/Manager.php(79): XF\Job\Manager->runJobEntry(Array, G)
#7 job.php(42): XF\Job\Manager->runQueue(false, 8)
#8 {main}
Request state
array(4) {
  ["url"] => string(8) "/job.php"
  ["referrer"] => string(53) "https://mysite.com/admin.php?options/"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}

**Comment by Nirjonadda** [comment]
@ichpen @LukasWieditz @JakeBooher Does this error fixed? I am also getting this server error log.
