### ISSUE TITLE
[Covers] Can not update

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1911]
Also getting /admin.php?tools/run-job The requested page could not be found when updating. /admin.php?add-ons/ThemeHouse-Covers/upgrade The requested page could not be found.

![ScreenShot01131](https://user-images.githubusercontent.com/6899856/60195678-ce1cd800-983b-11e9-8e1d-89accae19228.png)

**Comment by LukasWieditz** [comment]
I don't see any indicator in the code that could be the cause of this problem and fail to replicate it. Try to disable listeners in the config.php and see if you can proceed with the upgrade then.
