### ISSUE TITLE
[QAForums] Question status filter

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1913]
Question status filter should not be show non Question and Answer, only show for Question and Answer forum.

When checked:

![ScreenShot01134](https://user-images.githubusercontent.com/6899856/60208277-282b9680-9858-11e9-9edb-630cb9b23650.png)

Then show:

![ScreenShot01133](https://user-images.githubusercontent.com/6899856/60208269-21048880-9858-11e9-9e1e-a489f6cf8932.png)

**Comment by LukasWieditz** [comment]
The permission only controls, if the thread status is question by default, not whether it is possible to post a question in the forum or not, so that's no sufficient indicator to decide whether the filter should be shown or not.
