### ISSUE TITLE
[Nodes] Watch text is being shown instead of Unwatch when node is unwatched

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1920]
When hovering over the unwatch icon, the hover phrase shows "Watch" instead of "Unwatch" as you are already watching the node but are expecting to see "Unwatch" when hovering over the icon to unwatch the forum.
![image](https://user-images.githubusercontent.com/32306910/60538895-2424cc00-9cd1-11e9-844c-86066d16de4f.png)

**Comment by LukasWieditz** [comment]
This is a result of ajax-toggling, which is not capable of replacing the tooltip as XenForo doesn't support that. Upon reload, the phrase will be correct.
