### ISSUE TITLE
[QAForums] {type} placeholder in phrase thqaforums_your_answer_in_thread_x_has_received_a_x not translatable

### ISSUE THREAD

**Issue by setoy** [Audentio/xf2addon-issues#1926]
As the title states. Apparently the type is not phrased so a translation of the entire `thqaforums_your_answer_in_thread_x_has_received_a_x` phrase results in mixed languages.

**Comment by LukasWieditz** [comment]
`thqaforums_alert_downvote` and `thqaforums_alert_upvote`.
