### ISSUE TITLE
Reactions - SP to make reactions overview on profiles be made into a profile tab

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#193]
![screen shot 2018-04-12 at 2 56 29 pm](https://user-images.githubusercontent.com/32306910/38700925-3124ae12-3e62-11e8-8466-108e076363fa.png)

**Comment by lilalien** [comment]
This would be nice, and it can look somewhat like this...

![reactions_leaderboard_example](https://user-images.githubusercontent.com/35111972/38708683-6bff236e-3e85-11e8-86ff-c51dabff1805.png)

**Comment by LukasWieditz** [comment]
As this is a widget by default, I made a global setting to turn on a reaction stats tab that'll display the stats in a profile tab pane instead of a widget. @Ian-Hitt it needs some styling love though, probably.
