### ISSUE TITLE
[Donate] Template error

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1948]
ErrorException: Template error: Method canViewDonationCampaigns is not callable on the given object (XF\Entity\User) src/XF/Template/Templater.php:994

    Generated by: Unknown account Jul 24, 2019 at 6:00 AM

Stack trace

#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Method canViewD...', '/home/dressedw/...', 994, Array)
#1 src/XF/Template/Templater.php(994): trigger_error('Method canViewD...', 512)
#2 internal_data/code_cache/navigation_cache.php(426): XF\Template\Templater->method(Object(XF\Entity\User), 'canViewDonation...', Array)
#3 src/XF/Template/Templater.php(6646): XF\Pub\App->{closure}(Object(XF\Template\Templater), 'forums', Array)
#4 src/XF/Pub/App.php(560): XF\Template\Templater->renderNavigationClosure(Object(Closure), 'forums', Array)
#5 src/XF/Pub/App.php(513): XF\Pub\App->getNavigation(Array, 'forums')
#6 src/XF/App.php(1989): XF\Pub\App->renderPageHtml('

    
...', Array, Object(XF\Mvc\Reply\View), Object(XF\Mvc\Renderer\Html))
#7 src/XF/Mvc/Dispatcher.php(362): XF\App->renderPage('

    
...', Object(XF\Mvc\Reply\View), Object(XF\Mvc\Renderer\Html))
#8 src/XF/Mvc/Dispatcher.php(53): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#9 src/XF/App.php(2178): XF\Mvc\Dispatcher->run()
#10 src/XF.php(390): XF\App->run()
#11 index.php(20): XF::runApp('XF\\Pub\\App')
#12 {main}

Request state

array(4) {
  ["url"] => string(39) "/threads/what-are-you-wearing-today.86/"
  ["referrer"] => bool(false)
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}

Delete

**Comment by LukasWieditz** [comment]
Looks like he disabled the add-on but has a public navigation conditional left that relies on a function added by the add-on.
