### ISSUE TITLE
[Monetize] ErrorException: [E_NOTICE] Trying to get property 'thmonetize_custom_amount' [Bug]

### ISSUE THREAD

**Issue by GH-Rake** [Audentio/xf2addon-issues#1950]
Add-on Name:
Monetize

Add-on Version: 
1.0.1 Patch Level 3

XenForo Version:
2.1.3

Operating System (and Version):
Windows 10 1903

Browser Name (and Version):
Firefox

Summary of issue:
This error is logged:

`
ErrorException: [E_NOTICE] Trying to get property 'thmonetize_custom_amount' of non-object src/addons/ThemeHouse/Monetize/XF/Purchasable/UserUpgrade.php:17

Stack trace

#0 src/addons/ThemeHouse/Monetize/XF/Purchasable/UserUpgrade.php(17): XF::handlePhpError(8, '[E_NOTICE] Tryi...', '/home/*****/...', 17, Array)
#1 src/XF/Pub/Controller/Purchase.php(21): ThemeHouse\Monetize\XF\Purchasable\UserUpgrade->getPurchaseFromRequest(Object(XF\Http\Request), Object(SV\WarningImprovements\XF\Entity\User), Object(XF\Phrase))
#2 src/addons/ThemeHouse/Monetize/XF/Pub/Controller/Purchase.php(55): XF\Pub\Controller\Purchase->actionIndex(Object(XF\Mvc\ParameterBag))
#3 src/XF/Mvc/Dispatcher.php(321): ThemeHouse\Monetize\XF\Pub\Controller\Purchase->actionIndex(Object(XF\Mvc\ParameterBag))
#4 src/XF/Mvc/Dispatcher.php(244): XF\Mvc\Dispatcher->dispatchClass('XF:Purchase', 'Index', Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Monetize\XF\Pub\Controller\Purchase), NULL)
#5 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Monetize\XF\Pub\Controller\Purchase), NULL)
#6 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#7 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#8 src/XF.php(390): XF\App->run()
#9 index.php(20): XF::runApp('XF\Pub\App')
#10 {main}

Request state

array(4) {
["url"] => string(41) "/purchase/user_upgrade/?user_upgrade_id=4"
["referrer"] => string(50) "https://*****.com/attachments/*****rar.6077/"
["_GET"] => array(1) {
["user_upgrade_id"] => string(1) "4"
}
["_POST"] => array(5) {
["payment_profile_id"] => string(1) "3"
["_xfToken"] => string(8) "********"
["_xfRequestUri"] => string(25) "/attachments/*****rar.6077/"
["_xfWithData"] => string(1) "1"
["_xfResponseType"] => string(4) "json"
}
}
`

It doesn't matter if custom amount is turned off or on, it happens regardless on my board.

Detailed steps to reproduce the issue:
On my board with 110k members, the error occurs about once per day.

I have already submitted this to the themehouse.com ticketing system and in the resource thread on xenforo.com and haven't seen a fix so I'm posting it here as well.

**Comment by LukasWieditz** [comment]
References #1921
