### ISSUE TITLE
[Monetize] Replace only whole words

### ISSUE THREAD

**Issue by GH-Rake** [Audentio/xf2addon-issues#1960]
Add-on Name:
Monetize

Add-on Version:
1.0.1 PL3

XenForo Version:
2.13

Summary of issue:
When doing keyword replacement, if the keyword is "ice" it will replace "ice" in the word "nice"
This looks really silly.  The issue has been brought up on the Xenforo resource page a few times.

All your products are awesome, as a loyal customer I hope to see a fix soon :)

**Comment by LukasWieditz** [comment]
Disable "match in word".

**Comment by LukasWieditz** [comment]
Duplicate of #1914
