### ISSUE TITLE
TH QA - can't edit q and a thread 

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#1961]
Add-on Name:
TH Q&A

XenForo Version:
2.1.2

Operating System (and Version):

Browser Name (and Version):

Summary of issue:

Threads created as q and a threads cannot be switched back to normal threads as the thread is a question checkbox appears unchecked. 

Detailed steps to reproduce the issue:
As administrator edit any q and a thread, see if q and a checkbox is checked. Attempt to revert to a normal thread. 

Upload any screenshots related to the issue below

**Comment by LukasWieditz** [comment]
I find myself unable to reproduce this. The checkbox is checked as expected on question threads
