### ISSUE TITLE
[Monetize] [Enhancement] Limit keyword replacement frequency 

### ISSUE THREAD

**Issue by GH-Rake** [Audentio/xf2addon-issues#1962]
Add-on Name:
Monetize

Add-on Version:
1.0.2

XenForo Version:
2.1.3

Summary:
If a keyword is used 10 times in a paragraph, that paragraph has too many keyword replacements to be visually appealing.  At a minimum I think the replacement shouldn't occur twice in a sentence.  

Maybe limit the frequency across an array of characters, such as "only replace once per 200 characters".

**Comment by LukasWieditz** [comment]
Unless the keyword is a very common word, this seems like a very exotic edge case to me. Regardless, it's not really feasibly implementable either way, so we'll likely won't do it.
