### ISSUE TITLE
[Monetize] Bug - "Keyword replace limit per page" option not working with small values

### ISSUE THREAD

**Issue by GH-Rake** [Audentio/xf2addon-issues#1963]
**Add-on Name:**
Monetize

**Add-on Version:**
1.0.2 and 1.0.1 PL 3 as well

**XenForo Version:**
2.1.3

**Operating System & Browser:**
Windows 10 1903 & Firefox 68.0.1

**Summary of issue:**
When setting the "Keyword replace limit per page" setting in the Monetize Options to a number such as 2 or 5, zero keywords get replaced on the page, essentially disabling the entire keyword replacement feature.

If I set it to a large number like 50 or 99, it will perform the replacements, but due to the large number it's hard to notice if the limit is working.

The "Keyword replace limit per word/phrase" is working as intended.

**Detailed steps to reproduce the issue:**
Set the "Keyword replace limit per page" to 2.  Create a keyword replacement for "dog".  Create a thread that says dog 5 times.  No replacement occurs,

Thank you for the recent update :)

**Comment by LukasWieditz** [comment]
It appears posts that do not have any occurrence of the keyword still increase the replacement counter by one.
