### ISSUE TITLE
[Featured] Misaligned Buttons on Grid View

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1968]
Add-on Name: [TH] Featured Threads & Content

Add-on Version: 1.0.3 Patch Level 1

XenForo Version: 2.1.3

Operating System (and Version): Windows 10

Browser Name (and Version): Google Chrome - Version 76.0.3809.100 (Official Build) (64-bit)

Summary of issue:
Buttons are misaligned on featured polls when grid styling is selected in style properties. This was reported by Nikki when she was handling updated screenshots for the add-on.

Detailed steps to reproduce the issue:
Navigate to Appearance -> Style Properties -> Featured Threads and Content -> Set the Message Display style to Grid. Be sure you are featuring a poll that hasn't been voted on yet.
Upload any screenshots related to the issue below
![image](https://user-images.githubusercontent.com/32306910/63446080-2d900200-c3ff-11e9-9cc3-8adbc7610761.png)

**Comment by LukasWieditz** [comment]
Ian argued it's not an issue and just how the content works, due to it being different height.
