### ISSUE TITLE
[Feature] Icon Styling

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1969]
There doesn't seem to be any change in icon styling when changing it to `default style` or` postbit style`. Does the icon size need to be set to some specific size for it to change the icon styling?

Me and Nikki were able to replicate this when grabbing updated screenshots.

**Comment by JakeBooher** [comment]
<img width="263" alt="Screen Shot 2019-09-20 at 10 38 30 AM" src="https://user-images.githubusercontent.com/179180/65339975-d2366880-db92-11e9-94f0-a629f23f389c.png">
<img width="173" alt="Screen Shot 2019-09-20 at 10 38 18 AM" src="https://user-images.githubusercontent.com/179180/65339976-d2366880-db92-11e9-94d0-6af1318516ea.png">

I'm not able to replicate this, they look completely different for me
