### ISSUE TITLE
[Covers] When setting a animated image (gif) as my profile cover, it makes it a jpg file instead

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1977]
Add-on Name: [TH] Covers

Add-on Version: 1.0.4 Patch Level 2

XenForo Version: 2.1.3

Operating System (and Version): Windows 10

Browser Name (and Version): Google Chrome Version 76.0.3809.132 (Official Build) (64-bit)

Summary of issue: Animated images are being made non-animated images

Detailed steps to reproduce the issue: Grab an animated image before setting it as your own profile cover image, set the position, then save. As you'll see it no longer animated and when inspecting it you'll see the images file type has changed to a jpg.

Upload any screenshots related to the issue below

**Comment by LukasWieditz** [comment]
That's not a bug in Covers. Using GIFs in XenForo generally requires an underlying image processing library to be installed in addition, otherwise resizing GIFs will remove the animation.
