### ISSUE TITLE
[Giphy] Mixed content warning

### ISSUE THREAD

**Issue by setoy** [Audentio/xf2addon-issues#1985]
A gif in my forums is posted on a users profile page. The browser warns me because of mixed content.

```
Mixed Content: The page at 'https://domain.com/' was loaded over HTTPS, but requested an insecure image 'http://giphygifs.s3.amazonaws.com/media/5ev3alRsskWA0/giphy.webp'. This request has been blocked; the content must be served over HTTPS.
```

![image](https://user-images.githubusercontent.com/6497266/64562607-a70b7800-d34d-11e9-8bb3-c9f550c51a71.png)

**Comment by LukasWieditz** [comment]
Nothing we can do from here, that's an issue on Giphys end. It's also happening when you open the embed directly.
