### ISSUE TITLE
[IndicateThreadsStaffReplies] Permission issue with new registrations with the add-on enabled

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1986]
Add-on Name: [TH] Indicate Threads with Staff Replies

Add-on Version: 1.0.0

XenForo Version: 2.1.3

Operating System (and Version): Windows 10

Browser Name (and Version): Google Chrome -
Version 76.0.3809.132 (Official Build) (64-bit)

Summary of issue: Oops! We ran into some problems - You do not have permission to view this page or perform this action -- Is shown to newly registered users who have been approved by administrators or have verified their email while attempting to explore the forum and other areas of it.

Detailed steps to reproduce the issue: Disable any other add-ons besides [TH] Indicate Threads with Staff Replies. Register a new user, verify that users email, then try clicking around, any pages, forums, or options you try to click on replicates that error. It only happens with that add-on enabled. Registered user-group is left untouched when testing this.

This was replicated by [Lsdeep](https://xenforo.com/community/threads/th-indicate-threads-with-staff-replies-paid.167714/post-1373307) on xenforo.com/community 

Upload any screenshots related to the issue below

**Comment by LukasWieditz** [comment]
I'm unable to replicate this and couldn't even point at any potential sources. The add-on doesn't even come near any spots that deal with permissions.
