### ISSUE TITLE
[ReactionsPlus] Accessed unknown getter 'th_reactplus_hide_post'

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1987]
Error reported by ALMUSA on xenforo.com/community
> [LIST]
> [*]InvalidArgumentException: Accessed unknown getter 'th_reactplus_hide_post' on XF:Post[3053760]
> [*]src/XF/Mvc/Entity/Entity.php:194
> [/LIST]
> 
> 
> 
> #0 src/XF/Mvc/Entity/Entity.php(106): XF\Mvc\Entity\Entity->get('th_reactplus_hi...')
> #1 internal_data/code_cache/templates/l5/s32/public/post_macros.php(18): XF\Mvc\Entity\Entity->offsetGet('th_reactplus_hi...')
> #2 src/XF/Template/Templater.php(701): XF\Template\Templater->{closure}(Object(XF\Template\Templater), Array, Array)
> #3 internal_data/code_cache/templates/l5/s32/public/thread_view.php(612): XF\Template\Templater->callMacro('post_macros', 'post', Array, Array)
> #4 src/XF/Template/Templater.php(1301): XF\Template\Templater->{closure}(Object(XF\Template\Templater), Array)
> #5 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('thread_view', Array)
> #6 src/XF/Mvc/Renderer/Html.php(48): XF\Template\Template->render()
> #7 src/XF/Mvc/Dispatcher.php(418): XF\Mvc\Renderer\Html->renderView('XF:Thread\\View', 'public:thread_v...', Array)
> #8 src/XF/Mvc/Dispatcher.php(400): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
> #9 src/XF/Mvc/Dispatcher.php(360): XF\Mvc\Dispatcher->renderReply(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
> #10 src/XF/Mvc/Dispatcher.php(53): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
> #11 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
> #12 src/XF.php(390): XF\App->run()
> #13 index.php(20): XF::runApp('XF\\Pub\\App')
> #14 {main}

**Comment by LukasWieditz** [comment]
This seems to be the result of a 3rd party modification overwriting the entity structure.
