### ISSUE TITLE
[Feature] Stylistic suggestions: Masonry style/Read More button

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1990]
Bring back the masonry style and give the "Read More" button a more lively look.
https://xenforo.com/community/threads/th-featured-threads-and-content-portal-paid.166623/post-1373387

**Comment by LukasWieditz** [comment]
We've had an internal discussion about this and decided this is not something we want to implement. Masonry itself is a good concept, but we're not happy with the available solutions for it (aka. having to implement a Javascript library for it).
