### ISSUE TITLE
[Featured] If no attachment, look for background image in IMG tag, otherwise use a default image specified in a style property.

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1993]
If no attachment, look for background image in IMG tag, otherwise use a default image specified in a style property.
https://xenforo.com/community/threads/th-featured-threads-and-content-portal-paid.166623/post-1373387

**Comment by LukasWieditz** [comment]
We've decided against grabbing an image from an [img] tag, but we'll consider implementing a default image/icon fir #2039
