### ISSUE TITLE
Monetize "Require user upgrade on registration" not as expected Suggestion

### ISSUE THREAD

**Issue by GH-Rake** [Audentio/xf2addon-issues#2000]
**Add-on Name:**
Monetize
**Add-on Version:**
1.0.2
**XenForo Version:**
2.14
**Operating System (and Version):**
Windows 10 1903
**Browser Name (and Version):**
Brave Version 0.68.139 Chromium: 77.0.3865.90 & Firefox Quantum latest

**Summary of issue:**
If you register but do not select an upgrade, you can still browse the forum but you are "awaiting user upgrade purchase".

**Detailed steps to reproduce the issue:**
Register, when it asks to upgrade, just click away from that page.  You can still browse, just can't interact.

**Expected/Suggested outcome:**
My expectation would be that they can't do anything while "require user upgrade on registration" is enabled.  My suggestion would be either set their ability to view the forum to be NO while in this state, or to make it so they can't click away from the user upgrade purchase page.

**Comment by LukasWieditz** [comment]
Unless I'm missing something, all you need to do is set the "View" permission to "No" for the base user group and add it back in with the upgraded user groups.

**Comment by GH-Rake** [comment]
That would work.  The reason I brought this up is, some people are just not intelligent enough to see the "you must purchase an upgrade" notice and file complaints that the site is broken.  Not kidding, I've gotten ~5 of these emails since using Monetize.

You've provided a solution that works, you can close this or use the info for a future change.  thanks
