### ISSUE TITLE
[Nodes] Nodes Icon Tweak support

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2002]
One of our customers has reported issues with using our Nodes add-on with Xen Factory's Icon Tweak add-on. 

The following screenshots included shows with and without the icon tweak add-on enabled.
![With_Nodes_Icon_Tweak](https://user-images.githubusercontent.com/32306910/65521054-3e281200-deae-11e9-843f-3bec2fec1815.png)
![Without_Nodes_Icon_Tweak](https://user-images.githubusercontent.com/32306910/65521055-3e281200-deae-11e9-87de-a5eaf10126ed.png)

**Comment by dinhphucv** [comment]
Looking for this fix too as Material icon is lack of some icon compare with fontawesome

**Comment by LukasWieditz** [comment]
Nodes and/or UI.X don't limit you to Material icons. You can still use FontAwesome icons as you please.
