### ISSUE TITLE
[StyleSwitch] The style doesn't change completely

### ISSUE THREAD

**Issue by dinhphucv** [Audentio/xf2addon-issues#2005]
Add-on Name: [TH] Style Switch

Add-on Version: 1.0.0 Patch Level 2

XenForo Version: 2.1.4

Operating System (and Version): Windows 10

Browser Name (and Version): Chrome

Summary of issue: Style Switch doesn't change the the style completely

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35757295/65755946-f3cead00-e0c8-11e9-840a-63efa4ae9989.gif)

I haven't check with other styles

**Comment by JakeBooher** [comment]
Could you please elaborate on what exactly isn't changing? Unfortunately a gif of the entire screen isn't very descriptive of the issue

**Comment by JakeBooher** [comment]
Could you please create a ticket at themehouse.com with a link to your site? I'm unable to replicate this

**Comment by 6686** [comment]
have support #Rekt.

**Comment by dinhphucv** [comment]
> Could you please create a ticket at themehouse.com with a link to your site? I'm unable to replicate this

Ticket has been submit #15126
