### ISSUE TITLE
[Giphy] Giphy search doesn't work when you edit a post

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2010]
Reported by RDR on xenforo.com

> Is the giphy search not working when you edit a post?
> 
> I create a post and then go edit to insert giphy image and the search doesn't populate with anything.

I am able to replicate this on my demo as well. When editing a post, try to search for a GIF. You'll see that clicking the "Search" button does nothing.

**Comment by facebookbug** [comment]
Same again! I add GIF  and  the giphy search not working. I can't find it even tags and file name the same!
