### ISSUE TITLE
[Holidays] Read/Unread icons not viewable

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2024]
Some of these holidays don't have any read/unread images being shown when switching to them. I even tried to rebuild the add-on and disabled any other add-ons to see if it would fix it. But no luck.

- Birthday
- Christmas
- 4th of July

**Comment by LukasWieditz** [comment]
Which style(s)?

**Comment by daltonp** [comment]
I was able to replicate this on any of our styles and the default style.
