### ISSUE TITLE
[Holidays] Not compatible with other style?

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2030]
This add-on not compatible with @Ehren this [Uniform](https://xenforo.com/community/resources/uniform.5944/) style. So please can you do compatible update your add-on for work with other style?

Breadcrumb navigation long space when addon enabled.

![FrmIRx6BTB6Zo8LItqI4zA](https://user-images.githubusercontent.com/6899856/67510706-be9c8700-f695-11e9-9451-d428aa8f4fb2.png)

Breadcrumb navigation long space issue will be fixed with Adding this code to extra.less but Node icon not working for @Ehren Uniform style. So please do applie the solution. TH failing to add styling to the left div broke the layout since (with absolute positioning) it became a flex element. And despite their claims, the navigation is a flex element in the default theme too.

Adding this to extra.less will be fixed the problem Breadcrumb navigation long space issue.

```
.th_holiday__categoryStrip__left,
.th_holiday__categoryStrip__center,
.th_holiday__categoryStrip__right{
display: none;
} 
```

With holiday enabled.

![ScreenShot01241](https://user-images.githubusercontent.com/6899856/67510779-e12ea000-f695-11e9-9e64-b32a75ed6f94.png)

Without holiday disabled.

![ScreenShot01242](https://user-images.githubusercontent.com/6899856/67510813-ef7cbc00-f695-11e9-9f49-2cdb4690817e.png)

**Comment by LukasWieditz** [comment]
This is not something that [TH] Holidays can take care of. Individual holiday effects may need to be adjusted manually to work with your 3rd party style. You can edit them under ACP > Appearance > Holidays.
