### ISSUE TITLE
[Donate] Anonymous donations still trigger donation threshold for trophies

### ISSUE THREAD

**Issue by setoy** [Audentio/xf2addon-issues#2040]
Anonymous donations (whether hidden user or hidden amount) should not count towards the trophy threshold. Otherwise you'd see an anonymous donor receive donations about various amounts, thus unwantingly revealing the donation amounts.

**Comment by LukasWieditz** [comment]
As the criteria only entail the total donation amount, and not the total public donation amount, that would be correct behavior. It could be considered to add additional public donation amount criteria, but this specific situation would be working as expected.
