### ISSUE TITLE
Add functionality to allow administrators to set custom dates on holidays

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2043]
This was suggested by one of our customers on a support ticket:
There is no option in the Appearance → Holidays settings for holidays that fall on a designated day of the month regardless of the date. That needs to be programmed for dates such as these. For example Martin Lither King, Jr. Day is always on a 3rd Monday in January, regardless of the date it falls on.

**Comment by LukasWieditz** [comment]
This can be done with the callback option for activity checks. We're using this for Thanksgiving for example.
