### ISSUE TITLE
[Holidays] Thanksgiving are not end

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2050]
I have set Thanksgiving Start to 27 to End 28 but this start in 27 but this still are running after 28 and not ended after 30

![ScreenShot01296](https://user-images.githubusercontent.com/6899856/69899942-87dd1f00-136d-11ea-895e-1f1425830ffd.png)

**Comment by LukasWieditz** [comment]
The source of this is very likely that you have a callback & a start/end date. You should really only use one of them.
