### ISSUE TITLE
Stick Thread in "All Threads"

### ISSUE THREAD

**Issue by mailpass** [Audentio/xf2addon-issues#2051]
Add-on Name: [TH] Topics

Add-on Version: 1.0.2 Patch Level 1

XenForo Version: 2.1.5a

Operating System (and Version): Windows 10

Browser Name (and Version): Chrome 78.0.3904.108

Summary of issue: Can you make the "pin" function the one at the top of the "All Threads" list

Detailed steps to reproduce the issue:

Upload any screenshots related to the issue below
![image](https://user-images.githubusercontent.com/47533231/70060668-aa7c6b80-15eb-11ea-9295-53f5d533bd36.png)

**Comment by LukasWieditz** [comment]
That's not something we have planned to add, and would bear some nasty consequences for lots of forums with per-node sticky threads

**Comment by mailpass** [comment]
Can I somehow make a sticked theme myself? Maybe you could give some kind of code for less or for a template? In this plugin of yours or in the plugin [TH] Filters

**Comment by LukasWieditz** [comment]
That's nothing that can be achieved with a template modification alone. Sticky threads need to be fetched separately in the controller.
