### ISSUE TITLE
FILTERS Mobile styling 

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#2056]
Mobile view needs a bit of work particularly with long forum names. At the very least some spacing would help. 

![Screenshot_20191205-155343_Chrome](https://user-images.githubusercontent.com/5346876/70273313-d0367b80-1777-11ea-8cd1-4c2be8b1d020.jpg)

**Comment by LukasWieditz** [comment]
This seems to be unique to your style. The spacing is fine in both, the default style and our UI.X base styles.
