### ISSUE TITLE
Image Optimizer - New Covers errors

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#2060]
Upgraded to 1.1.2 latest at time of writing. May or may not be related but I've seen a few of the below show up in the server error log.

XF 2.1.5

ErrorException: Fatal Error: Declaration of ThemeHouse\Covers\ImageOptimizerHandler\Cover::hasImage(XF\Mvc\Entity\Entity $content) must be compatible with ThemeHouse\ImageOptimizer\ContentHandler\AbstractHandler::hasImage(?XF\Mvc\Entity\Entity $content = NULL) src/addons/ThemeHouse/Covers/ImageOptimizerHandler/Cover.php:9
Generated by: EJChevy Jan 3, 2020 at 9:41 AM
Stack trace
#0 [internal function]: XF::handleFatalError()
#1 {main}
Request state
array(4) {
  ["url"] => string(26) "/covers/thread/33726/image"
  ["referrer"] => string(79) "https://mysite.com/threads/new-corvette-monthly-programs.33726/"
  ["_GET"] => array(1) {
    ["/covers/thread/33726/image"] => string(0) ""
  }
  ["_POST"] => array(6) {
    ["cover_image_type"] => string(6) "custom"
    ["cover_image_url"] => string(743) "https://lh3.googleusercontent.com/vvKRJA_xykhQk4UcPThN9znDLAbue1UTy7IUfHvDECuxIU1gSb0wqOl-pP7HoHO-FGtZihUodHvVhnGzQ91B7jL20URJ5vjeWOvbqmtD3a8NcKl4Z1zEoDqU3SSiSMi_4FC5hD7gTs1g-raBvi_yXpnSPEJsRxy6gR4SMbxRZ94AZcPUsS2tqtAJiBL5d3-WTQEyBy2mCb7CpBEklWjXVkyyZ8_V13bH-kZQpdtKEyLSCnWF4Kn141v03HzGtMmjQk9nYM0KmPXruj-Tz6l6QpDwEWMhM7OW6H7hHfk55eZfyXLXBhfAajyL2xXSfniTibtyPWcbemCxhQAnkX_dp4dbUgikzXZCmuctRY309OAkmxoNnpSD-AVNToIZAR2C4Vs-K16pt5gcwCK1BvXuw96T_z1CndDDExhJQtL2e1OS8RJmgZYLIszA6NIH4mAbnIqdAtB-GYZ_KOtTnyuYZJ98f1YHb04CUUJXTDjJxw5A8W3LXMgEldrTYO-aTSj0JjgWuNn2IWp0UIL7cQu4tTbyXAsvEcJSCWaVBG37Cn1n1k_-A1CRa3jXV3wi6j27Z8295sX_1cyxOd8eFYyRhqFUI8q3VwsaoFAD1TbW_rayfE72zVSgyUJHfxJSuVePZn9xZaCFdV0mgdCJ4ZM33z1rhz61P-Pg2E9F8DfTBPRG06bW1tZUntM=w1259-h944-no"
    ["_xfToken"] => string(8) "********"
    ["_xfRequestUri"] => string(45) "/threads/new-corvette-monthly-programs.33726/"
    ["_xfWithData"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}

**Comment by LukasWieditz** [comment]
Not sure what happened there, but the function signature as per latest release (August 8th 2019) is correct:
```
public function hasImage(Entity $content = null)
```
