### ISSUE TITLE
Q&A - Template mod doesn't add back string

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#2063]
In the Q&A addon, the following template modification should add back the content

key: thqaforums_thread_view_structuredData

Currently Replace shows:
<xf:macro template="thqaforums_thread_view_macros" name="structured_data" arg-thread="{$thread}" arg-posts="{$posts}" />

Replace SHOULD be:
$0
<xf:macro template="thqaforums_thread_view_macros" name="structured_data" arg-thread="{$thread}" arg-posts="{$posts}" />

**Comment by LukasWieditz** [comment]
Not sure what happened there, but the latest released version (from 4 months ago) does include that:

```
<modification type="public" template="thread_view" modification_key="thqaforums_thread_view_structuredData" description="Add structured data to thread." execution_order="10" enabled="1" action="str_replace">
    <find><![CDATA[<!--[XF:content_top]-->]]></find>
    <replace><![CDATA[$0

<xf:macro template="thqaforums_thread_view_macros" name="structured_data" arg-thread="{$thread}" arg-posts="{$posts}" />]]></replace>
  </modification>
```
