### ISSUE TITLE
Q&A Forums - Unanswered Question links goes to What's New

### ISSUE THREAD

**Issue by GH-Rake** [Audentio/xf2addon-issues#2064]
Add-on Name: Q&A Forums

Add-on Version: 1.1.4 Patch Level 2

XenForo Version: v2.1.6 Patch 1

Operating System (and Version):
Mine: Win 10 1903
Server: CentOS 7 CentMinMod NGINX

Browser Name (and Version):
Brave, Firefox & Chrome tested

Summary of issue:
"Unanswered Questions" link in Statistics widget displays "what's new" post list instead of a list of unanswered questions

Detailed steps to reproduce the issue:

Go here:
![image](https://user-images.githubusercontent.com/15186628/71929025-b74e2b00-3166-11ea-9c8b-ce7b740691ec.png)

Click on Unanswered Questions.

You can try it on my site if you want too see it https://guidedhacking.com/

**Comment by LukasWieditz** [comment]
That is as designed. It leads to the new posts section with the "Show only: unanswered" filter activated, but your installation seems to have removed filters from that particular section, so it can't be applied - or is potentially just not visible in the UI.

**Comment by GH-Rake** [comment]
Another user is reporting the same issue and Jake B told us to open an issue here: https://xenforo.com/community/threads/th-question-and-answer-forums-paid.135615/post-1395442

Here is a list of others forums I could find which have the same problem:
https://www.gscalecentral.net/forums/
https://www.reef2reef.com/forums/
https://canadiancorvetteforums.com/forums/
https://www.gscalecentral.net/

**Comment by GH-Rake** [comment]
I think you need to re-read this issue, read this https://xenforo.com/community/threads/th-question-and-answer-forums-paid.135615/post-1397269 and re-open this issue.

If you're saying this is a configuration issue with our servers then I think it should be investigated.

If you're saying this is intended behavior but your users are expecting a different behavior then the developer and user expectations are not aligned but they should be.

**Comment by GH-Rake** [comment]
The request for this link is:
/whats-new/posts/?unansweredquestions=1

it should be:
/whats-new/posts/?thqa_answer_status=unanswered

modification key: thqaforums_widget_forum_statistics
