### ISSUE TITLE
[TH] Filters 1.0.2 - Cant remove filters once set as default

### ISSUE THREAD

**Issue by arm5ky** [Audentio/xf2addon-issues#2065]
Add-on Name:
[TH] Filters 1.0.2
Add-on Version:
1.0.2
XenForo Version:
v2.1.5

Summary of issue:
Saving default filters on all-threads. Selecting 7 days, can't seem to remove the filter, or change the default back to from 7 days to Any
Detailed steps to reproduce the issue:
Used demo on themehouse site. Set any flter and save as default. Try to reset default to not set and filters are kept.

Upload any screenshots related to the issue below

**Comment by ichpen** [comment]
I can verify that this happens when removing the last filter. Removing multiple filters works until the last one. It's very critical.

**Comment by ichpen** [comment]
Here's a video of the issue, note I'm hitting refresh at the beginning and end.

https://drive.google.com/file/d/1FLPAlLulPDsfFdVaOVXNthndOM5oLAsj/view?usp=sharing
