### ISSUE TITLE
Filters 1.0.3 Issues

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#2071]
Sorry combining 3 issues into one.

@LukasWieditz  and @daltonp 

Firstly this critical issue is not resolved #2065 

Secondly, you missed adding a None (or blank) option in filter prefixes in ACP in case you don't want to show ANY prefix filters.

Thirdly, I cannot UNSELECT and save using the FILTER MENU after selecting a filter using aforementioned filter menu. It's simply ignored. I can unselect it using the filter bar only. See video explainer:

https://drive.google.com/open?id=1RBZ1-tbT_aNYTZ23SPvQi4zFGE8bA_n8

**Comment by LukasWieditz** [comment]
Don't combine issues. Also if the issue is still open, that means it hasn't been resolved, that's very correct.
