### ISSUE TITLE
[Covers] Delete thread covers permission isn't functioning properly

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2076]
Add-on Name: Covers

Add-on Version: 1.0.4 Patch Level 2 

XenForo Version: 2.1.7

Operating System (and Version): Windows 10 64-bit

Browser Name (and Version): Version 79.0.3945.130 (Official Build) (64-bit)

Summary of issue: Usergroups who have the Delete thread covers permission set to allow in the usergroups section they still aren't able to delete thread covers. Even when the option Allow content owners to create/edit covers is checked off or not.

Able to replicate this behavior on my demo and on a customer's board.

Steps to replicate this issue:

- Allow users to delete thread covers
- Allow content owners to create/edit covers
- Disallow content owners to create/edit covers

**Comment by LukasWieditz** [comment]
@daltonp The delete thread cover permission depends on the edit thread permission, so if users aren't able to edit their threads, they won't be able to delete their thread covers.
