### ISSUE TITLE
[Attachments Plus] Offer functionality to Insert Recent Uploads

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2082]
It has been suggested by [ProCom](https://xenforo.com/community/threads/th-attachments-plus-paid.170121/post-1400538) on xenforo.com:

> Someone else asked / requested that previous images uploaded could be displayed with a way / option to load those images into another post. Is this implemented / can it?
> 
> Ideally, it would be GREAT to have something like this where clicking "Insert Recent Uploads" would bring up the 10 most recently uploaded files to choose from.
![1580461905354](https://user-images.githubusercontent.com/32306910/73955222-9e9d7600-48c8-11ea-86ed-78411de2e386.png)

**Comment by LukasWieditz** [comment]
That's not something we have planned to add at the moment.
