### ISSUE TITLE
[XPRess] XPress Plugin causing WP-CLI to croak

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#2084]
With XPress addon installed in a WP subdirectory I'm getting the below every time I attempt to run any wp-cli command such as 'wp plugin status'. Removing the addon fixes the issue.

Tried with multiple branches of PHP 7.2, 7.3 and 7.4.

Warning: file_exists(): Unable to find the wrapper "phar" - did you forget to enable it when you configured PHP? in /root/.wp-cli/packages/vendor/composer/ClassLoader.php on line 394
An unexpected error occurred. Please try again later.

**Comment by LukasWieditz** [comment]
Phar is required for the composer autoloader. There's a handful of WordPress plugins, most mentionworthy Divi, that disable it for reasons unknown to us. Any plugin that unregisters the phar wrapper will break XPress.

**Comment by teamracing** [comment]
Please explain why removing express fixes this issue whereas keeping it on breaks wp cli? No other plugins have been changed.

**Comment by ichpen** [comment]
Sorry was responding from my other account. I'm all for blaming the other guy but I don't use Divi nor have I added new plugins in the mean time to my repertoire (mostly upgrades). 

Your plugin directly causes wp cli to croak. Disabling your plugin fixes this issue. So who do I blame and who fixes this? I have a few CLI jobs that don't run because of this.
@LukasWieditz
