### ISSUE TITLE
[Reactions Plus] Popup does not close

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2086]
Popup does not closed automatically after given Reactions. We need use X close button after Reactions use.

![ScreenShot00025](https://user-images.githubusercontent.com/6899856/75373014-c0878880-58c9-11ea-9086-cfadfcf9a50e.png)

**Comment by LukasWieditz** [comment]
I find myself unable to reproduce this actually. The reaction picker is closing fine after selecting a reaction. Is there any error logged in your browser console after you selected one?

https://gfycat.com/UnfoldedSpitefulKestrel

**Comment by Nirjonadda** [comment]
@LukasWieditz This popup does not close when you are directly hit the like button without using popup menu.

See here: https://gfycat.com/agonizingcorruptbufeo
