### ISSUE TITLE
[Attachments Plus] "Oops! We ran into some problems" shows on the image view page

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2088]
Add-on Name: [TH] Attachments Plus

Add-on Version: 1.0.1 Patch Level 2 

XenForo Version: 2.1.7

Operating System (and Version): Windows 10 64-bit

Browser Name (and Version): Version 80.0.3987.122 (Official Build) (64-bit)

Summary of issue: Not able to view other users' images. When clicking the post and I am able to view them but when directly clicking the user's images I ain't able to and am sent to a page with the following message: "Oops! We ran into some problems."

Detailed steps to reproduce the issue: Navigate to a user's profile, click the "Images" tab, then click on the image and not the "View Post" link. You'll then be sent to an "Oops! We ran into some problems." page.

**Comment by LukasWieditz** [comment]
I'm not able to reproduce it. We'll need more input on what the error message is that gets logged when this happens.

**Comment by LukasWieditz** [comment]
@daltonp Can you try and follow up with the client?

**Comment by daltonp** [comment]
@LukasWieditz Will attempt to
