### ISSUE TITLE
[Donate] - Instant update promoted users

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2089]
Please can you add support Instant update promoted users after completed donate? Xenforo not updated Instantly,  promoted when they first log in or after they've been active for up to an hour. Promotions don't apply to users who have not logged in recently.

**Comment by LukasWieditz** [comment]
We don't have any plans to add that. There are add-ons out there I believe that trigger user promotions on profile update. Depending on how they are implemented, they may be able to trigger when the donation fields are updated.
