### ISSUE TITLE
[Covers] - Visitor menu not working

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2090]
Visitor menu Covers not working after updated to Xenforo 2.1.8

![ScreenShot00098](https://user-images.githubusercontent.com/6899856/77081797-780c4800-69fb-11ea-9ecf-d85c84c69e38.png)

**Comment by Nirjonadda** [comment]
This is Conflict with [Referral Contests](https://xenforo.com/community/resources/referral-contests-2-by-siropu.6220/) add-on.

**Comment by Nirjonadda** [comment]
Please can you give compatible update?

See here: https://drive.google.com/file/d/1rgJgo2Q5pUpJhENt4xq4z4Q4W6KA_w0m/view?usp=sharing

**Comment by Nirjonadda** [comment]
This issue still not Fixed with Xenforo PL2 Update. So do you have any solution for this issue?

**Comment by LukasWieditz** [comment]
Can you provide us with the template modification that the Referral Contests add-on is applying?

**Comment by Nirjonadda** [comment]
Look disabled Referral Contests TM but still UI.X Pro showing Invalid regular expression. You are looking for Template contents, Find or Replace code?

![ScreenShot00170](https://user-images.githubusercontent.com/6899856/77745493-a9989b00-701b-11ea-8dd5-33cab6f75db8.png)

**Comment by Nirjonadda** [comment]
@LukasWieditz This issue also happened with Conflict with multiple add-ons. UI.X Pro showing Invalid regular expression forum Editor & BB Code Manager and other also not applied with User Essentials add-on. If you want check in this issue in our demo site then please let me know.

![ScreenShot00171](https://user-images.githubusercontent.com/6899856/77748375-8d4b2d00-7020-11ea-9353-e8ef6a11f664.png)

**Comment by LukasWieditz** [comment]
You're running XenForo 2.1.8 PL 2?

**Comment by Nirjonadda** [comment]
> 
> 
> You're running XenForo 2.1.8 PL 2?


Yes, Do want check in this issue in our demo site then please let me know.

**Comment by Nirjonadda** [comment]
How many add-on Conflict with account_visitor_menu TS ?

1: Referral Contests add-on
2: Editor & BB Code Manager add-on
3: User Essentials add-on
4: Ads Manager add-on

**Comment by LukasWieditz** [comment]
It doesn't strike me as something that would be that large scale. The template modification is fairly straightforward, and realistically it should never give you an invalid regex exception. Can you try to install the add-ons on a different - preferably clean - installation to check if it happens there as well?

**Comment by Nirjonadda** [comment]
Yes we have made a test site for this site But issue still same after installed above 4 addon.

1: Editor & BB Code Manager add-on are not applying for UI.X Pro style and show Invalid regular expression

2: Invalid regular expression from other 3 add-on.

**Comment by Nirjonadda** [comment]
See only enabled 4 add-on.

![ScreenShot00174](https://user-images.githubusercontent.com/6899856/77772808-fe063f80-7048-11ea-97ef-7bbaeb33e21c.png)

**Comment by Nirjonadda** [comment]
@LukasWieditz I think Conflict with multiple add-ons.

See demo here: https://drive.google.com/file/d/1tn4quyWYGI7CJqM1RhjFSHkMARQjUDJo/view?usp=sharing

**Comment by Nirjonadda** [comment]
@LukasWieditz One update from other add-on Developer.

> All template modifications are applied except for those where the templates no longer exists.
> 
> However there was a conflict, when the referral add-on Account visitor menu (TM key siropu_referral_contests_account_visitor_menu_link) was turned on, the TH Covers template mod failed. Although the referral TM is a simple replacement expression the amount of code injected interfered with TH Covers (their regular expression fails). So I changed the execution order of the referral add-on TM for the second Account visitor menu mod to 20, and all seems to be fine now.

**Comment by Nirjonadda** [comment]
@LukasWieditz I have found this issue, Template modification Invalid regular expression issue with UI.X Pro from `account_visitor_menu` (Adds the profile cover to the user's visitor menu). I have set a lower execution order to 5 from 10 and all are worked. So please can you make the changes in the next update? Then this change not remained back to default with addon upgrade or Xenforo upgrade?

![ScreenShot00183](https://user-images.githubusercontent.com/6899856/78124496-0c20db00-7410-11ea-83b6-9a44c8921ce8.png)

**Comment by LukasWieditz** [comment]
Implemented that change for the next update.
