### ISSUE TITLE
[Q&A Forums] InvalidArgumentException Error

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2091]
Issue reported by one of our customers on Intercom

Add-on Name: [TH] Question & Answer Forums

Add-on Version: 1.1.4 Patch Level 2 

XenForo Version: 2.1.8 Patch 1

> InvalidArgumentException: Accessed unknown getter 'th_is_qa_qaforum' on XF:Thread[71]
> src/XF/Mvc/Entity/Entity.php:194
> #0 src/XF/Mvc/Entity/Entity.php(106): XF\Mvc\Entity\Entity->get('th_is_qa_qaforu...')
> #1 internal_data/code_cache/templates/l1/s1/public/thqaforums_post_macros_controls.php(68): XF\Mvc\Entity\Entity->offsetGet('th_is_qa_qaforu...')
> #2 src/XF/Template/Templater.php(701): XF\Template\Templater->{closure}(Object(XF\Template\Templater), Array, Array)
> #3 internal_data/code_cache/templates/l1/s1/public/post_macros.php(270): XF\Template\Templater->callMacro('thqaforums_post...', 'external_contro...', Array, Array)
> #4 src/XF/Template/Templater.php(701): XF\Template\Templater->{closure}(Object(XF\Template\Templater), Array, Array)
> #5 internal_data/code_cache/templates/l1/s1/public/thread_view.php(576): XF\Template\Templater->callMacro('post_macros', 'post', Array, Array)
> #6 src/XF/Template/Templater.php(1315): XF\Template\Templater->{closure}(Object(XF\Template\Templater), Array)
> #7 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('thread_view', Array)
> #8 src/XF/Mvc/Renderer/Html.php(48): XF\Template\Template->render()
> #9 src/XF/Mvc/Dispatcher.php(458): XF\Mvc\Renderer\Html->renderView('XF:Thread\\View', 'public:thread_v...', Array)
> #10 src/XF/Mvc/Dispatcher.php(440): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
> #11 src/XF/Mvc/Dispatcher.php(400): XF\Mvc\Dispatcher->renderReply(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
> #12 src/XF/Mvc/Dispatcher.php(58): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
> #13 src/XF/App.php(2184): XF\Mvc\Dispatcher->run()
> #14 src/XF.php(391): XF\App->run()
> #15 index.php(20): XF::runApp('XF\\Pub\\App')
> #16 {main}

The customer also mentioned that one of the problems was [TH] Post Comments 1.0.2 Patch Level 2.

**Comment by LukasWieditz** [comment]
This should be resolved with XenForo 2.1.8 Patch 2.
