### ISSUE TITLE
Nodes dont working after upgrade

### ISSUE THREAD

**Issue by KickOut-de** [Audentio/xf2addon-issues#2093]
Add-on Name:Node

Add-on Version:1.0.7

XenForo Version:2.1.8

Operating System (and Version):

Browser Name (and Version):

Summary of issue: After upgrade xenforo to 2.1.8 thsis is the given error :
`#0 src/addons/ThemeHouse/Nodes/Listener/TemplaterSetup.php(45): ThemeHouse\Nodes\Repository\NodeStyling->getClassesForNode(Object(XenMake\StyleProperty\XF\Entity\Node), Array)
#1 [internal function]: ThemeHouse\Nodes\Listener\TemplaterSetup::fnNodeClasses(Object(xenMade\SEo\XF\Template\Templater), true, Object(XenMake\StyleProperty\XF\Entity\Node), Array)
#2 src/XF/Template/Templater.php(936): call_user_func_array(Array, Array)
#3 internal_data/code_cache/templates/l3/s11/public/node_list_category.php(17): XF\Template\Templater->func('th_nodeclasses_...', Array, true)
#4 src/XF/Template/Templater.php(701): XF\Template\Templater->{closure}(Object(xenMade\SEo\XF\Template\Templater), Array, Array)
#5 internal_data/code_cache/templates/l3/s11/public/forum_list.php(30): XF\Template\Templater->callMacro('node_list_categ...', 'depth1', Array, Array)
#6 src/XF/Template/Templater.php(701): XF\Template\Templater->{closure}(Object(xenMade\SEo\XF\Template\Templater), Array, Array)
#7 internal_data/code_cache/templates/l3/s11/public/forum_list.php(64): XF\Template\Templater->callMacro('forum_list', 'node_list_entry', Array, Array)
#8 src/XF/Template/Templater.php(701): XF\Template\Templater->{closure}(Object(xenMade\SEo\XF\Template\Templater), Array, Array)
#9 internal_data/code_cache/templates/l3/s11/public/forum_list.php(244): XF\Template\Templater->callMacro('forum_list', 'node_list', Array, Array)
#10 src/XF/Template/Templater.php(1315): XF\Template\Templater->{closure}(Object(xenMade\SEo\XF\Template\Templater), Array)
#11 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('forum_list', Array)
#12 src/XF/Mvc/Renderer/Html.php(48): XF\Template\Template->render()
#13 src/XF/Mvc/Dispatcher.php(458): XF\Mvc\Renderer\Html->renderView('XF:Forum\\Listin...', 'public:forum_li...', Array)
#14 src/XF/Mvc/Dispatcher.php(440): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#15 src/XF/Mvc/Dispatcher.php(400): XF\Mvc\Dispatcher->renderReply(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#16 src/XF/Mvc/Dispatcher.php(58): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#17 src/XF/App.php(2184): XF\Mvc\Dispatcher->run()
#18 src/XF.php(391): XF\App->run()
#19 index.php(20): XF::runApp('XF\\Pub\\App')
#20 {main}`

Detailed steps to reproduce the issue:

Upload any screenshots related to the issue below

**Comment by daltonp** [comment]
Does this still happen even after updating to 2.1.8 Patch Level 2 of XenForo? @KickOut-de

**Comment by LukasWieditz** [comment]
This should be resolved with XenForo 2.1.8 Patch 2.
