### ISSUE TITLE
[Covers/Donate] Template Conflicts

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2094]
Reported by [Nirjonadda](https://xenforo.com/community/threads/th-donate-paid.145264/post-1412016) on xenforo.com/community

![image](https://user-images.githubusercontent.com/32306910/77198614-4f488900-6ab5-11ea-8836-7b5f4a974451.png)

> We have issue not working Donate cover. Disabling [TH] Covers add-on wiil be show Donate cover. This is Conflict with [TH] Covers add-on. Please can you give compatible update?

**Comment by Nirjonadda** [comment]
This issue fixed: https://github.com/Audentio/xf2addon-issues/issues/2092

**Comment by LukasWieditz** [comment]
This should be resolved with XenForo 2.1.8 Patch 2.
