### ISSUE TITLE
[Filter] and [Trending] Allows compatibility with other add-ons

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2097]
In the Both add-on the first thing do is use the get parent. This allows compatibility with other add-ons.  

The code doesn't appear to get the parent action. There's code in there to return the parent, but not get the parent action.

```
<?php

namespace ThemeHouse\Filters\XF\Pub\Controller;

use XF\Mvc\ParameterBag;

/**
* Class Forum
* @package ThemeHouse\Filters\XF\Pub\Controller
*/
class Forum extends XFCP_Forum
{
    /**
     * @param ParameterBag $params
     * @return \XF\Mvc\Reply\Reroute|View
     */
    public function actionIndex(ParameterBag $params)
    {
        if ($params['node_id'] || $params['node_name']) {
            return $this->rerouteController('XF:Forum', 'Forum', $params);
        }

        if ($this->responseType == 'rss') {
            return $this->getForumRss();
        }

        switch ($this->options()->forumsDefaultPage) {
            case 'thfilters_trending_threads':
                return $this->rerouteController('ThemeHouse\Filters:AllThreads', 'trending');
                break;

            case 'thfilters_latest_threads':
                return $this->rerouteController('ThemeHouse\Filters:AllThreads', 'latest');
                break;

            case 'thfilters_newest_threads':
                return $this->rerouteController('ThemeHouse\Filters:AllThreads', 'newest');
                break;


            default:
                return parent::actionIndex($params);
        }
    }
}
```

**Comment by LukasWieditz** [comment]
The code is fully compatible with any add-ons to my awareness. I'm not sure what you're suggesting should be changed here, but there's no need to get the parent methods output at the beginning of the method to ensure compatibility.

**Comment by Nirjonadda** [comment]
@LukasWieditz Please follow this link which explains how to properly extend classes.

https://xenforo.com/xf2-docs/dev/controller-basics/#modifying-a-controller-action-reply-properly

**Comment by Nirjonadda** [comment]
@LukasWieditz Please can you re-open this issue? My one [Forum password](https://xenforo.com/community/resources/forum-password.5681/) add-on not compatible with both add-on enabling. Not asking for password when enter the node but thread view ask for password. Please any compatible update?

**Comment by LukasWieditz** [comment]
The add-ons are fully compliant with the controller extension basics. Due to the nature of the redirects at the beginning of the extended method, the taken approach is necessary. The actual functionality of the default method is not touched in any way, it is merely extending the forums default page switch.

**Comment by LukasWieditz** [comment]
The `actionForum` method of the Forum controller, where the password protection would ideally go, is not touched. If it is necessary to run the password protection at the beginning of the `actionIndex` method, Andy will have to choose a higher execution order for his class extension so his code wraps ours.

**Comment by LukasWieditz** [comment]
You can try to replace the functions content with the following code, but it'll likely not have any effect on the functionality, as the routes live in a different controller. At maximum, your redirect there will become password protected, but that doesn't stop users from directly accessing the routes.

```
$response = parent::actionIndex($params);
        
        if($response instanceof Reroute) {
            switch ($this->options()->forumsDefaultPage) {
                case 'thfilters_trending_threads':
                    $response = $this->rerouteController('ThemeHouse\Filters:AllThreads', 'trending');
                    break;

                case 'thfilters_latest_threads':
                    $response = $this->rerouteController('ThemeHouse\Filters:AllThreads', 'latest');
                    break;

                case 'thfilters_newest_threads':
                    $response = $this->rerouteController('ThemeHouse\Filters:AllThreads', 'newest');
                    break;

                default:
                    break;
            }
        }

        return $response;
```

**Comment by Nirjonadda** [comment]
Yes fixed with this update: https://xenforo.com/community/resources/forum-password.5681/updates#resource-update-34388
