### ISSUE TITLE
Reactions: Option to set heart button as a reaction

### ISSUE THREAD

**Issue by Matthew2D** [Audentio/xf2addon-issues#21]
Similar to IPS, I think it would be a good idea to be able to set the heart button as a reaction and remove that reaction from the normal list. 

Functionality:
1st click: opens the reaction list
2nd click: applies the reaction that the heart button is set to.

**Comment by kylerc** [comment]
@JakeBooher Curious what would be required for your side to support this.  Basically would either want a list of the reactions as a SP to set a default or the option to set a single reaction as the default in the options that create and modify the reactions themselves.  I think the rest could be handled by me.

**Comment by mikecreuzer** [comment]
Ah I think this is done, so will close. We have the default option now.
