### ISSUE TITLE
[Nodes] - Add SP for forum and thread view

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2107]
Please can you add SP option for forum and thread view? So you can use Default cover for Thread view.

1. Banner image use for thread view or only for forum view?

**Comment by LukasWieditz** [comment]
This already exists. Style Properties > [TH] Nodes: Styling > Enable header styling on <x> view

**Comment by Nirjonadda** [comment]
@LukasWieditz Then you need update the descriptions for better understanding.

> If enabled, node banner image, background image, background & font color will be applied to the titlebar in XXXX.

![ScreenShot00197](https://user-images.githubusercontent.com/6899856/78356825-9dc74e80-75b0-11ea-9553-f18d21f50e53.png)

**Comment by LukasWieditz** [comment]
Will do, thanks
