### ISSUE TITLE
[Nodes] - Banner image also used for Forum list

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2108]
I have found one bug with Banner image. I have set only Banner image for forum view without setup Background image but Banner image also using in forum list.

**Comment by LukasWieditz** [comment]
I'm not able to reproduce that. There's an issue that applies the wrong class to the node list when a banner image is set, but the banner itself isn't applied to the node list item on the forum list.

**Comment by Nirjonadda** [comment]
I think this issue fixed with 1.0.8 Patch Level 1
