### ISSUE TITLE
[Style Switch] - Widgets Color are not change

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2112]
Widgets Color are not change not change without reloading page.

**Comment by LukasWieditz** [comment]
I am unable to reproduce that, everything (including widgets) is switching colors as expected.

**Comment by Nirjonadda** [comment]
My style default setup is from UIX add-on style installation.

![ScreenShot00206](https://user-images.githubusercontent.com/6899856/78369721-f3f2bc80-75c5-11ea-9fb1-2d0a10606ee9.png)

See here: https://gfycat.com/charmingdependablefeline

**Comment by LukasWieditz** [comment]
Can you give us a link to your site?

**Comment by Nirjonadda** [comment]
Yes, You are not reproduce because you are using autodetect style. Please try with UIX Pro light or dark style then try to use Toggle switch button. 

![ScreenShot00208](https://user-images.githubusercontent.com/6899856/78387806-3628f780-75e0-11ea-8e3b-4ed709394abf.png)

**Comment by LukasWieditz** [comment]
I have tried that, it still doesn't happen.

**Comment by Nirjonadda** [comment]
Where we can send sites link?

**Comment by Nirjonadda** [comment]
@LukasWieditz Also issue with Side nav icon are not showing correctly.

See here: https://gfycat.com/serenecloudylice

**Comment by LukasWieditz** [comment]
A ticket through themehouse.

**Comment by Nirjonadda** [comment]
Done!

**Comment by Nirjonadda** [comment]
@LukasWieditz This issue fixed for my site but now happened again with UI.X Pro Version 2.1.9.0.0 update.
