### ISSUE TITLE
[Style Switch] - Toggle switch position

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2113]
Please can be add option Toggle switch position before the toggle page width for UIX style.

![ScreenShot00198](https://user-images.githubusercontent.com/6899856/78365827-f18d6400-75bf-11ea-94d4-5c5c1c95d43c.png)

**Comment by LukasWieditz** [comment]
That's something that can be achieved with the custom switch option, which requires a manual template edit. We don't have planned to provide more positions at the moment.

**Comment by Nirjonadda** [comment]
@LukasWieditz Please can be done with CSS code?

**Comment by LukasWieditz** [comment]
Unlikely.
