### ISSUE TITLE
[StaffTracker] - UI.X Pro Dark no icon

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2115]
UI.X Pro Dark no icon showing in thread list.

UI.X Pro Dark: Not working

![ScreenShot00200](https://user-images.githubusercontent.com/6899856/78367295-1d114e00-75c2-11ea-9c07-120ec49c5713.png)

UI.X Pro Light: Working

![ScreenShot00201](https://user-images.githubusercontent.com/6899856/78367401-4fbb4680-75c2-11ea-8659-63e08c652f0c.png)

**Comment by LukasWieditz** [comment]
I'm unable to reproduce this. The add-on uses the default text highlight color of XenForo, which is untouched in UI.X 2 Dark:
![a0uBwOL](https://user-images.githubusercontent.com/38475165/83863568-c809c980-a723-11ea-97f9-1767465a96cc.png)
