### ISSUE TITLE
[Style Switch] - Template error: Function thstyleswitch_autodetect_enabled is unknown

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2117]
Server error log show when installing.

![ScreenShot00207](https://user-images.githubusercontent.com/6899856/78381539-cc0b5500-75d5-11ea-8a5e-32e793d6a54d.png)

**Comment by LukasWieditz** [comment]
This looks like a temporary issue that happened during installation or update. Unless it's recurring, it's safe to ignore.
