### ISSUE TITLE
[ContentCreationLimits] - Thread limit and Reply limit message

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2119]
Please can you add option Thread limit and Reply limit message?

Example:

![ScreenShot00210](https://user-images.githubusercontent.com/6899856/78398630-b7d65080-75f3-11ea-979f-a7188218735a.png)

![ScreenShot00209](https://user-images.githubusercontent.com/6899856/78398635-bc026e00-75f3-11ea-8433-3b43250e262f.png)

**Comment by LukasWieditz** [comment]
We've reviewed this and decided it's not something we're going to implement due to performance implications on large sites.
