### ISSUE TITLE
[Donate] Out of range exception when entering large decimal values

### ISSUE THREAD

**Issue by setoy** [Audentio/xf2addon-issues#2139]
When entering large values to donate (for example `9999999999999999`), it generates an exception instead of being handled gracefully.

**Comment by LukasWieditz** [comment]
I don't think there's a whole lot that can be done here that wouldn't involve a complex workaround for precision checking. As the column is saved as float value, there is technically no hard limit that can be used to cap off. If this is a recurring problem on your site, I would try to add a maximum value to the HTML input as first step to see if that helps resolve it.
