### ISSUE TITLE
[Covers] Scale/zoom covers

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2addon-issues#214]
Supporting zooming in and out of covers with a high enough resolution to let the user select the area he wants without having to scale the image himself would be a neat functionality. Has been requested for add-ons with similar functionality.

**Comment by kylerc** [comment]
@LukasWieditz I'd guess we'd want to do proper cropping of the image on the backed if we do this to avoid serving huge images to the clients.  Might also want to save different sizes of the images to better handle HiDPI displays?  But that does turn this into a larger feature development wise.  Thoughts?

**Comment by LukasWieditz** [comment]
The saving in different sizes is not so complicated and already handled in the backend. They aren't cropped however, that's right. I'm not really sure how feasible/easy it'll be to do real cropping, and we also lose out on the benefit of having images that do not have the "perfect" aspect ratio: https://gfycat.com/KnobbySharpLeafwing
