### ISSUE TITLE
[Q&A] - Empty forum showing "no threads matching filters" rather than "No threads in forum"

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2141]
Please can you add Enable/disable option for automatic filters?

Xenforo Default:

![ScreenShot00237](https://user-images.githubusercontent.com/6899856/79141581-66c81880-7dba-11ea-8229-2fba898bcf16.png)

With Question & Answer Forums:

![ScreenShot00236](https://user-images.githubusercontent.com/6899856/79141530-4730f000-7dba-11ea-8faf-1664f12f06e8.png)

**Comment by LukasWieditz** [comment]
As we're retiring Q&A forums with 2.2 and this is more of a beauty error, we've decided not to fix this one anymore.
