### ISSUE TITLE
[Q&A] - Enable Question status filter only for Question and Answer forum

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2145]
Please can you add option Enable Question status filter only for Question and Answer forum?

**Comment by LukasWieditz** [comment]
I think this has been requested in the past, but the reason why it isn't possible to implement that hasn't changed. There actually isn't a definition of what is a Question & Answer forum and what is not. The only indicator we have is a "Add question status by default" boolean on the forum object, which doesn't necessarily mean that a forum that doesn't have it enabled doesn't also include questions though.
