### ISSUE TITLE
[hCAPTCHA] - Use invisible hCAPTCHA

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2150]
Please add support option for Use invisible hCAPTCHA.

Example:

![ScreenShot00247](https://user-images.githubusercontent.com/6899856/79382808-653a5400-7f64-11ea-89e8-3bf39a72fdc1.png)

**Comment by LukasWieditz** [comment]
No support, as stated in the thread.

**Comment by Nirjonadda** [comment]
I am found this [one](https://xenforo.com/community/resources/hcaptcha-integration.7696/). So requested for development improvement because like to use TH add-on.
