### ISSUE TITLE
[Q&A] - Set thread status Question

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2154]
Please can you add option Enable Set thread status Question show only for Question and Answer forum?

![ScreenShot00266](https://user-images.githubusercontent.com/6899856/79669834-cd847200-81be-11ea-8b2d-57c765628b02.png)

**Comment by LukasWieditz** [comment]
We've explained this before in #2145 , there is no definition of a Question and Answer forum. The only definition there is on a node level is whether the box is pre-selected or not. Anything else is based on permissions, which also control whether the box shows or not.
