### ISSUE TITLE
[Q&A Forums] Automation that runs regularly to auto-mark Q&A threads that have been answered and have the highest points

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2155]
Requested by one of our customers on Intercom:

> Is there a way to auto mark a Q&A thread as Answered for the one with the highest points? Because currently, many users do not mark someone as best answer, resulting in it piling up.

**Comment by LukasWieditz** [comment]
As Q&A forums will be retired with XenForo 2.2, we've decided to not add any more features anymore.
