### ISSUE TITLE
[Donate] Template error: Template public:th_donate_campaign_new_comment is unknown

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2157]
Reported by [t0fx ](https://xenforo.com/community/threads/th-donate-paid.145264/post-1420713)on XenForo:

> ErrorException: Template error: Template public:th_donate_campaign_new_comment is unknown
> src/XF/Template/Templater.php:618
> #0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Template public...', '/var/www/vhosts...', 618, Array)
> #1 src/XF/Template/Templater.php(618): trigger_error('Template public...', 512)
> #2 src/XF/Template/Templater.php(566): XF\Template\Templater->getTemplateData('public', 'th_donate_campa...')
> #3 src/XF/Template/Templater.php(1314): XF\Template\Templater->getTemplateCode('public', 'th_donate_campa...')
> #4 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('th_donate_campa...', Array)
> #5 src/XF/Mvc/Renderer/Json.php(84): XF\Template\Template->render()
> #6 src/XF/Mvc/Renderer/Json.php(68): XF\Mvc\Renderer\Json->renderHtmlFallback('ThemeHouse\\Dona...', 'public:th_donat...', Array)
> #7 src/XF/Mvc/Dispatcher.php(418): XF\Mvc\Renderer\Json->renderView('ThemeHouse\\Dona...', 'public:th_donat...', Array)
> #8 src/XF/Mvc/Dispatcher.php(400): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Json), Object(XF\Mvc\Reply\View))
> #9 src/XF/Mvc/Dispatcher.php(360): XF\Mvc\Dispatcher->renderReply(Object(XF\Mvc\Renderer\Json), Object(XF\Mvc\Reply\View))
> #10 src/XF/Mvc/Dispatcher.php(53): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'json')
> #11 src/XF/App.php(2178): XF\Mvc\Dispatcher->run()
> #12 src/XF.php(390): XF\App->run()
> #13 index.php(20): XF::runApp('XF\\Pub\\App')
> #14 {main}

**Comment by LukasWieditz** [comment]
This seems to be an outdated version, or the template was accidentally deleted in debug mode. The template in question has been added in version 1.0.2 Patch Level 2.
