### ISSUE TITLE
[User Profile Notes] MySQL query error - Column 'last_edit_date'

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2158]
Reported by a customer within a support ticket:
<img width="814" alt="Screen_Shot_2020-04-29_at_1 36 59_PM" src="https://user-images.githubusercontent.com/32306910/80723420-3b397380-8ac6-11ea-9af3-e9542cb5f781.png">

**Comment by LukasWieditz** [comment]
Not sure how this would happen. The database column in question is defined as nullable and according to the git history always has been.
