### ISSUE TITLE
[TH] XPress Forum User Bridge - Not working 

### ISSUE THREAD

**Issue by FendyProject** [Audentio/xf2addon-issues#2160]
**Add-on Name**: [TH] XPress Forum User Bridge 

**Add-on Version**: 1.0.0

**XenForo Version**: v2.1.6 Patch 1

**Summary of issue**: After i sync my wordpress and XenForo my admin in wordpress suddenly get access denied when accessing dashboard .. after that i tried to clear cache in my broswer and login again using my admin account .. but i got redirected to profile area for new user when first registered ... 
is it possible when sync wordpress and xenforo .. all my wordpress account role changed to xenforo role (Both my wordpress and XenForo have different role name.. ex : Wordpress (Administrator) , Xenforo (Admin) ) 
Oh and one more .. when XenForo user tried to login to my wordpress website.. it's working, but when my wordpress user tried to login to my XenForo website .. it's always said ("User not found") 

**Detailed steps to reproduce the issue**: i just follow the instruction from this page https://help.themehouse.com/en/collections/2008276-xpress-forum-user-bridge

**Upload any screenshots related to the issue below**
Is this supposed to be empty? or it should show wordpress role?
![image](https://user-images.githubusercontent.com/63228471/80962145-abcdf080-8e36-11ea-9e09-873316b044de.png)

**Comment by LukasWieditz** [comment]
Your "Authenticate with WordPress" is disabled, so they won't be able to log into XF with their WP credentials.

The bridge changing your user roles suggests a wrong setup with a rule that takes priority and demoting everyone.

**Comment by FendyProject** [comment]
![image](https://user-images.githubusercontent.com/63228471/81131478-7bd93700-8f75-11ea-8263-bfd5a73f4a41.png)
Hello i also tried to do that but WP user still can't login to XF 

> The bridge changing your user roles suggests a wrong setup with a rule that takes priority and demoting everyone.

 I also tried to only check "Authenticate with WordPress" without checking the import role .. and the result is same .. my WP admin is get demoted

And after that i also tried to only put the API and URL on both WP and XF side without checking anything ("Authenticate with WordPress" and "Import Role") ... and the result is also same .. the WP admin get demoted
