### ISSUE TITLE
Skip ico files

### ISSUE THREAD

**Issue by briansol** [Audentio/xf2addon-issues#2161]
Add-on Name: 
[TH] Image Optimizer [Paid] 1.1.2

Add-on Version:
1.1.2

XenForo Version:
2.1.9

Operating System (and Version):
n/a

Browser Name (and Version):
n/a

Summary of issue:
ico files are being attempted.  They should be skipped.

```Server error log
ErrorException: Unable to find a suitable image optimizer provider for status ID 35992. Note: This is most likely not a bug and this message is only generated to notify you of the issue. Details: File size: 5222, Mime type: image/vnd.microsoft.icon src/XF/Error.php:75
```

Detailed steps to reproduce the issue:
paste a link to webpagetest.org in the forum, it attempts to load the ico file as part of the xf enhanced link object

**Comment by LukasWieditz** [comment]
We don't have any plan to make changes here. These issues are only being logged when verbose logging is enabled, and there's the theoretical possibility of a 3rd party integration providing a suitable provider to optimize ico files.
