### ISSUE TITLE
[Featured Threads and Content] Automatic feature criteria: Allow administrators to choose where they are displayed

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2167]
Currently, administrators aren't able to choose where automatically featured threads are displayed when setting them up within the Automatic feature criteria section. Allow administrators to choose if automatically featured threads are either displayed on the slideshow, grid, or just the featured page? Or maybe both?

**Comment by LukasWieditz** [comment]
Duplicate of #1991
