### ISSUE TITLE
On iOS 13.4 reaction tap always opens a menu

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2173]
Add-on Name: [TH] Reactions Plus

Add-on Version: 1.0.3 Patch Level 4 

XenForo Version: 2.1.10 PL2

This was reported by one of our customers through a ticket:

> Hi there, I just upgraded to the newest Xenforo version (v2.1.10 Patch 2) in attempt to fix the iOS 13.4 issue that has been plaguing my forum, where if you react to something on mobile, the entire reaction menu comes up instead of just liking the post. The Xenforo admins said they just fixed this issue with the new upgrade, but it was still reoccurring for me and I suspected it was because of this plug-in, so I disabled it and the reactions were working perfectly fine. I'm not sure if the plug-in is working as designed, but would it possible revert back to this behavior? Here is the thread about the iOS 13.4 bug: https://xenforo.com/community/threads/ios-13-4-reaction-tap-always-opens-menu.178282/ Thank you!

**Comment by addonflare** [comment]
Unable to replicate on ios 14: https://streamable.com/dsnu8g
