### ISSUE TITLE
[Donate] No template included for th_donate_campaign_new_comment

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2175]
This was reported by [Robert9](https://xenforo.com/community/threads/th-donate-paid.145264/post-1431638) on xenforo.com:

_In donate.php you have_

```
            $view = $this->view('ThemeHouse\Donate:Donation\NewComments', 'th_donate_campaign_new_comment',
                $viewParams);
```
but there is no template with this name: th_donate_campaign_new_comment

**Comment by LukasWieditz** [comment]
Duplicate of #2157
