### ISSUE TITLE
[Filters] - All filtering show page not found

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2189]
All filtering show page not found with v1.0.5

![ScreenShot00059](https://user-images.githubusercontent.com/6899856/86281410-c4137f00-bbdd-11ea-8d1e-010eae00cdb1.png)

**Comment by LukasWieditz** [comment]
Is this working in default style?

**Comment by Nirjonadda** [comment]
No, Same issue with default style.

**Comment by LukasWieditz** [comment]
Which action specifically triggers this?

**Comment by Nirjonadda** [comment]
Any one All filtering: https://gfycat.com/completeequalcirriped

**Comment by LukasWieditz** [comment]
Did you set up a route filter or delete/disable the default route filters?

**Comment by Nirjonadda** [comment]
No, I am not made any change. All are default. So route filter are automatically added from installation? 

![ScreenShot00060](https://user-images.githubusercontent.com/6899856/86377927-486f0c00-bc89-11ea-86a6-5aba50291640.png)

![ScreenShot00061](https://user-images.githubusercontent.com/6899856/86377929-4907a280-bc89-11ea-8ada-9f648659f289.png)

**Comment by LukasWieditz** [comment]
Hm yeah, they look fine.

**Comment by Nirjonadda** [comment]
@LukasWieditz Does this issue fixed in 1.0.5 Patch Level 1 ?

**Comment by LukasWieditz** [comment]
No, I'm unable to replicate or point at a cause still.
