### ISSUE TITLE
[Filters] Error experienced when updating

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2190]
Reported by [rootksk ](https://xenforo.com/community/threads/th-filter-paid.173168/post-1441181)on xenforo.com

> XF\Db\Exception: MySQL statement prepare error [1054]: Unknown column 'thfilters_default' in 'field list' in src/XF/Db/AbstractStatement.php at line 228

> INSERT INTO
> xf_th_filter_set (user_id, default, title, filter_data)
> SELECT
> user_id AS user_id,
> 1 AS default,
> 'Default' AS title,
> thfilters_default AS filter_data
> FROM
> xf_user
> WHERE
> thfilters_default
> 
> ------------
> 
> #0 src/XF/Db/Mysqli/Statement.php(196): XF\Db\AbstractStatement->getException('MySQL statement...', 1054, '42S22')
> #1 src/XF/Db/Mysqli/Statement.php(39): XF\Db\Mysqli\Statement->getException('MySQL statement...', 1054, '42S22')
> #2 src/XF/Db/Mysqli/Statement.php(54): XF\Db\Mysqli\Statement->prepare()
> #3 src/XF/Db/AbstractAdapter.php(94): XF\Db\Mysqli\Statement->execute()
> #4 src/addons/ThemeHouse/Filters/Setup.php(129): XF\Db\AbstractAdapter->query('
> IN...')
> #5 src/XF/AddOn/StepRunnerUpgradeTrait.php(122): ThemeHouse\Filters\Setup->upgrade1000531Step2(Array)
> #6 src/XF/AddOn/StepRunnerUpgradeTrait.php(71): ThemeHouse\Filters\Setup->upgradeStepRunner(1000531, 2, Array, NULL)
> #7 src/XF/Admin/Controller/AddOn.php(576): ThemeHouse\Filters\Setup->upgrade(Array)
> #8 src/XF/Mvc/Dispatcher.php(350): XF\Admin\Controller\AddOn->actionUpgrade(Object(XF\Mvc\ParameterBag))
> #9 src/XF/Mvc/Dispatcher.php(261): XF\Mvc\Dispatcher->dispatchClass('XF:AddOn', 'Upgrade', Object(XF\Mvc\RouteMatch), Object(XF\Admin\Controller\AddOn), NULL)
> #10 src/XF/Mvc/Dispatcher.php(113): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(XF\Admin\Controller\AddOn), NULL)
> #11 src/XF/Mvc/Dispatcher.php(55): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
> #12 src/XF/App.php(2190): XF\Mvc\Dispatcher->run()
> #13 src/XF.php(391): XF\App->run()
> #14 admin.php(13): XF::runApp('XF\\Admin\\App')
> #15 {main}

**Comment by LukasWieditz** [comment]
Will need a full stack trace before this can be actioned on.

**Comment by daltonp** [comment]
Updated the issue with a full stack trace provided by the reporter of this issue.
