### ISSUE TITLE
[Install & Upgrade] Printable Exception error

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2192]
> XF\PrintableException: Please enter a value for the required field 'latest_version'. src/XF/Mvc/Entity/Entity.php:1165
> Generated by: Unknown account Jul 1, 2020 at 2:00 PM
> Stack trace
> #0 src/XF/Mvc/Entity/Entity.php(1265): XF\Mvc\Entity\Entity->save(true, true)
> #1 src/addons/ThemeHouse/InstallAndUpgrade/InstallAndUpgrade/Traits/StyleHandlerTrait.php(188): XF\Mvc\Entity\Entity->saveIfChanged()
> #2 src/addons/ThemeHouse/InstallAndUpgrade/Job/UpdateCheck.php(100): ThemeHouse\InstallAndUpgrade\InstallAndUpgrade\ThemeHouse->checkStyleProductForUpdates(Object(ThemeHouse\InstallAndUpgrade\Entity\Product))
> #3 src/XF/Job/Manager.php(253): ThemeHouse\InstallAndUpgrade\Job\UpdateCheck->run(G)
> #4 src/XF/Job/Manager.php(195): XF\Job\Manager->runJobInternal(Array, G)
> #5 src/XF/Job/Manager.php(79): XF\Job\Manager->runJobEntry(Array, G)
> #6 job.php(42): XF\Job\Manager->runQueue(false, 8)
> #7 {main}
> Request state
> array(4) {
> ["url"] => string(8) "/job.php"
> ["referrer"] => string(67) "https://test.com/threads/test-test-test.55782/page-9"
> ["_GET"] => array(0) {
> }
> ["_POST"] => array(0) {
> }
> }

**Comment by LukasWieditz** [comment]
https://github.com/Audentio/xf2-installupgrade
