### ISSUE TITLE
Node Grid options missing from forum nodes, only show for category nodes

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#2194]
Node Grid options missing from forum nodes, only show for category nodes

https://app.intercom.com/a/apps/awlgtkwp/inbox/inbox/all/conversations/69958200000111

**Comment by addonflare** [comment]
This seems to be by design: https://xenforo.com/community/attachments/th-node-layout-styling-jpg.183880/
