### ISSUE TITLE
[Giphy] Limited array of GIPHY results on mobile devices

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2196]
Reported by one of our customers in ticket:

> The mobile page drastically limits the array of giphy results returned. On the desktop screen, I can click through dozens and dozens of options. On mobile, there are only twelve. As my users move to mobile devices primarily I am getting complaints about the limited nature of the add-on.

**Comment by LukasWieditz** [comment]
I'm not able to replicate this. As more and more modern mobile devices start to integrate giphy and tenor into their keyboards directly though, and as we're retiring the Giphy integration with XenForo 2.2 as it will be integrated into core, we're probably not going to fix this one anymore.
