### ISSUE TITLE
Class Extension Conflict - Ignore More

### ISSUE THREAD

**Issue by patsfans** [Audentio/xf2addon-issues#2218]
Add-on Name: IgnoreMore

Add-on Version: 2.0.1

XenForo Version: 2.1.10 Patch 2

Operating System (and Version):

Browser Name (and Version):

Summary of issue:
I get this error when trying to install the add on
An exception occurred: [ErrorException] [E_WARNING] Declaration of ThemeHouse\IgnoreMore\XF\Entity\User::getStructure(XF\Mvc\Entity\Structure $structure) should be compatible with MyAddon\User::getStructure($structure) 

Detailed steps to reproduce the issue:

**1) Create a Class Extension:**
Base class name: XF/Entity/User
Extension class name: MyAddOn\User

**2) Create File (User.php) in root src/addons**
```
<?php
namespace MyAddOn;

class XFpref {
	
	public $myheader;

	public function __construct($pfpref) {
	
	$db = \XF::db();
	$u = \XF::visitor();
        $userId = $u->user_id;
	$uidq = $db->fetchRow('SELECT header FROM xf_user_preferences WHERE user_id = ?', array($userId));
	
	// xf_user_preferences is a custom column I've created.

	$this->pfpref = $uidq;
		
	}
	
}

class User extends XFCP_User
{

public function pfHeader(){

	$myheader = new XFpref('header');

	$output = $myheader->pfpref;
	$out = $output['header'];
	
	return($out);
}
	
public static function getStructure($structure)

    {
	   
       $structure = parent::getStructure($structure);
 
	  	$structure->getters['xfHeader'] = ['getter' => 'pfHeader', 'cache' => true];  
	         
        return $structure;
    }
} 
?>
```

**4) Install Add on IgnoreMore**

It will crash the install, forcing you to disable addons and either disable my class extension, or uninstall the addon.

I appreciate any guidance you can provide.

Warm regards,

Ian

Upload any screenshots related to the issue below

**Comment by patsfans** [comment]
Solved.  Changed Class Extension Order to 20 and it took care of it.

**Comment by LukasWieditz** [comment]
You've been using the wrong function signature. `getStructure(XF\Mvc\Entity\Structure $structure)` is the correct one.
