### ISSUE TITLE
UI.X add-on - One-click installation functionality sends me to a "Oops! We ran into some problems." page when attempting to install/upgrade themes

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2244]
Add-on Name: UI.X add-on

Add-on Version: 2.2.0 Alpha 1

XenForo Version: 2.2

Operating System (and Version): Windows 10 64-bit

Browser Name (and Version): Version 85.0.4183.121 (Official Build) (64-bit)

Summary of issue: When attempting to install/upgrade themes within the one-click install function that is included within the UI.X 2 add-on, it doesn't allow me to do anything and tells me that "The UI.X add-on requires an update before you can upgrade this style." although I've already done that.

Detailed steps to reproduce the issue:
Install this version of the add-on which is now posted on Pinto, navigate to Appearance -> ThemeHouse Styles -> Click Install/Upgrade and then you'll replicate this same message.

Upload any screenshots related to the issue below

**Comment by zerophive** [comment]
I have the same problems. Here is the error message when you attempt to upgrade/install any purchased UI.X themes.
<img width="1175" alt="upgrade failure message" src="https://user-images.githubusercontent.com/869441/94629484-cd14fa80-0277-11eb-9395-08d9d8572014.png">
