### ISSUE TITLE
File health check results error with Xenforo 2.2

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2246]
File health check results error with Xenforo 2.2 after updated Donate and Reaction Plus addon but both Covers and Nodes addon disabled.

![ScreenShot00010](https://user-images.githubusercontent.com/6899856/94807105-716d7d00-03ef-11eb-9ec6-7973d6ee6b51.png)

**Comment by LukasWieditz** [comment]
Safe to ignore for now.
