### ISSUE TITLE
[Covers] - Thread permissions are not working

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2251]
I can not updated my live site or test site because [this error](https://github.com/Audentio/xf2addon-issues/issues/2249#issuecomment-702797292). So make one new test site and installed but permissions are not working. I have set Upload image for own resource covers set to NO but still can use upload image. Also all other permissions are not working.

![ScreenShot00025](https://user-images.githubusercontent.com/6899856/94947570-21b9af00-04de-11eb-828b-9dfb7d8e39ff.png)

**Comment by Nirjonadda** [comment]
![ScreenShot00026](https://user-images.githubusercontent.com/6899856/94947663-4dd53000-04de-11eb-9472-aa40af29e84d.png)

**Comment by LukasWieditz** [comment]
Is this on a fresh installation or the one that was stuck in the upgrade?

**Comment by Nirjonadda** [comment]
This from fresh installation.

**Comment by addonflare** [comment]
permissions are working, when toggling the permissions on/off while testing make sure to refresh the page because the modal gets cached

**Comment by Nirjonadda** [comment]
@addonflare No, Does not working because only set Use presets for own thread covers but does not show cover button in own thread.

User group permissions:

![ScreenShot00102](https://user-images.githubusercontent.com/6899856/98377312-f5e19a00-2044-11eb-8b3f-dca4cc43201d.png)

Own thread does not show cover button:

![ScreenShot00103](https://user-images.githubusercontent.com/6899856/98377327-faa64e00-2044-11eb-89ec-471882304404.png)

And other user thread show cover button but no permissions error:

![ScreenShot00105](https://user-images.githubusercontent.com/6899856/98377646-5ffa3f00-2045-11eb-9fda-edf80a2809de.png)

**Comment by daltonp** [comment]
I'm able to replicate the same issue as well.

**Comment by addonflare** [comment]
> @addonflare No, Does not working because only set Use presets for own thread covers but does not show cover button in own thread.
> 
> User group permissions:
> 
> ![ScreenShot00102](https://user-images.githubusercontent.com/6899856/98377312-f5e19a00-2044-11eb-8b3f-dca4cc43201d.png)
> 
> Own thread does not show cover button:
> 
> ![ScreenShot00103](https://user-images.githubusercontent.com/6899856/98377327-faa64e00-2044-11eb-89ec-471882304404.png)
> 
> And other user thread show cover button but no permissions error:
> 
> ![ScreenShot00105](https://user-images.githubusercontent.com/6899856/98377646-5ffa3f00-2045-11eb-9fda-edf80a2809de.png)

Can you try testing with a different user? (non-admin)
The current user you're testing with might have custom user permissions that are overriding the user group permissions.

**Comment by Nirjonadda** [comment]
Yes, issue are same but please can you let me know that what different between Admin or non-admin permissions? This permissions should work by user group and does not matter if Admin or non-admin.
