### ISSUE TITLE
Covers 1.1.0 Patch Level 1 getting stuck

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2addon-issues#2254]
It seem it's still getting stuck.

[https://xenforo.com/community/attachments/covers-upgrade-png.236471/](url)

Been doing this for ages now... I turned off the page and tried to upgrade again as it threw an error saying there might be inconsistencies due to the upgrade not completing. I hope I haven't broken anything by doing that.

**Comment by LukasWieditz** [comment]
If you've started your upgrade during the Version 1.1.0, the latest update will not resolve your issue. You'll need to reset the installer to restart the install step from scratch. If you don't know how to do that, shoot us a ticket with login credentials for your DB and ACP and we can do it for you.

**Comment by Nirjonadda** [comment]
Please update here step by step Information about reset the installer and restart the install. So this will help for everyone without opening ticket.

**Comment by joyfreak** [comment]
Basically upgrading broke something and now we need to fix it via resetting something in the DB.. Can't you just release an update that will resolve the issue for some of us experiencing this? Personally, I find it a lot of hassle to give out login credentials for you guys to resolve this.

**Comment by LukasWieditz** [comment]
We cannot. The bug is fixed, but the installer is stuck at that specific instruction, which we can't change.

**Comment by joyfreak** [comment]
Who am I contacting then to share my login credentials?

**Comment by LukasWieditz** [comment]
https://www.themehouse.com/contact/support

**Comment by Nirjonadda** [comment]
> 
> 
> We cannot. The bug is fixed, but the installer is stuck at that specific instruction, which we can't change. I'm not sure what you think we'd gain from having to do this manually for everyone.

If this then Created Support Ticket. Please check....
