### ISSUE TITLE
Nodes Search API results order incorrect

### ISSUE THREAD

**Issue by kylerc** [Audentio/xf2addon-issues#2256]
Right now even exact title matches tend to be lower in the results that longer titles.  Would there be a way that lower depth nodes (closer to root of node tree) could be prioritized since once you're on a node it's fairly easy to go to the children but the other way is often harder?

**Comment by LukasWieditz** [comment]
None that I know of. The ordering is performed on search engine level and I don't think we get control over this at any point.
