### ISSUE TITLE
[Covers] - Default Cover presets for Nodes

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2258]
Please add option for Default Cover presets for Nodes.

![ScreenShot00041](https://user-images.githubusercontent.com/6899856/95214397-276e0800-07f0-11eb-9fb3-564dd76cae1c.png)

**Comment by LukasWieditz** [comment]
Node banners are managed in the nodes add-on exclusively. We're not having any plans to further integrate with Covers
