### ISSUE TITLE
[TH] Donate - The requested page could not be found.

### ISSUE THREAD

**Issue by Graymanflo** [Audentio/xf2addon-issues#227]
Add-on Name: [TH] Donate

Add-on Version: 1.0.2

XenForo Version: 2.0.4

Operating System (and Version): Debian GNU/Linux 9.4 Stretch (64 bit)

Browser Name (and Version): Opera Next 53.0.2907.21

Summary of issue/Detailed steps to reproduce the issue: Fresh installation of XenForo 2.0.4 with [TH] Donate. I added PayPal (donation option) as a payment provider for my campaign and selected Euro as currency, whenever I try to checkout I get "The requested page could not be found." error. Developer console is showing the following: [https://i.imgur.com/LGpCZ4j.png](https://i.imgur.com/LGpCZ4j.png). I'm using Nginx webserver with full friendly URLs (I tried deactivating it but it does not seem to be the issue behind 404 as the friendly urls are working perfectly fine). Did I miss a step?

**Comment by JakeBooher** [comment]
@Graymanflo Did you upgrade from the XF1 version? If so did you upgrade straight to 1.0.2 or were you using any other versions previously?

**Comment by Graymanflo** [comment]
Hey there Jake.

No like I mentioned, just installed fresh copy of XenForo 2.0.4 with [TH] Donate 1.0.2, no middle steps and it does not seem to work out of the box for me. Is there anything I can try?

**Comment by JakeBooher** [comment]
@Graymanflo We've had a couple other people report this as well, I've posted steps that should resolve the issue while we look into why it only seems to be happening on some installs: https://xenforo.com/community/threads/th-donate-paid.145264/page-4#post-1244983

**Comment by Graymanflo** [comment]
That temporary fix solved it for me, thanks.
