### ISSUE TITLE
[Covers] Covers button is on the right instead of the left

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2274]
Add-on Name: [TH] Covers

Add-on Version: 1.1.0 Patch Level 2

XenForo Version: 2.2.1

Operating System (and Version): windows 10 Pro 64-bit

Browser Name (and Version): Version 86.0.4240.75 (Official Build) (64-bit)

Summary of issue: Is the Covers button that is shown on threads suppose to be on the right? If I remember correctly, it is usually on the left. This is even viewable on the default style.

Detailed steps to reproduce the issue:

Upload any screenshots related to the issue below
![image](https://user-images.githubusercontent.com/32306910/96151488-0df44c80-0ed1-11eb-926c-1241b10fea32.png)

**Comment by Nirjonadda** [comment]
This is correct position Covers button.
