### ISSUE TITLE
Hide "choose cover preset if there are no presets to choose from

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#2275]
<img width="457" alt="Screen Shot 2020-10-15 at 11 34 19 AM" src="https://user-images.githubusercontent.com/15836384/96159588-7136ac80-0eda-11eb-905a-1a761a37f277.png">

**Comment by Ian-Hitt** [comment]
confirmed fixed

**Comment by daltonp** [comment]
I'm not able to confirm a fix on version 1.1.1 Beta 2
