### ISSUE TITLE
change "style cover" phrase to "choose background color"

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#2276]
<img width="1119" alt="Screen Shot 2020-10-15 at 11 36 38 AM" src="https://user-images.githubusercontent.com/15836384/96159849-c4106400-0eda-11eb-9a27-81145b9c7259.png">

**Comment by daltonp** [comment]
This is still replicated on the latest which is 1.1.1 Beta 1 - Send me the latest once fixed please :)

**Comment by daltonp** [comment]
Able to replicate this feature now 👍
