### ISSUE TITLE
"modify cover image" phrase getting added to menu when there is a background color

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#2277]
this is somewhat potentially confusing because the user has **not** chosen a  background image, so it should still say "set cover image". Small issue, but maybe worth fixing if it's super simple
<img width="1165" alt="Screen Shot 2020-10-15 at 11 38 58 AM" src="https://user-images.githubusercontent.com/15836384/96160190-3ed97f00-0edb-11eb-92cf-8fde07b2e0a0.png">
<img width="573" alt="Screen Shot 2020-10-15 at 11 39 10 AM" src="https://user-images.githubusercontent.com/15836384/96160193-400aac00-0edb-11eb-87b0-de0c17a70eec.png">

**Comment by Ian-Hitt** [comment]
confirmed fixed

**Comment by daltonp** [comment]
I can confirm this is fixed as well
