### ISSUE TITLE
Use proper markup or covers preset modal/page. and use better grid layout

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#2278]
Currently just has a separate block for each category, and a block-header (h2). Shouldn't be a bunch of <h2>s and shouldn't be blocks. Instead, use class="block-body block-row" for each category, and use block-textHeader instead of block-header

Before

<img width="1022" alt="Screen Shot 2020-10-15 at 11 48 08 AM" src="https://user-images.githubusercontent.com/15836384/96161130-844a7c00-0edc-11eb-888c-f413e4451ed4.png">

after

<img width="1040" alt="Screen Shot 2020-10-15 at 11 48 01 AM" src="https://user-images.githubusercontent.com/15836384/96161158-890f3000-0edc-11eb-8fbd-c9aa528d0479.png">

**Comment by Ian-Hitt** [comment]
Sidenote, maybe an equal width grid would be better than variable grid width items. Try css grid and grid-template-columns: repeat( auto-fill, minmax(300px, 1fr) ); or so for correct sizing.

**Comment by daltonp** [comment]
I'm not able to see these changes on the latest beta that I was sent neither.

**Comment by daltonp** [comment]
Able to replicate these changes on the latest version as well.

**Comment by Ian-Hitt** [comment]
This is not done

**Comment by Ian-Hitt** [comment]
https://github.com/Ian-Hitt/xf2/commit/2b9545fe7795c587175679ee29d8aff457c4d187 fixed here
