### ISSUE TITLE
Add preset image preview in ACP, and add ability to set position as well (probably just copy more or less from front end)

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#2279]
Setting an image in the acp for cover presets kinda sucks because you can't position it. Can just do same thing in ACP as we don't on front end to allow users to set a default position

**Comment by Ian-Hitt** [comment]
Confirmed fixed

**Comment by daltonp** [comment]
Unless I'm missing it, I'm not able to replicate this fixed on 1.1.1 Beta 2 I'm afraid
