### ISSUE TITLE
[TH] Reactions - th_exceeded_daily_reacts_reactions

### ISSUE THREAD

**Issue by JakeBooher** [Audentio/xf2addon-issues#228]
```
Hi,
Whenever users attempt to react to content, they are met with the error th_exceeded_daily_reacts_reactions, even if they haven't reacted to any content at all today.
The "Maximum number of reacts per content" permission is set at 1, and the "Maximum amount of reactions per day" is set at 8.
I've temporarily set both of these to 'Unlimited' whilst we attempt to resolve this issue.```

**Comment by LukasWieditz** [comment]
`ThemeHouse\Reactions\Repository\ReactedContent::getUserReactCout()` might be the issue. The function uses MySQL functions to evaluate which posts belong to the current day, but that might not work, if the database is running a different timezone than the XF installation.

**Comment by LukasWieditz** [comment]
I do think we have this fixed. At least I am unable to reproduce it. If it happens to persist or pop up again, we can tackle it again.
