### ISSUE TITLE
"Use covers as Open Graph" images doesn't seem to work for resources or threads. 

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#2280]

**Comment by addonflare** [comment]
Unable to replicate
![Screen Shot 2020-10-15 at 10 25 31 AM](https://user-images.githubusercontent.com/7610372/96590626-dc51fb80-12ab-11eb-9a23-5ed602aaf16a.png)

**Comment by Ian-Hitt** [comment]
Working for me as well.
