### ISSUE TITLE
[Q&A Importer] Invalid Argument Exception error experienced

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2291]
Reported by one of our customers in ticket and in [thread ](https://xenforo.com/community/threads/th-question-and-answer-forums-importer.185920/post-1467836)on XF.com:
`
InvalidArgumentException: Attempted to convert NULL to integer [content_user_id] in src/XF/Mvc/Entity/Entity.php at line 759 XF\Mvc\Entity\Entity->_castValueToType() in src/XF/Mvc/Entity/Entity.php at line 637 XF\Mvc\Entity\Entity->set() in src/XF/Mvc/Entity/Entity.php at line 739 XF\Mvc\Entity\Entity->bulkSet() in src/addons/ThemeHouse/QAForumsImporter/Import/Importer/THQAForums.php at line 75 ThemeHouse\QAForumsImporter\Import\Importer\THQAForums->stepVotes() in src/XF/Import/Runner.php at line 232 XF\Import\Runner->runStep() in src/XF/Import/Runner.php at line 59 XF\Import\Runner->run() in src/XF/Admin/Controller/Import.php at line 234 XF\Admin\Controller\Import->actionRun() in src/XF/Mvc/Dispatcher.php at line 350 XF\Mvc\Dispatcher->dispatchClass() in src/XF/Mvc/Dispatcher.php at line 257 XF\Mvc\Dispatcher->dispatchFromMatch() in src/XF/Mvc/Dispatcher.php at line 113 XF\Mvc\Dispatcher->dispatchLoop() in src/XF/Mvc/Dispatcher.php at line 55 XF\Mvc\Dispatcher->run() in src/XF/App.php at line 2300 XF\App->run() in src/XF.php at line 464 XF::runApp() in admin.php at line 13
`

**Comment by jumuro-dev** [comment]
Hi!
Can I find out the approximate time frame for solving the problem?
I need this information to plan an XF update.

**Comment by jumuro-dev** [comment]
@daltonp @LukasWieditz
Hi!
Can I find out the approximate time frame for solving the problem?
I need this information to plan an XF update.

**Comment by thecodeby** [comment]
Hello. When will the problem be resolved? Regards, administrator codeby.net
