### ISSUE TITLE
Add more holidays

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#2300]
- [ ] St. Patrick's Day

- [ ] easter

- [ ] cinco de mayo

- [ ] earth day

- [ ] kwanzaa

- [ ] labor day

- [ ] chinese new year

- [ ] dia de los muertos

- [ ] oktoberfest

- [ ] Hanami (cherry blossoms festival)

- [ ] world peace day

- [ ] may day

**Comment by meganb-audentio** [comment]
wanna make sure i get it. so im adding holidays to our current selection of holidays? will have to secure icons + animations for each new one, yeah? is that what u mean by the bulleted list you sent me?
