### ISSUE TITLE
[ConnectedAccountProviders] - Add support Hybridauth for login providers

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2330]
Please add support [hybridauth](https://hybridauth.github.io/index.html) for login providers. which will improve on third-party login situation by implementing hybridauth. This will allow to support many login providers. It is about time to improve login as the original dependencies

Supported providers: https://hybridauth.github.io/providers.html

**Comment by LukasWieditz** [comment]
XenForo is already using a library for OAuth Provider handling, and replacing it is not possible. Any suggestions in that direction should be made to them directly.
