### ISSUE TITLE
Monetize - User should confirm email before performing payment

### ISSUE THREAD

**Issue by GH-Rake** [Audentio/xf2addon-issues#2331]
Add-on Name:
Monetize

Add-on Version:
1.0.2 Patch Level 1

XenForo Version:
v2.1.11

Operating System (and Version):
Windows 10 2004

Browser Name (and Version):
Firefox/Brave(chromium)

Summary of issue:

When using monetize with "Force Users to Purchase an Upgrade on Signup", the sign up process goes like this:

1. Register
2. Purchase upgrade
3. Confirm Email

This doesn't make sense to me, if they use a fake email address, they will have paid for an upgrade and then have a paid account which they can't reset the password to via email password reset.

It makes more sense to confirm email before the purchase, to ensure this doesn't occur.

**Comment by LukasWieditz** [comment]
While I see the issue, the flow is not changeable without a major restructuring of the code. In the end, someone using a fake email is willingly entering that risk of not receiving that mail, and, should need ever be, their purchase information would contain a valid email address for correspondence.
