### ISSUE TITLE
Instead of (child) the following is shown on child styles that are installed with I&U

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2333]
Might be ideal to change this so that it matches with installing manually with XML files or the installation function included with the UI.X add-on. Replace `(Config)` with `(child)`.

Currently, it shows this: 
![image](https://user-images.githubusercontent.com/32306910/97616263-5429cf80-19ea-11eb-80e4-a0ca6660799b.png)

**Comment by LukasWieditz** [comment]
This is intended behavior. "Child" will mean nothing to an inexperienced user, whereas "config" is intended to hint that this is where configurations/customizations should be made.

**Comment by daltonp** [comment]
Understood, thanks @LukasWieditz :)
