### ISSUE TITLE
The zipped file for Holidays is flagged as being to large when attempting to install as an archive

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2338]
Add-on Name: [TH] Holidays

Add-on Version: 2.1.0 Release Candidate 3

XenForo Version: 2.2.1

Operating System (and Version): Windows 10 Pro 64-bit

Browser Name (and Version): Version 86.0.4240.183 (Official Build) (64-bit)

Summary of issue: Even though I went ahead and installed it on the webserver instead when attempting to install as an archive I get the following error 

> Oops! We ran into some problems.
Could not process ThemeHouse-Holidays-2.1.0 Release Candidate 3.zip: The uploaded file is too large for the server to process.

Detailed steps to reproduce the issue:

Upload any screenshots related to the issue below

**Comment by LukasWieditz** [comment]
That's not a bug in the add-on. Each server has a configured upload limit, if a file exceeds that, it can't be uploaded using the web installer.
