### ISSUE TITLE
Monetize Suggestion/Enhancement: Add purchased upgrades to statistics

### ISSUE THREAD

**Issue by GH-Rake** [Audentio/xf2addon-issues#2341]
Add-on Name:
Monetize

Summary of Suggestion:

In the admin control panel, in the statistics tab it would be nice to be able to view the purchased upgrades statistics.  We can use these statistics to easily discover what techniques affect the purchase of which upgrades.  As I fine tune my forum for monetization this would be very helpful.

**Comment by LukasWieditz** [comment]
Offering a dynamically extending statistic list is unfortunately very dirty to implement with the currently given means by XenForo, and thus not something we have planned.
