### ISSUE TITLE
cover button markup not quite correct on resource (likely all pages)

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#2355]
<img width="428" alt="Screen Shot 2020-11-10 at 11 18 51 AM" src="https://user-images.githubusercontent.com/15836384/98708257-9508d900-2346-11eb-8a7b-90f073e5b80e.png">

**Comment by daltonp** [comment]
I'm able to replicate this currently as well

**Comment by daltonp** [comment]
This still needs to be fixed even in the latest version.

**Comment by Ian-Hitt** [comment]
Confirmed fixed

**Comment by daltonp** [comment]
Confirmed here
