### ISSUE TITLE
[Covers] preset upload & positioning

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2addon-issues#236]
Implement upload/download and positioning functionalities for cover presets.

**Comment by mikecreuzer** [comment]
I thought this was the only thing Kyler was necessary for. @kylerc didn't you do/start this?

**Comment by LukasWieditz** [comment]
I think you might confuse covers with cover presets here. We have implemented the functionality for covers already, but Dalton pointed out that we could do this for cover presets as well - we currently only have an option to put in a link to an image there at the moment.

**Comment by kylerc** [comment]
I only did the positioning part, but that's done afaik.  Didn't do anything with presets specifically though.

**Comment by mikecreuzer** [comment]
What is the difference? Do we need to position presets?

**Comment by LukasWieditz** [comment]
Covers are created specifically for each individual entity. Cover presets are defined in the ACP once and can be applied to as many entities as needed, without copying the actual image and styling over to each entity. Cover presets don't support image uploading and positioning at the moment however, only a URL that links to the image that'll be used as cover.

**Comment by mikecreuzer** [comment]
If you feel strongly its important then OK

**Comment by LukasWieditz** [comment]
Only for a future release. Dalton has pointed out that it'll likely be something that will be requested in the future.

**Comment by setoy** [comment]
I second this - preset positioning would be marvelous :)
