### ISSUE TITLE
When ignoring a forum, it should disappear from the grid instead of still be visible on the front-end

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2361]
Add-on Name: [TH] Ignore More

Add-on Version: 2.0.1

XenForo Version: 2.2.1

Operating System (and Version): Windows 10 Pro 64-bit

Browser Name (and Version): Version 86.0.4240.183 (Official Build) (64-bit)

Summary of issue:

Response from one of our clients in ticket (Tom McIntyre): 

> We installed the Ignore More feature because some users are only interested is a subset of our forums and wanted the ability to simplify their display as well as avoiding the traffic. When one selects a forum to ignore, the contents are suppressed, but the forum title is still displayed in the grid. We expect the forum to disappear from the grid and we had hoped the behavior could be extended to categories.

**Comment by LukasWieditz** [comment]
This is already happening, but may be prevented by a 3rd party add-on or style.
