### ISSUE TITLE
Ability to filter out ignored forums from the What's New display

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2362]
Add-on Name: [TH] Ignore More

Add-on Version: 2.0.1

XenForo Version: 2.2.1

Operating System (and Version): Windows 10 Pro 64-bit

Browser Name (and Version): Version 86.0.4240.183 (Official Build) (64-bit)

Summary of issue:

Response from one of our clients in ticket (Tom McIntyre): 

> I received some additional feedback from my users on this. Some or many of them were looking for the ability to filter out the ignored forums from the What’s New display. It appears that the selection checkboxes that appear when you select ignore for a forum could have that page in the selections to limit the ignore function to only the What’s New page (or any of the other thread list displays for that matter 😊)

**Comment by LukasWieditz** [comment]
This is already happening, but may be prevented by a 3rd party add-on or style.
