### ISSUE TITLE
There is currently no way to unignore media categories

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2369]
Add-on Name: [TH] Ignore More

Add-on Version: 2.1.0 Alpha 1

XenForo Version: 2.2

Operating System (and Version): Windows 10 Pro 64-bit

Browser Name (and Version): Version 86.0.4240.198 (Official Build) (64-bit)

Summary of issue:
When ignoring both news feed, media list, and the category list on Media categories. I am not able to unignore them. Am I missing something?

Detailed steps to reproduce the issue:
Navigate to "Media" click on a media category on the side navigation and then click "Ignore". Thereafter, click all three of the options and click "Ignore". Thereafter, you won't be able to unignore it as you literally have to uninstall the add-on in order to regain the viewable compatibility of the media categories you ignore.

**Comment by LukasWieditz** [comment]
I'm not able to reproduce this. On the category view page, the "ignore" button transforms into the "unignore" button, and otherwise, categories can be unignored via forums > ignored
