### ISSUE TITLE
Reactions: Ability for usergroups to post ratings anonymously

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#24]
I assume necessary functionality would be:

- [ ] User preferences that asks if they want all post ratings to be anonymous
- [ ] Tabbed in from that user preference will be all types of ratings that can be anonymous (positive, neutral, negative, etc.
- [ ] A flag that if it is negative, a way to change it to public (ie a link next to the rating or in the view all reactions list)
- [ ] No possible way for the rating to be linked back to their profile, so some type of flag on each reaction type
- [ ] A way for certain usergroups to see anonymous ratings (ie moderators/staff)

**Comment by LukasWieditz** [comment]
This cannot really be feasibly implemented with XenForos approach to reactions.
