### ISSUE TITLE
Allow notification when someone donates

### ISSUE THREAD

**Issue by Tipmoose** [Audentio/xf2addon-issues#240]
Add-on Name:
TH-Donate
Add-on Version:
Any
XenForo Version:
2.x
Operating System (and Version):
Any Supported
Browser Name (and Version):
Any Supported
Summary of issue:
Enhancement request. Would like to be able to configure the Donate add on to trigger an alert or notification or conversation with a user or usergroup whenever someone donates.  The purpose of this is for the admins on a forum to know in real time who donated so they can thank them and make sure the donor is properly placed in the correct user group. 
Detailed steps to reproduce the issue:

Upload any screenshots related to the issue below

**Comment by mikecreuzer** [comment]
Since this is simple enough, going to add it to our UIX Pro milestone.

**Comment by LukasWieditz** [comment]
Who's meant to receive these notifications though @mikecreuzer

**Comment by mikecreuzer** [comment]
A list of users I suppose OR a set of usergroup(s)

**Comment by LukasWieditz** [comment]
I've implemented a name input option so the admin can configure who'll receive these alerts.

**Comment by mikecreuzer** [comment]
No it will be in Donate it's just set for release in our UI.X Pro release. That's more for internal use
