### ISSUE TITLE
[TH] Donate - Donation Log

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#245]
Please add option Donation Log, Entries to show per page.
    User Name
    Start Date
    End Date
    Order By

**Comment by JakeBooher** [comment]
Could you elaborate on exactly what you're referring to?

**Comment by Nirjonadda** [comment]
All Donation Log, Who are made Donate Entries to show one place.

**Comment by Nirjonadda** [comment]
Donation transaction log. example below.

![14_donation_logs](https://user-images.githubusercontent.com/6899856/39249572-3df344c2-489f-11e8-801a-7c64054dc236.png)

**Comment by JakeBooher** [comment]
This is available in XenForo 2 by default, Logs -> Payment provider log and you can filter it to only donations

**Comment by Nirjonadda** [comment]
Yes but its best have Browsable Donation Log in separate page for Donate add-on. The list of people who donated can be found both via the AdminCP.

![11](https://user-images.githubusercontent.com/6899856/39262050-93c2a64e-48be-11e8-87ae-18ab600d06c2.png)

**Comment by Nirjonadda** [comment]
![13](https://user-images.githubusercontent.com/6899856/39262652-437cc3ca-48c0-11e8-8e0b-9235d870a4b1.png)
