### ISSUE TITLE
[TH] Donate - Sidebar Donate button open overlay

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#246]
Please add option Donate button opens an overlay where users fill in their donation amounts and optional message.

**Comment by LukasWieditz** [comment]
Simply adding the overlay trigger at this point does not work. Something in our implementation seems to trigger unexpected behavior here. Further investigation needed.

**Comment by mikecreuzer** [comment]
Not sure if related to https://github.com/Audentio/xf2addon-issues/issues/258 but seems to be asking for different things.

**Comment by LukasWieditz** [comment]
I think we can deem this as duplicate. It's from a code base not the same, but if we do it, we'll do it for all of them at once. Referencing #258 and closing this.
