### ISSUE TITLE
[TH] Donate - End of donation

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#249]
Please add option show End of donation and as well in sidebar.

![2](https://user-images.githubusercontent.com/6899856/39216956-25d7c01a-481e-11e8-8424-31eb00e2f96b.png)
![3](https://user-images.githubusercontent.com/6899856/39216958-25f48d80-481e-11e8-8de9-61675598094c.png)

**Comment by LukasWieditz** [comment]
Gonna need some styling for this once the data is available @Ian-Hitt
