### ISSUE TITLE
[TH] Donate - Option for disable goals

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#252]
Please can you add option for disable goals?

> Is it possible to have a donate link/button/navbar/widget that is unattached to a campaign? I don't need to set goals or campaigns for my users. I just want to give them an option to donate at their leisure.

**Comment by JakeBooher** [comment]
This is already possible, just leave the goal blank.

**Comment by Nirjonadda** [comment]
@JakeBooher No, Its still show Current progress. Its are not hide goals or campaigns.

I am asking example below.

![screenshot00146](https://user-images.githubusercontent.com/6899856/39249193-5ffbc6d0-489e-11e8-8fbd-254c52df38f7.png)

**Comment by JakeBooher** [comment]
Current progress isn't related to the goal, it's related to the daily/weekly/monthly reset, if you want to hide everything from the top this can be done via CSS

**Comment by Nirjonadda** [comment]
Then need back to using [[DBTech] Donate](https://xenforo.com/community/resources/dbtech-dragonbyte-donate.5870/) and I have Lifetime license. You need more improvement development because [DBTech] Donate have more functionality than your add-on.
