### ISSUE TITLE
[TH] Donate - User upgrades will add donations list

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#260]
Please can you add option Xenforo User upgrades will add user to donations list.

**Comment by mikecreuzer** [comment]
This should be doable with a user upgrade no?

**Comment by Nirjonadda** [comment]
No, Just show this user make upgrade in donation list. So user upgrade and donation list show in one place.

**Comment by JakeBooher** [comment]
That's really not in the scope of a donation, these are two entirely separate systems. You can add a user to a user group when they donate via User group promotions.
