### ISSUE TITLE
reactions display in discussion list is no good. suggestion: show categories instead

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#261]
<img width="957" alt="screen shot 2018-04-25 at 3 52 56 pm" src="https://user-images.githubusercontent.com/15836384/39272184-d059b61a-48a0-11e8-8c7e-2b0a11752d9f.png">

**Comment by mikecreuzer** [comment]
That should show number, and be limited to say 1-3 (a setting) of the top reaction times.

**Comment by Nirjonadda** [comment]
Yes this same issues i am reporter long time ago in Xenforo but no fix happened.

**Comment by mikecreuzer** [comment]
OK we'll get a fix.

**Comment by LukasWieditz** [comment]
I've chosen @mikecreuzer's way for now, as that's data we have currently available. We can think of using the reaction types in the future, but that'll require larger changes to the data structure.
