### ISSUE TITLE
Selected primary topic class is not removed on topic selection

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2addon-issues#262]
If a topic is pre-selected (for example when changing topics of a thread), the respective topic class is not removed and the styling stays active, potentially overriding the styling of the selected topic: https://giant.gfycat.com/BitterShabbyCaribou.webm

**Comment by LukasWieditz** [comment]
Seems we have to rework some of the javascript code for this to function properly. As of now, the current code to handle this situation has been missing because of wrong implementation. I've rectified these issues, so the code is now actually delivered to the frontend, but it can't be run because the topic chooser is not yet loaded at the time.

**Comment by kylerc** [comment]
This was fixed by Audentio/xf2#329
