### ISSUE TITLE
[TH] Reactions - About Reactions button

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#267]
When using Always Show Secondary Trigger then Default reaction should not be open popup because its will be direct take action. only Always Show Secondary Trigger will be show popup when enabled. Also Clicking Reactions button why the button image are marked?

More info: https://xenforo.com/community/threads/th-reactions-paid.134133/page-36#post-1242424

**Comment by Nirjonadda** [comment]
@kylerc Any update please? How many time you are take for bug fix update?

**Comment by LukasWieditz** [comment]
We have a lot of tasks at hand, so we can't give any definite time frame at the moment. We'll update this ticket once we know more.

**Comment by kylerc** [comment]
@Nirjonadda sorry about the delay on this, will be fixed in the next release
