### ISSUE TITLE
Unknown getter 'is_' - incompatibility with other add-on

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2addon-issues#283]
[Additional Information](https://xenforo.com/community/threads/th-reactions-paid.134133/page-40#post-1245116)

**Comment by LukasWieditz** [comment]
Can't replicate this issue. Stack trace doesn't suggest that it's our code either. Only mention of our class happens because of the class proxy system (last class to be extended to the templater), so not necessarily our fault.

**Comment by JakeBooher** [comment]
Just make sure to let them know, going to go ahead and close this issue though 👍
