### ISSUE TITLE
topic and forum list links both getting added to sub nav

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#289]
<img width="370" alt="screen shot 2018-05-01 at 4 09 30 pm" src="https://user-images.githubusercontent.com/15836384/39494011-721589b2-4d5a-11e8-9f0b-cec88a036f17.png">

**Comment by LukasWieditz** [comment]
This is correct if the forum list is not set to redirect to the topic list, but incorrect otherwise.
