### ISSUE TITLE
topic view: sidebar widget location does not work

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#291]
Add-on Name:

Add-on Version:

XenForo Version:

Operating System (and Version):

Browser Name (and Version):

Summary of issue:

Detailed steps to reproduce the issue:

Upload any screenshots related to the issue below

**Comment by LukasWieditz** [comment]
Can't reproduce this @Ian-Hitt, sidebar widget position is working fine for me.

**Comment by kylerc** [comment]
@Ian-Hitt did you maybe not rebuild the caches?  Was there no topics listed or something else wrong?
