### ISSUE TITLE
[UIX] Default collapsed state

### ISSUE THREAD

**Issue by kylerc** [Audentio/xf2addon-issues#298]
Similar to XF1, XF2 nodes should be able to default to collapsed (and be overridden per-user)

**Comment by JakeBooher** [comment]
Collapsable nodes is a UI.X feature, not Nodes. Isn't it?

**Comment by kylerc** [comment]
Hmm I guess it could make sense in either or.  But since nodes comes free with UI.X it might add more value in the nodes addon for users that choose to purchase it?

**Comment by JakeBooher** [comment]
it's not a matter of where it makes sense, it's a matter of collapsable nodes being in UI.X, not Nodes 👍

**Comment by kylerc** [comment]
@LukasWieditz this will require a setting added to each node to start it collapsed.  There will also need to be an endpoint to save the nodes that are expanded (similar to the current endpoint for nodes that are currently collapsed).  Let me know once that's added, I don't think the rest should be too involved.

**Comment by LukasWieditz** [comment]
You sure we want to keep a whole list of "expanded" nodes in addition to the collapsed ones and not just have them added to the list of collapsed ones upon creation?

**Comment by mikecreuzer** [comment]
In XF1 we just had a setting for level 0 nodes (Collapsed by default)

**Comment by kylerc** [comment]
Issues is that we need an override whenever a node doesn't start in a `default` state.  We don't need to know every expanded node (since most nodes are default expanded), just the ones that default to collapsed but a user has overridden to be expanded if that makes sense.  Similarly, for nodes that default to expanded but a user has overridden to be collapsed we already track this.

**Comment by jonw316** [comment]
@Ian-Hitt Can we close this?
