### ISSUE TITLE
QA Forums: Tie best answer/upvotes with like/reputation system

### ISSUE THREAD

**Issue by Matthew2D** [Audentio/xf2addon-issues#3]
When someone chooses an answer as the best answer, it would useful if it was tied into the like system in some way. Better yet, if this was tied into the Post Ratings addon, when the xf2 version comes out.

Also maybe do the same with up votes?

**Comment by mikecreuzer** [comment]
We have a similar concept to post ratings coming out called Reactions. I think we could definitely build some kind of way to integrate, what do you think @JakeBooher

**Comment by JakeBooher** [comment]
I'm not sure how much sense it'd make to integrate them, I suppose we could have an option to map up vote to either XF's like system, or a reaction and an option to map the down vote to a reaction

**Comment by ellisonpatterson** [comment]
Yeah reactions could have content actions so for each content type it will have options to perform moderation actions based on criteria. On X reactions reached for all posts or first posts, move thread, lock thread, auto reply, auto promote, set prefix, etc.
