### ISSUE TITLE
Reactions: One like per post per user, Positive reaction should be counted as the like

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#30]
XenForo User: invictus
> One like per post per user is fine, but any positive reaction should be able to be counted as the like, not just a specific one and the rest don't count. So maybe if a single user gives multiple reactions it only counts 1 like form that user, but it doesn't matter which positive reaction is use to give it. 

https://xenforo.com/community/threads/th-reactions-paid.134133/page-6

**Comment by JakeBooher** [comment]
If this gets implemented it's more likely that we'll allow multiple reactions to be a like handler, and any reaction with the "Like handler" option ticked would be handled this way, rather than assuming all positive reactions are likes

**Comment by mikecreuzer** [comment]
@JakeBooher fully agree I was actually thinking this as well. Its all counted as "1" aka a single like, but multiple can be used to give that total value of 1. I think I agree and yes we should aim to implement. Currently its just the one like button I think. So technically if you set 2 reactions as 'like' then a user can get more than one like from a single user, and I think "like" should be objectively defined as one like per reacting user per post.

**Comment by LukasWieditz** [comment]
Closing, as reactions has been discontinued.
