### ISSUE TITLE
When Redirect forum list to topic list is selected, forum list phrase should never show up

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#300]
<img width="425" alt="screen shot 2018-05-08 at 4 07 20 pm" src="https://user-images.githubusercontent.com/15836384/39783215-e6f3aaa0-52d9-11e8-95dc-bc747be2515f.png">
<img width="482" alt="screen shot 2018-05-08 at 4 07 22 pm" src="https://user-images.githubusercontent.com/15836384/39783216-e704a580-52d9-11e8-9af8-a65209cc2767.png">

**Comment by LukasWieditz** [comment]
There's no way to change that without hampering with the default XenForo navigation items. Hiding the "Topic List" menu item is the feasible way here.
