### ISSUE TITLE
Importer for [n] Best Answer add-on

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#31]
https://xenforo.com/community/resources/n-best-answer-q-a-system.4288/

**Comment by zastavra** [comment]
I'm gonna need that.

Thanks.

**Comment by zastavra** [comment]
Hey Mike, is there any progress on this?

**Comment by JakeBooher** [comment]
@zastavra I'm aiming to have this done in the next release :)
