### ISSUE TITLE
potentially re-visit the topic titlebar component.

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#310]
Perhaps try to use the default titlebar and change the values as opposed to re-creating an entire new component. running into incompatibility issues.

**Comment by LukasWieditz** [comment]
@Ian-Hitt current TitleBar is missing prefixes.

**Comment by LukasWieditz** [comment]
I think you have all required data to do this at hand. `$topic` holds the topic, if existing, and `$thCover` holds the entity with the cover.
