### ISSUE TITLE
Topics, trending, forum list, new posts, etc should "behave" like an index page with respect to sidebar

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#313]
Currently if you tab over to 'trending' you do not get a sidebar. But you should get the same default index page sidebar you'd get on a default xenforo page.

**Comment by LukasWieditz** [comment]
That's a thing that we best add to the configuration add-on @Ian-Hitt, just gotta make sure we have all the necessary widget positions in place.

**Comment by LukasWieditz** [comment]
I've added a new widget position "Forums default page: Sidebar". Widgets that are added there will always be displayed on the forums default page and if you change that page, widgets will automatically appear on the new page.
