### ISSUE TITLE
Hide visitor tab bookmark location by default (keep it a setting)

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#318]
<img width="390" alt="screen shot 2018-05-11 at 10 54 32 am" src="https://user-images.githubusercontent.com/1217271/39933861-b4593b46-5509-11e8-9a07-a1850923e085.png">

**Comment by LukasWieditz** [comment]
@Ian-Hitt add that to the configuration add-on

**Comment by mikecreuzer** [comment]
I mean wouldn't this just be edited on bookmarks? I still want link in the user dropdown.

**Comment by LukasWieditz** [comment]
Bookmarks has already been published, so we don't want to add an option and have it default to a different option than before. People will start asking where the tab went. So we want to add the option to turn it off, have it on by default, and set it to off in the UI.X Pro configuration.
