### ISSUE TITLE
Better active state on 'active' topic

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#329]
<img width="908" alt="screen shot 2018-05-14 at 10 03 54 am" src="https://user-images.githubusercontent.com/1217271/40005662-244f1a14-575e-11e8-815b-bda78826d386.png">

First, if the label bg was 'light' and we put dark text, the active state will do dark text ( see `Design` in the screenshot)

Ultimately there needs to be something more stateful. Why not just checkboxes like we do on the filter page instead of labels?

**Comment by LukasWieditz** [comment]
Maybe just add a checkbox in front of them for better visibility. I think that's all in all clearer.
