### ISSUE TITLE
Mobile styling with Topics/Covers

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#330]
<img width="329" alt="screen shot 2018-05-14 at 10 07 17 am" src="https://user-images.githubusercontent.com/1217271/40005859-9f14c910-575e-11e8-9a35-ae0bcbaf8ad7.png">

- [x] Something better for secondary topics
- [x] Mobile needs to be cleaned up a bit more, could center text or just reduce margins a bit at least

**Comment by LukasWieditz** [comment]
I would use full styling for all topics.
