### ISSUE TITLE
Scroll option like Flarum for threads with multiple topics

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#331]
<img width="516" alt="screen shot 2018-05-14 at 10 09 06 am" src="https://user-images.githubusercontent.com/1217271/40005996-e985fb18-575e-11e8-97b4-4e857b95c0a1.png">

Flarum's:

(note that you scroll)

<img width="290" alt="screen shot 2018-05-14 at 10 09 51 am" src="https://user-images.githubusercontent.com/1217271/40006035-00863120-575f-11e8-8254-75e302a18a95.png">

**Comment by kylerc** [comment]
@Ian-Hitt you should be able to do something similar to what we did for the navigation right? Using a before tag with the gradient?  Any JS required for that?

**Comment by Ian-Hitt** [comment]
@kylerc I've added the necessary markup, but the js isnt running. can you look through it to see what requirement is missing?

**Comment by mikecreuzer** [comment]
You dont want arrows though, just scroll/touch to move. Arrows are too large for this small area.

**Comment by LukasWieditz** [comment]
https://giant.gfycat.com/SpryQualifiedAstrangiacoral.webm
It's something I guess. Didn't the topics used to be at the right hand side of the thread list item @Ian-Hitt ?

**Comment by mikecreuzer** [comment]
Lol yeah only needs to expand when you hover the topic list bar not thread.
