### ISSUE TITLE
Phrases lowercase in footer widget for UIX

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#333]
Not sure if this is addon or theme related

<img width="359" alt="screen shot 2018-05-14 at 10 14 53 am" src="https://user-images.githubusercontent.com/1217271/40006367-cf2e0610-575f-11e8-9eab-1c43d892d1b9.png">

**Comment by LukasWieditz** [comment]
Probably phrases that do not exist.

**Comment by Ian-Hitt** [comment]
@LukasWieditz can you make these changes, they are in widgets in the add-on. can use `nav.defaultLogOut` for logged out. don't see a profile one, so make that phrase.

**Comment by LukasWieditz** [comment]
I've used `log_out` instead and `th_profile_uix` for profile, which was already existing. That only works for new installations however, so we gotta apply some sort of "quick fix", just capitalize the links with css.
