### ISSUE TITLE
Clear all maybe be a needed filter for Topics

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#338]
Im not sure, but since Flarum only lets you set one topic, our experience may need a clear since we could have multiple (under More, out of the screen, etc.)

This should probably sit next to the "More" link

**Comment by LukasWieditz** [comment]
@kylerc @Ian-Hitt clear the frontend selection and pass the new (empty) set to the backend. Code there should be able to handle the rest.
