### ISSUE TITLE
Case when there are no donation campaigns

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#340]
<img width="902" alt="screen shot 2018-05-14 at 2 17 31 pm" src="https://user-images.githubusercontent.com/1217271/40018350-9f3832ce-5781-11e8-8f26-83f4d9009fb7.png">

Potentially we should either have a phrase that says there are no donation campaigns currently running, OR we just disable the nav links or something?

**Comment by LukasWieditz** [comment]
I've included a "no donations available" sentence there. Disabling the NavBar would require us to either query the number of available campaigns on each page or create a cache of some sort. Not sure if we want to do that atm, would be a big effort for a small feature.
