### ISSUE TITLE
Tab bar takes the place of <h1> page Title

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#343]
We discuss this before. Avoid this situation (Ignore dark text color I know its just the wrong location atm)

<img width="985" alt="screen shot 2018-05-14 at 4 00 13 pm" src="https://user-images.githubusercontent.com/1217271/40023216-f35dbac8-578f-11e8-8e12-b0f8d85d5dd1.png">

**Comment by mikecreuzer** [comment]
This will also be nice as the sidebar/forum list triggers can show to the right of the tabs/title. 

This will help make tabs a common thing we can add to pages as well that we may want a quick filter for and no title. (Active tab is the title)

**Comment by Ian-Hitt** [comment]
@mikecreuzer i presume then that we do not want centered tabs ever, because we cannot safely center the tabs and also float things to the right without taking one of them out of flow.

Also I presume we only want this when there ARE tabs and NO breadcrumb specifically?
