### ISSUE TITLE
Add drag and drop support and ability to add the same topic multiple times at the ACP level

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#345]
This will let admins sort topics and display them how they want. Essentially what ordering nodes allows.

**Comment by LukasWieditz** [comment]
Frontend is fully functional now. Backend is lackluster at the moment, but I'll try to make some more improvements.

**Comment by LukasWieditz** [comment]
Backend Drag & Drop now works, including sorting and deleting items, but I've thrown out nesting for now, as it bugged out at lot. If @kylerc could take a look at it, that'd be awesome.
