### ISSUE TITLE
Ensure there are sufficient tools for both installing and uninstalling Topics

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#346]
Specifically I only have one user story I can think of:

- [x] Assign threads in node X as {primary | secondary} tag Y
- [x] Deleting forum also deletes topic

But give it some thought and make sure there aren't other options you can think of people woiuld need.

**Comment by LukasWieditz** [comment]
I think we have everything that is essential for both.

**Comment by mikecreuzer** [comment]
We do need `Assign threads in node X as {primary | secondary} tag Y` - I mean this is required just for setup

**Comment by LukasWieditz** [comment]
Hm, I might have misunderstood that. You mean you automatically want to assign topics to all threads upon installation?

**Comment by mikecreuzer** [comment]
Not automatically. Just a tool that lets you take an input (some criterion such as forum (even if just forum) and then a way to apply a topic to that criterion (both a primary and a secondary). So this is more of a tool with:

Choose criteria: [node, maybe more later] 
Apply primary tag: [none|any tag]
Apply secondary tags: [list of all tags]

Something like that

**Comment by mikecreuzer** [comment]
I still feel this tool will be needed by people. Updating milestone and adding priority tag. I dont think Topics need anything else, other than this, at the current time.
