### ISSUE TITLE
Mass moderation 'change topics' results in a move topics modal

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#360]
Not sure what to do if this is forced. But causes an issue. If I change topics, I should just get a modal with a filter to choose those topics. Potentially same style modal as create new thread (primary choices, then a search for all others)

<img width="980" alt="screen shot 2018-05-16 at 12 01 01 pm" src="https://user-images.githubusercontent.com/1217271/40131883-d2650f52-5900-11e8-9aaa-dc7ed2cc983e.png">

**Comment by LukasWieditz** [comment]
Seems this was just a copy/paste of the XF thread mover. Functionality is now implemented correctly and working.
