### ISSUE TITLE
Manually performance audit all the add-ons

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#363]
Queries, etc. Lets check this off after we've tested it on some beta user's boards.

Add-ons to check:

- [x] Trending
- [x] Topics
- [x] Bookmarks
- [x] Covers
- [x] Reactions
- [x] Donate
- [x] Post Comments
- [x] Nodes

**Comment by LukasWieditz** [comment]
Add-ons to check:

- [ ] Trending
- [ ] Topics
- [ ] Bookmarks
- [ ] Covers
- [ ] Reactions
- [ ] Donate
- [ ] Post Comments
- [ ] Nodes
