### ISSUE TITLE
[TH] Reactions - More than one reaction can be set per user per post from (at least) mobile

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#364]
Was reported by [Suineg on XenForo](https://xenforo.com/community/threads/th-reactions-paid.134133/post-1251737):
> Steps to reproduce:
> 
> 1. Select a post on mobile,
> 2. press and hold the reactions button to open the pop-up menu,
> 3. rapidly tap two different reactions of different types
> 4. The reactions list will display one reaction.
> 5. Open the "Show all"
> 6. *Sometimes* more than one reaction will be listed
> 
> Suggestion: add a uniqueness constraint in the table definition CONSTRAINT UC_Reaction UNIQUE (post_id,user_id)

![screen shot 2018-05-16 at 3 38 16 pm](https://user-images.githubusercontent.com/32306910/40143097-0fca8a1a-5920-11e8-9c7f-c2583ac7a7d0.png)

**Comment by LukasWieditz** [comment]
A uniqueness constraint is not gonna work here, as it is possible and wanted, that people can add multiple reactions to the same content item, if permissions are configured that way. However a flood check might solve the problem.

**Comment by LukasWieditz** [comment]
I've implemented a 3 seconds flood check for everyone. That should likely improve the situation.

**Comment by Nirjonadda** [comment]
@LukasWieditz Does also fixed [this issue](https://xenforo.com/community/threads/th-reactions-paid.134133/post-1247088)? As well [this issue](https://xenforo.com/community/threads/th-reactions-paid.134133/post-1237272)?

**Comment by LukasWieditz** [comment]
Probably should, yeah.
