### ISSUE TITLE
New profile cover position not saved

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2addon-issues#367]
Add-on Name: Covers

Add-on Version: 1.0.0 Beta 3

XenForo Version: 2.0.6

Operating System (and Version): MacOS High Sierra

Browser Name (and Version): Chrome 66

Summary of issue: After saving new user cover image position, on reload the new position is not saved and the cover returns to its original position.

Detailed steps to reproduce the issue: Set a new cover position, and reload the page.

**Comment by LukasWieditz** [comment]
I am unable to reproduce this on my Win10 machine. @kylerc you think this might be a browser bug (the value not being saved to the input field)?

**Comment by tom-coward** [comment]
Seems to be fixed in latest UI.X update. Not entirely sure what was causing it.

**Comment by tom-coward** [comment]
Encountering this issue again. Can reposition fine and click the 'Save cover' button, which then disappears as you'd expect. However, on page refresh the 'Save cover' button reappears and the new position isn't kept.

**Comment by LukasWieditz** [comment]
The position menu is restarted on page refresh because you're keeping the bit in the url that initiates the position mode on page load.
