### ISSUE TITLE
Member card issue

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2addon-issues#368]
Add-on Name: Covers

Add-on Version: 1.0.0 Beta 3

XenForo Version: 2.0.6

Browser Name (and Version): Chrome 66

Member card styling issue, as shown in screenshot:
![image](https://user-images.githubusercontent.com/34864926/40202822-21af4288-5a1b-11e8-9e06-2769260f6dd5.png)

**Comment by LukasWieditz** [comment]
What exactly is the bug there? I have trouble spotting anything. If you're missing the cover on the member card, have you turned it on the ACP options?

**Comment by tom-coward** [comment]
The empty, redundant space at the bottom of the card. The cover option is disabled.

**Comment by LukasWieditz** [comment]
Ahh, that's not a covers issue. I'll redirect it accordingly!

**Comment by tom-coward** [comment]
Ah sorry. I assume it is somehow related to Covers as I only encounter it with Covers installed.

**Comment by LukasWieditz** [comment]
Not a problem at all, thanks for reporting! See the referenced issue for issue tracking.
