### ISSUE TITLE
Update UIX icon and add tooltip that reads "View Documentation"

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#37]
@nikkiradloff we need a new icon 
<img width="203" alt="screen shot 2017-10-30 at 12 13 41 pm" src="https://user-images.githubusercontent.com/1217271/32184907-c80346ea-bd6b-11e7-8eb1-b3e40d1509a7.png">

Then assign to jake.

**Comment by nikkiradloff** [comment]
![uix2_icon](https://user-images.githubusercontent.com/15836402/32185021-05c19e6e-bd6c-11e7-9ae3-f16460f0fb02.png)

**Comment by JakeBooher** [comment]
You don't click the icon to view documentation, you click the link that says "View Documentation"
