### ISSUE TITLE
Covers - `No source file for cover set`

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2addon-issues#377]
`LogicException: No source file for cover set src/addons/ThemeHouse/Covers/Service/Image.php:250`

**Stack trace:**
`
#0 src/addons/ThemeHouse/Covers/Pub/Controller/Cover.php(84): ThemeHouse\Covers\Service\Image->updateCoverImage()

#1 src/XF/Mvc/Dispatcher.php(249): ThemeHouse\Covers\Pub\Controller\Cover->actionImage(Object(XF\Mvc\ParameterBag))

#2 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Cove...', 'Image', 'json', Object(XF\Mvc\ParameterBag), '', Object(ThemeHouse\Covers\Pub\Controller\Cover), NULL)

#3 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))

#4 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()

#5 src/XF.php(328): XF\App->run()

#6 index.php(13): XF::runApp('XF\\Pub\\App')

#7 {main}
`

**Comment by LukasWieditz** [comment]
Happens when someone renames an input field on the frontend. Probably wanna build a check in for that.
