### ISSUE TITLE
XF\Db\Exception: MySQL statement prepare error [1054]: Unknown column 'thtrending_positive_rating_count' in 'field list' src/XF/Db/AbstractStatement.php:21

### ISSUE THREAD

**Issue by andruswh** [Audentio/xf2addon-issues#378]
Add-on Name: TH Trending

Add-on Version:1.0.0a

XenForo Version:2.0.6a

Operating System (and Version): PC: Windows 10; Server:  CENTOS 7.5 standard [web] v68.0.38 

Browser Name (and Version): Any/All

Summary of issue:  I installed the  Xenforo's Media Gallery 2.0.4.  I get the error below when I try to attempted to upload media files (images) to it (See Screenshots below).  Xenforo's Support said that I needed to get with the author of the THTrending Addon. 

<code>

    XF\Db\Exception: MySQL statement prepare error [1054]: Unknown column 'thtrending_positive_rating_count' in 'field list' src/XF/Db/AbstractStatement.php:212 

    Generated by: Andrus May 19, 2018 at 11:48 PM 

Stack trace

INSERT  INTO `xf_mg_media_item` (`media_hash`, `media_type`, `user_id`, `username`, `category_id`, `media_state`, `title`, `media_date`, `exif_data`, `rating_weighted`, `rating_avg`, `media_id`, `description`, `last_edit_date`, `album_id`, `ip_id`, `view_count`, `watermarked`, `custom_fields`, `warning_id`, `warning_message`, `position`, `imported`, `thumbnail_date`, `custom_thumbnail_date`, `tags`, `last_comment_date`, `last_comment_id`, `last_comment_user_id`, `last_comment_username`, `rating_count`, `rating_sum`, `thtrending_positive_rating_count`, `thtrending_positive_ratings_views_per_minute`, `thtrending_positive_ratings_per_minute`, `thtrending_views_per_minute`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
------------

#0 src/XF/Db/Mysqli/Statement.php(196): XF\Db\AbstractStatement->getException('MySQL statement...', 1054, '42S22')
#1 src/XF/Db/Mysqli/Statement.php(39): XF\Db\Mysqli\Statement->getException('MySQL statement...', 1054, '42S22')
#2 src/XF/Db/Mysqli/Statement.php(54): XF\Db\Mysqli\Statement->prepare()
#3 src/XF/Db/AbstractAdapter.php(79): XF\Db\Mysqli\Statement->execute()
#4 src/XF/Db/AbstractAdapter.php(160): XF\Db\AbstractAdapter->query('INSERT  INTO `x...', Array)
#5 src/XF/Mvc/Entity/Entity.php(1389): XF\Db\AbstractAdapter->insert('xf_mg_media_ite...', Array, false)
#6 src/XF/Mvc/Entity/Entity.php(1121): XF\Mvc\Entity\Entity->_saveToSource()
#7 src/addons/XFMG/Service/Media/Creator.php(235): XF\Mvc\Entity\Entity->save()
#8 src/XF/Service/ValidateAndSavableTrait.php(40): XFMG\Service\Media\Creator->_save()
#9 src/addons/XFMG/Pub/Controller/Media.php(747): XFMG\Service\Media\Creator->save()
#10 src/XF/Mvc/Dispatcher.php(249): XFMG\Pub\Controller\Media->actionSaveMedia(Object(XF\Mvc\ParameterBag))
#11 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('XFMG:Media', 'SaveMedia', 'json', Object(XF\Mvc\ParameterBag), 'xfmg', Object(XFMG\Pub\Controller\Media), NULL)
#12 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#13 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#14 src/XF.php(328): XF\App->run()
#15 index.php(13): XF::runApp('XF\\Pub\\App')
#16 {main}
</code>

Detailed steps to reproduce the issue:  Attempting to upload media through Xenforo's Media Gallery Addon

Upload any screenshots related to the issue below

![image](https://user-images.githubusercontent.com/34595575/40283924-05b62280-5c4c-11e8-9c47-7fa85457f5e8.png)

![image](https://user-images.githubusercontent.com/34595575/40283929-204f797a-5c4c-11e8-936d-079d6345b695.png)

**Comment by LukasWieditz** [comment]
That happens when you install the XFMG after trending. We can't hook into the XF add-on installation process, so you gotta install the XFMG first. Reinstall trending to fix the issue.

**Comment by andruswh** [comment]
Just to be sure, so I need to uninstall Trending, then reinstall XFMG, and then reinstall Trending.  I need not make any manual database changes then,  correct?
