### ISSUE TITLE
Bookmark node should have a setting to show 'My bookmarked nodes' at the top above the forum list (as a widget perhaps?)

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#382]
Currently it sticks within the category but to me it should stick just at the top.
<img width="775" alt="screen shot 2018-05-21 at 2 47 24 pm" src="https://user-images.githubusercontent.com/1217271/40326711-e3f51e48-5d05-11e8-975b-24870552f8a9.png">

**Comment by Ian-Hitt** [comment]
<img width="842" alt="screen shot 2018-05-23 at 12 54 41 pm" src="https://user-images.githubusercontent.com/15836384/40442138-7bff8d6c-5e88-11e8-9415-8d12d95dcd60.png">

**Comment by Ian-Hitt** [comment]
@LukasWieditz need node type for icon, and also the icon form TH Nodes if possible. widget is called Bookmarked Nodes, template is th_widget_bookmarks_bookmarkNodes

**Comment by LukasWieditz** [comment]
You haven't made a PR yet.
