### ISSUE TITLE
Ability to 'collapse' or maybe even 'pin' styles

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#383]
Especially useful even just for our demos, but the non-nesting makes large amounts of themes look odd. Even if we can add a `level-n` class to each theme like XF1 did, but better yet if we can collapse with an arrow. Worth noting this should maybe only apply when the parent themes are not hidden.

Not sure if we can add some subtle enhancements to UIX add-on.  Suggestions welcome.

<img width="901" alt="screen shot 2018-05-21 at 2 53 19 pm" src="https://user-images.githubusercontent.com/1217271/40327020-ff5707d6-5d06-11e8-93ee-c819c476e7d2.png">

**Comment by mikecreuzer** [comment]
Image would be nice as well, can just be some conditional on whether a style property exists so we can give ours a thumnail.

**Comment by JakeBooher** [comment]
Can't really use a style property since you can only use style properties for the currently active style

**Comment by mikecreuzer** [comment]
@LukasWieditz says he has a tool for this under his admin tools system. At a later date after UIX Pro is done, can discuss. For now will close.
