### ISSUE TITLE
Setting to 'merge' watch/bookmark triggers (since the modal contains both)

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#390]
Just saves some space since the watch trigger is current not necessary. Small enhancement.

**Comment by LukasWieditz** [comment]
It's small in look but large in functionality. The backend can currently only handle one of these cases at a time. Is this really needed for the initial UI.X Pro release?

**Comment by LukasWieditz** [comment]
I can't really think of an Icon that represents both with their states at the same time either. I don't think merging this is a good idea.

**Comment by mikecreuzer** [comment]
Well.  Its just redundant. Arguably since its in the bookmark widget its not needed, but meh. I guess we can close, its not a huge deal.
