### ISSUE TITLE
[TH] Reactions - Moderator edit not aligned under reactions

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#391]
Previous bug, Moderator edit not aligned under reactions. This issue fixed in 1.0.11 Patch Level 1 then this bug happened again in 1.0.12?

![screenshot00080](https://user-images.githubusercontent.com/6899856/40433070-6c70a764-5eab-11e8-875a-679a3b594663.png)

**Comment by Nirjonadda** [comment]
Please make one thread Close, Sticky and watched.

![screenshot00082](https://user-images.githubusercontent.com/6899856/40439469-4daa5dc4-5ebb-11e8-991c-27f87fad0130.png)

**Comment by lilalien** [comment]
I can't reproduce this problem myself in ui.x, nor my custom offshoot...

**Comment by lilalien** [comment]
Oh I can reproduce this in the default XF style though!

**Comment by mikecreuzer** [comment]
Ive spent the last 20m trying to debug this and cannot simply replicate it on default or any of our themes. What browser do you guys have and is there any way you guys have a live demo?

**Comment by Nirjonadda** [comment]
Yes have live domo but where can send login info?

**Comment by Nirjonadda** [comment]
@mikecreuzer I have send PC in xenforo about demo login.

**Comment by Nirjonadda** [comment]
@LukasWieditz This issue also happened with Topics add-on.

![screenshot00093](https://user-images.githubusercontent.com/6899856/40488358-e2c23ac0-5f66-11e8-850a-f8e96a6fba95.png)

**Comment by mikecreuzer** [comment]
Removing cannot replicate since @lilalien confirmed it. I cannot still

**Comment by lilalien** [comment]
Here's a screenshot...

Latest stable chrome, latest stable windows 10. Xenforo Default Style.

![reactions_moderator_edit_alignment_issues](https://user-images.githubusercontent.com/35111972/40559160-d1579aba-6023-11e8-8dcf-5e717c82e551.png)

**Comment by Nirjonadda** [comment]
@mikecreuzer Do you checked this issue in my test site? I have send login info in xenforo.

**Comment by Nirjonadda** [comment]
Very strange things ! I am from mozilla firefox latest version with windows 8.1

![screenshot00132](https://user-images.githubusercontent.com/6899856/40736905-977b2314-643f-11e8-889b-c58ae9b26e1d.png)

**Comment by Nirjonadda** [comment]
@mikecreuzer Just one more thing, Please can you do make one thread watched?

**Comment by lilalien** [comment]
I can still confirm the edit link alignment being all over the place on default xf style in latest Chrome in Windows 10.

**Comment by mikecreuzer** [comment]
We are all on OS so maybe thats why. Ill debug on my windows partition. This didn't make the package update unfortunately.

**Comment by lilalien** [comment]
Makes sense.. There's been some recent difficulties with reproducing things, so I recommend since Windows is the primary *desktop* OS I'd recommend being able to test there too.

I'll always be helping to test there for you as well! I know what I'm doing, and always test against default styles and several browsers (chrome, firefox, edge). I also have an iPhone and an iPad. ;)

**Comment by mikecreuzer** [comment]
Agreed. Windows vs OS issues are rare at least with respect to what we're doing, doesn't happen to often. But yeah will debug this.

**Comment by LukasWieditz** [comment]
I cannot reproduce this on Latest Public or Canary Chrome on Win10. Could be fixed through some indirect changes already.
