### ISSUE TITLE
When editing thread cover background color, it adds a padding to the top - wondering if this should only happen for images

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#394]
<img width="514" alt="screen shot 2018-05-23 at 12 08 12 pm" src="https://user-images.githubusercontent.com/1217271/40439902-faa051ee-5e81-11e8-8812-25fbaeac99d3.png">

**Comment by LukasWieditz** [comment]
Ian wanted to remove it, but I feel like it's important to keep it visually equivalent to upload an image that has just this color. We don't want to introduce a third type of layout style (one without anything, one with cover, one with only color) and make it even more confusing to get a hold of the titlebar.

**Comment by Ian-Hitt** [comment]
I still think it should be for images only. The only point of adding the padding is to show more image. nobody gives a damn about showing more color :)

**Comment by Ian-Hitt** [comment]
@LukasWieditz to do this I'll need more helper classes, can you add `cover-hasImage`? ill add css now

**Comment by LukasWieditz** [comment]
I still am against changing this. No one is gonna understand why color only gives you no padding and single-color-images do.

**Comment by Ian-Hitt** [comment]
they dont need to understand why. We're giving them the best experience, that's all they need to know.

**Comment by LukasWieditz** [comment]
It's not the best experience to introduce a third layout that makes it even more confusing to spot the title for the eye. This is absolutely counterproductive from a user experience and interface design perspective.

**Comment by mikecreuzer** [comment]
Its a waste of space and not needed. The only time the padding is added is on image. A better argument then is not letting people change color of their thread, that seems even goofier. What if we turn that ability off by default? Same with presets (especially if there aren't any)

Then I care less. :P

**Comment by mikecreuzer** [comment]
Changing color of thread conflicts with topics anyway.

**Comment by LukasWieditz** [comment]
It'll override topics, or at least should. I personally don't like the idea of turning of colors for threads only, that'll involve writing massive workarounds. Either remove it all together or keep it altogether imo. If you want to remove the padding, so be it, but I still think that'll lower the overall SUS

**Comment by mikecreuzer** [comment]
lol I havent heard SUS used in years. I doubt itll be noticed by anyone but us. Since you feel adamantly and I think its just wrong but not crazy important, then I trust your judgement. 

I do think editing thread colors is silly anyway, so can we disable it by default?
