### ISSUE TITLE
Bookmarks icon kinda meh on default style

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#396]
<img width="421" alt="screen shot 2018-05-23 at 12 24 18 pm" src="https://user-images.githubusercontent.com/1217271/40440664-4b79418c-5e84-11e8-8eeb-0de62fd809e9.png">

**Comment by LukasWieditz** [comment]
I've added a `button--bookmark` class @Ian-Hitt, you can use that for styling. Basically needs to have line height of 1.4, but that breaks the UI.X styling.

**Comment by Ian-Hitt** [comment]
@LukasWieditz markup is just wrong you silly girl :)

**Comment by LukasWieditz** [comment]
*giggles girlishly*
