### ISSUE TITLE
Apparently no way to edit/moderate donate messages?

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#399]
I think that these can be public right? I mean we dont have a donate page at the moment its just campaign, but at least people can see it there.

**Comment by LukasWieditz** [comment]
Added permission to edit donation messages (own and/or all) including max. edit time and the ability to report donations to add them to the moderation report queue.

**Comment by LukasWieditz** [comment]
It's all working fine for me @mikecreuzer. As @Ian-Hitt had quite some trouble updating for some reason, I wouldn't be surprised if there's some heavy issues going on with his installation.

**Comment by mikecreuzer** [comment]
Error gone now, I now have permission.

But not seeing donate message edit button.

<img width="504" alt="screen shot 2018-05-29 at 1 10 20 pm" src="https://user-images.githubusercontent.com/1217271/40676902-ba741014-6341-11e8-9c13-d1fd796100f6.png">

**Comment by LukasWieditz** [comment]
Closing this for now, feel free to re-open or create a new ticket if this is an issue on a clean installation.
