### ISSUE TITLE
[TH] Covers - Use covers on resources

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#404]
Covers permissions > Use covers on resources, Should no be show if resources are not installed.

![screenshot00085](https://user-images.githubusercontent.com/6899856/40443243-ffdbb466-5ec5-11e8-8b77-bc11abdded5d.png)

**Comment by mikecreuzer** [comment]
Hmm Im not sure if this is possible. @LukasWieditz do you know?

**Comment by mikecreuzer** [comment]
Talked with Lukas and he says its not worth the effort. It just wont do anything if you do not have resources. A bug of sorts, but just the way XenForo is built.

**Comment by Nirjonadda** [comment]
@LukasWieditz Sure its can be fix. See [here](https://xenforo.com/community/threads/change-content-owner.142141/post-1245233)

**Comment by LukasWieditz** [comment]
It can be fixed with a dirty workaround that we're not considering to apply.
