### ISSUE TITLE
[TH] Post Comments - AJAX load

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#407]
Add support AJAX load editor box after clicking reply button.

**Comment by LukasWieditz** [comment]
It already does that.
https://gfycat.com/GoodTastyChipmunk

**Comment by Nirjonadda** [comment]
@LukasWieditz But my version are not work.

See here: https://giant.gfycat.com/SnivelingEverlastingGermanwirehairedpointer.webm

**Comment by Nirjonadda** [comment]
@LukasWieditz I have browser console.

````
Loading failed for the <script> with source “https://mysite.info/js/themehouse/post-comments/comment.js?_v=75c1bbb0”.
````
