### ISSUE TITLE
[TH] Post Comments - Count messages posted

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#410]
Please add option Post Comments Count messages posted user total.

**Comment by JakeBooher** [comment]
Could you elaborate on what you're referring to?

**Comment by Nirjonadda** [comment]
Count messages posted in toward user total. If enabled, Messages posted in Post Comments will contribute towards the posting user's total messages count.

**Comment by LukasWieditz** [comment]
They do already. They're literally just posts that get displayed differently.

**Comment by Nirjonadda** [comment]
So have enable/disable option for this?

**Comment by LukasWieditz** [comment]
No, they're technically posts, and there's no way to "disable" them from being posts, without hampering with every single XenForo method that deals with posts and that'd still leave add-ons that hamper with them untouched.

**Comment by Nirjonadda** [comment]
So this add-on for spammer for increase the post count?

**Comment by LukasWieditz** [comment]
lol what? It has the same restrictions as normal posts, it is **literally** normal posts displayed in a different way.
