### ISSUE TITLE
[TH] Topics - Some bug

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#411]
Please watch this video: https://giant.gfycat.com/ImpeccableBlondDiamondbackrattlesnake.webm

**Comment by Nirjonadda** [comment]
one more bug, text are 2 line.

![screenshot00089](https://user-images.githubusercontent.com/6899856/40448763-c68929b2-5ed6-11e8-9434-48b2ab331527.png)

**Comment by mikecreuzer** [comment]
We may want to limit the characters and do an ellipses overflow @Ian-Hitt something like 50px?

**Comment by mikecreuzer** [comment]
I have an issue already open on the duplicate. This was more styling I guess, Im only tagging you so you follow but didnt mean to assign.  Since you're involved in that threadbit overflow thing.

**Comment by mikecreuzer** [comment]
There are a few bugs in this so Ill just leave it as is.

**Comment by LukasWieditz** [comment]
The overflow is meant to be, that's intended behaviour. Multiple topics assignments have been fixed today with #393, the nodes list is a bug agreeably, but nodes related, not topics.
