### ISSUE TITLE
Remove bookmark node 'options' (comment out)

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#412]
When I bookmark something, just bookmark it, no need for a modal with options. No need for sticky or public or notes. It is or it isnt.

**Comment by LukasWieditz** [comment]
I do agree that it's clutter, but it's functionality that we've advertised and sold already. People will wonder where it went and why we cut it out.

**Comment by mikecreuzer** [comment]
Well let's just add a setting to remove the modal. Off by default as well I don't think it was neither advertised nor a feature that will be missed.

**Comment by LukasWieditz** [comment]
It's literally the first screenshot on the product page. But an option sounds good.
