### ISSUE TITLE
Remove the little action hover thing on the reactions trigger (make it a style property I guess?)

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#413]
@Ian-Hitt note that there is like a hover on icon AND on the button wrapper. Remove the hover on icon completely then wrap hover on button wrapper in a Hover style property boolean. Some people will want it, but to me it kinda looks janky.

**Comment by LukasWieditz** [comment]
@mikecreuzer I can't find the spot you describe. 

![rcvnxp8](https://user-images.githubusercontent.com/38475165/40721642-61d7893e-641a-11e8-8565-76c0f4ddbd9f.png)
We're talking about this icon, right? If so, only the button has a hover property, the inner html has none.

**Comment by mikecreuzer** [comment]
There is a double hover. One on the icon and one on the button. They both increase in size. I want neither to increase in size.

**Comment by mikecreuzer** [comment]
![untitled](https://user-images.githubusercontent.com/1217271/40734222-6775a578-63fd-11e8-8011-b1ff04044a32.gif)

**Comment by LukasWieditz** [comment]
Ahhh, I see. Alright!
