### ISSUE TITLE
[TH] Donate - Incorrect box

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#414]
When Goal amount are not set then Total amount box should not be show.

![screenshot00090](https://user-images.githubusercontent.com/6899856/40449071-bb4a3f5e-5ed7-11e8-909e-d0abefbc4258.png)

**Comment by LukasWieditz** [comment]
The "total amount" is the number of dollars that have been donated in total by all donators, not the "goal amount". This is working as intended.

**Comment by Nirjonadda** [comment]
So have enable/disable option for this "total amount" show?

**Comment by LukasWieditz** [comment]
I don't see a reason to disable it. You can edit the template if you want to remove it. Otherwise it'll just display how much has been donated in total.

**Comment by Nirjonadda** [comment]
Manually template edit is bad thing, Any functionality should have a option for choice, not force to use.

**Comment by LukasWieditz** [comment]
Considering that there is an infinite number of possible customization wishes, we literally can't have an option for everything, so editing templates is a good way, using CSS is an even better way.

**Comment by Nirjonadda** [comment]
Yes "total amount" collected should have a option because some one are not like its show in publicly.

**Comment by LukasWieditz** [comment]
What's gonna keep them from just summing up the donations that're listed below?

**Comment by Nirjonadda** [comment]
Yes donations listed OK but should have a option Total amount show or not.
