### ISSUE TITLE
Nodes - Node footer left and right

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#417]
Small change here, but 'More' looks odd now that we have other triggers. I feel like actions should be on left and the "more arrow" but just as an arrow icon, more can be tooltip I guess or something, would be better.

Small change, and I know it was like this in the design.

Arrow is redundant and just there to fill space 🤷‍♂️

**Comment by LukasWieditz** [comment]
@Ian-Hitt this mostly goes for the default style. It looks acceptable in UI.X
