### ISSUE TITLE
Topics - unable to deselect topic

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#418]
I can replicate it by:

Going to say new posts. Setting a topic.

Then click the tab bar away to say Trending. 

Then try clearing or deselecting, and refresh if you want, it will keep that original set topic.

**Comment by LukasWieditz** [comment]
You mean the topic filter bars? They keep different states for different positions. The backend will save your configuration for trending separate from the one for new posts.

**Comment by mikecreuzer** [comment]
I mean I dont see why they should keep different positions first of all.

Second, even if that was the case, this is still causing a bug where you simply cannot deselect it. The way to do it is to click on a topic view, then go back.

**Comment by LukasWieditz** [comment]
I do see that it doesn't reselect on a page reload if that's what you mean? It used to work before, @Ian-Hitt is the last person that touched this.

**Comment by Ian-Hitt** [comment]
@LukasWieditz I didn't touch this. this is a JS issue. Playing musical re-assign chairs? @kylerc :)

**Comment by LukasWieditz** [comment]
It's not a JS issue Ian, the classes that determine if the topic is selected upon page load are not touched by js at all.
