### ISSUE TITLE
[TH] Covers - cover preset set none

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#422]
cover preset set none are not working. Still are not reset to none.

![screenshot00095](https://user-images.githubusercontent.com/6899856/40491215-c77e754c-5f6d-11e8-9d66-81bd8319b0a1.png)

**Comment by LukasWieditz** [comment]
This works as expected. Choosing "none" will not override a custom cover, it will just reset the selected cover preset.

**Comment by mikecreuzer** [comment]
"defult"?

**Comment by Nirjonadda** [comment]
Defult color in blue but when set to none then this thread are reset to no color or no thread cover?
