### ISSUE TITLE
[TH] Nodes - create threads, watch, and bookmark icon

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#424]
create threads, watch, and bookmark icon are not showing correctly, Also watch icon tooltip are missing.

![screenshot00097](https://user-images.githubusercontent.com/6899856/40492489-dcb5b9e0-5f70-11e8-82b2-d45f4518e25d.png)

**Comment by mikecreuzer** [comment]
I think the nodes beta we posted is already bout of date and we have this fixed locally. I'll wait for Ian to approve but should be fixed.

**Comment by Ian-Hitt** [comment]
Correct, already fixed.
