### ISSUE TITLE
Replace topics icon in ACP

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#435]
`fa-th-list` is somewhat better
<img width="32" alt="screen shot 2018-05-29 at 12 43 33 pm" src="https://user-images.githubusercontent.com/1217271/40675638-eb2f4326-633d-11e8-80eb-26eac1f4fe01.png">

**Comment by mikecreuzer** [comment]
`fa-th` isnt bad either
<img width="22" alt="screen shot 2018-05-29 at 12 44 28 pm" src="https://user-images.githubusercontent.com/1217271/40675688-0c317058-633e-11e8-9f4a-c281ead1f5c9.png">

**Comment by LukasWieditz** [comment]
I've queried @nikkiradloff about this. She has suggested fa-th-list, but I think it's just as good or bad as tags. I'd rather like to have something unique. We can use customized .svgs here without any trouble, so there's generally no need to take "whatever barely fits" from FontAwesome

**Comment by mikecreuzer** [comment]
Ah OK sounds good. Yeah I dont like tags as its confusing

**Comment by LukasWieditz** [comment]
![rjixsnk](https://user-images.githubusercontent.com/38475165/40781250-7192bb3e-64db-11e8-8042-533d9d2246f0.png)
I've used `fa-th-large` for now.
