### ISSUE TITLE
[TH] Post Comments - Disable add-on

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#438]
If Disable add-on then post no are not correctly showing, as well page no are not working.

![screenshot00131](https://user-images.githubusercontent.com/6899856/40686309-33fd8884-6397-11e8-9154-6124f5a156c2.png)

**Comment by mikecreuzer** [comment]
This is by design, to keep the order of the posts. Otherwise replies would be made out of context. For ex (# represents order in which they were posted):

#1 What color is the sky
-----#3 Blue
#2 I dont know, what color is grass?

Without this, the outcome would be:
```
What is the color of the sky?
I don't know what color is grass
Blue
```

**Comment by Nirjonadda** [comment]
But Its best when add-on disabled then all post back to xenforo default.

Also why page no are not working? Can not go to next page.

**Comment by JakeBooher** [comment]
You can rebuild the counter in Toosls -> rebuild caches -> Rebuild threads (make sure to tick the box to rebuild post positions)

pagination is possibly broken because of the positioning issue, rebuild that and see if it resolves this issue
