### ISSUE TITLE
Latest post without latest posts needs padding

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#441]
We need to be using the standard components XenForo gives us when building components like this, so these little edge cases dont keep popping up

<img width="359" alt="screen shot 2018-05-30 at 3 08 28 pm" src="https://user-images.githubusercontent.com/1217271/40744874-8299d52c-641b-11e8-8d1b-017e64f6b919.png">

**Comment by LukasWieditz** [comment]
FWIW, we use XenForo components, they're just so nontransparent, that stumbling over these crappy inheritance class inheritance issues is kind of unavoidable.
