### ISSUE TITLE
Instead of oops page for trending without threads, can we just say no trending threads?

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#442]
<img width="430" alt="screen shot 2018-05-30 at 3 11 39 pm" src="https://user-images.githubusercontent.com/1217271/40744972-ce9f375a-641b-11e8-9bbb-5cbd13ac026f.png">

**Comment by LukasWieditz** [comment]
Was just a leftover from the installation quirks. Working now.
