### ISSUE TITLE
Extra margin on arrow (now that text is gone I assume)

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#443]
<img width="189" alt="screen shot 2018-05-30 at 3 13 41 pm" src="https://user-images.githubusercontent.com/1217271/40745077-17629658-641c-11e8-885e-47b8dc107f92.png">

**Comment by LukasWieditz** [comment]
Where do we find that arrow?

**Comment by LukasWieditz** [comment]
Took me quite a while to find this... Forum overview, nodes footer. Styling comes from one of the UI.X templates and overwrites the default style, I guess, @Ian-Hitt
