### ISSUE TITLE
[TH] Covers - forum cover

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#455]
How to getting forum have a cover? do you have option for this?

![screenshot00139](https://user-images.githubusercontent.com/6899856/40808090-5f2144fc-6526-11e8-81a0-c344c89b60ce.png)

**Comment by Nirjonadda** [comment]
As well thread cover image used from node image. does not find out any option for control.

**Comment by LukasWieditz** [comment]
That's a job for our Nodes add-on, not for covers. Covers is meant for users of your website.
