### ISSUE TITLE
[TH] Covers - node title are not visible

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#457]
node title are not visible, need some improvement.

![screenshot00141](https://user-images.githubusercontent.com/6899856/40808612-0a298106-6528-11e8-93cb-8dcfe509a009.png)

**Comment by LukasWieditz** [comment]
That area you screenshotted isn't even meant for covers. Titles on covers are readable just fine, when used in the right places.

![xvf5jxl](https://user-images.githubusercontent.com/38475165/40815825-7db45b3e-6549-11e8-8105-c2ee4191ce52.png)
