### ISSUE TITLE
[TH] Covers - Member popup

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#459]
Member popup are not showing correctly.

![screenshot00143](https://user-images.githubusercontent.com/6899856/40809617-6640c000-652b-11e8-9f98-82617e6366cc.png)

**Comment by LukasWieditz** [comment]
@Ian-Hitt I lived under the impression that you had this issue fixed. Why is this still a thing even though the other ticket is closed?
