### ISSUE TITLE
QAForums - Fatal error (`getNewPostsReply`)

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2addon-issues#460]
As per title:
`Fatal Error: Access level to ThemeHouse\QAForums\XF\Pub\Controller\Thread::getNewPostsReply() must be public (as in class ThemeHouse\PostComments\XF\Pub\Controller\Thread)`

Noticeable that this seems to have been flagged from a thread that isn't in a Q&A enabled forum.

**Comment by LukasWieditz** [comment]
Can you provide us with the full stack trace of this error please?

**Comment by LukasWieditz** [comment]
Hm, weird. Has this been a one-time error or is it showing up constantly? The function listed in the error does have the same visibility as the original XenForo function, so in pure theory, this error shouldn't be possible. If you have the request state, or even better, steps to reproduce it, that'd be helpful.

**Comment by LukasWieditz** [comment]
Only just noticed that this is actually an error in post comments, well hidden in the error message. Got that sorted.
