### ISSUE TITLE
Template error on default style

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2addon-issues#462]
Error appears on forum homepage.

![yyyfy1e](https://user-images.githubusercontent.com/38475165/40839590-99644704-65a3-11e8-9524-be356c5fb24a.png)

```
Template errors
Template public:uix_icons.less: Template public:uix_icons.less is unknown (src\XF\Template\Templater.php:583)
Template public:uix_icons.less: Macro public:uix_icons.less:icon is unknown (src\XF\Template\Templater.php:557)
```

**Comment by Ian-Hitt** [comment]
This is because the UI.X add-on has a widget that uses an icon from UI.X theme. Should we not do that then? I presume its safe to say if they have UI.X add-on they also have the theme

**Comment by JakeBooher** [comment]
They may also have other themes
