### ISSUE TITLE
Covers actions (save, cancel) showing up when not editing a cover

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#477]
<img width="802" alt="screen shot 2018-06-04 at 1 02 19 pm" src="https://user-images.githubusercontent.com/15836384/40933580-859fc71a-67f7-11e8-8dc6-a6c68336cc4e.png">

**Comment by Ian-Hitt** [comment]
Looks like this happens in UI.X Pro, but not UI.X, and I have no idea why. No template mods are failing in Pro, and there are no customized templates in Pro either.

**Comment by LukasWieditz** [comment]
When you upload a cover, you automatically go into position mode, check the url.

**Comment by LukasWieditz** [comment]
![l68ts1w](https://user-images.githubusercontent.com/38475165/40979870-54c632ce-68d7-11e8-8d0b-907646f4965e.png)

**Comment by mikecreuzer** [comment]
This happens when just visiting the thread as well.
