### ISSUE TITLE
TH Donate: Multiple campaigns view is lack-luster

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#479]
- [x] Deadline (if it recurs, the deadline is the time from when it recurs)
- [x] Status bar (percentage bar, with animation, just like on single but a small version)
Format: `$40 of $1000 goal (wrapped in a status bar)`
- [x] Add support for an icon or image (then show this on the single page too) -> I think like profile page style size at like 512x512 or something
- [x] Padding issue (see screenshot)

<img width="1394" alt="screen shot 2018-06-04 at 2 42 42 pm" src="https://user-images.githubusercontent.com/1217271/40938035-339ca758-6806-11e8-80b0-62f9fce33731.png">

- [x] View/donate call to action button to either a quick pay modal OR the view itself I guess - one or the other is fine but I think a quick modal is ideal

**Comment by LukasWieditz** [comment]
References #558

**Comment by LukasWieditz** [comment]
@Ian-Hitt hooked you up with some icons for campaigns. You get four sizes: xs (64x64), s (128x128), m (256x256) and l (512x512). Called with `{{ thdonate_campaign_icon($campaign, 'mySizecodeHere') }}` in the template of your choice..
