### ISSUE TITLE
Small visual to Topics Layout editor

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#480]
What we started with:

<img width="1214" alt="screen shot 2018-06-04 at 5 01 47 pm" src="https://user-images.githubusercontent.com/1217271/40944060-013316ae-6819-11e8-8f14-12d90071a127.png">

All in all, it was confusing the first time I used it. Here are some changes Id like to see:

- [x] (1) Preview mode is on the left, not the right. This is just a normal UX pattern.
- [ ] (2) Selectable should be more in a block or widget, modal, etc. Having them side by side looks odd. Worst case just need to look a bit different (@LukasWieditz know of any sidebars in XF ACP? Couldnt find one)
- [x] (3) Make topics not look like inline labels, but rather blocks. So they are easier to click, and look bigger when moving around. This will help the visuals of the page a bit more. Ill do a screenshot of roughly what I thought looked better:

<img width="799" alt="screen shot 2018-06-04 at 5 00 03 pm" src="https://user-images.githubusercontent.com/1217271/40943989-bfe3f970-6818-11e8-94c1-556984c2471f.png">

- [x] (4) Selectable/active topics headings are oddly large and wont be necessary once item 2 above is done
- [x] Title at the top says 'XenForo' should just say 'Topic layout'
- [x] Would like a page description of something like:

```This will allow you to modify the order of the widgets, and in some cases, a way to collapse topics of child or lesser importance.``` (suggestions welcome on this)
- [x] Add a little 'drag' icon to the ones that can be dragged `<i class="fa fa-bars"></i>`
<img width="484" alt="screen shot 2018-06-04 at 4 56 50 pm" src="https://user-images.githubusercontent.com/1217271/40943883-57ed6298-6818-11e8-9de5-64fd23f75681.png">

- [x] Odd padding on button? Wrong footer submit code used?

<img width="738" alt="screen shot 2018-06-04 at 4 55 07 pm" src="https://user-images.githubusercontent.com/1217271/40943799-1469f496-6818-11e8-877c-1475d764d08a.png">

**Comment by LukasWieditz** [comment]
That's the right markup on the submit button, it always looks this shitty because it's aligned to the form columns.

**Comment by LukasWieditz** [comment]
Haven't seen any sidebar elements on the ACP, not that I can think of. Shouldn't be too hard to just do two blocks and show them side by side with custom css though.

**Comment by mikecreuzer** [comment]
As none of this takes more than a few seconds (if you get stuck on the 3 lines of CSS lmk) assigning back as Ian is on some other things atm

**Comment by mikecreuzer** [comment]
Item 3 requires CSS, the rest is more just small modification to HTML/using XF content vars. That css is `display: block; padding: 10px;` on the label (instead of display: inline-block;)
