### ISSUE TITLE
[TH] Bookmarks - Icon on other style

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#484]
Add development improvement update for other style. Icon are not showing correctly.

![screenshot00171](https://user-images.githubusercontent.com/6899856/41062279-acac9c54-69d5-11e8-825a-bb2609cd22d6.png)

**Comment by Nirjonadda** [comment]
![screenshot00173](https://user-images.githubusercontent.com/6899856/41063356-b419084e-69d8-11e8-840d-30604a2d6ca7.png)

**Comment by Nirjonadda** [comment]
> Which theme/is there a link you have?

https://xenforo.com/community/resources/uniform.5944/

**Comment by mikecreuzer** [comment]
It will be hard to debug even just knowing the theme. I copied the HTML in and it works fine. So this may be something fixed at the moment. Please do re-open if you find it after we do the next beta update.
