### ISSUE TITLE
Fix filterbar padding and add colors for topics

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#490]
Not sure who to assign just tagging both for now. Filter bar padding is wrong, and each filtered topic Id like to keep the color if possible. Even if its just text color. Can be the BG as well, just like a normal label.

**Comment by kylerc** [comment]
@Ian-Hitt I did a bit on this, but you should be able to do whatever you need in the `thtopics_topic_macros.html` > `topic__filters_list` macro after my next PR.
