### ISSUE TITLE
Topic in titlebar still links to topic page - where to link?

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2addon-issues#492]
When having a thread open and clicking on one of the topics, we still get redirected to the dedicated topic page. Do we want to:
1.  Keep it that way
2. Remove the link entirely
3. Link somewhere else (where?)

**Comment by Ian-Hitt** [comment]
@mikecreuzer Agreed, should link back to "golden page" with that topic selected

**Comment by LukasWieditz** [comment]
So in other words just to the default forum landing page?

**Comment by mikecreuzer** [comment]
Yes
