### ISSUE TITLE
Thread answered icon, make that checkmark green

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#501]
<img width="142" alt="screen shot 2018-06-08 at 9 53 11 am" src="https://user-images.githubusercontent.com/1217271/41164862-ca9e96e0-6b01-11e8-9c25-3d8b963e0f88.png">

Go on, pick your own green color

**Comment by JakeBooher** [comment]
#00FF00 you're welcome

**Comment by LukasWieditz** [comment]
Wait, what exactly am I supposed to do @mikecreuzer ?

**Comment by mikecreuzer** [comment]
color: someGreen;

on that checkmark icon

**Comment by LukasWieditz** [comment]
#8BC34A for answered, #f44336 for unanswered @mikecreuzer ?

**Comment by mikecreuzer** [comment]
Perfect
