### ISSUE TITLE
[TH] Donate - issue with Stripe's apple pay support

### ISSUE THREAD

**Issue by JakeBooher** [Audentio/xf2addon-issues#504]
https://xenforo.com/community/threads/th-donate-paid.145264/page-8#post-1259510

**Comment by LukasWieditz** [comment]
Cannot replicate this, seems to work fine for me.

**Comment by LukasWieditz** [comment]
Closing this for now, as we're unable to reproduce it. As he described it as "not showing up", he might simply have not selected it in the backend as available payment provider.
