### ISSUE TITLE
[TH] Covers - Random text in cover on default stye

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#511]
Random text is only seen when you first upload your own image once you install Covers for the first time.
![screen shot 2018-06-12 at 4 20 33 pm](https://user-images.githubusercontent.com/32306910/41318024-9b8243e4-6e5c-11e8-92f9-8e65c3eda6ec.png)

**Comment by LukasWieditz** [comment]
Apparently already fixed, but unfortunately PRed after we built the final release file.
