### ISSUE TITLE
[TH] Covers - User criteria

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#512]
User criteria are not work, I set User is an administrator but its still using for all member.

**Comment by LukasWieditz** [comment]
You talking about default presets (which are per content type, user criteria do not apply here) or the preset selector in the frontend?

**Comment by Nirjonadda** [comment]
Both, Used in default presets and can be use in front.

**Comment by LukasWieditz** [comment]
For default, that is expected. As explained above, they're per content type only, as it wouldn't be efficient to check criteria each time we apply the default and there's no way to determine which one to pick when a user meets both, either.

For frontend preset selection, criteria are working fine for me, cannot reproduce any issues there.
