### ISSUE TITLE
[TH] Covers - Can set cover image

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#514]
What does usergroup permissions Can set cover image? Also can not find out moderator permissions.

**Comment by LukasWieditz** [comment]
https://www.themehouse.com/help/documentation/covers2/setting-up-covers#user-group

**Comment by Nirjonadda** [comment]
> Can set cover image Allows users to set an image to their covers. Disallowing this setting keeps users from being able to define a cover image on their profile, resources, or threads.

Still can not understand about what does Can set cover image? Can set cover image vs Can upload cover image?
