### ISSUE TITLE
Inline moderation highlighting issue

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2addon-issues#520]
Unable to tie it down to one individual addon, but ever since updating to the latest spree of addon releases there seems to be this issue with inline moderation on every thread:
![image](https://user-images.githubusercontent.com/34864926/41320534-17f669ce-6e98-11e8-99fc-3bcd8240a49f.png)

I'll try and pin it down to a single addon, and report back.

**Comment by LukasWieditz** [comment]
Is that on the default style?

**Comment by tom-coward** [comment]
Got same issue on XF default style, yeah.

**Comment by tom-coward** [comment]
Seems to be resolved on all threads after I deselected on one. The threads were definitely selected after the updates though, as I didn't select them manually.

**Comment by mikecreuzer** [comment]
@tom-coward is this still happening? Not seeing this myself.

**Comment by mikecreuzer** [comment]
Can confirm. This is in UIX.

This is Xenith for example:

<img width="145" alt="screen shot 2018-06-19 at 3 41 29 pm" src="https://user-images.githubusercontent.com/1217271/41623088-56dd866a-73d7-11e8-927f-e8c723de06a0.png">
<img width="253" alt="screen shot 2018-06-19 at 3 41 00 pm" src="https://user-images.githubusercontent.com/1217271/41623089-56ee9f18-73d7-11e8-8a9e-f05a61186667.png">

**Comment by LukasWieditz** [comment]
@Ian-Hitt this is a styling issue in our themes, why assign it to me?
