### ISSUE TITLE
[TH] Reactions - Display profile tab

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#521]
Display profile tab are not working but i have enabled Display profile tab.

**Comment by daltonp** [comment]
I'm able to view the profile tab with no troubles on our boards, are you getting any errors or have you tried to resync the add-on to see if that helps?

**Comment by Nirjonadda** [comment]
I am reported not showing Reactions profile tab.

**Comment by mikecreuzer** [comment]
Hmm, this may require us taking a closer look, as the tab is working for me as well.

**Comment by Nirjonadda** [comment]
Reactions profile tab, This not showing for me in live site and demo site.

**Comment by mikecreuzer** [comment]
Can confirm its not working after toggling the option.

**Comment by LukasWieditz** [comment]
Cannot reproduce anything here. Disabling "Display profile tab" hides the profile tab as expected, enabling it, shows the tab as expected. The widget on the right hand side has to be removed manually either way, if you want to remove it.

**Comment by Nirjonadda** [comment]
@LukasWieditz do you like check out this in our demo forum?

**Comment by LukasWieditz** [comment]
Would be cool.

**Comment by Nirjonadda** [comment]
@LukasWieditz Please check in xenforo for login.
