### ISSUE TITLE
[TH] Covers - Phrases showing in admin cp

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#525]
Phrases showing in admin cp.

![screenshot00004](https://user-images.githubusercontent.com/6899856/41321857-25bd712a-6ea6-11e8-9d5c-62217ca46fce.png)

![screenshot00005](https://user-images.githubusercontent.com/6899856/41321861-2898b22e-6ea6-11e8-9f61-62e34504a1d0.png)

**Comment by daltonp** [comment]
I am able to confirm this on one of our boards as I using the latest version which is Covers 1.0.0 Patch Level 1. 
![coverphrasebug](https://user-images.githubusercontent.com/32306910/41362122-38559218-6ef6-11e8-9c53-60e42cd4542d.png)
