### ISSUE TITLE
Topics - Topics list styling issues

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2addon-issues#532]
As per title; the search bar in the topics list:
![image](https://user-images.githubusercontent.com/34864926/41375993-acc3297c-6f4f-11e8-9095-d5f90651d880.png)

**Comment by Ian-Hitt** [comment]
@tom-coward are you referring to the missing margins here? The search itself is intentional

**Comment by Ian-Hitt** [comment]
The search filters your topics, so if you have many you can more easily find them

**Comment by tom-coward** [comment]
Ah okay, understand what the search bar was for, just thought the styling looks a bit off. Even if there is intentionally no margin, the topics themselves are slightly misaligned with the search bar.
