### ISSUE TITLE
UI.X add-on - open new tab

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#533]
add click here open new tab for admin CP.

![screenshot00007](https://user-images.githubusercontent.com/6899856/41377960-f3fa3804-6f5d-11e8-95e2-33ce4657ec7c.png)

**Comment by Ian-Hitt** [comment]
@Nirjonadda Do you mean add text? It does open in a new tab.

**Comment by Nirjonadda** [comment]
No, click here will be open current tab, not new tab.

**Comment by LukasWieditz** [comment]
We're not planning to make any changes here. Getting back to the index page is a one click action from anywhere in the ACP, so this is not really an issue.
