### ISSUE TITLE
[TH] Topics - DEBUG: Template thtopics_option_topic_list_data not found.

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#535]
DEBUG: Template thtopics_option_topic_list_data not found.

![screenshot00008](https://user-images.githubusercontent.com/6899856/41378509-88d5381a-6f5f-11e8-80b8-b94646653ccf.png)

**Comment by LukasWieditz** [comment]
Cannot reproduce this issue. Template is definitely in the build file. Might be something else going on here, but can you try rebuilding the add-on @Nirjonadda ?

**Comment by Nirjonadda** [comment]
No, rebuilding the add-on are not fix.
