### ISSUE TITLE
Topics - 'New posts' homepage issue

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2addon-issues#539]
When 'New posts' is set as the forums default page, `forum/-/list` is appended to the end of the URL and the normal default node list homepage shows.

**Comment by LukasWieditz** [comment]
Can't reproduce this. Setting the default page to `New Posts` and then opening my board via the ACP link to the frontend directs me to the root page as expected, which shows New Posts. Navigating to the forum list appends `forums/-/list` to the URL as expected, that is default XF behavior. Clicking on the forum navigation tab brings me back to New Posts as expected.

**Comment by Ian-Hitt** [comment]
@LukasWieditz I can confirm this bug on my board
