### ISSUE TITLE
[TH] Donate - manually add donation 

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#546]
add support can manually add donation via mobile browser.

**Comment by JakeBooher** [comment]
This is already possible in the AdminCP.

**Comment by Nirjonadda** [comment]
No, Its not possible via mobile browser.

**Comment by mikecreuzer** [comment]
Do you mean like in the ACP?

**Comment by Nirjonadda** [comment]
Yes ACP with mobile browser.

**Comment by Nirjonadda** [comment]
Can not find out Donations link in ACP with mobile browser.

![screenshot00039](https://user-images.githubusercontent.com/6899856/41607724-f2af6770-73e6-11e8-9c33-c0d4f29e7084.png)
