### ISSUE TITLE
[TH] Covers - Username using two line

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#547]
Username using two line

![screenshot00029](https://user-images.githubusercontent.com/6899856/41553999-c0c991b2-7333-11e8-92bc-de56c5a37911.png)

**Comment by Ian-Hitt** [comment]
@Nirjonadda Am not able to replicate. Can you provide any additional info?

**Comment by Nirjonadda** [comment]
I Am also not able to replicate.
