### ISSUE TITLE
th_uix_replied missing phrase

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#551]
![image](https://user-images.githubusercontent.com/1217271/41607029-b144971a-73aa-11e8-8107-52cd9d5120ba.png)

Not sure what addon this phrase belongs to

**Comment by Nirjonadda** [comment]
This issue also we have in thread list.

**Comment by LukasWieditz** [comment]
![ylbjepa](https://user-images.githubusercontent.com/38475165/41773406-41f95ae8-761c-11e8-9e4f-b739da84a041.png)
The phrase exists and is assigned to the right add-on. Need more input on where (page(s) & style(s)) this is happening to do anything about it.

**Comment by Nirjonadda** [comment]
This happened with UI.X Pro style in thread list > /forums/main-forum.2/

**Comment by Ian-Hitt** [comment]
@Nirjonadda Your add-on is outdated on your demo.
