### ISSUE TITLE
Issues concerning inline replies

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#555]
<img width="444" alt="screen shot 2018-06-19 at 2 17 21 pm" src="https://user-images.githubusercontent.com/1217271/41619352-8c4c2e3e-73cb-11e8-97c8-50fceb641c3b.png">

UIX:

- [ ] Quick reply box doesnt keep same avatar size (in pic its larger)

Add-on I assume?:

- [x] First inline reply has odd padding on left
- [ ] `.listInline.listInline--bullet > li:before` has a bullet thing touching the username, looks broken. Can probably just remove.
- [x] Avatar/username a bit too close together by 1-3px? idk

And the big issue:
- [ ] Nesting padding is inconsistent on the left with respect to the others (for the first one)
- [ ] We should probably put these inside the card. Too many card components, its looking messy. I think these can all be inside the original post with like a border-left or something to associate it as connected. Reddit does this

<img width="499" alt="screen shot 2018-06-19 at 2 29 33 pm" src="https://user-images.githubusercontent.com/1217271/41619827-370505f2-73cd-11e8-97b3-5e150c5f9201.png">

@nikkiradloff do you want to do a quick wireframe?

**Comment by nikkiradloff** [comment]
![inline comments](https://user-images.githubusercontent.com/15836402/41626545-2f455c8a-73e2-11e8-8fc4-a0b1457ceb9e.png)

**Comment by nikkiradloff** [comment]
would something like above work? @Ian-Hitt @mikecreuzer

**Comment by mikecreuzer** [comment]
I like it. Maybe not dotted but structure looks great

**Comment by mikecreuzer** [comment]
So we need a markup change, Ian has asked me to post what that is.

I've recreated the ideal situation here: http://jsfiddle.net/sbnpefj5/46/

But ultimately we need:

=======
---$Message
------Message Meta (postbit etc)
------Message Content (where the post itself is
------Message Tools (links, reply, delete, etc.)
------Message Replies (where the replies are made, IF there are any)
-----------Inside here another $Message with same markup
=======

So right now we are doing `.nested-container`. Rename that to `.message__replies` and only show it if there are actual replies. Keeping the level like you are doing now is nice, not needed atm but good to have.

Second, the entire .message__replies component needs to be inside the <article> (message) recursively each time the same way. (right below `.message-inner` I think is fine)

Thats all, just moving it that one spot and making sure the current nested replies are inside the original message will do the trick.

**Comment by LukasWieditz** [comment]
@Ian-Hitt what exactly am I needed here for?

**Comment by Ian-Hitt** [comment]
@LukasWieditz Need the markup change that mike requested in his last comment. Need to essentially nest comments inside of the parent.

**Comment by LukasWieditz** [comment]
The data structure is now nested @Ian-Hitt

**Comment by LukasWieditz** [comment]
@Ian-Hitt if you're able to wrap this up, we'd be able to push this add-on out of the door.
