### ISSUE TITLE
TH Donate: listing changes

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#558]
- [x] The goal/total bar should touch sides of card @Ian-Hitt 
- [x] Add progress bar with animation (same component we have on the list view, above the goal/total bar @Ian-Hitt 
- [x] Should we not add total raised vs current repeating cycle raised? These are the possible things we should store:

1. total donated on the campaign
2. total donated during current repeating cycle
3. number of cycles so far and/or start date
4. campaign end date
5. goal per repeating cycle (progress bar should be total donated during current goal of total desired goal for that cycle)

- [x] We should list a bit more on card listing such as the above ^^

 - [x] View button AND donate button? Right now it says Donate but just takes you to view

<img width="469" alt="screen shot 2018-06-19 at 3 33 56 pm" src="https://user-images.githubusercontent.com/1217271/41622946-d47d716c-73d6-11e8-9d38-e69d792c9a1f.png">

**Comment by LukasWieditz** [comment]
@Ian-Hitt hooked you up with some icons for campaigns. You get four sizes: xs (64x64), s (128x128), m (256x256) and l (512x512). Called with `{{ thdonate_campaign_icon($campaign, 'mySizecodeHere') }}` in the template of your choice..

**Comment by LukasWieditz** [comment]
We have all the data you listed already available, except for the number of previous cycles, which I personally see no value in, and wouldn't work out being added in retrospect for existing campaigns.
