### ISSUE TITLE
Filter bar color issue with topics

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#559]
<img width="192" alt="screen shot 2018-06-19 at 3 42 47 pm" src="https://user-images.githubusercontent.com/1217271/41623141-78dad90c-73d7-11e8-9860-abbe56fb6112.png">

I would just make them the same style as what we do here:

<img width="146" alt="screen shot 2018-06-19 at 3 43 21 pm" src="https://user-images.githubusercontent.com/1217271/41623149-81ff5094-73d7-11e8-8e1e-dba0ece0ae70.png">

**Comment by Ian-Hitt** [comment]
fixed again :)
