### ISSUE TITLE
XPress - Admin navigation index page

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2addon-issues#564]
At `/admin.php?thxpress`, there should be an index page in place with navigation links for consistency with other XF admin navigation categories.

**Comment by mikecreuzer** [comment]
Since it only has a super limited amount of tools in the ACP, Ill say we do this when we have more functionality. I dont quite know what that is yet.

**Comment by LukasWieditz** [comment]
It's just an XF-generated default page, nothing to do for us other than adding two lines of code. Done.
