### ISSUE TITLE
XPress - Redirect XF->WP in new tab

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2addon-issues#565]
Maybe redirect from the XF ACP to WP (and vice-versa) in a new tab? Noticed it's a bit annoying currently when reverting between the two. Alternatively maybe use an iframe, although I'm not sure if 
& how this would work?

**Comment by mikecreuzer** [comment]
Which link(s) are you referring to?

**Comment by tom-coward** [comment]
All but 'Settings' here:
![image](https://user-images.githubusercontent.com/34864926/41799845-3af6cb70-7673-11e8-9303-b550357a2e92.png)

**Comment by mikecreuzer** [comment]
Sure, makes sense/

**Comment by LukasWieditz** [comment]
Can't do, XF navigation doesn't allow that.
