### ISSUE TITLE
XPress - Login default option

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2addon-issues#566]
Unless I'm completely misinterpreting what these options mean, might be best having 'Single sign-on' as the default option here?
![image](https://user-images.githubusercontent.com/34864926/41799439-dba283c2-7671-11e8-89d9-101f298f21ab.png)

**Comment by mikecreuzer** [comment]
Wtih respect to order, I agree it should be first. Default, I honestly dont know whats best.

**Comment by LukasWieditz** [comment]
SSO is the default, for as long as you start in XenForo. WP doesn't allow us to define default values for options unless we do dirty hacks.
