### ISSUE TITLE
XPress - XF advanced search doesn't work on WP pages

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2addon-issues#567]
As per title. When trying to navigate to advanced search via. the header search bar, user is simply redirected back to the homepage.

**Comment by LukasWieditz** [comment]
Wordpress doesn't have any advanced search and we've removed the advanced search button for default style and UI.X. You're using a 3rd party style?

**Comment by LukasWieditz** [comment]
Should be fixed for UI.X
