### ISSUE TITLE
XPress - To forum discussion

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#569]
To forum discussion link are not work.

![screenshot00048](https://user-images.githubusercontent.com/6899856/41802017-65791b90-767e-11e8-9ce2-746ddcf6185a.png)

**Comment by mikecreuzer** [comment]
Do you have it setup to work with a node?

**Comment by Nirjonadda** [comment]
Yes but not created threads in this node.

![screenshot00049](https://user-images.githubusercontent.com/6899856/41802111-df712514-767e-11e8-8a1b-6bbb719a631b.png)

**Comment by mikecreuzer** [comment]
Hm so it is setup so it knows what nodes to pull. Are you getting an error message in XenForo ACP server log?

**Comment by LukasWieditz** [comment]
It's missing the user. You gotta make sure you've set up a fallback user or your WordPress and XenForo account are actually linked.

**Comment by mikecreuzer** [comment]
@LukasWieditz since it is tricky, what if we do a health check? Or rather it will show somewhere some nice message that says You need X or Y isn't working etc

**Comment by Nirjonadda** [comment]
OK but if username or node are not selected then why not hide To forum discussion button? So we are not get any error.

**Comment by LukasWieditz** [comment]
Agreed, both things that should be done.

**Comment by LukasWieditz** [comment]
Thinking about it, we might need a way to link two existing accounts as well, I don't think we have that atm.
