### ISSUE TITLE
TH Nodes node footer support for TH Bookmarks (stateful bookmark icon next to create thread)

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#57]

**Comment by LukasWieditz** [comment]
![hithn9j](https://user-images.githubusercontent.com/38475165/40176791-dd8a7976-59dc-11e8-8a15-4bbe3ed23f33.png)
I've implemented this just now. Needs a little styling love, but that should be trivial @Ian-Hitt.
