### ISSUE TITLE
TH Nodes - Toggles for showing node styling on titlebar of either forum_list, forum_view, and thread_view

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#571]
A checkbox for the following would be ideal. Pass to @Ian-Hitt  when settings are created. 

- [x] forum_list (this should be turned on by default) - I get that this is kinda the point of node styling so this may exist in some other form already. Just call it like "Show node styling on forum index"

- [x] forum_view
- [x] thread_view

**Comment by LukasWieditz** [comment]
References #470 #561

**Comment by Ian-Hitt** [comment]
@LukasWieditz  I don't see where that conditional is being used, can you point me?

**Comment by LukasWieditz** [comment]
Template mods with ids `thnodes_category_view`, `thnodes_thread_view`, `thnodes_forum_view` as seen in the commit https://github.com/LukasWieditz/xf2/commit/0c573227dc9ef3f8500677a43b7a5c97b600fe8b
