### ISSUE TITLE
Trending/new posts have different filter setups

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#575]
New:
<img width="1214" alt="screen shot 2018-06-25 at 11 09 19 am" src="https://user-images.githubusercontent.com/1217271/41861975-469f6c92-7868-11e8-8b9d-8bdeae70b547.png">

Trending:
<img width="1189" alt="screen shot 2018-06-25 at 11 09 33 am" src="https://user-images.githubusercontent.com/1217271/41861983-4b19b714-7868-11e8-80ec-f791828e5955.png">

**Comment by Ian-Hitt** [comment]
@LukasWieditz bug in a trending template mod, but I can't tell exactly what the difference is.

**Comment by Ian-Hitt** [comment]
Trending
```
<xf:macro template="thtopics_topic_scroller"
		  name="scroller"
		  arg-route="trending"
		  arg-page="{$page}"
		  arg-filters="{$filters}"
		  arg-extra="{$trending.trending_id}"
		   />
```
New Posts
```
<xf:macro template="thtopics_topic_scroller"
		  name="scroller"
		  arg-filters="{$filters}"
		  arg-route="new_posts"
		  arg-page="{$page}" />
```

Removing arg-extra doesnt change it. What am I missing here?

**Comment by mikecreuzer** [comment]
@Ian-Hitt says JS/CSS is missing
