### ISSUE TITLE
Allow multiple topics to link to the same node

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#579]
- [x] Make a checkbox/setting OR Remove functionality that creates nodes when creating topics
- [x] Update create/edit topic to no longer check if the node is already set by another topic
- [x] Moderation tools. Specifically just moving thread and changing topic. I think these can be merged though to `Set topic`. This will move in the background. It asks for primary first, then secondary, same as creating a new thread for the markup. 

@LukasWieditz no real need to start this right away if its going to take 20-40 hours. Just setting it up for now.

**Comment by LukasWieditz** [comment]
First point is not even a thing to begin with. Crossing it off the list.
