### ISSUE TITLE
topic post thread modal secondary topics not working

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#580]
in the modal selecting secondary topics does not carry over when you click continue.
<img width="986" alt="screen shot 2018-06-26 at 8 42 40 am" src="https://user-images.githubusercontent.com/15836384/41916364-80e3cc3a-791d-11e8-988f-4c4fa2a63ee7.png">
<img width="926" alt="screen shot 2018-06-26 at 8 42 43 am" src="https://user-images.githubusercontent.com/15836384/41916365-80f3bae6-791d-11e8-85e5-c76838918ca4.png">

**Comment by Ian-Hitt** [comment]
Mike re-created it :) https://github.com/Audentio/xf2addon-issues/issues/587

**Comment by mikecreuzer** [comment]
Sorry
