### ISSUE TITLE
[TH] Covers - Users not able to delete covers on resources 

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#581]
Users aren't able to delete resource covers nor are they able to see it on the drop-down when the user group permission `Can delete covers` is allowed.

I was able to replicate this on the beta board [here](http://demo.themehouse.com/xf2/beta).

**Comment by LukasWieditz** [comment]
Can anyone reproduce this?

**Comment by Nirjonadda** [comment]
I can't replicate because we have not resources.

**Comment by mikecreuzer** [comment]
Not able to replicate.
