### ISSUE TITLE
Remove filter trigger is on the li not the a

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#583]
For whatever reason we continue to put triggers on li's and divs. Sometimes this is needed, but most times just put it on the <a>. You get hover and such for free. Now, there is a way where I can remove the trigger by clicking the padding on the <li>. Not an important bug, just something Im making an issue over cause Im just mad we did this. lol I assume its just changing a selector somewhere.

This SHOULD NOT be solved with CSS. Just change the trigger selector.

**Comment by kylerc** [comment]
The JS should be already running on the `.th_topics_clearTopics` which is the anchor.  I believe that's correct @mikecreuzer but let me know if something needs to be updated on my end.

**Comment by mikecreuzer** [comment]
Why close without confirming? Still happening

**Comment by mikecreuzer** [comment]
![anchor](https://user-images.githubusercontent.com/1217271/42049865-efbb9704-7acc-11e8-84cd-75adf66ab02e.gif)

**Comment by mikecreuzer** [comment]
its still kinda able to happen, but its better than it was so
