### ISSUE TITLE
Topics - Clicking the title unchecks the rest and just does itself. Checking the box adds that topic?

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#586]
There currently, I think, needs to be a way to get JUST the topic. There will be plenty of people who just want the one topic. If they have to uncheck each time it seems like a less than desirable experience. As most people will probably want just one or two, and may want to toggle quickly, we need to consider this.

A proposed suggestion is that we split the triggers. The checkbox/square VS the title link.

Clicking the title link will deselect the rest, and then select just the one topic.
Clicking the checkbox, will add to the existing list of selected topics.

Thoughts?

**Comment by Ian-Hitt** [comment]
@mikecreuzer I think that UX pattern is confusing. Also, there is already a solution in place for this (the clear button.) IMO it is the suggested action is unintuitive, and would cause confusion for the user.

**Comment by mikecreuzer** [comment]
I think its confusing that we chain them by default. Dont forget that yes we added multiple support, but the majority of people will only care about one topic at a time. Or at least a majority of the time. Its added functionality, not the main functionality. 

Clicking the trigger the most intuitive way should clear the rest and toggle just the one you selected. To add additional should be an extra trigger. We could make the default a setting, but more often then not you want just the one node. It actually makes it so we dont need the clear topics in the filter component.

**Comment by kylerc** [comment]
Closing this since #598 has this now
