### ISSUE TITLE
Creating a new thread - bugs with secondary topics

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#587]
When creating a new thread, it asks for primary. Which is fine.

It then asks for secondary, and a few things happen:

- [x] It filters the thread list behind the modal. I think these should not filter the thread list. Its a nice idea for it to have those topics already selected instead. So if I was browsing with topic X, Y, Z then those are already selected. Sure itll ask me for primary, but otherwise the others persist.

- [x] They do not carry over to the next page. Whatever I select is not saved when I visit the actual create thread route.

- [x] When a primary topic is selected, its also showing up as a secondary option

**Comment by kylerc** [comment]
@LukasWieditz I think the second one is maybe server side?  But let me know if it ends up involving me.  I can handle the first issue though.

**Comment by LukasWieditz** [comment]
@mikecreuzer please do not group multiple bugs into one issue. Create one issue per bug. If they happen to be related, we can link them to one another.

**Comment by LukasWieditz** [comment]
@kylerc regarding the third: can you hide the secondary topic element if it's selected as primary? Class to hide should be `thTopicAction--{topic-id}`.

**Comment by LukasWieditz** [comment]
To the second issue: Someone used the wrong class... I've corrected that, it's working again now.
