### ISSUE TITLE
[TH] Donate - User has donated no more than X amount in the past Y days

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#588]
Using criteria User has donated no more than X amount in the past Y days are adding lot of user who are not donated.

**Comment by mikecreuzer** [comment]
Are you saying people are incorrectly passing the user criteria? Or can you elaborate please?

**Comment by Nirjonadda** [comment]
Yes, Incorrectly passing the user criteria.

**Comment by LukasWieditz** [comment]
Users who donated 0 (nothing) in the past Y days have essentially always donated less than X, cause 0 is less than everything else.

**Comment by Nirjonadda** [comment]
@JakeBooher How to Invalid this? User has donated no more than 5 amount in the past 15 days, will adding user who are not donated.

**Comment by Nirjonadda** [comment]
Please let me know what does this criteria `User has donated no more than X amount in the past Y days:`? As I know X amount user how many amount and Y days used when promotions expiring?

**Comment by JakeBooher** [comment]
If you specify X (amount) as 10 and Y (days) as 15 it will return true for any user that has donated **less than or equal to** $10 (or whatever currency you're using), including $0.

**Comment by mikecreuzer** [comment]
So the question is should it include people who have donated or should it include all people. Can you just chain it with Has Donated?

**Comment by JakeBooher** [comment]
You can chain it with has donated, "has donated at least X in Y days" etc. This flagging people that have donated $0 is completely expected with this criteria, same applies to "User has posted no more than X times" and a few others
