### ISSUE TITLE
[TH] Donate - Rebuild user group promotions

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#589]
Rebuild user group promotions are adding user in promotions from Rebuild time, not from their donate date/time.

**Comment by JakeBooher** [comment]
Could you elaborate?

**Comment by Nirjonadda** [comment]
Also Rebuild user group promotions are re-set old promoted date to new date from Rebuild time.

**Comment by JakeBooher** [comment]
That entire process is handled by XenForo, so there isn't really anything we can change here.

**Comment by mikecreuzer** [comment]
Doesnt the cron run with respect to minutes? So wouldnt this be a rare edge case that wouldnt really need fixing?
