### ISSUE TITLE
[TH] Donate - multiple criteria for User group promotions

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#590]
Add support multiple criteria for User group promotions.

Example:

$5 donated adding 15 day expiring
$10 donated adding 30 day expiring
$20 donated adding 60 day expiring

**Comment by LukasWieditz** [comment]
This is nothing we have control over with the way XenForo user group promotions operate. Enhancement suggestions of that type have to be made on XenForo.com
