### ISSUE TITLE
[TH] Donate - double promotions

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#591]
I have added User group promotions, one criteria is `User has donated at least 5 amount in the past 15 days` and `User has donated at least 10 amount in the past 30 days`. Rebuild user group promotions are adding both promotions.

**Comment by LukasWieditz** [comment]
Use `User has donated no more than X amount in the past Y days` in addition to avoid this.

**Comment by Nirjonadda** [comment]
Yes but using this will happened this issue: https://github.com/Audentio/xf2addon-issues/issues/588
