### ISSUE TITLE
Promotions expiring

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#593]
Add support to show user promotions when expiring.

**Comment by mikecreuzer** [comment]
So like an alert to the user?

**Comment by mikecreuzer** [comment]
idk I mean yes you can make a separate add-on. Ultimately you want to know when donors are on their way out of their donate service, and its best as one system so you can have it say "Thank you for your donate X days ago, we'd most appreciate a donation again so you can continue to hold a premium status. Click here to donate"

**Comment by LukasWieditz** [comment]
I don't think this is something we should look into. Either XenForo should provide a general way to send alerts for expiring promotions or it should be a new product in general.

**Comment by mikecreuzer** [comment]
Isnt this a simple cron check though? See who is expired, generate alert?

**Comment by LukasWieditz** [comment]
If you want to do it after expiration, we can do a general alert upon expiration/downgrade. If you want to do it beforehand, it's a bigger thing to do it efficiently.

**Comment by LukasWieditz** [comment]
I still don't really feel like this is something that should go into donate but rather either into XenForo or into a new product.

**Comment by mikecreuzer** [comment]
I find the feature vastly useful imo and not that complex. I want to keep this open as if indeed its a cron check to simply see the time is one week from expiration or whatever, it sends an on-platform alert. If someone can explain why this is so difficult we can then consider moving it to an add-on or something.

**Comment by jonw316** [comment]
Adding this to Monetize.

**Comment by jonw316** [comment]
I think this is actually already possible with the combination of the criteria provided by Donate and the messaging system in Monetize, so closing.
