### ISSUE TITLE
[TH] Nodes - Ability to quickly toggle styling off or on for a theme

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#60]
A little checkbox somewhere to toggle styling, perhaps on the list.

**Comment by daltonp** [comment]
Got this error after clicking `Enable styling for style` - Was able to get passed it when clicking `Rebuild cache`

> An exception occurred: [TypeError] Argument 1 passed to XF\Mvc\Entity\Entity::bulkSet() must be of the type array, boolean given, called in /home/demo/public_html/xf2/beta/src/addons/ThemeHouse/Nodes/Admin/Controller/NodeLayout.php on line 72 in src/XF/Mvc/Entity/Entity.php on line 669
> 
> XF\Mvc\Entity\Entity->bulkSet() in src/addons/ThemeHouse/Nodes/Admin/Controller/NodeLayout.php at line 72
> ThemeHouse\Nodes\Admin\Controller\NodeLayout->actionToggle() in src/XF/Mvc/Dispatcher.php at line 249
> XF\Mvc\Dispatcher->dispatchClass() in src/XF/Mvc/Dispatcher.php at line 88
> XF\Mvc\Dispatcher->dispatchLoop() in src/XF/Mvc/Dispatcher.php at line 41
> XF\Mvc\Dispatcher->run() in src/XF/App.php at line 1931
> XF\App->run() in src/XF.php at line 328
> XF::runApp() in admin.php at line 13
