### ISSUE TITLE
[TH] Covers - Covers button are not showing correctly in mobile browser

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#603]
Covers button are not showing correctly in mobile browser.

![screenshotcapture_2018_07_02_17_11_54_299](https://user-images.githubusercontent.com/6899856/42176675-07426c1c-7e2a-11e8-996e-c3984764df8b.jpg)

**Comment by daltonp** [comment]
What mobile device are you replicating this on? Also, what theme are you using? Can you show a screenshot of this issue on the default style, please?

**Comment by Nirjonadda** [comment]
I am using android mobile device from this style: https://xenforo.com/community/resources/uniform.5944/

**Comment by Nirjonadda** [comment]
@Ian-Hitt I think, now xenforo default style are not showing correctly.

xenforo default style view:

![screenshotcapture_2018_07_13_14_40_18_991](https://user-images.githubusercontent.com/6899856/42692274-6fdfa332-86ab-11e8-8c96-fbed24532f1d.jpg)

other (Uniform) style view are look nice:

![screenshotcapture_2018_07_13_14_39_36_613](https://user-images.githubusercontent.com/6899856/42692305-8c7d41d4-86ab-11e8-94b3-98c962aebffa.jpg)

**Comment by Ian-Hitt** [comment]
Hello,

That is because of the very large horizontal paddings on the side of the page. The buttons are simply displaying how they can with the space provided.
