### ISSUE TITLE
[TH] Q&A - Sort by votes button are not showing correctly in mobile browser

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#604]
Sort by votes button are not showing correctly in mobile browser.

![screenshotcapture_2018_07_02_17_11_54_299](https://user-images.githubusercontent.com/6899856/42176705-2bf66234-7e2a-11e8-8249-e0a89b0625af.jpg)

**Comment by daltonp** [comment]
Same question that I asked in issue #603 as well, thanks for your reporting.
