### ISSUE TITLE
Post comments - getting a weird cancel reply message and the textarea doesnt focus when clicking reply

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#605]
<img width="985" alt="screen shot 2018-07-02 at 3 32 49 pm" src="https://user-images.githubusercontent.com/1217271/42185067-42ab6f6e-7e0d-11e8-9695-8a34111974cf.png">

**Comment by LukasWieditz** [comment]
That is not post comments, that's the standard wordpress cancel reply link.

**Comment by mikecreuzer** [comment]
We don't need it. Not sure why its there either

**Comment by LukasWieditz** [comment]
Cause it's default from WordPress? When you click "reply" to a comment, it won't give you a separate reply box but just scroll down to the reply box there already is. That link gives you the option to stop replying to that one specific comment you clicked reply on and instead do a general comment again. Removing it means there's no way to stop replying to that one specific comment you clicked reply on (fwiw the selection persists through page reloads) unless you modify the url.

**Comment by mikecreuzer** [comment]
Well, whatever the reason, its wrong. Can revisit it if we dont have time.

**Comment by LukasWieditz** [comment]
![tt7vjci](https://user-images.githubusercontent.com/38475165/42237008-daa09002-7efc-11e8-8f9b-f9c601b26202.png)
Is that better?

**Comment by mikecreuzer** [comment]
No, its the fact that its needed. It may require we do something different, like inline quick reply boxes under the reply in flow. Instead of jumping to the bottom.

For now we can leave it as is, and then I guess this does look slightly better, its just no one will understand why it is this way when no commenting systems I've ever used work this way UX-wise.

**Comment by LukasWieditz** [comment]
Dunno, it's default WordPress, but I agree on getting rid of it and have an inline reply box as in post comments.

**Comment by mikecreuzer** [comment]
We can circle back to this. For now its fine for launch.
