### ISSUE TITLE
Duplicate topic label on profile postings tab

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#611]
profile
<img width="790" alt="screen shot 2018-07-03 at 4 10 02 pm" src="https://user-images.githubusercontent.com/1217271/42244676-90a47494-7edb-11e8-979f-1169d60098f4.png">
/#recent-content

**Comment by LukasWieditz** [comment]
Working fine on NeoGAF, UI.X, UI.X Pro and Default, seems to be some old state or so?
