### ISSUE TITLE
Given reactions link for a specific reaction not working

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#616]
members/audentio.1/reactions?type=given&reaction_id=2

For me it turns other people's posts, shouldn't it be own where I reacted with reaction id 2?

**Comment by LukasWieditz** [comment]
Can't replicate and the code couldn't be more straightforward.

```
if ($type == 'given') {
    $reactedContentFinder->where('react_user_id', '=', $user->user_id);
} elseif ($type == 'received') {
    $reactedContentFinder->where('content_user_id', '=', $user->user_id);
} else {
    $reactedContentFinder->whereOr([
        'content_user_id', '=', $user->user_id
    ],[
        'react_user_id', '=', $user->user_id
    ]);
}
```

Only situation where you should get both is when the type is neither `given`, nor `received`. It's case sensitive atm, but that can probably be changed.
