### ISSUE TITLE
Topics page stats line

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#617]
<img width="974" alt="screen shot 2018-07-05 at 12 10 05 pm" src="https://user-images.githubusercontent.com/1217271/42337432-6cdbce1e-804c-11e8-8263-382128f2fe17.png">

**Comment by LukasWieditz** [comment]
Getting a feeling someone did not reference tickets when working through these issues. Seems to be fixed as well.

**Comment by mikecreuzer** [comment]
Reference tickets? @LukasWieditz what did I do?

**Comment by JakeBooher** [comment]
He's referring to referencing the issue ID in the commit that fixes the issue
