### ISSUE TITLE
[TH] Cover - Allow users to set the thread image before they create the thread

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#620]
Users should be able to set the thread image way before they create the thread. By default they would need to set the thread image after they've created the thread. This was suggested by one of users of this add-on on XenForo:

> Furthermore it would be nice if the user could set the cover while he is creating a thread not after he had created a thread.

**Comment by JakeBooher** [comment]
There may be a fundamental issue with allowing this, and really isn't that uncommon for similar features (setting your cover on Twitter, for example). Will leave it up to @LukasWieditz though on whether it's even possible, and if it is if it'd be worth doing

**Comment by LukasWieditz** [comment]
I doubt we're gonna do this. For one it's not possible to store the cover before the thread has been saved, so we'd need to shift the cover save routine _after_ the thread creation, which leaves us with the issue of not being able to return cover save errors while simultaneously not having the thread being created, and secondly, similar native XenForo features use the same mechanic of first having to create the entity, then assign the image to it (Avatar, Resource Icon).
