### ISSUE TITLE
[TH] Reactions - margin and spacing

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#627]
Margin and spacing issue still are not fixed in Version 1.0.13 Patch Level 1

![screenshot00072](https://user-images.githubusercontent.com/6899856/42643463-78c87ca6-85f9-11e8-9d04-7c5e54721a61.png)

**Comment by Nirjonadda** [comment]
![screenshot00073](https://user-images.githubusercontent.com/6899856/42643701-19f01134-85fa-11e8-84a0-b4f59cc3da72.png)

**Comment by mikecreuzer** [comment]
Did you customize any templates? Does this happen on stock default style or stocky UI.X theme?

**Comment by Nirjonadda** [comment]
No, I have not made any manually template edit and this Screen Shot from default xenforo style.

**Comment by Ian-Hitt** [comment]
@Nirjonadda I am unable to replicate this on your board in any theme. Are you experiencing the issue here? https://nirjonmela.info/threads/%E0%A6%A8%E0%A6%BF%E0%A6%B0%E0%A7%8D%E0%A6%9C%E0%A6%A8%E0%A6%AE%E0%A7%87%E0%A6%B2%E0%A6%BE-%E0%A6%A8%E0%A7%81%E0%A6%A4%E0%A6%A8-%E0%A6%95%E0%A6%B0%E0%A7%87-%E0%A6%97%E0%A6%A0%E0%A6%A8.2/

**Comment by Nirjonadda** [comment]
@Ian-Hitt This happened when Location to display reaction bar in content set to "Above signature". Also this issue from Live site and Demo site are not updated Version 1.0.13 Patch Level 1.

**Comment by mikecreuzer** [comment]
<img width="1396" alt="screen shot 2018-07-17 at 12 19 46 pm" src="https://user-images.githubusercontent.com/1217271/42834192-09c60ae6-89bc-11e8-8a27-87b0d7d762f0.png">
<img width="1369" alt="screen shot 2018-07-17 at 12 19 36 pm" src="https://user-images.githubusercontent.com/1217271/42834193-0b7c5f2a-89bc-11e8-8170-3260884fc648.png">

**Comment by Nirjonadda** [comment]
@JakeBooher @Ian-Hitt Does not fixed this issue in UI.X Pro 1.0.0 Release Candidate 1?

**Comment by Nirjonadda** [comment]
See here: https://giant.gfycat.com/HollowRingedKagu.webm

**Comment by Ian-Hitt** [comment]
This is behaving as intended.

**Comment by mikecreuzer** [comment]
Im a bit confused here, shouldnt we show this at the bottom?

**Comment by Nirjonadda** [comment]
Its look like bug when its show the near post?

![screenshot00291](https://user-images.githubusercontent.com/6899856/45321083-a8407400-b544-11e8-92de-bba50d87e385.png)

**Comment by mikecreuzer** [comment]
Ah so thats not even the default position? OK.

It should show aligned to bottom by default, regardless of UI.X or XenForo default. Just above postbit actions. If this is the case, and solved, please close
