### ISSUE TITLE
Trending no padding on 'no trending' message

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#636]
This is messed up. Im mad that we even have a bug like this as that means it was probably done in a goofy way.

1. Go to a filter configuration on trending that doesnt ahve results. Normal padding.
2. Now refresh the page, padding goes away. 

No words lol

<img width="721" alt="screen shot 2018-07-19 at 2 22 53 pm" src="https://user-images.githubusercontent.com/1217271/42965318-41bab2d6-8b5f-11e8-844c-87464c8d793d.png">
<img width="724" alt="screen shot 2018-07-19 at 2 22 46 pm" src="https://user-images.githubusercontent.com/1217271/42965325-4543096c-8b5f-11e8-9e24-e3bb40b39ea7.png">

**Comment by LukasWieditz** [comment]
Also fixed.
