### ISSUE TITLE
Visiting create thread as guest throws 500

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#640]
`index.php?forums/gaming-discussion.2/post-thread&secondary_topic_ids%5B0%5D=2` for ex that route structure as a guest 

Probably topics related but not sure

**Comment by LukasWieditz** [comment]
Not seeing an error 500 anymore, but the login form. Not sure how you got that error, but seems to be fixed. Guess if this ever pops up again we can investigate again.
