### ISSUE TITLE
Reactions images need absolute pathing to avoid issues

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2addon-issues#641]
Having reactions images set to relative pathing causes issues with installations that run in subfolders, where you either have them not working in the frontend (by default) or in the backend (if the frontend is fixed).

**Comment by jonw316** [comment]
How to replicate this? I've created installation in a subfolder and turned friendly URLs on and off, but images always seem to work fine.

**Comment by LukasWieditz** [comment]
Haven't tried to replicate this yet. We had two clients report it in tickets. Seems to be a somewhat uncommon problem, might be related to some style property setting related to their smilies or so (as iirc, we reuse some of that code).
