### ISSUE TITLE
Readme.html file

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#65]
- [ ] Link to documentation (if set)
- [ ] Link to product page
- [ ] Link to where to post issues
- [ ] Link to where to get help (/help)

@Ian-Hitt where is html?

**Comment by LukasWieditz** [comment]
Any plans on this @mikecreuzer @Ian-Hitt ? What's to be done here?

**Comment by LukasWieditz** [comment]
Small bump @mikecreuzer

**Comment by mikecreuzer** [comment]
lol I was told we'd have readme files for each product. Multiple times. So since we don't have it after all this time, idk. The markup is just an email template html, found inside themehouse repo. Copy it, and create a script to generate this from pinto (ideally)

Will leave here as I think we should have readme files with license and support info

**Comment by Ian-Hitt** [comment]
[readme.html.zip](https://github.com/Audentio/xf2addon-issues/files/2507645/readme.html.zip)

**Comment by mikecreuzer** [comment]
Thanks for doing this bud. A few things:

- [ ] Typo on ThemeHouse.com (hotlink as well)
- [ ] Reduce the image, its huge
- [ ] Can you align buttons to center? the way they are now is a bit goofy
- [ ] In general the 2x2 button thing looks odd. Feel free to merge or do something subtly different

Ultimately Im not sure if we will be able to automate this as was originally planned. So its possible that we need to manually add these to each (XF2) product. Tagging @JakeBooher in case there is something clever we can do

**Comment by LukasWieditz** [comment]
@Ian-Hitt
