### ISSUE TITLE
[TH] Covers - split up permissions to a complete per-content basis

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2addon-issues#650]
We currently have a Use covers on x/y/z permission for each individual content type, but individual permissions like upload/download/use preset, etc. are only generally set.

This would introduce some compatibility issues with existing extensions for the add-on, where 3rd party extensions might not have the required setup to mitigate these changes out of the box, so we'd probably want to do this on a second dot release earliest.

**Comment by daltonp** [comment]
#619
