### ISSUE TITLE
[QA Forums] Add Structured Data

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#658]
This is forward thinking but Google has already launched experiments for Q&A Structured Data markup (among other types of microdata). Would be good to keep this as a consideration going forward to markup Q&A Threads.

Relevant resource for markup:
https://schema.org/QAPage

**Comment by LukasWieditz** [comment]
We'll look into this, but might not implement it, for the next update.

**Comment by jonw316** [comment]
Example: https://www.question2answer.org/qa/

**Comment by jonw316** [comment]
I'm thinking it might be easier to do this as a separate add-on as the template modifications can get quite complicated and it would be nice to add some more structured data for non-questions and content from other add-ons (e.g. Post Comments).

@LukasWieditz @JakeBooher Thoughts?

**Comment by LukasWieditz** [comment]
Can consider adding structured data into our themes, but structured data related to the specifics of each add-on (QA, Post Comments) should still go into the respective add-ons, if anywhere.
