### ISSUE TITLE
Topics widget - children items unchecking when parent deselected - not as expected

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#664]
https://gfycat.com/NecessaryNervousAffenpinscher

Ignore jumping around thats just #663 

Not a priority, just logging

**Comment by LukasWieditz** [comment]
Dunno what exactly is going on in your installation, but normally unselecting the parent should (in addition to unselecting it ofc) also unselect all children, as the child list will be folded and hidden again, so we don't want any invisible filters to stay around.
