### ISSUE TITLE
Remove hardcoded phrases

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2addon-issues#666]
Stumbling over lots of hardcoded phrases lately. Please turn them all into phrases and don't hardcode them anymore in the future.

**Comment by mikecreuzer** [comment]
Which add-ons?

**Comment by JakeBooher** [comment]
There are several places in different add-ons with hardcoded phrases still, not sure why this was closed with no comment...

**Comment by mikecreuzer** [comment]
I think we'll need to be specific, I wouldn't know what to look for if this was assigned to me

**Comment by mikecreuzer** [comment]
Ian tells me he is unaware of any. Closing now
