### ISSUE TITLE
Replace thumbs up with smilie

### ISSUE THREAD

**Issue by nikkiradloff** [Audentio/xf2addon-issues#684]
Attaching one-color svg of the icon

@mikecreuzer can elaborate more if needed
[smilie.svg.zip](https://github.com/Audentio/xf2addon-issues/files/2379716/smilie.svg.zip)

**Comment by mikecreuzer** [comment]
@nikkiradloff smilie looks kinda off is this from a set?

**Comment by nikkiradloff** [comment]
updated icon in first comment with outline version

**Comment by Ian-Hitt** [comment]
@LukasWieditz SP is set and image is uploaded, but throwing this error
```
Template public:th_reaction_list_reactions: No template type was provided. Provide template name in type:name format. (src/XF/Template/Templater.php:1228)
```

Looks like you are using the SP in PHP for the function reaction_trigger_icon()

**Comment by LukasWieditz** [comment]
That has nothing to do with this issue though, so please create a separate issue for that.
