### ISSUE TITLE
show all topic select modal clear doesnt work

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#686]

**Comment by Ian-Hitt** [comment]
Steps to replicate:

1. open modal to select topics (shows in horizontal scroller for mobile), and select a topic.
2. use the clear all X button (not the x that clears the topic itself.)

**Comment by jonw316** [comment]
I'm struggling to replicate this. Did you ever manage to get it to happen on your home computer?
