### ISSUE TITLE
on create thread page only show selected sub topics

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#695]
Showing all sub topics here sucks. Hide deselected sub topics in a collapse/expand menu?

<img width="1004" alt="screen shot 2018-09-10 at 4 02 12 pm" src="https://user-images.githubusercontent.com/15836384/45324163-f472c080-b512-11e8-89aa-8fcea08e274b.png">

**Comment by mikecreuzer** [comment]
https://github.com/Audentio/xf2addon-issues/issues/750
