### ISSUE TITLE
Bookmarks: Remove "See more" button when limit isn't reached

### ISSUE THREAD

**Issue by Matthew2D** [Audentio/xf2addon-issues#7]
I think you should remove the "See more" button when the bookmark limit isn't reached.

**Comment by JakeBooher** [comment]
I've done it the way it is intentionally to keep it consistent with the other tabs, for example on Postings it shows up even if the user only has one post:

<img width="1200" alt="screen shot 2017-08-03 at 10 04 07 am" src="https://user-images.githubusercontent.com/179180/28928557-1c5bc45c-7833-11e7-9963-52955770e3fb.png">
