### ISSUE TITLE
Install and Upgrade add-on

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#706]
- [ ] Install and upgrade
- [ ] External service providers
- [ ] Method to do a ThemeHouse add-on that supports themehouse.com API
- [ ] Support for themes/add-ons  (UIX addon)

**Comment by mikecreuzer** [comment]
Essentially, we want a way for the community to have a product, but also (maybe a different? product) that funnels all our customers to one add-on with XenForo. We already have UI.X addon that does themes. We can start with that?

**Comment by LukasWieditz** [comment]
https://docs.google.com/document/d/1FGQxA9E_x7anT3PV2kF8M3pMbzQZPRM9K_WzVUoGtd8

**Comment by LukasWieditz** [comment]
Splitting this up in different issues now.
