### ISSUE TITLE
[TH] Topics - disable post-thread

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#707]
Add option can disable Topics show from post-thread.

![screenshot00308](https://user-images.githubusercontent.com/6899856/45448832-cc7e8b00-b6d3-11e8-89c8-e01520ad0948.png)

**Comment by Nirjonadda** [comment]
SP > [TH] Topics: Create Thread

Enable topic bar

Remove breadcrumb

**Comment by LukasWieditz** [comment]
If your users are unable to set topics, that would ruin the purpose of the product.
