### ISSUE TITLE
Remove the X closer on create new post page in topic header

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#738]

**Comment by jonw316** [comment]
The X closer still needs to be there if there are multiple topics assigned to a forum.

**Comment by mikecreuzer** [comment]
What is this exactly?

**Comment by jonw316** [comment]
For forums with only one topic, we don't need the closer. Or do we want to still leave open the option of not having a topic?

**Comment by jonw316** [comment]
Going to leave this as it is for now. #950 is the main thing that is needed.
