### ISSUE TITLE
Secondary trigger is skewed

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#748]
![image](https://user-images.githubusercontent.com/1217271/45697150-c1d85180-bb2a-11e8-8cf1-844e7c39ea3c.png)

**Comment by Nirjonadda** [comment]
I am see this.

![screenshot00327](https://user-images.githubusercontent.com/6899856/45705552-2d95db00-bb7a-11e8-9da7-e2e8bdc58da2.png)

**Comment by Nirjonadda** [comment]
does not know if this happen for this, Enable Hover for Triggers option not working but still open in hover without first click.

**Comment by mikecreuzer** [comment]
> does not know if this happen for this, Enable Hover for Triggers option not working but still open in hover without first click.

Not sure what you mean on this, if its a new issue can you make a new issue on it? Apologies and thank you!
