### ISSUE TITLE
Mobile topics filter: usability issue

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#749]
- [ ] Create a setting on the widget for whether multi or single select is enabled (default I think can be multi)
- [ ] Apply it so we remove the checkbox being different from the link, they both will either multi OR single select the topic - this is a large issue on mobile and we will just avoid it
- [ ] KEEP the modal as multiselect regardless of the setting - that way if anyone does want multiple they can use the all topic modal to choose

**Comment by mikecreuzer** [comment]
Sorry for this guys, I thought about it and decided this had to be done

**Comment by Ian-Hitt** [comment]
Will need @kylerc as well for the js changes regarding differentiating the function for the modal items

**Comment by mikecreuzer** [comment]
Is everyone on the same page here at least? We had a lot of calls about this, and after playing with it for the last month or two, this is what I am confident in

**Comment by mikecreuzer** [comment]
@jonw316 do you feel confident in this? If not let me know and I can talk to kyler about sparing an hour or two or whatever

**Comment by jonw316** [comment]
Should be simple enough, although will probably take me longer than Kyler so up to you.

**Comment by mikecreuzer** [comment]
Since he is stuck on Geex, it would be ideal if he doesnt have to. But feel free to ask him questions. Ill keep you assigned for now, thank you @jonw316
