### ISSUE TITLE
[Nodes] Option for create thread trigger to go straight to create thread page (and not modal)

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#756]

**Comment by jonw316** [comment]
Is this assigned to the wrong project (i.e. Nodes instead of Topics)?

**Comment by LukasWieditz** [comment]
I'm pretty sure he references to this button:
![dhwfjdr](https://user-images.githubusercontent.com/38475165/45959953-63740d00-c01b-11e8-8736-7763c8974e32.png)

It seems to point to the right page already, just opens it in a modal at the moment. Just a matter of removing the overlay trigger in the template if I'm not mistaken.

**Comment by mikecreuzer** [comment]
Its assigned correctly, just related to something similar we are doing in Topics. Here, we just want a setting that lets you go direct without a modal (for Nodes). Referenced it just as its a similar UX concern, but in Topics I think we dont need a setting we just need a proper method that doesnt add additional clicking
