### ISSUE TITLE
Topics Error Log

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2addon-issues#759]
Using UI.X Pro + Topics. Judging by the error log seems it must be clashing with another add-on. I got this error after another user posted in a thread and though the post is recent, it sits in between older posts on the same page. Weird. Here is the error log:

ErrorException: Template error: Method canChangeTopics is not callable on the given object (EWR\Atendo\Entity\Thread) src/XF/Template/Templater.php:936
Generated by: Savage Sep 19, 2018 at 5:55 PM
Stack trace
#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Method canChang...', '/home/gnonline/...', 936, Array)
#1 src/XF/Template/Templater.php(936): trigger_error('Method canChang...', 512)
#2 internal_data/code_cache/templates/l1/s66/public/thread_view.php(488): XF\Template\Templater->method(Object(EWR\Atendo\Entity\Thread), 'canChangeTopics', Array)
#3 src/XF/Template/Templater.php(1250): XF\Template\Templater->{closure}(Object(SteamAuth\XF\Template\Templater), Array)
#4 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('thread_view', Array)
#5 src/XF/Mvc/Renderer/Html.php(48): XF\Template\Template->render()
#6 src/XF/Mvc/Dispatcher.php(332): XF\Mvc\Renderer\Html->renderView('XF:Thread\\View', 'public:thread_v...', Array)
#7 src/XF/Mvc/Dispatcher.php(303): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#8 src/XF/Mvc/Dispatcher.php(44): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#9 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#10 src/XF.php(329): XF\App->run()
#11 index.php(13): XF::runApp('XF\\Pub\\App')
#12 {main}
Request state
array(4) {
  ["url"] => string(43) "/threads/advertisement-thread.18340/page-12"
  ["referrer"] => string(38) "https://www.joyfreak.com/forums/-/list"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}

**Comment by jonw316** [comment]
I've tested the add-on with XenAtendo and I can't replicate the above issue.

**Comment by LukasWieditz** [comment]
@joyfreak can you investigate which add-on is causing this error? Try disabling them one by one until the error doesn't pop up anymore.
