### ISSUE TITLE
UI.X Pro (xenPorta Features)

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2addon-issues#760]
![xenporta features](https://user-images.githubusercontent.com/43339306/45769377-529c5380-bc37-11e8-97cd-0f9ffa15ef77.png)

Does not fit screen like in XF Default theme. Go compare.

**Comment by LukasWieditz** [comment]
Theme issues belong into https://github.com/Audentio/xf2theme-issues/issues
