### ISSUE TITLE
Topics

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2addon-issues#761]
![addon](https://user-images.githubusercontent.com/43339306/45773259-c17eaa00-bc41-11e8-8b2f-13578a355a39.png)

When selecting topics in an overlay then exiting, this is what happens:

**Comment by mikecreuzer** [comment]
This is fixed in a more recent version. Will close, but curious how you got this. What version?

**Comment by joyfreak** [comment]
[TH] Topics 1.0.0 Release Candidate 2

**Comment by mikecreuzer** [comment]
Thats what was released last, so will leave open. But I think its resolved in next release at minimum

**Comment by jonw316** [comment]
Can anyone else replicate this?

**Comment by LukasWieditz** [comment]
As Mike stated above it may already be solved in our current work state.

**Comment by mikecreuzer** [comment]
I was able to replicate this by:

1. Open All Topics modal
2. Make an edit
3. Click close on modal

**Comment by jonw316** [comment]
I'm not even sure what I'm trying to replicate (there seems to be several things wrong in that screenshot), but I can't replicate any of them. Are you sure this isn't a caching issue due to old JS/CSS?

**Comment by jonw316** [comment]
I've managed to replicate this now.
