### ISSUE TITLE
UIX Pro filters dropdown appears opposite side between topics/forums 

### ISSUE THREAD

**Issue by arm5ky** [Audentio/xf2addon-issues#770]
Add-on Name:
UIX Pro
Add-on Version:
UIX Pro
XenForo Version:
v2.0.9
Operating System (and Version):

Browser Name (and Version):

Summary of issue:

UIX Pro filters dropdown appears opposite side between topics/forums 

Detailed steps to reproduce the issue:

Upload any screenshots related to the issue below

![image](https://user-images.githubusercontent.com/6074069/45843394-64edbe80-bd17-11e8-8c89-688a91760a8e.png)
![image](https://user-images.githubusercontent.com/6074069/45843402-6e772680-bd17-11e8-9c1d-9940f344547a.png)

**Comment by mikecreuzer** [comment]
This appears to be happening still on default theme

**Comment by jonw316** [comment]
Works fine for me on default theme.

**Comment by mikecreuzer** [comment]
I noticed it on @Ian-Hitt 's demo - trending and new posts pages. Maybe he is behind

**Comment by LukasWieditz** [comment]
Those screens appear to be from a UI.X theme. Might be theme specific

**Comment by mikecreuzer** [comment]
No I checked on default Hes not in right now or Id screen

**Comment by mikecreuzer** [comment]
![image](https://user-images.githubusercontent.com/1217271/46879004-76078800-ce0a-11e8-888d-cf8921a379ba.png)

**Comment by jonw316** [comment]
The bug was that that wasn't happening.

**Comment by mikecreuzer** [comment]
The filters trigger should just stay in one place (the right)

**Comment by jonw316** [comment]
If you compare with the filters on a forum page, for example, this is not the case. It switches from one side to the other depending on whether there are filters selected or not. I don't make the rules!

**Comment by mikecreuzer** [comment]
![image](https://user-images.githubusercontent.com/1217271/46879500-d8ad5380-ce0b-11e8-90d6-3d289d768db5.png)

**Comment by jonw316** [comment]
That doesn't count!

**Comment by mikecreuzer** [comment]
![image](https://user-images.githubusercontent.com/1217271/46879918-e3b4b380-ce0c-11e8-954e-07c8070588a3.png)

lol

**Comment by jonw316** [comment]
I would have agreed with you if you'd posted this:
<img width="735" alt="screenshot 2018-10-12 at 16 54 47" src="https://user-images.githubusercontent.com/42781420/46880067-96056e80-ce3f-11e8-9a56-e7e9efb8b46e.png">

**Comment by mikecreuzer** [comment]
Are you trolling me Jon lol every page I see has Filter trigger on right

**Comment by mikecreuzer** [comment]
OK so we can close this?
