### ISSUE TITLE
Reactions - 'Reactions given' page doesn't work

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2addon-issues#771]
As per title, at url **[profile]/reactions?type=given&reaction_id=2**:
![image](https://user-images.githubusercontent.com/34864926/45847520-3a096780-bd23-11e8-8d70-384c6cf4d061.png)

**Comment by jonw316** [comment]
@tom-coward This might be conflicting with another add-on. Does this still happen with other add-ons disabled?

**Comment by Nirjonadda** [comment]
Yes, I am also Can not Replicate.

Reactions given by
Reactions received by

both working in my test site from [TH] Reactions 1.0.13 Patch Level 2

**Comment by tom-coward** [comment]
@jonw316 Only seem to be encountering issue with certain users, for example here: https://fellowsfilm.co.uk/members/leylandnationalstagecoach.12163/reactions?type=given&reaction_id=2, with it working fine here: https://fellowsfilm.co.uk/members/whistlehead.3/reactions?type=given&reaction_id=2

**Comment by LukasWieditz** [comment]
Judging from the fact that one profile url is accessible without an account and the other one is not, it might be related to the privacy settings of the user.

**Comment by LukasWieditz** [comment]
@tom-coward Could you send us acp login details for that page through a ticket please? I'd like to have a look at a few things.

**Comment by tom-coward** [comment]
https://www.themehouse.com/customer/tickets/12124

**Comment by LukasWieditz** [comment]
Thank you. Do you hard delete content on your board? Looking at the settings, and code, the situation is that the whole page content gets filtered out. There's two reasons why this could happen:

- The viewing user does not have permission to view any item on the page
- All content of the reactions that would've been displayed on the page has been deleted

Do you hard delete content at your board?

**Comment by tom-coward** [comment]
We rarely hard delete any content, no

**Comment by LukasWieditz** [comment]
Thanks. Did some further debugging. It appears all the reactions on that page for the user are from conversation messages, hence not viewable for anyone not part of that conversation. It's a pretty rare edge case. I doubt we can actually fill the page with content, but I'm gonna build in a message stating that there's no *viewable* reactions on this page to explain to users why the page is empty.

**Comment by tom-coward** [comment]
Just thinking, would it not make more sense to simply exclude reactions when selecting them to show in the profile list anyway if they're from, for example, a conversation message?
