### ISSUE TITLE
Downgrade to last version

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#773]
I just thought or this. We have issues where we release ardons and something so small ends up having huge consequences, and even makes it past testing.

My idea is to add a downgrade back to previous version for add-ons and themes. I don't know if feasible but this would help so much.

**Comment by LukasWieditz** [comment]
Downgrading is mechanically not possible.

**Comment by LukasWieditz** [comment]
Downgrading is not a thing in XF. You can uninstall and then install a lower version, but that'll cleanse your installation of all data. There's no mechanism to reverse database changes.
