### ISSUE TITLE
Topic filter bar state can show incorrectly

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#776]
1. Click on global topic filter
2. Go to a page that doesnt have anything to filter, say members
3. Click on a different topic on the global topic filter

![image](https://user-images.githubusercontent.com/1217271/45894832-2c8cc580-bd95-11e8-9a3a-f6f10b6e735d.png)

**Comment by jonw316** [comment]
I can't replicate this. What do you mean by "global topic filter"? Is this only on UI.X Pro theme?

**Comment by mikecreuzer** [comment]
Its whenever the topic filter is global, as you wouldnt be able to do step 2 if not

**Comment by jonw316** [comment]
Still can't replicate. I've never seen a mismatch between the widget and the filters.
