### ISSUE TITLE
[Trending] Allow options to criteria

### ISSUE THREAD

**Issue by arm5ky** [Audentio/xf2addon-issues#777]
Add-on Name:
[TH] Trending
Add-on Version:
101 Patch Level 1
XenForo Version:

Operating System (and Version):

Browser Name (and Version):

Summary of issue:
This is a enhancement request.  Allow an options screen of criteria for trending.

Include more criteria from Reactions.

**Comment by arm5ky** [comment]
Currently there is no options or criteria for trending. You may want to not include likes, just views or vice versa. You may want to only include threads from the last week. Etc etc.
Currently there is no indication what drives the trending threads

**Comment by arm5ky** [comment]
And yes, you may want to use positive reactions as one of those criteria

**Comment by mikecreuzer** [comment]
I agree, ultimately we had Trending Pro planned, but never finished it and it had dozens of criteria. We will be planning to update Trending properly after Pro goes live, right now its a light version that is OK but I agree we need to replan the scope of the product.

**Comment by LukasWieditz** [comment]
This is already possible
