### ISSUE TITLE
Topics - No topics available.

### ISSUE THREAD

**Issue by arm5ky** [Audentio/xf2addon-issues#781]
Add-on Name:
Topics
Add-on Version:
 [TH] Topics 1.0.0 Release Candidate 2
XenForo Version:
v2.0.9
Operating System (and Version):

Browser Name (and Version):

Summary of issue:
When in forum list and go to a node with no topics set  and post a message i get the message:
"No topics available."

I know there are no topics available as that's the setting for node., so why not remove if no topics available.

Upload any screenshots related to the issue below
![image](https://user-images.githubusercontent.com/6074069/45928016-9abbbe80-bf34-11e8-8eb0-262f4e6c9d47.png)

**Comment by LukasWieditz** [comment]
You should never have nodes that don't allow the selection of a topic. That defeats the entire purpose of topics.
