### ISSUE TITLE
[Topics] Only show threads from nodes with topics enabled in Trending/Latest Threads

### ISSUE THREAD

**Issue by arm5ky** [Audentio/xf2addon-issues#782]
Add-on Name:
UIX Pro RC3
Add-on Version:
UIX Pro RC3
XenForo Version:
v2.0.9

Summary of issue:

Xenforo gives an option to exclude a node from new posts, and not to appear in node list.

Have similar settings to allow exclusion from trending/latest threads/new posts on the MainTabBar. 

Why:

If your forum has a main focus, you would want to focus on that. But then most forums also have a discussion area which is off topic for the niche of site and also have  an area for site changes, bugs etc.
I want to use Topics to focus only on niche. The other nodes, I have set no topics against and people can use "Whats new" to refer to whole site.

**Comment by mikecreuzer** [comment]
To be clear, this would be two settings right?

1. Show: (All OR  you can choose which ones)
2. Hide (choose which ones to explicitly hide)

**Comment by jonw316** [comment]
I think this is the option being referred to:
<img width="533" alt="screenshot 2018-11-22 at 12 15 54" src="https://user-images.githubusercontent.com/42781420/48902417-70ad4c80-ee50-11e8-9efa-eb9ba2f4be0e.png">

**Comment by arm5ky** [comment]
> I think this is the option being referred to:
> <img alt="screenshot 2018-11-22 at 12 15 54" width="533" src="https://user-images.githubusercontent.com/42781420/48902417-70ad4c80-ee50-11e8-9efa-eb9ba2f4be0e.png">

That's basically what i'm referring to, To either adhere to that setting or add a similar checkbox against a node, to include node in trending and latest threads.

**Comment by arm5ky** [comment]
I suppose but administration could get a bit messy. That's why I was trying to simplify by making it node specific.
