### ISSUE TITLE
UIX Pro RC3 - Console Error 

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#783]
UIX Pro RC3

Check it here:
https://zumbatalk.com/forum/trending/threads.1/

No other addons or anything installed/changed. Base install with UIX Pro RC3.

content_script.js:1 Uncaught TypeError: Cannot read property 'style' of null
    at setStyle (content_script.js:1)
    at e (content_script.js:1)
    at HTMLDivElement.<anonymous> (content_script.js:1)

**Comment by LukasWieditz** [comment]
I'm not seeing any errors on that page, console is empty.

**Comment by ichpen** [comment]
> I'm not seeing any errors on that page, console is empty.

Me neither today. WTF, it was there yesterday and I've not changed a single bit. Must be the North Westerly wind changing direction. Thanks for checking, you can close this guy.
