### ISSUE TITLE
UIX Pro RC3 - Whitespace Galore

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#784]
I like minimalist as much as the next guy but there's way too much unused white space at 1080p +.

Suggestion, break it up into more/smaller columns or even a grid like layout. Move Topics to the middle, add list of users (avatars) in there, add trending index (views) in there etc etc. There's a lot you can do with that whitespace.

![whitespace](https://user-images.githubusercontent.com/5346876/45930088-1ca5ea80-bf29-11e8-8845-69423ce3ffba.png)

**Comment by ichpen** [comment]
> Are you modifying or toggling width?
> 
> I tend to agree you should fill space, but in this case (XenForo) and to work with add-ons, there isn't much you can do. That said, this style of view is a style property, you can go back to table view.

Let me check, I've not messed around with any properties yet. Thanks for the quick response.

**Comment by Ian-Hitt** [comment]
This is intentional styling . It does look like you do not have a sidebar on this page, which is intended for trending, topic thread list, and forum new posts as we discussed in slack :)
