### ISSUE TITLE
[Topics] Autocomplete/Typeahead Feature

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#786]
Make it easier to create a thread, offer autocomplete/typeahead for topics so user can quickly spacebar their way past the screen.

**Comment by mikecreuzer** [comment]
Can you elaborate on this a bit? What specifically do you recommend?

**Comment by ichpen** [comment]
> Can you elaborate on this a bit? What specifically do you recommend?

Sure, today I hit Post Thread, I get the topics modal, I have to use my mouse to click the topic(s) then mouse to continue. 

Tomorrow, I start typing topic name, topic is suggested  in my input box, I hit space to select suggestion and autocomplete it, I can continue typing secondary topic etc etc I hit enter to go on. Makes it a bit more streamlined, plus I don't get to try to find my topic in a wall of text eventually (especially with similarly spelled topics). This can work in conjunction with the filtering you have right now in the topic selection modal.
