### ISSUE TITLE
UIX Pro 3 - Needs a Quick Thread Feature

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#787]
Given Pro is all about highlighting and encouraging relevant discourse I'd like to suggest the ability to utilize XF's native quick reply/thread feature to create threads with topics (and optional tags) right from any of the popular views like new_posts, all-threads?topics=XXX, trending etc.... The experience would be similar to XF's with the added ability to quickly select topics as well as thread tags (optional).

**Comment by ichpen** [comment]
> Hmm this should have been planned for, and something that should just work out of the box. I think we made it a widget though? Tagging @Ian-Hitt

Could be user error, but I've not seen a widget or option to enable quick thread. Hopefully Ian is hiding it somewhere in anticipation of this suggestion :)

**Comment by LukasWieditz** [comment]
Quick thread should be available at all three topic routes and at the trending threads view
