### ISSUE TITLE
UIX Pro - Remove Post Thread In Modal

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#788]
If I'm in a topic, and you've already preselected my topic why do I need this modal screen again? Especially since I can add more topics on the create thread screen thereafter?

I suggest remove this modal entirely to streamline experience.

![remove-screen](https://user-images.githubusercontent.com/5346876/45930236-a22a9a00-bf2b-11e8-96b8-f628293b642f.png)

**Comment by LukasWieditz** [comment]
@jonw316 The topic should only be pre-selected here if there's only one topic associated with the given forum. I guess we can either just always forward to the create thread form or only do it if there's only one topic to pre-select. Either way we wanna make sure that people are still "forced" to select a topic no matter what we do here.

**Comment by jonw316** [comment]
I think the current implementation streamlines the user experience enough without being inconsistent.

Taking thread prefixes as an example of a different type of filter: if you filter by a prefix and then click Create Thread it does not automatically select that prefix on the Create Thread page.

**Comment by ichpen** [comment]
> I think the current implementation streamlines the user experience enough without being inconsistent.
> 
> Taking thread prefixes as an example of a different type of filter: if you filter by a prefix and then click Create Thread it does not automatically select that prefix on the Create Thread page.

I have to disagree on this a little. Firstly conceptually you should not be setting the bar at being consistent with XF base features (prefixes etc are different beasts IMHO and are entirely optional), topics is supposed to be a different, more streamlined and engaging experience that's content centric. Any time you put a modal that can be avoided you're making the experience less streamlined. Take for instance your bookmarks addon, you have an option to popup a modal or not (by default) which to me is a good compromise. 

I would encourage you to at least give the admin the option to kill as many modals as possible.

**Comment by LukasWieditz** [comment]
As we do indeed have the topic selection in the thread create form, we should indeed consider if the modal is really necessary. I'm personally not familiar with why this design choice was made, as it was already implemented when I took over the project. Maybe @Ian-Hitt @JakeBooher @mikecreuzer have more to say about this.

**Comment by jonw316** [comment]
The create thread screen has now been simplified, so now the modal makes more sense. Closing.
