### ISSUE TITLE
Topics - "Redirect forum list to topic list" - Trending Widget Has Fourm name and link

### ISSUE THREAD

**Issue by arm5ky** [Audentio/xf2addon-issues#789]
Add-on Name:
[TH] Topics
Add-on Version:
 [TH] Topics 1.0.0 Release Candidate 2
XenForo Version:
v2.0.9

Summary of issue:

Setting up to use topics rather than forums, yet trending widget has forum name and link in.

Upload any screenshots related to the issue below
![image](https://user-images.githubusercontent.com/6074069/45931690-67475700-bf69-11e8-9f63-3233da59b9bb.png)

**Comment by jonw316** [comment]
There are lots of other widgets and other areas (e.g. search) where this is also the case. If I fix this, I will also have to fix all those other areas, and then we would also have to consider third-party add-ons.
