### ISSUE TITLE
[TH] Reactions - Likes to Reactions in Messages

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#791]
Please add change Likes to Reactions in Messages.

![screenshot00348](https://user-images.githubusercontent.com/6899856/45947225-b4700b00-bff3-11e8-84dc-8bcf0399ca9f.png)

**Comment by jonw316** [comment]
@Ian-Hitt I've made the change in XenForo default theme as requested, but we might want to add this to the UI.X theme too. Probably best to do this in the UI.X theme itself using a conditional to check if the add-on is enabled.
