### ISSUE TITLE
[Topics] Thread Filter/Sort additions

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#793]
Currently I see Author and Last Updated as filters which are not particularly useful and not easy to use.

We need a lot more in my modest opinion.

- [ ] add a few new sorting methods
1. Most Viewed (no of views)
2. Most Active (no replies / 30 or X days days)

- [ ] Tags (XF tags)
- [ ] Prefixes (XF Prefixes)
- [ ] Search - title
- [ ] Search - on first post

- [ ] Quick pick time filters for:
1. Yesterday
2. Last Week
3. Last Month
4. Last Year

Probably others I can't think of at this time.

**Comment by ichpen** [comment]
> I agree quite a bit. Question here is whether XenForo should add these themselves?

Yeah might be a while before we see this in base XF. I can go make the suggestion over there. In mean time I think Prefix filter is already available so ignore that and tags may be problematic if left unrestricted. Rest though would be highly useful IMHO.

**Comment by mikecreuzer** [comment]
@jonw316 specifically Unread as well as discussed

**Comment by LukasWieditz** [comment]
I don't think this is something that should go into topics, but rather the UI.X add-on. None of these filter/sort options are topics specific.

**Comment by jonw316** [comment]
I think the idea is that the purpose of Topics is to improve content discovery, so this fits under that.

**Comment by mikecreuzer** [comment]
Agreed with Jon. Topics is the same as saying Filters.
