### ISSUE TITLE
Watch and Mark Read a Topic

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#803]
Apparently this got skipped, but I think we need it. Im not sure how much work this would be, if we could copy what nodes does and apply it to a Topic. 

Adding priority for now as if its feasible, we need to scope it in before launch, as I expect a lot of people will ask for this.

**Comment by LukasWieditz** [comment]
We had it at some point, but it got deleted along with the topic thread list. The data structure, and I think most logic, still exists.

**Comment by jonw316** [comment]
Probably only going to make this work for primary topics. Adding in secondary topics is probably going to start slowing things down too much. Any objections?

**Comment by LukasWieditz** [comment]
Should be possible to fetch all last read states in one go, and then just check against the required ones thread per thread.

**Comment by jonw316** [comment]
I'm not convinced this is feasible without slowing everything down. Topics are still showing as unread when they are not if someone marks forums as read or marks other topics as read, as the system is just not set up to allow for overlapping forums/topics.

**Comment by mikecreuzer** [comment]
Isn't marking a primary topic as read == marking its forum as read?

Regarding secondary, that I dont know

**Comment by LukasWieditz** [comment]
> Isn't marking a primary topic as read == marking its forum as read?
It used to be, until we introduced multiple the n:1 relation between topics and forums. Now that it's no longer guaranteed that all threads in the forum have that one topic, it's not the same anymore.

**Comment by LukasWieditz** [comment]
Looking at the code in `\ThemeHouse\Topics\XF\Entity\Thread::getVisitorReadDate()`, shouldn't it check all topics already @jonw316 ?

**Comment by jonw316** [comment]
The main problem is to do with the isUnread() method. I can't come up with a way of checking whether a topic is unread that takes into account forums being marked as read if you include secondary topics.

I think primary topics is the only way. I've just finished updating the code to only do primary topics, although I've had to add in an extra column to the DB as I assume that we still want to include secondary topics in the message counts etc.

**Comment by jonw316** [comment]
This is only the "mark as read" stuff so far. I've still got to do the watch topics stuff.

**Comment by LukasWieditz** [comment]
Pretty sure the code for sending is still there. `\XF\Service\Post\Notifier` and `Notifier\Post\TopicWatch`

**Comment by jonw316** [comment]
<img width="933" alt="screen shot 2018-09-27 at 14 44 09" src="https://user-images.githubusercontent.com/42781420/46150158-dbcd0f00-c263-11e8-982b-15dba788efa8.png">
@Ian-Hitt Could you take a look at the styling for the Watched Topics page. It currently looks like nodes, which is OK, but probably not quite right. I wouldn't even know where to start.
