### ISSUE TITLE
[TH] Install & Upgrade - Add support for update UI.X add-on

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#819]
Add support for update/install UI.X add-on.

**Comment by LukasWieditz** [comment]
There is already support for that.

**Comment by Nirjonadda** [comment]
@LukasWieditz Then how to update? I have not find out any way for update.

![screenshot00368](https://user-images.githubusercontent.com/6899856/46137860-c5668980-c24a-11e8-9ac6-b6ea2efdb3a7.png)

**Comment by LukasWieditz** [comment]
Which UI.X add-on version are you running?

**Comment by Nirjonadda** [comment]
[TH] UI.X 2.0.8

**Comment by LukasWieditz** [comment]
Then it should show up once the update cron is run, under the assumption that you have your ThemeHouse Install & Upgrade profile set up correctly.

**Comment by Nirjonadda** [comment]
> ThemeHouse Install & Upgrade profile set up correctly.

Yes.

![screenshot00369](https://user-images.githubusercontent.com/6899856/46142278-c1d8ff80-c256-11e8-893a-c44215ddc432.png)

> Then it should show up once the update cron is run

When run cron? now over 12 hours. manually run this cron but not showing up.

Available add-ons does not have this.

![screenshot00370](https://user-images.githubusercontent.com/6899856/46142359-fea4f680-c256-11e8-8b7b-d77072d3ffa9.png)

**Comment by Nirjonadda** [comment]
One more thing, [TH] UI.X add-on are not show up because this are out side from `/customer/account/api` and this one are free, not in Subscriptions or Purchased.
