### ISSUE TITLE
[TH] Install & Upgrade -  Check for updates

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#827]
Check for updates are not work when new Version available in xenforo.

**Comment by LukasWieditz** [comment]
Considering #826, it looks like you haven't been able to set up your XenForo account details yet? Without that, it will naturally not be able to fetch anything.

**Comment by Nirjonadda** [comment]
Oh that test site are not used Xenforo License, Does this happened for this issue?

**Comment by LukasWieditz** [comment]
I don't exactly understand.

**Comment by Nirjonadda** [comment]
Where I am installed this add-on, The domain are not added in XenForo Customer Area.

**Comment by LukasWieditz** [comment]
Yeah, your XF license must be registered to the same domain that has been entered in the install & upgrade account provider.

**Comment by Nirjonadda** [comment]
So need another Xenforo License for test site? If so then I can not help beta test for this add-on?

**Comment by LukasWieditz** [comment]
There's nothing stopping you from using your registered license on a test site. It's as legal as having the installation in the first place.

**Comment by LukasWieditz** [comment]
I have that one fixed for the next version, see #826, so I'm gonna close this ticket.
