### ISSUE TITLE
Reactions - Unable to delete users if XFMG is installed

### ISSUE THREAD

**Issue by jonw316** [Audentio/xf2addon-issues#833]
https://admin.audent.io/tickets/12027

**Comment by mikecreuzer** [comment]
Is this priority? @jonw316

**Comment by mikecreuzer** [comment]
Or rather urgent?

**Comment by jonw316** [comment]
I have a fix for it.

**Comment by mikecreuzer** [comment]
Urgent to patch*

**Comment by jonw316** [comment]
Not super urgent I don't think. I'll try and fix the other two bugs next week then we can release a patch.

**Comment by jonw316** [comment]
If you want to fix the bug manually, it is line 275 of ThemeHouse\Reactions\Service\User\Deleter. Replace MediaComment with just Comment.

I'm preparing a release now as all the other bugs I wanted to fix have been fixed.

**Comment by lilalien** [comment]
How's this coming along?

You had mentioned 8 days ago there was a release pending.. Is that still coming along?

Thank you!

**Comment by jonw316** [comment]
Release is still pending, sorry. Did you try the manual fix?

**Comment by lilalien** [comment]
No, I did not test that manual fix as you mentioned a release was being prepared.. If you can't get to a release this week let me know, and I'll apply the manual fix so I can complete the maintenance jobs.

**Comment by lilalien** [comment]
OK I updated to the latest version, then ran the "manual rebuild jobs awaiting completion" (since without this fix it would just result in the previously mentioned error).

Unfortunately, what it does now is once it gets to the last item it them circles back and reruns the entire manual rebuild all over again. I'm watching it right now, and its running it for like the 6th time right now.

**Comment by lilalien** [comment]
![problem](https://user-images.githubusercontent.com/35111972/47043814-9c0b9000-d15c-11e8-9288-eddada6334a3.gif)

**Comment by jonw316** [comment]
If it's not still happening, then it might have just been because of the error before that it got stuck. Let me know if it happens again in future.

**Comment by lilalien** [comment]
OK @jonw316 - I'm sure in the next week I'll be doing another unactivated user purge and we'll see what happens!

**Comment by jonw316** [comment]
Thanks. There's nothing special about the user reactions deleting process and we haven't had this reported by anyone else, so I'm hoping that is the last we see of that.
