### ISSUE TITLE
Mark read a topic on front-end

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#834]
Referencing #803 

- [x] Add a trigger (in the form of a dot icon?) to Topics list
- [x] Add a mark all read on topic page filter bar itself
- [x] Modify watched-topics page to include a button to mark that topic as read (same icon is fine)

Anything else we can think of @jonw316 @LukasWieditz ?

**Comment by jonw316** [comment]
Mark all topics read basically does exactly the same thing as mark all forums read, so there is already a link for that in the navigation bar. It can also be replaced with a mark all topics read link if people feel the need (there is a link in the ACP navigation section that is disabled by default).

**Comment by jonw316** [comment]
The above commit also fixes a bug that causes topics to incorrectly be marked as unread.
