### ISSUE TITLE
Reactions - Excruciatingly long queries with deletion of members (reaction deletion queries)

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2addon-issues#841]
Add-on Name: Reactions

Add-on Version: Latest

XenForo Version: Latest

Operating System (and Version): Windows 10 - 64 bit (stable)

Browser Name (and Version): Chrome 69 (stable)

Summary of issue: When doing a deletion of a member, it is quick to delete them with the built-in xf functionality, but then it attempts to delete all their reactions too (even if they NEVER had ANY), and that takes a HUGE period of time.. If you are batch-deleting members (we purge members who never confirm e-mail for example, or spammers, and this can be hundreds of people at a time), the reactions deletion can take FOREVER.

There must be something that can be done to fix this, its pretty severe.

**Comment by lilalien** [comment]
How's this coming along?

The time it takes to delete hundreds of unvalidated members for example is unbearable...

**Comment by LukasWieditz** [comment]
As you can see here, we haven't started on it, as it's scheduled for the release after the next.

**Comment by jonw316** [comment]
This will probably not be fixed now until XF 2.1.

**Comment by lilalien** [comment]
@jonw316 Quite a lot of people will not upgrade to XF 2.1 for a long time.. This function has a bug and makes this feature completely unusable in its current form. We simply can't delete unactivated members on a regular basis anymore because of this add-on. I hope you reconsider if its at all possible.

**Comment by jonw316** [comment]
Potentially we could release another version for XF 2.0 once the code for XF 2.1 is made available.

**Comment by lilalien** [comment]
I would be OK with that.

So there is something inherent to XF 2.0's deletion processes that creates this issue in the Reactions add-on?

**Comment by Nirjonadda** [comment]
Please give fix update for current bug stage, this not happen update XF 2.1 immediately. So we can contributed use in live site.

**Comment by jonw316** [comment]
That will be clearer once we have access to the XF 2.1 code. Feel free to pester the XenForo team and suggest they give developers access to the code as soon as possible!

**Comment by Nirjonadda** [comment]
Do you have any special reason for delaying this bug fix update? Then We are using in Xenforo 2.0, So why you need XF 2.1 for this fix. Make fix for XF2.0. This are not meaning you are open bug for life, when we have broken deleting user. So give bug fix update first.

Thanks

**Comment by jonw316** [comment]
The reason is that the next big upgrade for this add-on will be updating it to work with XF 2.1, so any changes we make now will need to be compatible with that. Any change I make now to try and speed this up will be quite a big change, so I wouldn't want to do anything that makes it less compatible with XF 2.1.

Hopefully we will have access to XF 2.1 code very soon -- possibly within the next few weeks.

I should also say that we do not consider this a bug. Technically it all works as it should, it is just a bit slow on large sites.

**Comment by lilalien** [comment]
I wouldn't call us a large site.. But if you delete a couple hundred inactive users it can take hours stopping you from doing anything else. I know people with sites that just have a few hundred thousand posts total who regularly delete inactive/0 posters and have this add-on and the slowness is unbearable.

If you load up an app, an OS, or most things and you can barely get anywhere because its "processing" something forever I've always seen it classified as a bug myself... I do understand about the 2.1 codebase, but that's going to take forever. You're going to have to finalize a list of what the NEW 2.1 compatible add-on is going to include and no longer include and get working on it and that will take a couple of months at least.

I can no longer run some regular cleanup/maintenance that I've been running since XF came out now because of this one add-on.

**Comment by mikecreuzer** [comment]
I think ultimately, just due to uncertainties, we won't be able to invest more development time into this until 2.1 is at least released to developers, so that we can migrate to their system. When that happens, I think this issue resolves as XenForo will have solved it or at least be responsible for it. I know thats not ideal, but its the situation we are put in.

**Comment by ichpen** [comment]
@jonw316 

On my small ish site was about to log a similar defect. Deleting users now takes a realllllllly long time (deleting reaction 1, deleting reaction 2 etc etc) around 5 mins per user as it goes through 12 reactions.  Prior to reactions it was almost instantaneous. Luckily I don't have to do this too often but major pain when I do.

**Comment by Nirjonadda** [comment]
So what the solution for XF 2.0 ?  Site update to XF 2.1, this will take long time because when XF 2.1 goes to stable then need to wait XF 2.1 compatible add-on update.

**Comment by jonw316** [comment]
All our add-ons will be compatible with XF 2.1 by the time it is stable.

The only reason we would change the data structure in the current version is if there was a demand for a version of Reactions that was an alternative to the XF 2.1 reactions. I am not aware of a single person who wants this.

**Comment by LukasWieditz** [comment]
No longer a thing, as this is now handled by XenForo
