### ISSUE TITLE
Redoing interface for Topic choosing

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#846]
Ultimately every client we talk to, and internally we've wanted this redone, so here is an issue:

![image](https://user-images.githubusercontent.com/1217271/46426899-7e264000-c705-11e8-9ff1-3323c0b7f1b8.png)

I think best way is to just quickly chat about what we want.

**Comment by jonw316** [comment]
Did we make a decision on this? Would it be better to have an option to move "additional topics" to below the editor?

**Comment by mikecreuzer** [comment]
We can revisit once we have secondary topics and such. The experience could subtly change depending on whether or not there are min and Max the user is asked to choose. 

Ultimately it's not smooth, so I have some ideas. But probably best to wait until major concerns are resolved i assume.
