### ISSUE TITLE
[TH] Donate - Donation reminder

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#852]
Please add a option for Sends an email to members reminding them that your forum runs on donations.

**Comment by LukasWieditz** [comment]
You can do that via ACP > Communication > Contact Users > Email users. I don't see any particular benefit in sending this automatically, as a regular "reminder" would likely get you listed as spam through accumulating reports.

**Comment by Nirjonadda** [comment]
Indicates how many emails will be sent.
Ability to send a test email.
Emails are never sent to banned, invalid, or members that have selected not to receive site mailings.
Unsubscribe link provided
Only remind user once

**Comment by LukasWieditz** [comment]
Can all be done via the email users functionality...
