### ISSUE TITLE
If topics not enabled, show node title in forum list

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#855]
![image](https://user-images.githubusercontent.com/1217271/46566432-095d2c80-c8e4-11e8-8dee-8f4bdd1bed00.png)

**Comment by mikecreuzer** [comment]
As you can see it leaves a weird space. Node should be there.

**Comment by Ian-Hitt** [comment]
I guess this is a change to Topics as well as Trending, I presume? This is what the add-ons do on the default theme

<img width="1026" alt="screen shot 2018-10-08 at 3 20 15 pm" src="https://user-images.githubusercontent.com/15836384/46631682-bb2b7180-cb0d-11e8-9cc1-db98d14bde1d.png">
