### ISSUE TITLE
Additional settings we need but do not know we need

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#865]
Making this a generic issue, as I'd like us to unassign ourselves when we feel we cannot think of anything else that we absolutely need.

**Comment by Ian-Hitt** [comment]
This is not a setting, but perhaps we could re-consider how we present the purpose of the primary topic to the users? Right now we have them choose primary first, and then additional, but we do not offer any explanation of the significant of the firs topic (that being that it adds the permissions for the thread.) I think if users don't know this, then thy won't be able to properly use it either.

**Comment by mikecreuzer** [comment]
Thats a good suggestion. I wonder if its as simple as just a message at the top of this modal:

![image](https://user-images.githubusercontent.com/1217271/46825898-4a2cc980-cd5a-11e8-997b-61a6dad107b8.png)

"Select the primary overall topic of discussion." Just show that above the search bar.
