### ISSUE TITLE
Manually edit product associations

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2addon-issues#866]

**Comment by mikecreuzer** [comment]
I was wondering about this over the weekend actually. How could we even build an interface for this? They would need to like choose a provider, AND a URL? Not sure on this. But ultimately everyone has their forum setup already, so they would (currently) need to uninstall then reinstall to use the system. Which simply won't work. My questions:

1. What did you have in mind?
2. Is this pivotal of a feature (as I get the feeling it could be, maybe not for release but super therein after)

**Comment by LukasWieditz** [comment]
You're describing #858
