### ISSUE TITLE
Clean code up

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#868]
Another generic issue. Making a few issues as points to aim for:

- [x] Once completed with any new issues/settings, clean code up such that there is no randomly commented out code
- [x] Reorganize as needed
- [x] Ensure it should upgrade easily
- [x] Ensure it should be easy to build on top of
- [ ] CSS cleanup

**Comment by jonw316** [comment]
This really needs to be done first.
