### ISSUE TITLE
[TH] Install & Upgrade - ThemeHouse-UIX-2.0.8_Patch_Level_1.zip

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#870]
Can not update UIX add-on from ZIP files.

````
Oops! We ran into some problems.
This add-on cannot be installed. 
````

**Comment by Nirjonadda** [comment]
This now show in Available update After this error.

**Comment by LukasWieditz** [comment]
You can only install from zip, not update.

**Comment by Nirjonadda** [comment]
Can update from RM URL?

**Comment by Nirjonadda** [comment]
Not, Show in Upgradeable add-ons but error.

![screenshot00483](https://user-images.githubusercontent.com/6899856/46617243-8f63b800-cb1c-11e8-914b-0cb9b17a6b93.png)

**Comment by LukasWieditz** [comment]
If you try to install an already installed add-on, it'll extract the files correctly (except for that one file listed in your screenshot, but I got that fixed for the next update), but it can't install the already installed add-on. That button/function is really for installing only, not updating.
