### ISSUE TITLE
Layout manager for Topics

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#872]
Currently its a very easy going format. I had a couple suggestions to maybe add to it:

- [ ] When new topics are created, they get added to the system (and nested if secondary)
- [ ] A setting to disable this auto-add (this is what WP does)

**Comment by jonw316** [comment]
@mikecreuzer Is this priority?

**Comment by mikecreuzer** [comment]
I don't know. Theoretically if it continues to let people set up topics it's fine. But I wonder if it's not needed with Groups now

**Comment by LukasWieditz** [comment]
Iirc, they already get auto-added upon creation

**Comment by jonw316** [comment]
Correct.

**Comment by mikecreuzer** [comment]
It didn't before. That must be new?

**Comment by LukasWieditz** [comment]
https://github.com/Audentio/xf2/commit/ab9dbfc3981a4054ef9d2f049752f969aac9af7a#diff-3ef74bbb2127d04152f4a394b7caf5fa

Got added on June 6th

**Comment by mikecreuzer** [comment]
After talking with Jon I dont think we need this
