### ISSUE TITLE
[I&U] DragonByte eCommerce

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#876]
Add support for DragonByte eCommerce.

https://xenforo.com/community/resources/dbtech-dragonbyte-ecommerce.6387/

**Comment by mikecreuzer** [comment]
@LukasWieditz to me, since this is a third-party, should we not leave this up to those developers to support this? I think he is running a custom cart system. Same with Chris' cart system.

**Comment by LukasWieditz** [comment]
I'm keeping it in the backlog, but the add-on dev can always create the handler himself and push it to our repo if he wants.

**Comment by LukasWieditz** [comment]
Implemented
