### ISSUE TITLE
[TH] Install & Upgrade - On/off button

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#878]
Add On/off button for disable without delete.

![screenshot00485](https://user-images.githubusercontent.com/6899856/46618194-321d3600-cb1f-11e8-9b22-c3e4466a46aa.png)

**Comment by mikecreuzer** [comment]
Quite useful, especially if a site goes offline, could throw errors. And in general, always good to have a quick toggle system for anything like this.
