### ISSUE TITLE
Node Layout Separator Issues - Word "separator" appears when Node Grid is disabled

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#88]

**Comment by JakeBooher** [comment]
Unfortunately nothing we can do about this, it's just how XenForo handles node types that aren't handled by an add-on.

**Comment by daltonp** [comment]
![screen shot 2017-12-19 at 3 18 05 pm](https://user-images.githubusercontent.com/32306910/34179310-06c685fa-e4d0-11e7-95df-291ab592a53f.png)
![screen shot 2017-12-19 at 3 18 23 pm](https://user-images.githubusercontent.com/32306910/34179328-13e87f90-e4d0-11e7-8eaf-31a491e37590.png)

This was tested on [demo.themehouse.com/xf2/themes](https://demo.themehouse.com/xf2/themes), none of our other demo boards show this issue. Both the add-on and theme used are both up to date. 

To replicate this, navigate to the administrative panel > Forums > Nodes > Add Node > Select the node type Node Layout Separator > Proceed to the nodes editing menu > Add a random title > Save the node separator's title > Refresh the forum itself before viewing it, you should then see random text that says "separator".

**Comment by JakeBooher** [comment]
Does this only happen when the Nodes add-on is disabled?
