### ISSUE TITLE
Q&A Add-on & Topics Compatibility 

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xf2addon-issues#880]
The Q&A Add-on isn't working with Topics. All of my nodes are tied to a Topic and I am using Topics instead of the forum list. I have set up the nodes to always have threads as questions.

**Comment by mikecreuzer** [comment]
Since primary topics require a node, I suppose that you would need to simply set the node as a QA node and it should work with those respective topics.

**Comment by mikecreuzer** [comment]
@victoriad can you have screens, video, or steps to replicate?

**Comment by mikecreuzer** [comment]
Ah this is by design. Its quite difficult to "merge" forum settings. In this case, "Topic 2" and "Topic 1" in each of the latter screens are primary nodes, and therefore, QA will only work there. QA will need to be primary for it to work.
