### ISSUE TITLE
[TH] Install & Upgrade - Error when attempting to add/edit profiles

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#884]
XF\Db\Exception: MySQL statement prepare error [1054]: Unknown column 'has_tfa' in 'field list' in src/XF/Db/AbstractStatement.php at line 212
XF\Db\AbstractStatement->getException() in src/XF/Db/Mysqli/Statement.php at line 196
XF\Db\Mysqli\Statement->getException() in src/XF/Db/Mysqli/Statement.php at line 39
XF\Db\Mysqli\Statement->prepare() in src/XF/Db/Mysqli/Statement.php at line 54
XF\Db\Mysqli\Statement->execute() in src/XF/Db/AbstractAdapter.php at line 79
XF\Db\AbstractAdapter->query() in src/XF/Db/AbstractAdapter.php at line 160
XF\Db\AbstractAdapter->insert() in src/XF/Mvc/Entity/Entity.php at line 1403
XF\Mvc\Entity\Entity->_saveToSource() in src/XF/Mvc/Entity/Entity.php at line 1135
XF\Mvc\Entity\Entity->save() in src/XF/Mvc/FormAction.php at line 69
XF\Mvc\FormAction->XF\Mvc\{closure}() in src/XF/Mvc/FormAction.php at line 159
XF\Mvc\FormAction->run() in src/addons/ThemeHouse/InstallAndUpgrade/Admin/Controller/InstallUpgradeProfiles.php at line 99
ThemeHouse\InstallAndUpgrade\Admin\Controller\InstallUpgradeProfiles->actionSave() in src/XF/Mvc/Dispatcher.php at line 249
XF\Mvc\Dispatcher->dispatchClass() in src/XF/Mvc/Dispatcher.php at line 88
XF\Mvc\Dispatcher->dispatchLoop() in src/XF/Mvc/Dispatcher.php at line 41
XF\Mvc\Dispatcher->run() in src/XF/App.php at line 1931
XF\App->run() in src/XF.php at line 329
XF::runApp() in admin.php at line 13

**Comment by LukasWieditz** [comment]
You can update from alpha, you have to reinstall still...
