### ISSUE TITLE
Topics filter: When canvas is collapsed, filters do not show up

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#886]
![screen shot 2018-10-09 at 12 48 24 pm](https://user-images.githubusercontent.com/1217271/46687893-a1e3fd00-cbc1-11e8-8571-a972ed08162e.png)

At minimum side navigation content needs to EQUAL off canvas. They still do not despite a few issues on it. That would be part of the solution (as right now I could not filter topics at this viewport size)

Another concern might be whether or not having them open the canvas is the best experience.

**Comment by Ian-Hitt** [comment]
@mikecreuzer this is a style property that needs to be set in Topics, so not a bug

**Comment by mikecreuzer** [comment]
Needs to be the default then?

**Comment by Ian-Hitt** [comment]
No? Its default is correct
