### ISSUE TITLE
Move free add-ons to a place people can submit PRs on

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#890]
Not sure best way to do this, but might be a good idea for all of our free add-ons. License may need to change as well on that, but not sure what to.

**Comment by JakeBooher** [comment]
All of our open source add-ons are already on GitHub. https://github.com/themehouse-xf

**Comment by mikecreuzer** [comment]
Can we add our xf2 ones? I don't see user criteria.

**Comment by mikecreuzer** [comment]
Bump on this, for sake of Install and Upgrade

**Comment by mikecreuzer** [comment]
BUmp
