### ISSUE TITLE
 [TH] Reactions - Compatible update for Change Content Owner

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#891]
Change Thread Owner with [this add-on](https://xenforo.com/community/resources/change-content-owner.6124/), add support move all Reactions count to new thread/post Owner.

**Comment by LukasWieditz** [comment]
That's nothing we're gonna look into. The resource author can contact us for a development version if he wants to implement it himself, as it's better suited to be located in his add-on.
