### ISSUE TITLE
[Topics] Ajax Loading Indicator

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#893]

**Comment by Ian-Hitt** [comment]
<img width="730" alt="screen shot 2018-10-09 at 4 34 20 pm" src="https://user-images.githubusercontent.com/15836384/46700036-56414b80-cbe1-11e8-9cab-a604c5dc1f60.png">

Either a loading spiiner, or maybe even something like this

**Comment by LukasWieditz** [comment]
Use the default XenForo loading indicator. No need to come up with something completely different just for one functionality.

**Comment by jonw316** [comment]
The default XenForo loading indicator is already being used.

**Comment by mikecreuzer** [comment]
Actually the loadiny icon in the corner isn't that I was referring to exactly. Currently changing a filter causes entire list to disappear then after .5 to 1 second it comes back. I was thinking we should put something there meanwhile.

**Comment by LukasWieditz** [comment]
That rather sounds like the list is cleared before the ajax call is made. It should only be cleared once the new content is being inserted, so it doesn't stay empty if the ajax call crashes for w/e reason.

**Comment by jonw316** [comment]
I changed it because it was confusing that the topics were being changed in the filter pre-ajax call but the content wasn't being updated until after. We should pick one or the other.

**Comment by LukasWieditz** [comment]
Both should be updated on a successful call only imo

**Comment by jonw316** [comment]
Because the widget is itself a filter, that then gets quite confusing as the filters become out of sync with one another.

**Comment by LukasWieditz** [comment]
The widget(s) should be synchronized right on click. The time between that sync and the filter bar being updated & the content being replaced is visually displayed by the ajax load indicator.

**Comment by jonw316** [comment]
I think having anything out of sync is ugly and unhelpful. I actually prefer Ian's original suggestion, although I agree it would be a lot of work just for one functionality.

**Comment by mikecreuzer** [comment]
So why not just do loading indicator? Itll only show for a second, but better than no table at all. Leaving open for now. I dont think we want to do the facebook thing, its the same exaact thing as the loading icon just looks more like text. Its not a hard thing to do either @jonw316 . We literally copy the threadbit, and wherever there is text, we replace with a div of X length, display inline-block and the same bg as text-color. Do that for all text and the avatar, show it 3 times, and you'd have the same result as the loading indicator.

**Comment by mikecreuzer** [comment]
Moved milestone, but keeping bug label. It looks very odd as is but not show stopping

**Comment by jonw316** [comment]
This has been improved now, so I've removed the bug label.
