### ISSUE TITLE
[TH] Reactions - Animation Type missing that allows admins to disable reaction animations

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#896]
Unless this was removed in past releases or when we were updating how animations worked. I've reviewed the latest animation types and other settings with no luck in finding such a function.
![screen shot 2018-10-10 at 10 09 35 am](https://user-images.githubusercontent.com/32306910/46746405-9f8eab00-cc74-11e8-9753-cff1e2194429.png)

This has also been reported by a few customers as well who would like to see it added again.

**Comment by mikecreuzer** [comment]
Reassigning to Jon, it might just be setting got unassociated somehow. Im sure the logic is all there.

**Comment by jonw316** [comment]
I've added the style property back, but it is all broken and needs fixing. Shall I close this?

**Comment by mikecreuzer** [comment]
This removes our animations apparently which is a big reason for why we did Reactions. We need to address this. It might just be a front-end thing we can get Ian or Kyler to look at @jonw316
