### ISSUE TITLE
[TH] Install & Upgrade - Add-on icons on product page

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#897]
Just to be sure, are the original icons suppose to be showing on this page just like they do on the other page?
![screen shot 2018-10-10 at 10 20 33 am](https://user-images.githubusercontent.com/32306910/46747205-4cb5f300-cc76-11e8-8ed7-22fea27de666.png)
They are showing on the Avaliable add-ons page though.
![screen shot 2018-10-10 at 10 23 52 am](https://user-images.githubusercontent.com/32306910/46747337-9e5e7d80-cc76-11e8-8ebf-aaa9badb6582.png)

**Comment by LukasWieditz** [comment]
Nope, that's all correct. They're not supposed to show there.

**Comment by mikecreuzer** [comment]
Could we add support for this easily?

**Comment by mikecreuzer** [comment]
could we skim it though? like in each custom handler? find it in the page or endpoint?

**Comment by LukasWieditz** [comment]
Is it really that important? Languages and styles don't have icons either.

**Comment by JakeBooher** [comment]
Add this to the AddOn entity:

```
function getAddOnHandler()
{
    return \XF::app()->addOnManager()->getById($this->addon_id);
}
```

then for the icon you can just do:

```
<xf:macro template="addon_list_macros" name="addon_list_item_icon" arg-addOn="{$addOn.getAddOnHandler()}">
```
