### ISSUE TITLE
Install & Upgrade - Error when attempting to a XenForo Customer Area profile

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#917]
> Exception: No XenForo license found for url https://demo.themehouse.com/xf2/addons. in src/addons/ThemeHouse/InstallAndUpgrade/InstallAndUpgrade/XenForo.php at line 184
> ThemeHouse\InstallAndUpgrade\InstallAndUpgrade\XenForo->getLicenseId() in src/addons/ThemeHouse/InstallAndUpgrade/InstallAndUpgrade/XenForo.php at line 102
> ThemeHouse\InstallAndUpgrade\InstallAndUpgrade\XenForo->getProductsFromProvider() in src/addons/ThemeHouse/InstallAndUpgrade/Entity/InstallUpgradeProfile.php at line 48
> ThemeHouse\InstallAndUpgrade\Entity\InstallUpgradeProfile->getProductsFromProvider() in src/addons/ThemeHouse/InstallAndUpgrade/Job/FetchProducts.php at line 24
> ThemeHouse\InstallAndUpgrade\Job\FetchProducts->run() in src/XF/Job/Manager.php at line 241
> XF\Job\Manager->runJobInternal() in src/XF/Job/Manager.php at line 187
> XF\Job\Manager->runJobEntry() in src/XF/Job/Manager.php at line 103
> XF\Job\Manager->runByIds() in src/XF/Admin/Controller/Tools.php at line 120
> XF\Admin\Controller\Tools->actionRunJob() in src/XF/Mvc/Dispatcher.php at line 249
> XF\Mvc\Dispatcher->dispatchClass() in src/XF/Mvc/Dispatcher.php at line 88
> XF\Mvc\Dispatcher->dispatchLoop() in src/XF/Mvc/Dispatcher.php at line 41
> XF\Mvc\Dispatcher->run() in src/XF/App.php at line 1931
> XF\App->run() in src/XF.php at line 329
> XF::runApp() in admin.php at line 13

All domains that are entered include `http` or `https` but even after this error the profiles are still shown in the Install & Upgrades profiles page.
![screen shot 2018-10-11 at 9 55 16 am](https://user-images.githubusercontent.com/32306910/46813151-c7951180-cd3b-11e8-9f8e-767b2eda0105.png)

**Comment by LukasWieditz** [comment]
That's not a bug. The error is trying to tell you that you're entering a wrong license url.
