### ISSUE TITLE
create milestone widget for donate campaign view sidebar

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#921]

**Comment by mikecreuzer** [comment]
What would this do?

**Comment by Ian-Hitt** [comment]
Show the progress for each milestone of a campaign. Its a custom widget for campaign single view

**Comment by Ian-Hitt** [comment]
<img width="427" alt="screen shot 2018-10-11 at 1 57 01 pm" src="https://user-images.githubusercontent.com/15836384/46827154-8ca3d580-cd5d-11e8-83ec-8b54dde9f4c5.png">

**Comment by mikecreuzer** [comment]
Do we even have milestones?

**Comment by LukasWieditz** [comment]
Yes
