### ISSUE TITLE
UI.X: "View Documention" => "View Documentation"

### ISSUE THREAD

**Issue by jonw316** [Audentio/xf2addon-issues#923]
<img width="1215" alt="screenshot 2018-10-12 at 11 55 05" src="https://user-images.githubusercontent.com/42781420/46865513-c0dacd00-ce15-11e8-88ca-51032d4f16c0.png">

**Comment by LukasWieditz** [comment]
I don't think a typo is so critical that we need to release an update for it, so gonna remove the priority tag and just ship it with the next update.

**Comment by LukasWieditz** [comment]
It's one of our glorious hardcoded phrases (the whole error message is hardcoded) in the UI.X Style. Gonna change it to phrases...

References #666

**Comment by JakeBooher** [comment]
That’s intentionally not a phrase, it shows up when the addon isn’t installed..
