### ISSUE TITLE
Topics page - sub-topics dropdown

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#930]
- [x] Phrase missing
- [x] Left align stats, right align dropdown?

![image](https://user-images.githubusercontent.com/1217271/46969225-021fe680-d07b-11e8-92bc-a0a7faed8444.png)

**Comment by jonw316** [comment]
Do you need to do a dev import or something. The phrase is definitely there:
https://github.com/Audentio/xf2/blob/master/src/addons/ThemeHouse/Topics/_output/phrases/thtopics_sub_topics.txt

**Comment by mikecreuzer** [comment]
Ian says he did do it that way. Not sure
