### ISSUE TITLE
[Topics] 1) Order - Not Adjustable  2) Ability to ensure 1 selection from group is selected.

### ISSUE THREAD

**Issue by arm5ky** [Audentio/xf2addon-issues#940]
Add-on Name:
 [TH] Topics 
Add-on Version: 
1.0.0 Release Candidate 6
XenForo Version:
v2.0.9

Summary of issue:
topics appear in creation date order in filter bar. This leads to some odd placement of key topics.
I also think it would be a good idea if you could make selections from groups mandatory if required and put these groups in the front of the thread create.

Detailed steps to reproduce the issue:
Upload any screenshots related to the issue below
![image](https://user-images.githubusercontent.com/6074069/47080859-0544df00-d201-11e8-8403-ecab65df09bf.png)
![image](https://user-images.githubusercontent.com/6074069/47080944-3a513180-d201-11e8-9e4b-22225de2f405.png)

**Comment by mikecreuzer** [comment]
This was added to 1.0.0 milestone @LukasWieditz is this critical? Are we needing two settings?

1. Order which is used in places other than the widget itself?
2. A setting to ask for child group first if applicable? Or am I missing that
