### ISSUE TITLE
[QA Forums] User Permissions

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xf2addon-issues#949]
The Q&A add-on user permissions are not grouped together in their own section like other add-ons. Right now they are under "Forum Permissions".

**Comment by JakeBooher** [comment]
This is intentional, if they were in another group you wouldn't be able to set the permission per node.

**Comment by mikecreuzer** [comment]
Yeah why not group them? Nothing to do with per node permissions

**Comment by LukasWieditz** [comment]
The per node permissions are selected based on the permission group (which has to be 'forum'). Forum moderator permissions already demonstrate, that it is possible to have permissions within that same group but in a different display group (important here to distinguish between "display group", which is what you guys see, and "permission group", which is not visible to the user). TL;DR: safe to move them to their own display group.
