### ISSUE TITLE
[ReactPlus] Notable members enhancements

### ISSUE THREAD

**Issue by JakeBooher** [Audentio/xf2addon-issues#95]
option to have tabs for individual reactions, as well as reaction types

**Comment by lilalien** [comment]
Really looking forward to this one.. Would be really great to be able to add Reactions statistics to this page instead of just seeing the XF-default "Likes" total..

**Comment by LukasWieditz** [comment]
Do we want/need this for ReactPlus in the future?

**Comment by JakeBooher** [comment]
The issue with this (and why it was never completed) was due to the way the notable member system works, it requires you to specify a specific field in xf_user - so unless something has changed this still won't be possible, but I'll look into it
