### ISSUE TITLE
[Donate] Recurring Donations default selection

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#959]
When enabled Allow recurring donations then should be Recurring checked by default and UN-checkeable.

![screenshot00536](https://user-images.githubusercontent.com/6899856/47233421-fd3c9900-d3d2-11e8-91a0-3cb2ea6536ad.png)

**Comment by mikecreuzer** [comment]
Is this required for useful use of recurring donations? May be more than just an enhancement if so.

**Comment by LukasWieditz** [comment]
I personally feel that making the choice for an unaware user is probably more problematic than helpful. If they want to do it, they can manually opt in.

**Comment by JakeBooher** [comment]
I've added an option to check the box by default, and have placed a description under it
