### ISSUE TITLE
[TH] Reactions - Moving the reaction bar above the action bar

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#96]
Allow users to move the reaction bar above the action bar.

> I believe that where it should so we can be flexible in styling the message footer and the action bar as well. Another thing is there an option to make the menu stay open instead of clicking and then clicking. I do have only one reaction so there is no reason to click twice.

 -ALMUSA from XenForo's Community

**Comment by JakeBooher** [comment]
This is not currently planned as there isn't an easy way for this to be supported within UI.X as far as I'm aware
