### ISSUE TITLE
[TH] Donate - add Donate button after Description

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#961]
add one more Donate button after Description.

![screenshot00538](https://user-images.githubusercontent.com/6899856/47233645-adaa9d00-d3d3-11e8-8404-6fc38add9387.png)

**Comment by LukasWieditz** [comment]
Leaving this design choice to @Ian-Hitt . Personally I think it's not needed in duplicated form.

**Comment by Nirjonadda** [comment]
Same here, Donate button should be highlight, 2 button are different location should not bad idea? all are open overlay.

**Comment by Nirjonadda** [comment]
I think Donate button should be show both location?

![screenshot00548](https://user-images.githubusercontent.com/6899856/47237421-514d7a80-d3df-11e8-9192-cda1c37cf51f.png)

**Comment by Ian-Hitt** [comment]
I think the duplicate button is unnecessary. easy enough to add if you want to do it custom, but putting it in the call to action location makes it front and center.

**Comment by Nirjonadda** [comment]
@Ian-Hitt Please send me CSS code for this?
