### ISSUE TITLE
[TH] Donate - Donation progress Bar

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#962]
add option can enable Donation progress Bar before Description.

![screenshot00539](https://user-images.githubusercontent.com/6899856/47233764-08dc8f80-d3d4-11e8-9f4b-e1493fc4b8bc.png)

**Comment by LukasWieditz** [comment]
Not sure how I feel about this. Technically, the progress bar is already in the sidebar. Gonna leave this choice to @Ian-Hitt

**Comment by mikecreuzer** [comment]
I could see a setting to make the entire widget show in the overview. Each campaign and its progress, yeah. Its just maybe not a priority anytime soon.

**Comment by Nirjonadda** [comment]
Sidebar are Optional and this are not highlight.

**Comment by Ian-Hitt** [comment]
I've added both of the widgets in at the top of the page, but they are hidden until the sidebar breakpoint. You can edit the CSS if you would like to change this, but no need to add an option. These widgets are not added via the widget manager, so they cannot be removed.

**Comment by Nirjonadda** [comment]
@Ian-Hitt Please let me know that what CSS code need edit for this?
