### ISSUE TITLE
[Donate] Alert for new capaign comment / watch campaigns

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#964]
missing Alerts for Donations Comments messages

**Comment by LukasWieditz** [comment]
I don't think the alerts are missing (I know there are none sent, don't get me wrong here, I just think they're not necessary/wanted), but we may implement a watch feature in the future that'll send out alerts to everyone who opts in to receive them.

**Comment by Nirjonadda** [comment]
@LukasWieditz Sorry, like Alerts missing.

**Comment by Nirjonadda** [comment]
Should you get Alerts when like your Donations Comments and messages?

**Comment by LukasWieditz** [comment]
Ohhh, yeah, that should happen. I'll create a separate issue and leave this one up as suggestion for the future.
