### ISSUE TITLE
[TH] Donate - Bypass approval

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#965]
add User group permissions can Bypass approval from Donations Comments messages

**Comment by LukasWieditz** [comment]
They should be managed by the same permissions that decide for all other content types if stuff gets moderated or not. That would mostly be `Submit content without approval` in the general permission section.

**Comment by Nirjonadda** [comment]
Should not separate for this? when have moderator permissions Approve / unapprove comments.

**Comment by LukasWieditz** [comment]
Don't think so, no. XenForo does it everywhere. They have a per content-type "Approve/unapprove" permission, but only that one "Submit without approval" general permission.
