### ISSUE TITLE
[TH] Donate - Time limit on editing donation messages

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#966]
Time limit on editing donation messages used 2 time.

Time limit on editing/deleting own comments to Time limit on deleting own comments?

![screenshot00544](https://user-images.githubusercontent.com/6899856/47234456-3de9e180-d3d6-11e8-9732-5bfdcb23cb2f.png)

**Comment by LukasWieditz** [comment]
Donation messages and comments are two different things.

**Comment by Nirjonadda** [comment]
Oh sorry !
