### ISSUE TITLE
[Donate] Missing end date

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#967]
donations goal end date missing.

![screenshot00545](https://user-images.githubusercontent.com/6899856/47234609-a933b380-d3d6-11e8-86c4-56bd03d8eca5.png)

**Comment by Ian-Hitt** [comment]
@LukasWieditz data isnt avaialble in $milestone there

**Comment by Ian-Hitt** [comment]
Fixed

**Comment by Ian-Hitt** [comment]
https://github.com/Ian-Hitt/xf2/commit/01bb32973603eb0730f929719e511f4f99ba5b69

**Comment by Nirjonadda** [comment]
@LukasWieditz @Ian-Hitt Still are not fixed in [TH] Donate 1.0.4 ?

**Comment by Nirjonadda** [comment]
Does not find out where this are showing. Do we need enable any option for this functionality?
