### ISSUE TITLE
[TH] Install & Upgrade -  Decryption required are not save

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#969]
Decryption required are not save, its still open after save.

![screenshot00547](https://user-images.githubusercontent.com/6899856/47237256-c66c8000-d3de-11e8-8342-02d73bd45f7c.png)

**Comment by mikecreuzer** [comment]
If this is indeed happening as described then Im assuming its priority and a bug.

**Comment by JakeBooher** [comment]
This is because after saving it redirects you to the refresh page so it can load in products. This should probably only require the encryption key for profiles that support products (ThemeHouse and XenForo only, I believe). But otherwise, this is realistically behaving as expected, unless there is a different issue

**Comment by LukasWieditz** [comment]
I've renamed the button to "submit" to make it clear that nothing is actually "saved" here.

**Comment by Nirjonadda** [comment]
@LukasWieditz Re-open this issue

> This is because after saving it redirects you to the refresh page so it can load in products.

@JakeBooher This does not, This still stand by the  Decryption required after enter/submit the key. This should be redirects products page.

**Comment by mikecreuzer** [comment]
@Nirjonadda just so Im clear you want this reopened for a new reason? Lukas is saying he fixed the OP of this ticket

**Comment by Nirjonadda** [comment]
@mikecreuzer Not new reason from @JakeBooher reply, This still stand by the Decryption required page after enter/submit the key. This should be redirects products page.

See here: https://giant.gfycat.com/ZigzagLegitimateGrebe.webm

> 
> 
> This is because after saving it redirects you to the refresh page so it can load in products. This should probably only require the encryption key for profiles that support products (ThemeHouse and XenForo only, I believe). But otherwise, this is realistically behaving as expected, unless there is a different issue
