### ISSUE TITLE
Donate or InstallandUpgrade add-on

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2addon-issues#971]
Not sure if it's one or the other that has caused this. But I just updated the files via ftp with the new downloads released earlier today. Donate 1.0.4 and I&U 1.0.0 beta 7. My forum list disappeared. Everything worked other than my forum list disappearing. Got a friend to check, same thing so I weren't the only one. Luckily I could access the admin cp where I took it upon myself to upgrade the Donate add-on where it had fixed the issue and the forum list reappeared.

**Comment by LukasWieditz** [comment]
That's not necessarily something unexpected. If you uploaded an update of a currently installed piece of software (in this case an add-on), but haven't installed it yet, you're executing the software in an inconsistent state. The database is still in the state of the previous version, while the code is already in the new state, hence there's a big hole of inconsistency. Until you fix this by upgrading the software, such errors are to be expected.
