### ISSUE TITLE
[TH] Install & Upgrade - Import from uploaded zip file

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#972]
Files name out of the box from Import from uploaded zip file.

![screenshot00549](https://user-images.githubusercontent.com/6899856/47246453-258dbd00-d3fe-11e8-9255-6f7d9350e906.png)

**Comment by LukasWieditz** [comment]
That widget is made completely out of native XF building blocks, so that's an issue on their end.

**Comment by LukasWieditz** [comment]
That widget is made completely out of native XF building blocks, so that's an issue on their end.
