### ISSUE TITLE
[TH] Install & Upgrade - Manually associate product

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#974]
Manually associate product then where are show info that are associate with this add-on? so how to understanding that what are associate or not?

should show in Installed products?

**Comment by mikecreuzer** [comment]
Hi there @Nirjonadda not sure I understand here

**Comment by Nirjonadda** [comment]
When Manually associate product then where will be show this add-on are associate with Install & Upgrade?

**Comment by LukasWieditz** [comment]
They'll show up in the "Installed products" section (admin.php?install-upgrade-products/installed) once you manually associated them. #980 may prevent them from being correctly associated atm though.
