### ISSUE TITLE
[TH] Install & Upgrade - automatic forum open

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#977]
I have closed my forum from public view but Its automatic opened.

**Comment by LukasWieditz** [comment]
That's because you have the option on to automatically close your forum when an install & upgrade process starts, and reopen it once the process is complete.

**Comment by LukasWieditz** [comment]
That's because you have the option on to automatically close your forum when an install & upgrade process starts, and reopen it once the process is complete.

**Comment by Nirjonadda** [comment]
But this should respect Bord active option.

**Comment by LukasWieditz** [comment]
That's technically not possible.
