### ISSUE TITLE
UIX Pro - Report - Clicking checkbox resolves

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#979]
I missed this :P but yeah clicking checkbox == resolve button. I don't mind having both buttons. I fell for this myself :P

**Comment by LukasWieditz** [comment]
As there's only a very small percentage of items that support this anyway, I don't feel that would be consistent behavior.

**Comment by mikecreuzer** [comment]
Then lets just get rid of the checkbox. Its a useless icon
