### ISSUE TITLE
Reactions / UI.X - Threadview Reactions Alignment

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2addon-issues#981]
Style Name: UI.X Dark

Style Version: Latest

UI.X Add-on Version: Latest

XenForo Version: Latest

Operating System (and Version): Windows 10 / 64-Bit Latest Stable

Browser Name (and Version): Chrome 70 / 64-Bit Latest Stable

Does this issue happen in the default XenForo style? No.

Summary of issue: When viewing the threadview page, the viewable reactions are not aligning properly and going where they belong (on a separate line) as the XF default style does.

These screenshots should help:

![thread_view_reactions_ui-x-dark](https://user-images.githubusercontent.com/35111972/47313886-1a10e080-d60e-11e8-8a55-c0851223bff4.png)
![thread_view_reactions_xf_default_theme](https://user-images.githubusercontent.com/35111972/47313888-1aa97700-d60e-11e8-8641-fee0dbc6f7bf.png)

**Comment by mikecreuzer** [comment]
Closing this, but will discuss on theme repo: https://github.com/Audentio/xf2theme-issues/issues/856
