### ISSUE TITLE
UI.X Dark - Threadview Inline New Thread Vertical Button Alignment

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2addon-issues#982]
Style Name: UI.X Dark

Style Version: Latest

UI.X Add-on Version: Latest

XenForo Version: Latest

Operating System (and Version): Windows 10 / 64-Bit Latest Stable

Browser Name (and Version): Chrome 70 / 64-Bit Latest Stable

Does this issue happen in the default XenForo style? No.

Summary of issue: When viewing the threadview page in UI.X Dark, and using the inline new thread functionality, the "Post Thread" and "More Options" buttons are not aligning properly. This is exactly the same issue as the Search popup box that @Ian-Hitt already fixed! I don't see the issue anywhere else.

These screenshots should help:

![thread_view_inline_new_thread_vertical_alignment_uix_bug](https://user-images.githubusercontent.com/35111972/47314192-f8642900-d60e-11e8-8dac-d8c7da8fd615.png)

**Comment by Ian-Hitt** [comment]
https://github.com/Audentio/xf2theme-issues/issues/857
