### ISSUE TITLE
UI.X Dark - Threadview Deleted Thread Edit / Checkbox Alignment Bug

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2addon-issues#983]
Style Name: UI.X Dark

Style Version: Latest

UI.X Add-on Version: Latest

XenForo Version: Latest

Operating System (and Version): Windows 10 / 64-Bit Latest Stable

Browser Name (and Version): Chrome 70 / 64-Bit Latest Stable

Does this issue happen in the default XenForo style? No.

Summary of issue: When viewing the threadlist, you will see that the "Edit" / Checkbox is on the left, when it should be on the right instead.

These screenshots should help:

![uix_dark_deleted_thread_alignment_bug](https://user-images.githubusercontent.com/35111972/47314411-8a6c3180-d60f-11e8-93eb-61cc9f369985.png)

**Comment by Ian-Hitt** [comment]
moved to https://github.com/Audentio/xf2theme-issues/issues/856
