### ISSUE TITLE
UI.X Dark - Sidebar Content Box Default Icons Override (Request)

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2addon-issues#984]
Style Name: UI.X Dark

Style Version: Latest

UI.X Add-on Version: Latest

XenForo Version: Latest

Operating System (and Version): Windows 10 / 64-Bit Latest Stable

Browser Name (and Version): Chrome 70 / 64-Bit Latest Stable

Does this issue happen in the default XenForo style? No.

Summary of issue: When previously creating custom sidebar boxes, there was no default icon in previous UI.X versions. To make it look better I added them. Now that you have added a default icon recently, it takes away from the uniqueness. I don't mind the default icons at all (looks better than none!) but may I ask for a way to properly override these if I want to use my own such? I'd like them not to BOTH show up in as seen in the screenshot! Any tips would be useful!

These screenshots should help:

![sidebar_box_header_icons_override_uix](https://user-images.githubusercontent.com/35111972/47314526-e931ab00-d60f-11e8-9ea5-d46ff13baf1f.png)

**Comment by Ian-Hitt** [comment]
Moving to themes here: https://github.com/Audentio/xf2theme-issues/issues/855
