### ISSUE TITLE
[TH] Install & Upgrade - Add-on updates available version issue

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#985]
Add-on updates available are not correct version.

See here: https://giant.gfycat.com/NaiveBreakableFlyingfish.webm

**Comment by LukasWieditz** [comment]
Which download URL is it linked to?

**Comment by Nirjonadda** [comment]
URL: https://xenforo.com/community/resources/user-activity-by-xon.5567/

I think this add-on installed with URL or ZIP.

User Activity add-on are Manually associate product. So this add-on URL link linked  with Group Legend Widget add-on?

**Comment by LukasWieditz** [comment]
Once you correct the wrong association caused by #980, this should work.
