### ISSUE TITLE
Topics - If no topic is set OR topics system is off - show node title on thread bit

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#990]
- [x] If no topics are set (but topics system is on) show the node in the top right of the thread bit
- [x] Regardless of if topics are set, the system is OFF, show node title in the top right of the thread

![image](https://user-images.githubusercontent.com/1217271/47387591-6c690480-d6d5-11e8-839f-3b4a1a20d5fe.png)

**Comment by mikecreuzer** [comment]
On second thought, maybe this is only an issue on Trending.

**Comment by jonw316** [comment]
This needs fixing in the Trending add-on.
