### ISSUE TITLE
Missing phrases on Topics

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#991]
- [x] nav.thTopics_watchedTopics (in Pro sidenav)
![image](https://user-images.githubusercontent.com/1217271/47388082-e5b52700-d6d6-11e8-9990-35a1ed114a70.png)

- [ ] Someone else reported that /forums/-/newest-posts thee title was displaying as `newest_topic_posts`

![image](https://user-images.githubusercontent.com/1217271/47388144-0bdac700-d6d7-11e8-8025-1d9647bd51c8.png)

**Comment by jonw316** [comment]
The newest_topic_posts must be because someone has made a template edit and not merged in the latest changes. That phrase is not used any more.
