### ISSUE TITLE
On filter bar, add back clear filter icon

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#993]
Not sure where it went or if there was a rationale behind it

![image](https://user-images.githubusercontent.com/1217271/47388497-f914c200-d6d7-11e8-8201-7602bfc0d3c1.png)

**Comment by mikecreuzer** [comment]
Ah, this is a bug. Will work with multiple Topics, but not if there is nodes OR nodes and topics. Should work both ways. But the phrase will have to change.

@jonw316 suggestion: Show the clear 'X' if there are 3 or more of anything? A small enhancement Topics adds. But theoretically it could live in UI.X if you preferred.

**Comment by jonw316** [comment]
Not a bug. The clear filter button only ever cleared all topic filters and not all filters, so it makes more sense for it to be on the right hand side and also makes sense for it not to show if there is only one topic filter selected. There is a separate clear filter button for node filters.

**Comment by mikecreuzer** [comment]
I assume that code reference tagged this one incorrectly.

But I find the clear button position on the right very odd. Why not left?

**Comment by jonw316** [comment]
No, there was a small bug.

<img width="833" alt="screenshot 2018-10-24 at 17 26 55" src="https://user-images.githubusercontent.com/42781420/47445965-08683e00-d7b2-11e8-95b3-ab15f51c7860.png">
I think the above would be a lot less clear if the crosses were on the right.

If we want to change the functionality of the cross to clear all filters, then I think on the left makes sense. But with the current functionality, I think on the right is better.
