### ISSUE TITLE
Cannot create comment on a second post while the first comment box is open

### ISSUE THREAD

**Issue by JakeBooher** [Audentio/xf2addon-issues#997]
```
And the third one, if you click the comment button on a post but if you give up, and will post a new comment to another post, you can't do this because you should click the close button. Or else you can't. As a result of this, if you didn't close the comment box, you cannot post a comment for another post. I feel like that is a big problem.
```

This may be intentional, or a limitation of the editor, but just creating this issue as it was brought up by someone

**Comment by mikecreuzer** [comment]
Well, the way I see it is that indeed its a small UX bug. In an ideal world, you should be able to perform the action you are intending to do.

The technical way to fix this would, I think, be to delete/unregister the existing editor (if one is currently running) so that a new one can be created.

**Comment by mikecreuzer** [comment]
https://www.froala.com/wysiwyg-editor/examples/inline-two-instances

**Comment by LukasWieditz** [comment]
There is and was never a bug with Froala here. The XenForo backend is simply not capable of fully handling this without running into issues on every end.

**Comment by mikecreuzer** [comment]
Id like to reconsider options for this as it does make the system broken. Id rather not have an editor at all.

**Comment by mikecreuzer** [comment]
https://github.com/Audentio/xf2addon-issues/issues/1389
